### ISSUE TITLE
Include option to export registered tifs for >1 channel

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#100]
This is a feature request. Would it be possible to include the option for exporting the registered tifs for either one or a list of channels? For example, if I choose to align on the second channel, but want to inspect registered tifs from the first channel, "align_by_chan" would be "2", and "reg_tif_...." would "1,2" if I want to get tif exports for both channels.

**Comment by carsen-stringer** [comment]
Now there are two options: 'reg_tif' and 'reg_tif_chan2'. Regardless of which channel is being aligned to, the 'reg_tif' folder now contains tiffs from the functional channel and 'reg_tif_chan2' folder contains tiffs from the non-functional channel.

**Comment by horsto** [comment]
Perfect, thanks!
