### ISSUE TITLE
<Please write a comprehensive title.>

### ISSUE THREAD

**Issue by IbrahimLab-23** [MouseLand/suite2p#1007]
### Describe the issue:

Hello I am trying to install Suit2p GUI but I got this error 

File "C:\Users\alyahyma\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\visualize.py", line 13, in <module>
    from rastermap.mapping import Rastermap
ModuleNotFoundError: No module named 'rastermap.mapping'

### Provide environment info:

conda info

**Comment by chriski777** [comment]
Hi @IbrahimLab-23, this issue has been fixed in the latest version of the `dev` branch. Can you pull that version and try again?

**Comment by chriski777** [comment]
Should be fixed so please try again with the newest release!

**Comment by IbrahimLab-23** [comment]
Thank you for your reply,

I installed the latest version of Suit2p Vera 1.13 but still same error

**Comment by chriski777** [comment]
Can you try again? The newest release was just put out maybe not too long ago. Also, the latest version should be 0.14.0.

**Comment by IbrahimLab-23** [comment]
Thank you so so so much I tried it and it worked.

Thank you for your support
