### ISSUE TITLE
'fast_disk': ['/path/to/disk'] should be 'fast_disk': '/path/to/disk'

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#101]
Tried using the batch jupyter notebook and setting fast_disk with square brackets gave the following error:

`expected str, bytes or os.PathLike object, not list`

from os.fspath

Leaving fast_disk empty did not show the error.

Passing it without brackets as: 'fast_disk': '/path/to/disk' did the right thing

**Comment by carsen-stringer** [comment]
thanks! I've specified that it expects a string not a list and put an example in the jupyter-notebook
