### ISSUE TITLE
Error trying to open GUI after fresh install on Windows 10

### ISSUE THREAD

**Issue by outlace** [MouseLand/suite2p#1010]
### Describe the issue:

I have followed the instructions to install for Windows, and it appears the installation goes fine, but when trying to open the GUI I get an error:

`
(base) PS C:\Users\Yu Lab> conda activate suite2p
(suite2p) PS C:\Users\Yu Lab> python -m suite2p
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 84, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 80, in main
    gui.run()
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 712, in run
    GUI = MainWindow(statfile=statfile)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 96, in __init__
    b0 = self.make_buttons()
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 155, in make_buttons
    masks.make_colorbar(self, b0)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\masks.py", line 192, in make_colorbar
    colorbarW = pg.GraphicsLayoutWidget(parent)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\widgets\GraphicsLayoutWidget.py", line 51, in __init__
    GraphicsView.__init__(self, parent)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\widgets\GraphicsView.py", line 61, in __init__
    QtWidgets.QGraphicsView.__init__(self, parent)
TypeError: 'PySide6.QtWidgets.QGraphicsView.__init__' called with wrong argument types:
  PySide6.QtWidgets.QGraphicsView.__init__(MainWindow)
Supported signatures:
  PySide6.QtWidgets.QGraphicsView.__init__(Union[PySide6.QtWidgets.QWidget, NoneType] = None)
  PySide6.QtWidgets.QGraphicsView.__init__(PySide6.QtWidgets.QGraphicsScene, Union[PySide6.QtWidgets.QWidget, NoneType] = None)
`

If I just open python and import suite2p I don't get any errors.

I see issue #942 appears to have the same error, but the advice from maintainers was "This is a pyqtgraph issue and an incompatibility with pyside6 6.5. We (pyqtgraph maintainers) are about to release PyQtGraph 0.13.3 which will address this issue." But my PyQtGraph version is 0.13.3 when I do `pip show pyqtgraph`.

### Provide environment info:

```
     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Yu Lab\.condarc
 populated config files : C:\Users\Yu Lab\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=12.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Anaconda3  (read only)
      conda av data dir : C:\ProgramData\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Yu Lab\.conda\pkgs
                          C:\Users\Yu Lab\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Yu Lab\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\Yu Lab\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.22000
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by outlace** [comment]
Update: I got it working by downgrading pyqtgraph to 0.12.0

**Comment by milesOIST** [comment]
What worked for me was this specific order:
`conda create --name suite2p python=3.9`
`pip install PyQt-builder`
`python -m pip install 'suite2p[gui]'`
`python -m pip install suite2p[io]`
` python -m suite2p`

**Comment by chriski777** [comment]
Closing this issue as #1057 should have addressed this. Feel free to reopen if the issue persists!
