### ISSUE TITLE
Installation issue: "Could not load the Qt platform"

### ISSUE THREAD

**Issue by doleduke** [MouseLand/suite2p#1016]
### Describe the issue:

I'm currently trying to download suite2p on a new system (a linux shell) and I downloaded suite2p following the instructions on the github. I ran into the following error:

![image](https://github.com/MouseLand/suite2p/assets/88160794/9b8733a1-0bcf-47b2-845b-c063242a3d88)

I have tried a few different solutions online, it seems like it might be a problem with different versions of Qt conflicting with each other? Any advice would be appreciated, thank you!

### Provide environment info:

     active environment : suite2p
    active env location : /home/dleduke/anaconda3/envs/suite2p
            shell level : 2
       user config file : /home/dleduke/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __cuda=12.0=0
                          __linux=4.19.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dleduke/anaconda3  (writable)
      conda av data dir : /home/dleduke/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dleduke/anaconda3/pkgs
                          /home/dleduke/.conda/pkgs
       envs directories : /home/dleduke/anaconda3/envs
                          /home/dleduke/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/4.19.0-25-amd64 debian/10 glibc/2.28
                UID:GID : 1923:1400
             netrc file : None
           offline mode : False

**Comment by milesOIST** [comment]
https://github.com/MouseLand/suite2p/issues/1010#issuecomment-1666857297

**Comment by chriski777** [comment]
Hi @doleduke, this issue should have been fixed in #1057. Also, @milesOIST's suggestion should work here. I'll close this for now but feel free to reopen if the issue persists!
