### ISSUE TITLE
BUG: Merged ROIs not saving in stat.npy in GUI

### ISSUE THREAD

**Issue by yrleftbrain** [MouseLand/suite2p#1021]
### Describe the issue:

Merged ROIs (via GUI alt+enter) aren't saving in stat.npy - they only save in the .mat file. Therefore, I can't retrieve the spatial footprints and the indices are likely off in stat.npy. However, the iscell.npy file does update (sometimes). 

### Reproduce the code example:

```python
in GUI
```

### Version information:

v0.14.0

### Context for the issue:

If I cannot get the correct spatial footprints, I will not be able to align anatomy to cell activity.

**Comment by yrleftbrain** [comment]
"imerge" is not being updated in the .mat file either, but "iscell" is.

**Comment by chriski777** [comment]
Hi @yrleftbrain, sorry for the late response. To save your merged ROIs (done via the GUI) in the `stat.npy` file, you have to additionally go to the menu and click `Merge ROIs` >> `Append merges to npy files`. This will then save the merged ROI into your `stat.npy` file. You'll then find your newly merged ROI at the end of the `.mat` and `stat.npy` files. The `imerge` for these newly added ROIs will contain the ROI indices of the ROIs you merged to form the newly added ROIs.

For instance, if you have 610 total ROIs and you merge ROI 5 and ROI 6, you will find your new ROI (ROI 611) at the end of the array in`stat.npy` or the end of the `stat` array in your `.mat` file. ROI 611's `imerge` field will contain the indices of the ROIs that were merged to form this ROI (e.g., [5, 6]). 

I will update the documentation to make this clearer and hopefully this addresses the problem.
