### ISSUE TITLE
no output file

### ISSUE THREAD

**Issue by tehrensbaker** [MouseLand/suite2p#103]
Hi, thank you very much for the great pipeline. I've run it with my recordings (tif files), the pipeline run without crashing, however, there's no output file at all. I ran through gui so it tried to load the file itself, and then it showed 'unsupported file format' because the output folder is empty (it did create the suite2p/plane0). Could you please assist on this? Many thanks.

**Comment by carsen-stringer** [comment]
Are you using the pip install or the github version? try `pip install suite2p --upgrade` if you don't have the latest version (I made one yesterday, we're at version 0.4.2). I'm not able to replicate your error. How many frames do you have in your tiffs?

**Comment by tehrensbaker** [comment]
I'm using the pip install, and I've upgraded it but it's still the same... it's 30000 frames in one tiff and I have two tiff files in the data path folder since I'd like to run them together. I tried to run one tiff only and it's still the same.

**Comment by tehrensbaker** [comment]
Thanks for your prompt reply! I'm using the pip install, and I've upgraded it but it's still the same... it's 30000 frames in one tiff and I have two tiff files in the data path folder since I'd like to run them together. I tried to run one tiff only and it's still the same.

**Comment by tehrensbaker** [comment]
Is it possible that during the running there might be some error but didn't show up in the embedded command line? I used to get memory error (which interrupted the pipeline and showed in the embedded command line) until I run it through 64 bit python rather than 32 bit.

**Comment by marius10p** [comment]
Please post the cmd line output during the run.

Did you change any of the default settings? Can you look during the run to see if the files are created in that folder? It cannot run at all if the files are not created, so they have to be somewhere. Did you give it a separate save path from where the data is?

**Comment by marius10p** [comment]
Some errors may not show in the embedded command line, check the real command line where you started the GUI. This could happen due to parallelism for example.

**Comment by tehrensbaker** [comment]
The cmd output:

C:\Users\tehrensb>python -m suite2p
loaded default ops
['L:/data/tb101/20180925']
Running suite2p!
starting process
{'data_path': ['L:/data/tb101/20180925'], 'subfolders': [], 'save_path0': 'E:/', 'fast_disk': 'C:/suite2p_binary/'}
E:/suite2p\plane0\stat.npy
ERROR: this is not a stat.npy file :( (needs stat[n]["ypix"]!)

The embedded cmd output:

Found 2 tifs
Unsupported file format: 
Opening in GUI (can close this window)

I only changed the diameter and the frame rate. Checked during the run and seems like no file showed up in the data folder. I did give a separate save path from the data path. Also tried the default data path as the save path though but it's the same.

**Comment by carsen-stringer** [comment]
Unfortunately I think what's happening is that your tiffs are too big - we currently read a whole tif at at time (assuming tifs are around ~2-4GB this isn't a problem). We will implement an incremental tiff reader soon. In the meantime, if your tifs are indeed really big, you could try splitting them into multiple tiffs and see if it works.

**Comment by tehrensbaker** [comment]
I see, indeed my tiff file is around 15 GB, and I'm running two at once. Thank you very much for trying to solve the problem with me anyway! I'll try to split the tiff and see if it works, hopefully wouldn't run into some alignment problems with the behaviour. May I ask if you have any idea of when the incremental tiff reader would be implemented? Thank you very much again for the great pipeline and all your help!

**Comment by marius10p** [comment]
I'll do it now.

**Comment by tehrensbaker** [comment]
Thank you so much!!

**Comment by marius10p** [comment]
I have added incremental tiff loading in batches of 2000 frames. If you want to try it before the next pip update, simply clone the github repo and run suite2p from inside the repo. 

I'll close this issue, please reopen if necessary.

**Comment by tehrensbaker** [comment]
It works!! Thank you so much!
