### ISSUE TITLE
ROI information in suite2p numpy array?

### ISSUE THREAD

**Issue by Eddymorphling** [MouseLand/suite2p#1038]
Hi,
I have been using the Cellpose model to extract cells and analyze Calcium spikes using Suite2p. 

I am using the "Top 40" cells to extract cells based on the skewness factor in Suite2P. My question is - once the top 40 cells are selected, is there a way to retrieve the ROI information for these cells from the numpy array in Suite2P (highlighted in red in the attached image). Is this possible? Thank you.

![Untitled](https://github.com/MouseLand/suite2p/assets/67712116/b3f69b11-17c2-4bdd-a719-49bcd9a2e985)

**Comment by chriski777** [comment]
Hi @Eddymorphling, I believe this information should be available in the `stat.npy` associated with this dataset. 

```
stat = np.load('stat.npy')
stat[n] # n here can be anyone of the numbers highlighted in red and you can get the ROI information.
```
You can find what the keys in the stat dictionary mean [here](https://suite2p.readthedocs.io/en/latest/outputs.html). Feel free to reopen the issue if you run into any other problems.
