### ISSUE TITLE
What is the difference between the ROI when filled and when only circled?

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#104]
Why is the green ROI in the upper image "more compact" while when I click it, it grows in size?

Does the lower image show the area used to assess neoropili and the above one the ROI used for fluorescence?

![screenshot 2018-10-04 16 21 44](https://user-images.githubusercontent.com/4943380/46480650-f407d580-c7f1-11e8-93a8-5b41ef2f2cb6.png)
![screenshot 2018-10-04 16 21 38](https://user-images.githubusercontent.com/4943380/46480651-f407d580-c7f1-11e8-90b0-3eeef79ae98b.png)

**Comment by Cumol** [comment]
Another related question. Why does a ROI look differently in the cells vs. non-cell view?

The purple ROI in the upper image appears compact in the non-cell view. When I try to add it to the cells view (and send the blue one to the non-cells view) it becomes much smaller and doesn't cover the whole cell.

![screenshot 2018-10-04 16 28 35](https://user-images.githubusercontent.com/4943380/46481017-b3f52280-c7f2-11e8-8ed1-889ad03ed12e.png)
![screenshot 2018-10-04 16 28 48](https://user-images.githubusercontent.com/4943380/46481023-b5bee600-c7f2-11e8-93c0-fe7d74ca1d3b.png)

**Comment by Cumol** [comment]
And another GUI question.
In the above image there seem to be two red ROIs in the correlation map. One a clear circle and another, left to it that is somehow dotted.

In the enhanced (or only ROI view) there is only one red ROI visible.

Is this a glitch or something else happening?
![screenshot 2018-10-04 16 33 40](https://user-images.githubusercontent.com/4943380/46481268-51505680-c7f3-11e8-9609-0e8a8124fdba.png)
![screenshot 2018-10-04 16 33 49](https://user-images.githubusercontent.com/4943380/46481275-544b4700-c7f3-11e8-8d09-620b9427181a.png)

**Comment by carsen-stringer** [comment]
The circles are the size of the estimated radius of the ROI. In your first example there's an outlier pixel that was picked up that the circle is encompassing. If you run with connected=1 then the ROIs will be connected only.

Unfortunately the last two look like bugs. The first one, the overlapping may not be working right - flip the ROI back and forth a couple times to make sure that the size is right (this brings it to the front of the masks). Sorry I'll have to debug that. No idea about the second example -- is it showing up in the normal ROI view (no background)?

**Comment by Cumol** [comment]
The analysis was always run with connected = 1. So I am not supposed to see any flying pixels...

Flip-flopping the ROI didn't help. It is usually a problem when I have completely overlapping ROIs

The last one does not show up in the "No Background" option but only in the correlation map. I am also not able to click on it.

**Comment by carsen-stringer** [comment]
Is that ROI on the "not cells" side? I have a lot of issues with the correlation map view in terms of taking care of overlaps with outlines so there certainly could be bugs in that view, sorry.

**Comment by Cumol** [comment]
The last ROI (with the discontinued line) does not show up in the "not cells" side.

Don't be sorry. Thank you for making (and maintaining) a straight forward pipeline that seems to work with my simple data and doesn't need me sitting on a cluster :) I am just trying to make it as best it can be (without having much of a clue about python programming)

**Comment by carsen-stringer** [comment]
The overlaps shouldn't be messed up anymore in the non-correlation map views. The correlation map view also seems to be bug free :D but if there are more than 3 cells on top of each other, then things may get messed up. This shouldn't happen often though.

The circling of cells in the mean img (when you click on them) will remove color from ANY pixels that are related to that cell, so things may change when you click on it (if it's underneath another cell) - watch what happens to this pink cell when it gets clicked on:
![image](https://user-images.githubusercontent.com/15067541/47969594-d8d5f300-e047-11e8-9853-e06f5b6d8535.png)
![image](https://user-images.githubusercontent.com/15067541/47969597-ec815980-e047-11e8-8683-b337b3599b80.png)

The mysterious cell though that shows up only in the correlation map view is weird though and not sure how that happened still

**Comment by Cumol** [comment]
@carsen-stringer Thank you for the updates, the GUI is less buggy now :)

I still get the occasional "1 pixel cell" that are not obvious. But I am able to find them in the visualization view as they usually are not really cells.

A more important issue is when there are cells stacked on top of each other. Meaning, nearly the same ROI size, different colors and on top of each other (matching exactly). I usually miss those as I am not able to find them that easily without checking every cell manuall (sending it to "non-cell" and then back).

Attached is an example:
![screenshot 2019-01-24 10 27 32](https://user-images.githubusercontent.com/4943380/51668534-b4444400-1fc2-11e9-8fbb-cb4e1e2dce4d.png)

![screenshot 2019-01-24 10 26 33](https://user-images.githubusercontent.com/4943380/51668485-94148500-1fc2-11e9-819b-6b50d1349bb5.png)

the upper part shows a cell that I have on the "is cell" side, and below is the cell on the same stop but on the "non cell" side. Before finding out, they were both on top of each other on the "is cell" side.

Is there a way to avoid this? Or better, some option to show ROIs that show more then X overlap?

**Comment by carsen-stringer** [comment]
Yeah these overlaps are a problem. They are a consequence of some normalizing that we're doing in the cell extraction procedure. We're hoping this problem will be solved in an upcoming algorithm update, so that they will no longer be a problem (and require a graphical solution as you suggest). The algorithm should also be able to better find cells of different sizes like you have in your recordings. I'll let you know when this version is updated.

In the meantime if you set "max_overlap"=0.5, then any cell that overlaps more than 50% with another ROI will be thrown out. And/or you can set "allow_overlap"=1 so that cells' signals are computed from ALL their pixels, not just the ones that overlap - if "allow_overlap"=0, any overlapping pixels are not used to compute the fluorescence traces. You can also run fewer iterations of cell extraction and see if fewer overlapping ROIs are extracted (ops["max_iterations"]).

**Comment by Cumol** [comment]
Is it possible that there was a change in the algorithm from say version 0.3 to 0.4? I am somethow getting many more ROIs connected to long processes (which are in some cases indeed their own processes) or ROIs only made out of neuropili since updating recently.

![screenshot 2019-02-18 14 25 17](https://user-images.githubusercontent.com/4943380/52953937-26713400-3389-11e9-949d-c60f315af294.png)

**Comment by carsen-stringer** [comment]
I'm going to close this issue as discussion has continued in another issue with using 'sparse_mode' and this algorithm gets fewer overlaps for the most part.
