### ISSUE TITLE
FEATURE: Extract signal from manual segmentation via ImageJ

### ISSUE THREAD

**Issue by just-meng** [MouseLand/suite2p#1045]
### Feature you'd like to see:

I need to do manual segmentation, because my FOV includes both somata and dendrites (trunk and thin branches). Since it is sparse, it is easier for me manually draw and annotate the ROIs instead of figuring out the optimal set of parameters for automated segmentation. My workflow is to use suite2p for registration, ImageJ for segmentation, and python script to extract the signal.

However, I wish to use suite2p to explore my data and look at the traces. It would also be very nice, if I could upload the RoiSet.zip from ImageJ after manual segmentation and suite2p would extract both F and Fneu based on my ROIs. 

Could this be implemented as new feature or is there a workaround that I could try out myself?

### Attempted alternative approaches:

As described above.

**Comment by chriski777** [comment]
Hi @just-meng, sorry for the late reply. We don't have this specific feature you describe but I think this [link](https://suite2p.readthedocs.io/en/latest/gui.html#manual-adding-of-rois) might be helpful for manually adding ROIs. You can add your ROIs then press extract ROIs to get out the F and Fneu for all your added ROIs. I'll close this for now but feel free to reopen this issue if this approach is not satisfactory.
