### ISSUE TITLE
Saving motion corrected registered video

### ISSUE THREAD

**Issue by Ayetheint** [MouseLand/suite2p#1052]
### Issue with current documentation:

Hi, I am using Suite2P GUI and use "View the registered binary" to visualize the registered video.
Could anyone suggest how to save the motion corrected video using GUI?
Thanks.

**Comment by chriski777** [comment]
Hi @Ayetheint, if you run `suite2p` again with the `reg_tif` parameter set to 1: 
<img width="1192" alt="pic" src="https://github.com/MouseLand/suite2p/assets/10649054/0b7c88b2-e997-48e2-99a9-eb69d0142c9f">
you should find a tiff file of the registered output in your suite2p output directory. Feel free to reopen this issue if you run into any other problems!

**Comment by Ayetheint** [comment]
Hi, Thanks for response @chriski777  ... I did what you suggested. I didn't get .tiff file in output directly.

**Comment by chriski777** [comment]
Just to be clear, is there no  `../suite2p/plane0/reg_tif` directory?

**Comment by Ayetheint** [comment]
I re-ran again. Now I could get the registered .tiff.  We can close the case. Thank you!

**Comment by chriski777** [comment]
Awesome, glad to hear that!
