### ISSUE TITLE
gui mean image

### ISSUE THREAD

**Issue by tehrensbaker** [MouseLand/suite2p#106]
Hello, I opened the stat.npy in the gui and found that a) the displayed mean image looks really different from my imaging FOV b) the displayed mean image seem to be more extended than the ROIs, mean_enhanced, and the correlation map. I'm attaching them in the comments. Is it something wrong with my setting? Many thanks!!

**Comment by tehrensbaker** [comment]
My mean imaging FOV:
![fov](https://user-images.githubusercontent.com/43807433/46655753-5b33da00-cba4-11e8-8068-8fddd2bb42a5.JPG)

mean image in the GUI
![mean](https://user-images.githubusercontent.com/43807433/46655810-7ef72000-cba4-11e8-84a0-2607ee96d682.JPG)

**Comment by tehrensbaker** [comment]
ROIs
![rois](https://user-images.githubusercontent.com/43807433/46655832-8fa79600-cba4-11e8-9d90-910f23cb4024.JPG)

mean enhanced
![mean_en](https://user-images.githubusercontent.com/43807433/46655844-97ffd100-cba4-11e8-8074-9d04f895b513.JPG)


correlation map
![corr](https://user-images.githubusercontent.com/43807433/46655860-9df5b200-cba4-11e8-8b09-457180434e7d.JPG)

**Comment by marius10p** [comment]
Looks like your tiffs might be int16, is that true? I am not sure we treat those correctly, we usually expect uint16.

**Comment by carsen-stringer** [comment]
Could you please share a tiff so we can test it? Thanks

**Comment by carsen-stringer** [comment]
This is super weird. I'm not sure how that happened! I downloaded your tiff and ran suite2p with the default run settings (from the github) and it worked fine. There may have been a bug in the version of suite2p you were using that has now been fixed (we are now forcing int16). Here's what the output of the tiff you sent me looks like:
![image](https://user-images.githubusercontent.com/15067541/47856707-348d4b80-ddbe-11e8-9789-c391119ec77f.png)

To use the github version of suite2p (in case you don't know already), you download the folder and then change directories into that folder and run "python -m suite2p" from there. Also it looks like there is some non-rigid motion in the tiff, so I'd recommend trying out non-rigid registration (set 'nonrigid'=1).

**Comment by tehrensbaker** [comment]
Yes works now after I cloned the github version. Thanks a lot and sorry for the hassle!

**Comment by carsen-stringer** [comment]
no problem not a hassle :) please reopen this issue if it's still messing up

**Comment by tehrensbaker** [comment]
Hello again, may I ask how to check if the non-rigid registration has corrected all the non-rigid motion? Thank you!

**Comment by tehrensbaker** [comment]
Hello, I've tried the non-rigid registration that you have recommended me to do. I'm just wondering if you have any advice on how much 'pixel shift' shown in the 'registration metrics' would mean the motion is acceptable? Also what is the y axis of the 'shift plot' in the 'view registered binary', and what would be an acceptable range for that? Thank you so much.

**Comment by marius10p** [comment]
If you "play" the third plot in the GUI you will get a sense of the pixel shift for that PC. Generally, for a good 2p recording it gets down to 0.1-0.2 nonrigid, and near 0 rigid shift. It can be larger if patches of the image are quite dark, because the metric reports maximum pixel shifts for patches across the FOV.

**Comment by tehrensbaker** [comment]
Thank you that's very helpful! Might there be a way to exclude a specific PC if the pixel shift is >0.2 nonrigid for that PC? Empirically what would be be the maximum pixel shift acceptable for a cellular recording? 

One a side note, if I remember right, the registration in the MATLAB version includes both rigid and nonrigid by default - does the MATLAB version also have the function to check the maximum pixel shift?

Thank you very much again for answering these questions!
