### ISSUE TITLE
ROIs not showing

### ISSUE THREAD

**Issue by mtvrdic1** [MouseLand/suite2p#1063]
### Describe the issue:

When I open suite2p the ROIs do not show up. I have tried this across different recordings and I get the same thing. All other features are there. Can you help?

### Reproduce the code example:

```python
stat.npy file was loaded using the gui
```

### Version information:

suite2p v0.14.2

**Comment by chriski777** [comment]
Hi @mtvrdic1, how many ROIs are detected by suite2p? Have you tried pressing spacebar? Can you send a screenshot of what you see in the GUI?

**Comment by oterocoronel** [comment]
I'm also having the same issue. I've used previous versions of suite2p just fine, so I guess it is a recent update? I can still 'click' on the GUI and get the traces of the different invisible ROIs

![image](https://github.com/MouseLand/suite2p/assets/78885453/8fef2011-1513-4609-9f91-13443d562656)

**Comment by chriski777** [comment]
Hi @oterocoronel, what machine are you using? This is the latest version of suite2p, correct?

**Comment by fieldsch98** [comment]
@chriski777  I too am having the same issue. Just downloaded the latest version of the suite2p GUI today and tried to use it, then encountered this issue. I had a colleague load the same stat.npy file into their (old) version of suite2p and it worked no problem. I believe I'm running windows 10 on a desktop built for large analyses. Let me know if you need more info, thanks

**Comment by fieldsch98** [comment]
@chriski777  Also, yes I've tried pressing space bar and my colleague who is very familiar with suite2p tried helping out but could not figure it out. There were ~4400 detected ROIs. Can provide a screenshot tomorrow but it's quite literally a blank grey screen where there should be ROIs, but it still shows the fluorescence traces at the bottom

**Comment by chriski777** [comment]
Thanks for your quick replies, everyone! Can y'all try installing the latest github version of the code? 
```
pip install git+https://github.com/MouseLand/suite2p.git
```
Do the ROIs still not show up? I think we added a fix to this but we just haven't made a new pip release yet.

**Comment by fieldsch98** [comment]
Yes I will try tomorrow morning and report back, thanks.

**Comment by oterocoronel** [comment]
Worked for me, thank you!

**Comment by fieldsch98** [comment]
@chriski777 Unfortunately this did not seem to work for me, but I can hopefully provide some information that might explain why. One question though, do I literally just type "pip install git+https://github.com/MouseLand/suite2p.git" into Anaconda to do this new installation? Without uninstalling the old one? I am very unfamiliar with python programming so please excuse my ignorance. In any case, I did exactly that and it seemed to mostly work with a few warnings at the end about certain files not being on path. I've pasted the output into a google doc here

After installing this latest github version of code and restarting the computer, the GUI seems to behave the exact same as before. Everything except the ROIs work. One additional thing that I noticed is that every time I hit the space bar to toggle ROIs on or off (even thought they're always off) I get the following two lines of code in my Anaconda window:
"QGraphicsScene::removeItem: item 0x1a3aa25e260's scene (0x0) is different from this scene (0x1a3ab427400)
QGraphicsScene::removeItem: item 0x1a3aa264500's scene (0x0) is different from this scene (0x1a3ab427400)"

I am unsure what these mean or if it's helpful in diagnosing the issue. Let me know if you have any ideas though, thank you!

**Comment by chriski777** [comment]
No worries, @fieldsch98! Thanks for sending a log of the output. I've noticed that you ran the pip install command in your base environment: 
```(base) PS C:\Users\cfiel>```
You should instead run it in your suite2p environment. Please try the following steps: 
```
conda activate suite2p
pip install git+https://github.com/MouseLand/suite2p.git
```
The pip install command should automatically replace the version of suite2p you have installed so there is no need to uninstall.

**Comment by chriski777** [comment]
Awesome! I'll close this issue for now since it should be fixed in the latest pip version. Feel free to reopen if the issue persists!
