### ISSUE TITLE
code formatting

### ISSUE THREAD

**Issue by hrouault** [MouseLand/suite2p#107]
Would you consider increasing the compliance with PEP-8?
I put `gui2p.py` through `black` and can add a pull request if you'd like.
I can also add a git hook with `flake8`, but that would require modifying all the other files first.

**Comment by marius10p** [comment]
For simple things, sure, but if it's too much work I think we should leave it for an eventual refactoring.

**Comment by carsen-stringer** [comment]
I'm happy to change all the files to this correct format (I liked the change you made to gui2p) if it's the same changes throughout -- I just would prefer that variable and function names don't change

**Comment by hrouault** [comment]
If you want to do the same on the other files, you cun run the `black` fixer on all the `.py` files. This does not correct all the PEP-8 recommendations though. You would have then to run `flake8` and correct manually what remains.
Then one could add a git hook to make sure that all the commits comply with PEP-8. Let me know whether you want me to help with that.
