### ISSUE TITLE
BUG: Suite2p trouble on rendering the GUI at Ubuntu20.04

### ISSUE THREAD

**Issue by Kim-HaYeon** [MouseLand/suite2p#1071]
### Describe the issue:

I installed the GUI version of suite2p and encountered the problem. 
I'm using Ubuntu20.04 as server computer and TigerVNC to view it in my local computer (Windows 10)

I found a few solutions same as my problem. 
1. https://www.reddit.com/r/linux4noobs/comments/kubglu/comment/gmmrwy9/
2. https://github.com/MouseLand/suite2p/issues/797

What I did for solving my problem is,
1. `ln -s  libxcb-util.so.0.0.0  libxcb-util.so.1`
2. `sudo apt-get install libxcb-xinerama0`
3. `pip uninstall PyQt6` >> `pip install PyQt5`
4. Download libxcb-util1_0.4.0-0ubuntu3_amd64.deb  (manually from https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libxcb-util1_0.4.0-0ubuntu3_amd64.deb.html) and run `sudo dpkg -i libxcb-util1_0.4.0-0ubuntu3_amd64.deb`

However none of these solved my case. This is my situation and any advice for solving this problem would be greatly appreciated.

### Reproduce the code example:

```python
suite2p
```

### Error message:

```shell
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

### Version information:

suite2p v0.14.4.dev9+gf6d6c7d

**Comment by chriski777** [comment]
Hi @Kim-HaYeon, I don't think this is a suite2p-specific issue but rather a system configuration issue. Things get tricky when you try to run a GUI with the server set-up you mention here. It seems the folks in the QT/tiger VNC community might be more helpful: https://forum.qt.io/topic/115064/qt-qpa-xcb-could-not-connect-to-display. 

I'd suggest looking for a way to make sure the tigerVNC app you're using properly forwards the graphical output of suite2p to your local computer. This link could potentially be helpful..? https://forum.qt.io/topic/134114/error-when-launching-rqt/9. I'll be closing this issue as we don't know too much about tigerVNC and forwarding graphical outputs.
