### ISSUE TITLE
Manual labeling issues

### ISSUE THREAD

**Issue by Kojot1444** [MouseLand/suite2p#1076]
### Describe the issue:

Hi,
I am using the latest version of suite2P and getting some issues with the manual labeling option. In the manual labeling interface the image appears in a smaller size  so that the cells on the edges are not visible and can not be labeled. I am attaching the  screenshots below. 
An other question, I would like to use manual labeling option to track the same cells collected at different days.  Is there a way to save the Ids of the marked cells?  So that the cell that  I mark first would have  Id1 and so on?

![Capture](https://github.com/MouseLand/suite2p/assets/73760887/a46bef70-35bd-4c4a-ac7d-5b825e615f88)
![Capture_manual labling](https://github.com/MouseLand/suite2p/assets/73760887/36d8b473-1f9d-4413-b450-63155684b07f)

Thanks a lot!

### Reproduce the code example:

```python
I do not get any errors in the code
```

### Version information:

v0.14.0

**Comment by chriski777** [comment]
Hi @Kojot1444, for the manual labeling issue, you can try playing with the `spatial_taper` parameter as it determines the number of pixels that are ignored for analysis on the edges. You can try lowering it a bit to see if you can get the pixels involved in the cells you want to manually add. There is a tradeoff though between including more pixels in the edges and the quality of the registration so keep that in mind! 

As for your second point on being able to have labels across multiple days, we don't explicitly yet have features to accommodate that. One thing you can do is just run the datasets for multiple days together through suite2p. Then, your labels will be consistent across days. This assumes though that the FOV is roughly similar across days.

**Comment by Kojot1444** [comment]
Hi,
thank you for reply! I am using 2P and gCamp8m.  Is there any other parameters for 2P that  I could change  for analysis on the edges?
Thanks!

**Comment by RichieHakim** [comment]
For tracking ROIs over multiple sessions: https://github.com/RichieHakim/ROICaT

**Comment by Kojot1444** [comment]
Thanks a lot! Cool stuff!

**Comment by Kojot1444** [comment]
> For tracking ROIs over multiple sessions: https://github.com/RichieHakim/ROICaT

Thanks a lot! Cool stuff!

**Comment by Kojot1444** [comment]
Thanks a lot!

**Comment by chriski777** [comment]
Closing since the issue seems to have been addressed(?).
