### ISSUE TITLE
FEATURE: operating extraction on cropped region

### ISSUE THREAD

**Issue by jingxuanf0214** [MouseLand/suite2p#1098]
### Feature you'd like to see:

I am not sure if this can be done now, so if it already has I would also love to know how to access it. Basically, I am working in fruit fly system. The kind of 2p imaging data we get is not signals filled in whole field of view (filling the square for example). So my image looks like a bright region of structure on a black background. And if I just input this image for extraction it finds a lot of rois in the background. 
![Screen Shot 2024-02-23 at 11 49 07 PM](https://github.com/MouseLand/suite2p/assets/66086600/576c913a-2760-435f-84af-c94cdb739950)

### Attempted alternative approaches:

I haven't tried intensively. I think I could crop to small pieces by hand and run on each pieces. But I think it would be nice to be integrated in a pipeline.

**Comment by chriski777** [comment]
Hi @jingxuanf0214, I'm not sure I understand what your request is. When you use suite2p, the pipeline should perform the extraction on all of the ROIs you've enclosed in the rectangle as long as suite2p identifies them as ROIs. You can access them by getting the ROI numbers for the ROIs in the rectangle you made. You should then be able to find the corresponding fluorescence traces and spikes for these ROIs in the `F.npy` and `spks.npy` files, respectively.

**Comment by chriski777** [comment]
Closed due to inactivity. Feel free to reopen if your question hasn't been answered @jingxuanf0214!
