### ISSUE TITLE
BUG: error when running suite2p

### ISSUE THREAD

**Issue by Monodia97** [MouseLand/suite2p#1103]
### Describe the issue:

Hello, I met errors after updatng suite2p. How can I resolve it?Thank you
![error in suite2p](https://github.com/MouseLand/suite2p/assets/80382483/107de730-d64e-4c70-8742-b7994d224460)

### Reproduce the code example:

```python
python -m suite2p
```

### Error message:

```shell
Traceback (most recent call last):
  File "D:\cbj\Anaconda\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 441, in run_S2P
    pretrained_model_path = model_path(pretrained_model_string, 0, True)
TypeError: model_path() takes from 1 to 2 positional arguments but 3 were given
```

### Version information:

suite2p v0.14.3

**Comment by chriski777** [comment]
Hi @Monodia97, do you mind installing the Github version and seeing if that fixes it for you? I believe we fixed this in https://github.com/MouseLand/suite2p/issues/1093 but we might not have published a new release with this update.

**Comment by chriski777** [comment]
Hi @Monodia97, this should now be fixed in the latest version that should be deployed on pip soon. Please try reinstalling your suite2p package and let us know if this issue persists! I will close this issue for now.
