### ISSUE TITLE
Error when run ops file

### ISSUE THREAD

**Issue by KKroba** [MouseLand/suite2p#1105]
### Describe the issue:

When I run ops file in suite2p in python, it shows:Traceback (most recent call last):
  File "D:\ml\venv\lib\site-packages\suite2p\gui\rungui.py", line 441, in run_S2P
    pretrained_model_path = model_path(pretrained_model_string, 0, True)
TypeError: model_path() takes from 1 to 2 positional arguments but 3 were given

### Reproduce the code example:

```python
Traceback (most recent call last):
  File "D:\ml\venv\lib\site-packages\suite2p\gui\rungui.py", line 441, in run_S2P
    pretrained_model_path = model_path(pretrained_model_string, 0, True)
TypeError: model_path() takes from 1 to 2 positional arguments but 3 were given
```

### Version information:

newest

**Comment by chriski777** [comment]
Hey @KKroba, do you mind installing the Github version and seeing if that fixes it for you? I believe we fixed this in #1093 but we might not have published a new release with this update.

**Comment by Milamber64** [comment]
Hello, 

We use suite2p all the time for our imaging analysis and love the software. We were getting a new student up and running with the software this week when we ran into this exact same issue. I would be interested to know how to resolve this issue as all the solutions we attempted have failed at this time. I will try the solution you linked in your comment.

**Comment by KKroba** [comment]
Hi,

I install it from GitHub again and solve it, hope it will help u.

Thanks

Harrison Stratton ***@***.***>于2024年3月12日 周二16:27写道：

**Comment by chriski777** [comment]
Great, glad to hear @KKroba! I'll close this issue and create a new release.
