### ISSUE TITLE
BUG: model_path() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by lea-danics** [MouseLand/suite2p#1108]
### Describe the issue:

I face an error when I'm trying to run suite2p form GUI.
I set the data_path where my .tif files are located (C:\Users\danic\CaImaging\tiffiles\green) and press RUN, but nothing happens, and in terminal window the below copied error pops up.
(I tried with .h5 file as well)
Could you please help me, what would be the problem?

### Reproduce the code example:

```python
loaded default ops
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\danic\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 441, in run_S2P
    pretrained_model_path = model_path(pretrained_model_string, 0, True)
TypeError: model_path() takes from 1 to 2 positional arguments but 3 were given
```

### Version information:

suite2p v0.14.3

**Comment by bbaserdem** [comment]
I'm having the exact same issue; trying to run as described in the [tutorial page](https://github.com/MouseLand/suite2p/blob/main/tutorial/tutorial.md).

**Comment by chriski777** [comment]
Hi all, this should be fixed in the newest release on pip. Can y'all reinstall suite2p and make sure that the version you have is 0.14.4? I'll close this for now but feel free to reply and reopen this issue if the issue persists.

**Comment by bbaserdem** [comment]
That solves it. I just installed suite2p yesterday, and used `conda install` to install it which gave me `v0.14.3`. (Might have been an invisible mistake on my end, just started using anaconda to manage my environment.) Upgrading via pip within the `suite2p` environment solved my issue.
