### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by sonjablumenstock** [MouseLand/suite2p#113]
Hi,

I would like to use suite2p on on mac, however after installation and while trying to run on some images, I get the following errors (The program only gets to detecting the images):

Found 1000 tifs
>>>ERROR<<<
Traceback (most recent call last):
File "/anaconda3/envs/suite2p/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
"__main__", mod_spec)
File "/anaconda3/envs/suite2p/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/anaconda3/envs/suite2p/lib/python3.6/site-packages/suite2p/__main__.py", line 32, in <module>
suite2p.run_s2p.run_s2p(ops, db)
File "/anaconda3/envs/suite2p/lib/python3.6/site-packages/suite2p/run_s2p.py", line 144, in run_s2p
ops1 = utils.tiff_to_binary(ops)
File "/anaconda3/envs/suite2p/lib/python3.6/site-packages/suite2p/utils.py", line 254, in tiff_to_binary
ops1[j]['meanImg'] += im2write.astype(np.float32).sum(axis=0)
ValueError: operands could not be broadcast together with shapes (2,512) (2,512,512) (2,512)
===== 2018.10.18 16:10:01 =====
Interrupted by error (not finished)

Is there something I missed during installation?

**Comment by carsen-stringer** [comment]
This doesn't seem like an install error, it seems like your tiffs are not in a shape usually expected. Is this a multiplane recording? Could you share a tiff with us?

**Comment by sonjablumenstock** [comment]
Hi,
It is a time series recording in one plane and with one channel, taken with a ThorLabs B-Scope and the ThorLabs Imaging Software.
When I made a single tiff file (with ImageJ), containing the whole image series, suite2p started working and making the registration. However after 5-10 mins, my Mac (3,3 GHz Processor, 16GB RAM) runs out of memory and crashes.
Does my computer not meet some hardware requirements, or is the image size of the single file (1,2 GB) too big?

Thanks for your help!

[cid:D159F751-1864-410F-8C08-3DED89670CAA@neuro.mpg.de]

On 18. Oct 2018, at 17:00, carsen-stringer <notifications@github.com<mailto:notifications@github.com>> wrote:


This doesn't seem like an install error, it seems like your tiffs are not in a shape usually expected. Is this a multiplane recording? Could you share a tiff with us?

**Comment by carsen-stringer** [comment]
We accidently had the default batch_size in the GUI set to 1000. Is that what it is set to in your pipeline? It's under the "Registration" column. I'd try 200 frames, and if that's still problematic, 100 frames. If it still uses too much memory, you can turn off parallelization (set 'num_workers' = -1).

**Comment by carsen-stringer** [comment]
I'm going to close this issue because I think it's just a memory issue related to batch size, if it's still buggy please reopen this issue
