### ISSUE TITLE
Error in GUI  - Space in Users name

### ISSUE THREAD

**Issue by AMlsct** [MouseLand/suite2p#1141]
### Describe the issue:

Hi everyone!

I bring a problem previously reported in several other issues... But I installed earlier the latest version of suite2p v0.14.5, and I end up with that error on the GUI when I run my files.

error: unrecognized arguments: Lab\.suite2p\ops\ops.npy Lab\.suite2p\ops\db.npy

After reading all the threads, I think it's due to my user name... There is a space in the path.

Do you guys have any idea how I could fix this?

Thanks for your help!

Antoine

### Reproduce the code example:

```python
error: unrecognized arguments: Lab\.suite2p\ops\ops.npy Lab\.suite2p\ops\db.npy
```

### Version information:

V.0.14.5

**Comment by EricMartineau3** [comment]
For anyone having this issue, comment 3 lines and uncommenting another in C:\...\Anaconda3\envs\suite2p\Lib\site-packages\suite2p\gui\rungui.py did it.


lines 451-457
`#cmd = f"-u -W ignore -m suite2p --ops {ops_file} --db {db_file}"`
`#print("python " + cmd)`
`#self.process.start(sys.executable, cmd.split(" "))`
`self.process.start('python -u -W ignore -m suite2p --ops "%s" --db "%s"' %`
`                   (ops_file, db_file))`

Guess they left the correct line there just in case
