### ISSUE TITLE
New s2p version cannot handle lists of h5 files

### ISSUE THREAD

**Issue by oterocoronel** [MouseLand/suite2p#1149]
### Describe the issue:

If "h5py" in ops is a list, then the function find_files_open_binaries turns it into a list of lists when doing:

`fs = [fs]`

This causes the following error: 

```
Traceback (most recent call last):

  Cell In[1], line 258
    ops_out = suite2p.run_s2p(ops=ops_folder)

  File ~\miniforge3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:501 in run_s2p
    ops0 = convert_funs[ops["input_format"]](ops.copy())

  File ~\miniforge3\envs\suite2p\lib\site-packages\suite2p\io\h5.py:54 in h5py_to_binary
    with h5py.File(h5, "r") as f:

  File ~\miniforge3\envs\suite2p\lib\site-packages\h5py\_hl\files.py:536 in __init__
    name = filename_encode(name)

  File ~\miniforge3\envs\suite2p\lib\site-packages\h5py\_hl\compat.py:19 in filename_encode
    filename = fspath(filename)

TypeError: expected str, bytes or os.PathLike object, not list
```

The issue can be solved by replacing:

`fs = [fs]`

with:

```
if not isinstance(fs, list):
                fs = [fs]
```

I had not experienced this issue in the previous suite2p version

### Reproduce the code example:

```python
ops_out = suite2p.run_s2p(ops=ops_folder)
```

### Version information:

v0.14.4

**Comment by chriski777** [comment]
@oterocoronel, thanks for bringing this to our attention! We've added a general fix that addresses this issue with `h5py`'s. I've checked this fix works with both lists of h5pys and a string corresponding to a single h5py. 

This change is available in the `dev` branch and will soon be integrated into main. Feel free to re-open this issue if problems persist.
