### ISSUE TITLE
save_mat Output Setting 

### ISSUE THREAD

**Issue by cmketchmark** [MouseLand/suite2p#115]
Hi, 

We are trying to change the save_mat output setting to true. In the GUI, it looks like this is a binary input where 0 is false. I tried changing the input to 1 but this is still outputting .npy files. What should I change the save_mat parameter to in order to get the .mat files? 

Thank you so much!

**Comment by carsen-stringer** [comment]
You will always get .npy files from the pipeline (they are output so you can use the GUI). The matlab file is called "Fall.mat" and it should be in the folder with all of the other files:
![image](https://user-images.githubusercontent.com/15067541/47855886-20e0e580-ddbc-11e8-9473-53d8dd421d8f.png)

Let me know if you didn't get an "Fall.mat" file when you ran it.

**Comment by cmketchmark** [comment]
Got it! Thank you so much.
