### ISSUE TITLE
nframes not updated if do_registration==0

### ISSUE THREAD

**Issue by neurodroid** [MouseLand/suite2p#117]
We're running into an issue if we want to perform segmentation on data that we've registered outside of suite2p (or if the data does not require registration).
When setting `do_registration` to `0`, `ops['nframes']` is going to be wrong in `celldetect.get_mov` (in our example file, 750 instead of 2750). We have been able to fix this error by adding the following code in `run_s2p.py` at around l.173:
```
        if not flag_binreg:
            ops1[ipl] = register.register_binary(ops1[ipl]) # register binary
            np.save(fpathops1, ops1) # save ops1
            print('time %4.4f. Registration complete for %d planes'%(toc(i0),ni))
+       else:
+           ops1[ipl[0]]['nframes'] = register.get_nFrames(ops1[ipl[0]])
```
I'm reluctant to file a pull request with this change as I don't think it is compatible with `num_workers_roi != -1`. You may have to iterate over all `ipl` or something similar?

**Comment by carsen-stringer** [comment]
Sorry for the delay in responding to this. Are you feeding in registered binaries or registered tiffs?

**Comment by carsen-stringer** [comment]
Your fix works, but 'nframes' should have been correct from utils.tiff_to_binary. I've fixed it now so that the 'nframes' that gets assigned to ops in utils.tiff_to_binary should be the correct one. Let me know if it still doesn't work.

**Comment by carsen-stringer** [comment]
This has been tested for awhile, so I'm going to close the issue, please reopen if it's still a problem for you
