### ISSUE TITLE
load detected cells data from python version to matlab verssion

### ISSUE THREAD

**Issue by rajatsaxena** [MouseLand/suite2p#120]
Can the cells detected in python suite2p version be loaded to look into the Matlab GUI? It will be nice to have this cross-compatibility. Thanks!

**Comment by carsen-stringer** [comment]
I've added a function to the matlab repository to do this:
https://github.com/cortex-lab/Suite2P/blob/master/convert_Fall.m

Note, by looking at this function, you'll see that the python cells are embedded in the FULL field of view, not the cropped area like the matlab version. This hopefully means things are less confusing overall, but just keep that in mind.

**Comment by carsen-stringer** [comment]
Did you update the matlab repository? I had to change some things to make sure this worked.

**Comment by rajatsaxena** [comment]
With the updated matlab repository I was able to load the data. Thanks a lot! Although the `roi `window is rotated (90 degree counterclockwise) when compared to the `corr `window in matlab. I have attached screenshot below. Thanks for your quick response. 

![capture1_roi](https://user-images.githubusercontent.com/5181888/49240314-c1c1c100-f3b9-11e8-8835-4162eaa03472.PNG)
![capture2_corr](https://user-images.githubusercontent.com/5181888/49240315-c25a5780-f3b9-11e8-9d99-9322c006ad66.PNG)

**Comment by carsen-stringer** [comment]
Oops I had ypix and xpix swapped. Try the convert_Fall conversion file again, it's been updated.

**Comment by carsen-stringer** [comment]
Sorry I should have been testing a non-square recording :P try it out now.

**Comment by rajatsaxena** [comment]
It works perfectly now! I had one last question if there is a similar script for loading data edited in matlab to python as well?
You can close the issue. Thank you for the quick responses!

**Comment by carsen-stringer** [comment]
To bring it back to the python version, I think you just want to bring back the cell labels? The python GUI only uses "iscell.npy" to decide which cells are on the left and the right. It's a matrix that's ncells x 2 where the first column is 0,1's and the second column is probabilities. In a _proc.mat file, stat has 2 fields 
[stat.iscell] and [stat.cellProb]. Save these as "iscell.npy" (you will need Nick Steinmetz's utility https://github.com/kwikteam/npy-matlab):

`
icell = [dat.stat.iscell];
cellProb = [dat.stat.cellProb];
iscell=[icell(:) cellProb(:)];
writeNPY(iscell, 'iscell.npy')
`

I've added these lines of code to convert_Fall.m.
