### ISSUE TITLE
Export only accepted cells 

### ISSUE THREAD

**Issue by mcarbotano** [MouseLand/suite2p#121]
Hi there, I was wondering if there is an option in the GUI to only export or write in the F.npy (or the Fall.mat) file the cells detected as such. I'm still getting used to the GUI but I can not find my way around it. After the initial cell detection I discard some to the not cells side, but that selection is not transferred to the files containing the information. I do all the post processing in R and is really difficult to tell which cells are the ones accepted as such. 
Thanks!

**Comment by carsen-stringer** [comment]
Ah I should have answered this one first :) Yeah so only "iscell.npy" changes when you flip cells so unfortunately you'll have to load in the "iscell.npy" file after you do the processing. It is too slow to rewrite F.npy or Fall.mat after each cell flip, so only "iscell.npy" gets changed.

**Comment by carsen-stringer** [comment]
Btw in case it's not in the documentation, "iscell.npy" consists of two columns, the first column iscell[:,0] contains 0's and 1's corresponding to which side you put the cell on in the GUI. The second column are the probabilities that the cell is a cell based on the default classifier.

**Comment by carsen-stringer** [comment]
Glad you like it :) I'm going to close this issue for now, please reopen it if you're still having this problem
