### ISSUE TITLE
Export to csv?

### ISSUE THREAD

**Issue by mcarbotano** [MouseLand/suite2p#122]
Is it possible to add the option to save the results to cvs (one or multiple)? Something similar the the one already present in the GUI to save all in a matlab file.
Best

**Comment by carsen-stringer** [comment]
I'm not super familiar with csv's. What would make sense for those, a separate csv for each npy file?

But as a warning, if you make changes in the GUI as to which cells are cells/not cells, only the "iscell.npy" file will change, not the matlab file/ a csv file. So you'll have to be able to reload that file anytime you flip cells.

**Comment by carsen-stringer** [comment]
So do you still want me to make a csv saver? It won't be too hard

**Comment by mcarbotano** [comment]
No its fine,
Thanks!
