### ISSUE TITLE
GUI batch processing doesn't work

### ISSUE THREAD

**Issue by PhantomSpike** [MouseLand/suite2p#126]
Hi,

Thanks a lot for developing this superb software. I've just started to use it and it is really amazing. :)

I've just started using Suite2P on Python so maybe I am missing something but it doesn't seem possible to do batch processing of the data from the GUI.

I followed the instructions from this tread https://github.com/MouseLand/suite2p/issues/85 

"Batch processing has been added to the GUI. add data_path or h5 path and change settings and then click "save settings and add more (batch)" and then set up another recording and so on... "

When I tried to do that  by doing Terminal -> python -m suite2P -> File -> Run suite2p

I then add my first folder (e.g. Area01) and then there is no button "save settings and add more (batch)" in my GUI (See Picture 1). Not sure if there is something wrong with my copy or you guys have disabled it?

Anyways, I then proceed to add another folder with .tif files (e.g. Area02) and then I run "RUN SUITE2P" button. But it seems that Suite2P is taking all the .tif files and processing them together rather than processing them separately as Area01 and Area02. When I look at the traces they have been incorrectly processed together (See Picture 2).

Does this mean that if I want to processes batches the only way to do it through the suite2p/jupyter/run_pipeline_batch.ipynb notebook? I can run the processing here and then use the GUI on the already processed data to select the "Cells" and "Not cells"? That's still quite convenient (actually more similar to the Matlab Suite2P!) it would be just good to know whether I am doing something wrong with the GUI or it is simply not supported.

@marius10p @carsen-stringer  - Thanks a lot again for all of your hard work!

![example1](https://user-images.githubusercontent.com/23742907/49537438-ee497180-f8c0-11e8-99ad-1969ad77a613.png)
![example2](https://user-images.githubusercontent.com/23742907/49537445-f0abcb80-f8c0-11e8-8935-6c33e3070d24.png)

**Comment by carsen-stringer** [comment]
Sorry the documentation is currently matching the github folder version NOT the pip. I need to update the pip, but for now, please use the github version of the code by cloning the repository and running `python -m suite2p` inside the main folder (folder suite2p, not folder suite2p/suite2p)

**Comment by PhantomSpike** [comment]
Thanks a lot for the reply.

Now it is working fine when running directly from the command line and in the folder. :)
