### ISSUE TITLE
Change the O: "ROIs On" shortcut to something else

### ISSUE THREAD

**Issue by PhantomSpike** [MouseLand/suite2p#130]
Hi,

This is really a minor thing but it would make my life a lot easier if it can be done.

I like to toggle the shortcut  O: "ROIs On" quite often but I find it very inconvenient to press O on the keyboard. I normally use my right hand to click and my left to press the shortcuts so O is in a very awkward place. 

Is there any way to change it to something else not currently used e.g. space bar would be really nice?

Sorry to be a pain!

**Comment by carsen-stringer** [comment]
The space bar is a good idea (and was very easy to change), it's working in the github version

**Comment by PhantomSpike** [comment]
Thanks @carsen-stringer ! I really appreciate how quick you guys are and the thoughtful replies. It's great for the community. :)
