### ISSUE TITLE
GUI not showing results 

### ISSUE THREAD

**Issue by mcarbotano** [MouseLand/suite2p#132]
Hi, 
Reporting a bug. 
After updating to version 0.5.1 the GUI is no longer showing the results. Nothing to click to, its black. I can run the analysis but then there are not shown in the GUI (the same for opening older files). The problem is not happening with older versions, tried 0.5.0 and 0.4.9.
I'm on Linux Mint 19.
Best

**Comment by carsen-stringer** [comment]
Thanks for catching this bug! I pushed the fix to the github version, and version 0.5.2 should be working, please let me know if it's still buggy

**Comment by mcarbotano** [comment]
Its working great in 0.5.2 now
Thanks!
