### ISSUE TITLE
Introduce the 9 nonants back into the Python version?

### ISSUE THREAD

**Issue by PhantomSpike** [MouseLand/suite2p#133]
Hi,

It would be really helpful if it's possible to re-introduce the 9 nonants (9 quadrants?) that divide the FOV to be clicked into the Python version, same as the Matlab one. It is quite convenient to have a fixed routine as you go through the ROI manual selection. 

I know it is not a big deal to have to navigate manually but would really appreciate it!

Thanks a lot!

**Comment by marius10p** [comment]
We found the 9 quadrants to be a little confusing when switching from one to the next, but we'll try to bring it back as an optional feature. Panning and zooming tends to be faster for us, and the pyqtgraph interface works smoothly for that.

**Comment by PhantomSpike** [comment]
Hi,

Zooming works fine in general but it is harder to keep track of where you have been exactly. With the quadrants you can go a bit more systemically and make sure that you don't miss any cells.

It would be great if you can bring it back, yes. :)

Thanks a lot!

**Comment by carsen-stringer** [comment]
I've added this to the GUI - the buttons are in the upper right corner (sparse_mode branch)

**Comment by carsen-stringer** [comment]
this is now in the main branch / pip.  please try the latest version, and see the installation instructions on the readme
