### ISSUE TITLE
Mising outputs in Python version

### ISSUE THREAD

**Issue by QNeuron** [MouseLand/suite2p#134]
Hi,

First thanks a lot for developping and offering this awesome pipeline. We used the Matlab version and we are now transitionning to the Python version. I am a bit confused because two of the output variables in stat seems to be missing in the python version: 
 - stat.ipix
 - stat.neuropilCoefficient

Could you please let me know if there is a way to get these variables back, or if their names have changed ?

Thanks a lot,

**Comment by PhantomSpike** [comment]
Great question, was wondering the same thing!

**Comment by QNeuron** [comment]
Hi Marius,

Thanks a lot for your answer. We were also using a constant 0.7 for the neuropil correction, so we'll keep using that.

Thanks for the clarification about the indexing, it makes sense now. And once again, thanks for your great work !

**Comment by carsen-stringer** [comment]
I've added this to the documentation so I'm going to close this issue
