### ISSUE TITLE
best min_neuropil values to set

### ISSUE THREAD

**Issue by MariangelaP** [MouseLand/suite2p#136]
Hello,
we are acquiring neuronal fields at 512x512 pixels at zoom 2 with a 16X obj.
When running suite2p, we usually set our cells' diameter at 12, which is the same as the default value. We so far have also used the default min_neuropil diameter value of 350. For higher zoom acquisitions, would you just increase the min_neuropil value linearly? For example, we use diameter 17 when we have zoom 3 acquisitons. Would you use min_neuropil 495 in this case?

many thanks.

**Comment by MariangelaP** [comment]
Thanks Marius, this makes perfect sense.

**Comment by carsen-stringer** [comment]
I'm going to close this because it seems resolved, feel free to open it if you have more questions
