### ISSUE TITLE
A way to extract cell size?

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#137]
I was wondering if it is possible to get a cell size (or diameter in pixel) from the data of the ROIs

**Comment by carsen-stringer** [comment]
Do you mean before or after processing? We output the 'radius' of the cell in pixels which is estimated by fitting a 2D Gaussian to the cell mask (https://github.com/MouseLand/suite2p/wiki/Outputs#statnpy-fields). Is this what you had in mind?

**Comment by Cumol** [comment]
Yes, exactly. Thank you :)

**Comment by Cumol** [comment]
I went on to use the radius in the stat.npy file that the pipeline spits out and found out that all the radi (from any cell) are all the same. In my case, 7.26 px.

Is that a bug?

**Comment by Cumol** [comment]
It seems to be a bug in the older versions of suite2p but that does not happen in the newer versions. Sorry for the unneccesary notifications!

**Comment by Cumol** [comment]
Another question in that direction. How is it possible that a ROI has a radius of 0? I seem to have a few of those in each dataset, now that I am checking the stats.npy.

When I check their traces they all seem to be bad cells, that I would usually kick out in the GUI.

**Comment by carsen-stringer** [comment]
ah yes those are cells that are fully overlapping with other cells - they should have been thrown out I think ... set ops['max_overlap']=0.5 and that should get rid of some of them. Also set ops['allow_overlap'] = 1 to have cell traces computed from ALL the pixels (not just the non-overlapping ones) if you're getting too many crappy ROIs

**Comment by Cumol** [comment]
Shouldn't the radius that is calculated be independent of the trace calculation?

Or is it not showing the radius of the area used to calculate the trace?
