### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by sfailor** [MouseLand/suite2p#138]
Hi, I am seeing a strange error in registration that is unique to the python version of suite2p. When viewing the saved reg tifs I will find that registration is abysmal until a point where the plane incorrectly changes, after which it will register properly. We are using a more recent version of scanimage, so I wonder if this might be related?

**Comment by carsen-stringer** [comment]
that's not good, are you sure you're using the correct nplanes parameter? (just checking that you input this because the python version does not automatically check the header for the number of planes)

what format is the tiff? (uint16, int16?)

**Comment by sfailor** [comment]
nplanes is set correctly. The tiff format is int16.

**Comment by carsen-stringer** [comment]
has this always been an issue with the python version or is it a recent bug? does the same plane always start the tiff? does the first tiff have a different plane first than subsequent tiffs?

**Comment by sfailor** [comment]
I've only just started using it so I can't say whether it is recent or not.
I took a closer look at the registered tifs and it appears that it actually
changes planes several times and occasionally will register correctly for a
block of frames, but then changes plane again and stops registering. Happy
to share the tifs if you'd like to take a look.

**Comment by carsen-stringer** [comment]
can you check the tiff order? and yeah I can take a look at the tiffs too, maybe just the first three are enough?

**Comment by sfailor** [comment]
Registered correctly with the github version.
