### ISSUE TITLE
Custom ROI Mask Color

### ISSUE THREAD

**Issue by NDolensek** [MouseLand/suite2p#139]
Not really an issue, but would it be possible to expose the masking function to produce custom ROI mask colors?

I want to produce plots like in the GUI where a ROI average frame is overlaid with detected cellular ROI masks in different colors - I just want to be able to decide on the colors on my own based on analysis. Would it be possible to add a function to create a custom mask by passing a npy array of matplotlib color strings - at least in python?

**Comment by carsen-stringer** [comment]
Do you want each ROI to have a different color? Or each pixel in each ROI to have a different color? Either is doable. What kind of analysis is it? (is it the sort of thing other users might also want to use)

If your analysis is a correlation with a behavioral/stim trace, then that is already implemented (you can load a 1D npy file with a behavioral/stim trace and suite2p will compute the correlation of it with each ROI).

**Comment by NDolensek** [comment]
Yes, I'd like each ROI to have a different color.

Example use cases are: 
-labeling ROIs based on regression analysis results, especially with more than 1 regressor
-using a statistical threshold to select cells/ROIs responsive to different stimuli and labeling them in different colors to investigate spatial distributions
-measuring correlation to a behavioural trace that is sampled with a significantly higher sampling rate upsampling the flourescence traces for each ROI before analysis, or the opposite
-calculating a custom score assigned to each ROI


For now I'm making do with some python code I wrote but I think your overlay looks better and this would be a nice addition to the software.

**Comment by carsen-stringer** [comment]
try out the github version. the option is in the visualization menu under 'load custom hue' load a npy file with the same number of values as ROIs (length of stat) and they will become the hues of the cells (scaled to between 0 and 1) for the HSV map

it's added to the rastermap button - if you do rastermap then the colors will change and vice versa this will overwrite the rastermap colors

**Comment by carsen-stringer** [comment]
I've added this info to the wiki and I'm going to close this, please comment if you have any issues.
