### ISSUE TITLE
*copy built-in classifier to default classifier*

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/suite2p#141]
I think when suite2p is installed and called for the first time from within a script via run_s2p(), it aborts with: ERROR: incorrect classifier file. This is because it looks like its trying to load classifier_user.npy, but I think the directory suite2p/classifiers only contains classifier.npy per default.

**Comment by marius10p** [comment]
Sorry about that. Is this with the pip install? I wonder if we are creating the classifier file on the first GUI run. @carsen-stringer knows better.

**Comment by alex-attinger** [comment]
It happens both from the pip install and also when I clone it from github.

**Comment by carsen-stringer** [comment]
sorry for the delay in this I promise I will get to it this weekend. in the meantime, in your github version, make a copy of classifier.npy called 'classifier_user.npy' in the suite2p/classifiers folder as a work-around.

**Comment by carsen-stringer** [comment]
I've fixed this now, it will copy classifier.npy to classifier_user.npy if it doesn't exist in run_s2p.py

**Comment by carsen-stringer** [comment]
I'm going to close this issue as I think it's working fine, please comment if it's still a problem.

**Comment by Cumol** [comment]
Maybe this is related to this issue. I built and set my own classifier as default, and since then I am getting this error:

```
/home/generalubuntu/Downloads/suite2p-test/suite2p/suite2p/classifiers/classifier_user.npy
ERROR: incorrect classifier file

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-61516f5848fb> in <module>()
     37 
     38     # run one experiment
---> 39     opsEnd=run_s2p.run_s2p(ops=ops,db=db)

~/Downloads/suite2p-test/suite2p/suite2p/run_s2p.py in run_s2p(ops, db)
    209             print(classfile)
    210 
--> 211             iscell = classifier.run(classfile, stat)
    212             np.save(os.path.join(ops['save_path'],'iscell.npy'), iscell)
    213             # save as matlab file

~/Downloads/suite2p-test/suite2p/suite2p/classifier.py in run(classfile, stat)
     75     model = Classifier(classfile=classfile)
     76 
---> 77     flag = np.zeros(len(model.keys), 'bool')
     78     new_keys = []
     79     for j in range(len(model.keys)):

AttributeError: 'Classifier' object has no attribute 'keys'


```

**Comment by carsen-stringer** [comment]
We are going to change the classifier soon, right now the keys in sparse_mode are not the same as the built in. Sorry this will be broken for a bit

**Comment by Cumol** [comment]
Did this get fixed, btw?

**Comment by carsen-stringer** [comment]
no sorry this is still broken in sparse_mode

**Comment by Cumol** [comment]
For clarity, currently I am able to build a classifier from datasets ran with sparse_mode and also load it into the GUI.

The only issue is setting it as a default classifier for suite2p to run with during the pipeline.

**Comment by carsen-stringer** [comment]
oh I'm sorry I misunderstood. Does your "classifier_user.npy" have 'keys' when you load it yourself?
```
model = np.load('classifier_user.npy').item()
print(model['keys'])
```

**Comment by carsen-stringer** [comment]
I think you need to overwrite the user classifier with the default - we don't allow you to pull that one from github because it would overwrite your built-in settings. but because we added a new key this is a problem.
```
cp suite2p/classifiers/classifier.npy suite2p/classifiers/classifier_user.npy
```
then add data to this classifier and try running in the GUI. this worked for me.

**Comment by Cumol** [comment]
> print(model['keys'])

Sorry, I somehow forgot you answered this one, this is the output:
`
['skew', 'compact', 'npix_norm']`

**Comment by carsen-stringer** [comment]
what version of numpy are you using? I think the newer numpy's treat loaded dict's differently. I'm using numpy==1.14 and not getting this error

**Comment by Cumol** [comment]
I am using the same version as you. numpy 1.14

```
>>> np.__version__
'1.14.0'
```

**Comment by carsen-stringer** [comment]
Potentially it couldn't find the file. Is this the classifier that you've been loading and looking at: `/home/generalubuntu/Downloads/suite2p-test/suite2p/suite2p/classifiers/classifier_user.npy`?

This is the exception block that prints `ERROR: incorrect classifier file`
```
try:
            model = np.load(self.classfile)
            model = model.item()
            self.stats = model['stats']
            self.iscell = model['iscell']
            self.keys = model['keys']
            self.loaded = True
except (ValueError, KeyError, OSError, RuntimeError, TypeError, NameError):
            print('ERROR: incorrect classifier file')
            self.loaded = False
```

**Comment by carsen-stringer** [comment]
I finally found this bug!! it was in "save loaded as default" sorry all for the trouble! (see issue #192)
