### ISSUE TITLE
fft multicore slow on some PCs/CPUs

### ISSUE THREAD

**Issue by paulnaser** [MouseLand/suite2p#142]
Hi guys,

first off, thank you for this great software. It works wonderfully for my data except for one small problem. I can't get it to use the GPU. It maxes out 100% CPU but the GPU stays idle. I am running Windows 10 with a dual Xeon System and a Quadro GPU. Cuda tools are installed. 
I apologize in advance in case I have overread some important installation advice on how to get GPU support working.

Thanks in advance for your support.

Paul
![gpu_suite2p](https://user-images.githubusercontent.com/26045849/52127311-0a079480-2632-11e9-9720-17cb7c12187d.png)

**Comment by marius10p** [comment]
Hi Paul,

We don't have GPU support yet. We tried scikit-cuda briefly last September, but we couldn't get a good speedup, even from a high-end GPU. The pull request is still open. The only part where this speedup would help is in registration, so what we'd need is a good GPU-based fft. If anyone knows of one, we'd be happy to try it. 

Just out of curiosity, what kind of multi-core speedup for registration do you get on that system? You should also increase the batch_size from 200 to maybe 1000 or more, since you have plenty of RAM, and the fft is a little better with batch sizes above ~10-20. 

Cheers,
   Marius

**Comment by marius10p** [comment]
Thanks. What operating system are you on? We do get a significant speed up with parallelization, I am surprised that all your configurations don't. What size is your field of view, and do you use non rigid = 1 (the default).

**Comment by marius10p** [comment]
Also, could you please monitor how many cores are used when you set parallel to 0? I wonder if your fft is somehow linked against a multi-core version of fft. I'm almost sure the fft from numpy doesn't do that, but just in case. We've been exploring different fft versions recently and sometimes they behave strangely.

**Comment by marius10p** [comment]
Ok, then we'll definitely look into this. Let's keep this issue open until we have a chance to look at the fft multi-core behavior.

**Comment by paulnaser** [comment]
Thanks! Actually, even though its not using all of the computers resources, it works reasonably fast for me now that I've disabled multi-core, so thanks again for this cool software.

**Comment by kthcwd** [comment]
I think I am having the same issue. I am using Xeon(R) CPU E5-2640 v4 2.4 GHz on a windows 10 machine, also with a NVIDIA Quadro M4000. Using MATLAB 2016b we are sorting an expt with ~56000 frames in <1 hour. The same expt with the python version takes >8 hours... the python version is not using the cores, as described above...

**Comment by carsen-stringer** [comment]
We've made the development branch (**sparse_mode**) completely single-threaded. If you run it through the GUI then numpy and scipy will be set to be single-threaded. All parallelization is implemented using 'multiprocessing' pools, and therefore this interference between threads should (in theory) be absent. It runs significantly faster in ubuntu and windows. 'git checkout sparse_mode' to try it out.

**Comment by carsen-stringer** [comment]
if you want to run it in a notebook, then BEFORE importing numpy or scipy, say these commands:
```
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1" 
```

**Comment by carsen-stringer** [comment]
please try the latest version, and see the installation instructions on the readme. we've made everything parallel with numba instead of multiprocessing so registration should be much faster. DO NOT set the threads to 1

**Comment by carsen-stringer** [comment]
I'm going to close this because we've removed all 'multiprocessing' from the pipeline, so this should no longer be an issue
