### ISSUE TITLE
Load behavior or stim trace : How to convert matlab data into npy using matlab ?

### ISSUE THREAD

**Issue by kamo86** [MouseLand/suite2p#143]
Hi,

I don't code in Python and I would like to convert matlab data (.dat) to npy to be able to load it to the GUI.

Thanks for your help.

**Comment by marius10p** [comment]
Hi,  .dat is not a Matlab format, it's more likely a flat binary file. Are you able to load it into Matlab? If so, from Matlab you can write it the array to an NPY array with the writeNPY function in the [npy-matlab repository](https://github.com/kwikteam/npy-matlab). It will have to be a one-dimensional trace sampled at the same times as the frames in your recording.

**Comment by carsen-stringer** [comment]
I'm going to close this for now, please reopen this if you are having issues still
