### ISSUE TITLE
number of frames and x-axis for two channels 

### ISSUE THREAD

**Issue by KnightyOwl** [MouseLand/suite2p#144]
Hi,

I did a two-channel recordings, first channel is GCaMP, second channel is static tdTomato. The data are stored as tiff files in an interleave way with 2000 frames in total, 1000 for each channel. I did registration and align on the first channel, set the n_channel as 2. However, after run the pip, in the GUI it showed 2000 in the plot of x axis.

Does the pipeline deinterleave the 2 channels and traces automatically? Or do I have to deinterleave the F traces in python and replot it?

Thanks for developing this amazing tool!

**Comment by carsen-stringer** [comment]
sorry I had introduced a bug in the previous version! can you please 'pip install suite2p --upgrade' or run the github version and see if you have the same issue

**Comment by KnightyOwl** [comment]
> sorry I had introduced a bug in the previous version! can you please 'pip install suite2p --upgrade' or run the github version and see if you have the same issue

Thanks! This issue has been resolved.

**Comment by KnightyOwl** [comment]
Hi, thanks for developing this tool! I found a similar issue again. When I have interleave Green and Red tiff images and chose 2 channels with 1 as functional channel, it computes all frames of both green and red channels and do the registration based on that. The final x_axis in GUI is total frames from two channels rather than the first...Could you help to look into this?
