### ISSUE TITLE
Load single files instead of folder

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#147]
Hi! Would it be possible to include the option to run suite2p directly from a list of tif files instead of relying on folder / look_one_level_down syntax? So basically skip the searching through folders step?
This would help a lot in cases where tifs land in the same folder, but are split over sub-sessions or in cases where only a subset of files should be included in the analysis. 
Thanks!

**Comment by carsen-stringer** [comment]
I could have it so that you choose the folders you want, suite2p makes the list, and then you can select tiffs you want from a list?

**Comment by horsto** [comment]
Thanks, sounds good, but would it be possible to build in a little check instead into `list_tifs` or before in `get_tif_list`? Such that if `ops['data_path']` is a list of tifs instead of list of folders, then just return those tif filepaths? It would be great to just create the `db['data_path']` entry directly with those selected tif files. 
https://github.com/MouseLand/suite2p/blob/5baff9bc9b0f8e083d4c059c8e02d7c60d41d58f/suite2p/utils.py#L391

**Comment by carsen-stringer** [comment]
ah sure, that's even easier. so you don't need GUI support for this?

**Comment by horsto** [comment]
No, I don't need the GUI (although that was a cool idea too ...).

**Comment by KnightyOwl** [comment]
Hi, I have a similar issue on reading a list of tiffs from a folder:
In my case, I loaded the folder directory through GUI, it seems the pipeline concatenated all the frames together and did the registration, the x axis in GUI is the total frame number across several tiff files. How can I keep track the tiff files and map each tiff file back to the concatenated frames in order, since different tiff files are with different experiments although with the same FOV?

Thanks!

**Comment by carsen-stringer** [comment]
@horsto try out the github version now - see how to use in the last cell in this [notebook](https://github.com/MouseLand/suite2p/blob/master/jupyter/run_pipeline_tiffs_or_batch.ipynb).  specify 'tiff_list' and ops['data_path'][0] as the folder that they live in

@KnightyOwl I'm not keeping track of the length of tiffs only how many frames in each folder filled with tiffs, are your different experiments in different folders and you're using 'look_one_level_down'? then the numbers will be in ops['frames_per_folder']

**Comment by horsto** [comment]
Thanks a lot, Carsen!

**Comment by carsen-stringer** [comment]
I'm going to close this issue as I've tested it a bit more since then and had no problems. please let me know if you have issues.
