### ISSUE TITLE
Explain additional option in GUI (smooth_mask, high_pass)

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#148]
There are some options in the new GUI that are not explained on the suite2p page, such as smooth_mask, high_pass.

**Comment by carsen-stringer** [comment]
these were options that were not previously exposed:
'smooth_masks' whether or not to use smoothed ROIs (correlation map smoothed using diameter) or not 
'high_pass' window defining high-pass filtering in time of binned frames. say 'high_pass'=100 and frames is time x pixels x pixels, then 
```
frames[:100,:,:] -= frames[:100,:,:].mean(axis=0)
```
it's a fast way to high-pass the data, if 'high_pass' is less than 10 then we do it more properly:
```
frames -= gaussian_filter1d(frames, ops['high_pass'], axis=0)
```

**Comment by carsen-stringer** [comment]
btw Marius recently pushed a version of the cell detection that doesn't depend on cell diameter, the branch is 'sparse_mode' if you want to check it out. I've updated it with the latest changes to the main branch.

see description here: https://github.com/MouseLand/suite2p/issues/129#issuecomment-459035360

**Comment by Cumol** [comment]
> these were options that were not previously exposed:
> 'smooth_masks' whether or not to use smoothed ROIs (correlation map smoothed using diameter) or not
> 'high_pass' window defining high-pass filtering in time of binned frames. say 'high_pass'=100 and frames is time x pixels x pixels, then
> 
> ```
> frames[:100,:,:] -= frames[:100,:,:].mean(axis=0)
> ```
> 
> it's a fast way to high-pass the data, if 'high_pass' is less than 10 then we do it more properly:
> 
> ```
> frames -= gaussian_filter1d(frames, ops['high_pass'], axis=0)
> ```

Is smooth_masks used in the sparse_mode too, which has a variable diameter?

When is it useful to have a lower high_pass? Does it make the image "sharper" then?

**Comment by carsen-stringer** [comment]
high_pass is used in sparse_mode. The high_pass is good when you have something like 1P data where the whole field of view changes brightness sometimes. The high-pass is in time so it will only make the image "sharper" in time (not the conventional image sharpening sense)

**Comment by carsen-stringer** [comment]
I'm closing this and adding this info to the wiki
