### ISSUE TITLE
AttributeError when loading tiffs

### ISSUE THREAD

**Issue by elhananby** [MouseLand/suite2p#149]
When trying to load a folder of two-channel large TIFF files (~3GB per file), I get this error:
>raise AttributeError(name)
AttributeError: is_indexed
Interrupted by error (not finished)

I've attached to full error log:

'Found 6 tifs
===== 2019.02.27 13:02:59 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    >>>ERROR<<<
"__main__", mod_spec)
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 32, in <module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
>>>ERROR<<<
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 146, in run_s2p
>>>ERROR<<<
    ops1 = utils.tiff_to_binary(ops)
>>>ERROR<<<
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\suite2p\utils.py", line 238, in tiff_to_binary
>>>ERROR<<<
    tif = TiffFile(file, fastij = True)
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1331, in __init__
>>>ERROR<<<
    self._fromfile(pages, fastij)>>>ERROR<<<

  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1381, in _fromfile
>>>ERROR<<<
    page = TiffPage(self, skip)
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\skimage\external\tifffile\tifffile.py", line 2073, in __init__
>>>ERROR<<<
    self._process_tags()
>>>ERROR<<<
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\skimage\external\tifffile\tifffile.py", line 2250, in _process_tags
>>>ERROR<<<
    if self.is_indexed:
  File "C:\Users\bbo\Anaconda3\envs\suite2p\lib\site-packages\skimage\external\tifffile\tifffile.py", line 2747, in __getattr__
>>>ERROR<<<
    >>>ERROR<<<
raise AttributeError(name)
AttributeError: is_indexed
Interrupted by error (not finished)'

**Comment by carsen-stringer** [comment]
Is this a tiff saved in imageJ? It may be too large to be supported. 

I've written a short wiki thing about it that might help you: https://github.com/MouseLand/suite2p/wiki/Input-format-and-supported-file-types#tiffs

Also I'd recommend using the github version as that's the most up-to-date code and it may solve this issue right away. Download the github folder and run 'python -m suite2p' from there. also 'pip install scanimage-tiff-reader'

**Comment by elhananby** [comment]
This is a tiff image directly out of ScanImage; however I suspect the issue is that it's actually BigTiff (>2GB) and so suite2p has an issue loading all the data. I have the same issue with ImageJ, where loading the file only opens the first 2GB of data, and therefore there's an unequal number of frames for both channels - so converting the tiff using imagej might not be an option.

After cloning the last git, along with installing scanimage-tiff-reader, I'm still getting the same error; with the addition of "ScanImageTiffReader not working for this tiff type, using scikit-image" in the begining.
I know scikit-image is not using the latest tifffile package version, however I'm not sure if it's possible to update it

**Comment by carsen-stringer** [comment]
:( I'll tell the developer of scanimage-tiff-reader, this is definitely a problem that needs to be fixed. We moved to their reader because scikit-image has changed their tiffreader.

Can you put an example tiff here: https://drive.google.com/drive/folders/1OE8FCNfRKmWfAUAVT39IGjXHAmSS1EKd

Also in the meantime, you could set your acquisition to save fewer frames per tiff.

**Comment by carsen-stringer** [comment]
ah you already did thanks!

**Comment by elhananby** [comment]
I just uploaded the example tiff now (M161209TH_01__001.tif)
Though after doing a lot of testing I suspect the issue is with the tiff files themselves - it throws similar errors in python, matlab, imagej, etc...
It seems like they all have a corrupt tag at some point that prevent them from being read after a certain point.

**Comment by carsen-stringer** [comment]
Ah yeah I usually don't get that corrupted tag error, I get a different with bigtiff's if they don't work. I've added the folder to the gitlab issue. Maybe you can change things on the acquisition side?

**Comment by elhananby** [comment]
Just wanted to update the issue is indeed with the tiff file, specifically larger (>2GB) files created in older versions of ScanImage(<5).

This repository has a script that enables reading such files in Matlab:
https://github.com/dgreenberg/read_patterned_tifdata

Thanks for the help!

**Comment by carsen-stringer** [comment]
thanks for the update, I'll add this info to the wiki

**Comment by XuanweiLi** [comment]
Hi Carsen, thanks for the great work. I am wondering if I can default the scikit-image reader? Because scanimage-tiff-reader ended up in pure noises in my case.
