### ISSUE TITLE
Extract fluorescence from second channel?

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#150]
In addition to the image with the green channel (my calcium dye), I have an image (single frame, static) of a marker gene that is reported in red. I was wondering how I can find out which of the cells that are detected by suite2p are red and which aren't.

Currently I am manually selecting the ROIs in imagej and doing the analysis in imagej, as I can use the same ROI mask for the red channel and extract a mean grey value.

Is there a clever way of doing it with suite2p?

I asked once if it is possible to export the ROIs from suite2p as imagej ROIs but I understood from @marius10p  (https://github.com/MouseLand/suite2p/issues/93) that it is not very adviseable.

Any better idea?

**Comment by carsen-stringer** [comment]
We do now have red channel cell detection for tiffs with an interleaved red channel. In your case with a separate image it will only work in a jupyter-notebook like this:
```
ops = {your settings}
ops['meanImg_chan2'] = your_red_image

opsEnd=run_s2p(ops=ops,db=db)
````
The pipeline looks for a meanImg_chan2 to do red cell detection, so if you have it in your ops it should work (but I'd recommend testing on a few tiffs to check that it works).

**Comment by Cumol** [comment]
I only have a few cells that are red. So it shouldn't base the ROI extraction in the green channel on the red one...

I give it a try as suggested above and let you know!

**Comment by carsen-stringer** [comment]
nope it won't! this will just run a filter basically on the red channel to see if any of your ROIs from the green channel also have red channel intensity

**Comment by Cumol** [comment]
Closing this for now until I try it out!

**Comment by Cumol** [comment]
Got to try this and getting an error:
This is the code I am using. It is originally from a loop to run multiple files. I am feeding it only one folder though.

```
import glob, os
from natsort import natsorted
import imghdr

froot = ['/home/generalubuntu/mnt/Muad/ca-imaging/exp164-20190626/1drg-on/']
ops['meanImg_chan2'] = '/home/generalubuntu/mnt/Muad/ca-imaging/exp164-20190626/1drg-on/tdtomato/red.tif'



for fri in froot:
    
    files = glob.glob(os.path.join(fri, "*.*"))
    condition = np.empty(len(files))
    for i, name in enumerate(files):
        condition[i] = imghdr.what(files[i]) == 'tiff'
    files = np.extract(condition,files)
    files = natsorted(files)
    for n,f in enumerate(files):
        files[n] = os.path.basename(f)

    db = {
          'h5py': [], # a single h5 file path
          'h5py_key': 'data',
          'look_one_level_down': False, # whether to look in ALL subfolders when searching for tiffs
          'data_path': [fri], 
                                # a list of folders with tiffs 
                                # (or folder of folders with tiffs if look_one_level_down is True, or subfolders is not empty)

          'subfolders': [], # choose subfolders of 'data_path' to look in (optional)
          'tiff_list': files # list of tiffs in folder * data_path *!
        }
    
    
    
    # run one experiment
    opsEnd=run_s2p.run_s2p(ops=ops,db=db)

```

The error I am getting is the following:

```
/home/generalubuntu/mnt/Muad/ca-imaging/exp164-20190626/1drg-on/suite2p/plane0
found binaries
/home/generalubuntu/suite2p/plane0/data.bin
skipping registration...
[6 6]
nt0=10
(1050, 516, 695)
spatial scale 3, time epochs 1.00, threshold 60.00 
0 0.03669571876525879 1503.2659912109375
200 21.48070764541626 255.8083038330078
394 32.10496187210083 0.0
time 82.4969. Found 394 ROIs
extracted 1000/10500 frames in 9.87 sec
extracted 6000/10500 frames in 63.47 sec
extracted 10500/10500 frames in 115.98 sec
extracted 10500/10500 frames in 115.99 sec
time 214.6798. Extracted fluorescence from 394 ROIs

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-103a141b93bc> in <module>
     36 
     37     # run one experiment
---> 38     opsEnd=run_s2p.run_s2p(ops=ops,db=db)

~/Downloads/suite2p-test/suite2p/suite2p/run_s2p.py in run_s2p(ops, db)
    205             roidetect = True
    206         if roidetect:
--> 207             ops1[ipl] = utils.get_cells(ops1[ipl])
    208             ops = ops1[ipl]
    209             fpath = ops['save_path']

~/Downloads/suite2p-test/suite2p/suite2p/utils.py in get_cells(ops)
    651         if 'chan2_thres' not in ops:
    652             ops['chan2_thres'] = 0.65
--> 653         ops, redcell = chan2detect.detect(ops, stat)
    654         np.save(os.path.join(fpath, 'redcell.npy'), redcell)
    655         np.save(os.path.join(fpath, 'F_chan2.npy'), F_chan2)

~/Downloads/suite2p-test/suite2p/suite2p/chan2detect.py in detect(ops, stat)
     49     #ops2 = ops.copy()
     50     mimg = ops['meanImg'].copy()
---> 51     mimg2 = ops['meanImg_chan2'].copy()
     52 
     53     # subtract bleedthrough of green into red channel

AttributeError: 'str' object has no attribute 'copy'

```

Any idea what is happening?

**Comment by carsen-stringer** [comment]
hmm it seems like it didn't think you had a red channel. Can you update to the github version? In a notebook:
```
import sys
sys.path.insert(0,'/github/suite2p/') # path to github
```

**Comment by Cumol** [comment]
Same problem.
I also changed the "nchannel" argument to "2" because I thought that this would be the problem. did not help.

Maybe I am supplying the path of the red channel in a wrong format?

**Comment by carsen-stringer** [comment]
I am going to update the anatomical red channel segmentation soon and then I'll check that this works. In the meantime I can believe that there might be issues because this isn't usually the way it's used.

**Comment by Cumol** [comment]
any idea what I could try?

Is there a way to extract the ROIs as files readable by the ImageJ ROI manager?

**Comment by carsen-stringer** [comment]
I'm sorry I see what you were trying to do now, in your code above, set 
```
import skimage
ops['meanImg_chan2'] = skimage.io.imread('tif_path')
```
because it expects it that way. Now you should be able to see it in the GUI (hopefully).

For computing the red I'd recommend importing the ImageJ ROIs into a jupyter-notebook and looking at the overlaps with the masks found by suite2p.
