### ISSUE TITLE
Small mistake on the wiki page

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#151]
> threshold_scaling: (float, default: 1.0) this controls the threshold at which to detect ROIs (how much the ROIs have to stand out from the noise to be detected). if you set this higher, then **fewer ROIs** will be detected, and if you set it lower, **fewer ROIs** will be detected.

Higher = fewer ROIs
Lower = more ROIs.

**Comment by carsen-stringer** [comment]
thanks!
