### ISSUE TITLE
Choose custom classifier file before running suite2p

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#152]
Is it possible to choose the classifier used by suite2p before running the pipeline?

Currently I am running the pipeline, loading my own classifier that I built into the GUI and then using that to sort the cells. Pointing suite2p to my custom classifier from the beginning would ease that.

Or is it easier to load my custom classifier into the GUI once, set it as default and then run the pipeline again? Will suite2p use my custom classifier or the built-in one?

**Comment by carsen-stringer** [comment]
Yes if you set the classifier to default then suite2p will use it during running the pipeline (suite2p uses 'classifier_user.npy' which is the user default, in the pipeline)
