### ISSUE TITLE
Google Drive is bad for sharing data

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [MouseLand/suite2p#154]
The example data you provide is hard to download. When you try to get the 50 layers, Google creates a ton of zip archives of 1.5GB average. It's not as bad as Dropbox, that Misha Ahrens tried to use to publish sample data:

[![image](https://user-images.githubusercontent.com/18427584/54024727-cfe16380-4198-11e9-8ea5-8dd3344d6b71.png)](https://twitter.com/MishaAhrens/status/1058079873728684032)

In response, they published the data on https://figshare.com/ which is more suited for this need.

**Comment by carsen-stringer** [comment]
thanks this is a good point and sorry for the trouble - we will move this in the future / just store in a few big tiffs that can be downloaded one at a time without compression.

**Comment by carsen-stringer** [comment]
I've compressed this recording to 5 tiffs, which should make things easier: https://drive.google.com/open?id=1PCJy265NHRWYXUz7CRhbJHtd6B-zJs8f

I'd recommend clicking and downloading one at a time - not ideal, but I didn't want to make them too big in case people want to load them in imageJ for instance.

I think we'll eventually use something like figshare or zenodo for larger raw data.
