### ISSUE TITLE
bidirection scanning 

### ISSUE THREAD

**Issue by rajatsaxena** [MouseLand/suite2p#155]
Does the suite2p package take care of bidirectional scanning dataset and computes the phase offset? is there any specific parameter for it?

**Comment by carsen-stringer** [comment]
yeah I actually just recently added it but it's only in the sparse_mode branch right now. if you want to try it out:

```
git checkout sparse_mode
```
You will also have to overwrite your 'ops_user.npy' if you are running in the GUI (because I've added these new parameters that weren't there previously). 
```
cp github/suite2p/suite2p/ops/ops.npy github/suite2p/suite2p/ops/ops_user.npy
```

if ops['do_bidiphase']=1, the pipeline computes the bidirectional phase offset for you from a range of -10 to 10 pixels (if ops['bidiphase']=0). Alternatively you can set the bidiphase offset yourself with ops['bidiphase']=integer of pixels

It uses the 'nimg_init' frames to compute the offset. If you find the estimation to be unreliable, you may want to increase ops['nimg_init'] (default is 200, may need 400 or 500 with low SNR).

**Comment by rajatsaxena** [comment]
I will try this out asap. Thanks!

**Comment by suyashh94** [comment]
Elaborate please!! 

Tried running a bidirectional tiff on python suite2p. Got an error. I run a lot of these on Matlab supported Suite2p and they work great!

**Comment by carsen-stringer** [comment]
Can you post the error please?

**Comment by suyashh94** [comment]
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\harla\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\harla\Anaconda3\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\harla\Anaconda3\lib\site-packages\suite2p\__main__.py", line 32, in <module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
>>>ERROR<<<
  File "C:\Users\harla\Anaconda3\lib\site-packages\suite2p\run_s2p.py", line 171, in run_s2p
>>>ERROR<<<
    ops1[ipl] = register.register_binary(ops1[ipl]) # register binary
  File "C:\Users\harla\Anaconda3\lib\site-packages\suite2p\register.py", line 363, in register_binary
>>>ERROR<<<
    op = register_binary(op)
  File "C:\Users\harla\Anaconda3\lib\site-packages\suite2p\register.py", line 379, in register_binary
>>>ERROR<<<
    raise Exception('the total number of frames should be at least 50 ')
Exception: the total number of frames should be at least 50 
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
Is your recording less than 50 frames? suite2p automatically errors when a recording is too short

**Comment by suyashh94** [comment]
Nope. There are 2 tiff files in there, 3000 frames each!

**Comment by carsen-stringer** [comment]
what format are the tiffs in? Unfortunately python's scikit-image tiff reader recently changed and removed some of its functionality :( and we've had to change our default tiff reader. are you using the sparse_mode branch or the main github branch?

**Comment by suyashh94** [comment]
I am using the main github branch. They are 16 bit tiffs.

**Comment by carsen-stringer** [comment]
did you save the tiffs in imageJ? that's what's giving issues unfortunately (see info here https://github.com/MouseLand/suite2p/wiki/Input-format-and-supported-file-types#tiffs). Also, the bidirectional scanning is currently only on the **sparse_mode** branch, I haven't pulled it in yet, so I'd recommend changing to that branch `git checkout sparse_mode`

**Comment by suyashh94** [comment]
Ah I see. Gotcha!

**Comment by carsen-stringer** [comment]
Also suite2p will take single tiffs, there's no need to stack them in imageJ for it

**Comment by carsen-stringer** [comment]
everything is now in the main branch. please try the latest version, and see the installation instructions on the readme. please open a new issue if you're still having problems
