### ISSUE TITLE
Launch GUI with stat.npy specified

### ISSUE THREAD

**Issue by adilgkhan** [MouseLand/suite2p#156]
Hello,
Currently I can launch the GUI from command line with
`from suite2p import gui2p`
`gui2p.run()`

However I can't launch the GUI with the stat.npy file already chosen. Do you think you could provide an optional argument to `gui2p.run`such that one could do something like
`gui2p.run('my\path\suite2p\plane0\stat.npy')`

Or maybe there is already a way to do this?
Thanks

**Comment by carsen-stringer** [comment]
I've added this in the development branch **sparse_mode** and will be pulled into master in a couple weeks

**Comment by carsen-stringer** [comment]
this is in the master now, please try the latest version, and see the installation instructions on the readme
