### ISSUE TITLE
No module named 'ScanImageTiffReader'

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/suite2p#161]
Hi,
When installing the current version (with pip install -e) from my local git directory, I get a ScanImageTiffReader not found error. Is this a required module to read in tiffs? Or do I only need it for scan image tiffs?

**Comment by carsen-stringer** [comment]
Yeah sorry you'll have to 'pip install scanimage-tiff-reader' It's not a specific scanimage tiff reader

**Comment by Cumol** [comment]
Just had the same issue. Could it be added to the install script?
