### ISSUE TITLE
applying user define affine matrix for the registration step

### ISSUE THREAD

**Issue by vrutten** [MouseLand/suite2p#163]
Hello again,

Would it be possible for the user to give the x-y shifts for each timepoints and and each plane (instead of feeding in already registered data)?
Why?
I have an efficient way to run registration (which otherwise takes a very very long time), however saving registered data to then feed to suite2p is starting to be really very prohibitive. Is there any chance we could give the pipeline our own x-y shifts?

**Comment by carsen-stringer** [comment]
Registration was slow (especially if threads were interfering), but we've made it significantly faster in the *sparse_mode* branch. This version runs single-threaded numpy/scipy, only using multiple cores through multiprocessing pool's. To ensure the single-threaded-ness, either run suite2p through the GUI or in a notebook with these commands BEFORE importing numpy or scipy:
```
import os
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
```
and make sure that ops['num_workers']=0 or a specified large number to have parallelism. And increasing the batch size will improve speed up to a certain point.

We will pull this into the main branch in a couple weeks.

**Comment by carsen-stringer** [comment]
As an aside, you can run suite2p without "non-rigid" registration to make the registration run faster, but I'd recommend checking first that you don't need "non-rigid" shifts in your data, by looking at the registration metrics. Our computation of the shifts was never super slow (although that's faster now too), but it was the shifting itself that we primarily sped up.

**Comment by vrutten** [comment]
Cool - thanks for the tips. Will try all of this out.

**Comment by carsen-stringer** [comment]
we've made registration much faster, I highly recommend using Ubuntu if you have a choice, see the new install instructions on the readme
