### ISSUE TITLE
Permission denied: 'ops.npy'

### ISSUE THREAD

**Issue by KevinChauNTU** [MouseLand/suite2p#164]
Hi, I'm a new user of Suite2p. I use the python version (running in Anaconda). When I click Run Suite2p in the GUI, I kept getting the error message below:

fid = open<file, "wb">
PermissionError: [Errno 13] Permission denied: 'ops.npy'

Have anyone encountered this before? I will really appreciate if you can offer some insights
Thanks!

**Comment by carsen-stringer** [comment]
To run suite2p from the GUI, we save your specified 'ops.npy' and 'db.npy' in the current working folder temporarily. Do you have write access in the folder from which you're running suite2p? If not, then I think this would be the error you'd get.

**Comment by KevinChauNTU** [comment]
I changed the working directory, and it works now! Thanks a lot! : D

**Comment by carsen-stringer** [comment]
great! I will add this info to the readme :)
