### ISSUE TITLE
extract fluorescence traces using cell detection from other channel

### ISSUE THREAD

**Issue by atranvan** [MouseLand/suite2p#165]
Hi,

I have seen the notebooks for analyzing multiple functional channels, that involve running cell detection on each channel separately.
Is there a way to also extract fluorescence traces from one channel using the ROIs from the second channel? 

thanks a lot in advance!

**Comment by carsen-stringer** [comment]
this is not currently possible, but I can add it as an option with not too much difficulty. I will add this to the sparse_mode branch btw (this is the branch that is currently in development). give me a few days.

**Comment by carsen-stringer** [comment]
sorry for the delay in this. the fluorescence from the second channel is now extracted by default and saved to "F_chan2.npy" and "Fneu_chan2.npy". If you have multiple functional channels, you will still need to run cell extraction twice in a notebook as described - this won't take care of that. also when using sparse_mode branch in a notebook make sure to force single-threaded processing with the following commands BEFORE importing numpy or scipy or suite2p:
```
import os
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1" 
```

**Comment by atranvan** [comment]
Thanks a lot, that solves it perfectly!

**Comment by carsen-stringer** [comment]
great I've added this info to the wiki so I'll close the issue
