### ISSUE TITLE
Export spatial footprints of found ROIs

### ISSUE THREAD

**Issue by fbolanos** [MouseLand/suite2p#166]
Hello I was wondering if it's possible to export the final set of ROIs that were found during the processing as a spatial mask that would be of dimensions (n_rois, height, width).  Height and width being the 2P image size.
Then each image would be mostly zeros, except the spatial profile of that particular ROI.

The reason is I would like to track the same cells over many days, for example utilizing this toolbox: 
https://github.com/zivlab/CellReg
This toolbox expects the spatial footprints as an input and will output statistics of whether or not the same cells are observable in multiple sessions.

**Comment by fbolanos** [comment]
Just realized this information is compressed in the stat.npy file.
Here is a code snippet to extract the footprints from it:

```
st = np.load(STATS_FILENAME)
n_rois = st.shape[0]
# Image size in pixels
# What if motion correction changed the image size? 
height = 512
width = 512
spatial_footprints = np.zeros((n_rois, height, width))

for i in range(n_rois):
    spatial_footprints[i, st[i]['ypix'], st[i]['xpix']] = st[i]['lam']
```

I do wonder what if the motion correction algorithm changed the final dimensions of the image, where can we find that information.
Also, highly recommend to prune the final footprints by the iscell.py file.

**Comment by carsen-stringer** [comment]
The 'ypix' and 'xpix' are given in the coordinates of the original file, so you don't have to worry about cropping things. Glad you worked things out. We don't save the masks like that because with many cells they would be very large. We recommend the user makes them themselves as you did.

**Comment by Cumol** [comment]
Maybe a step further.

Is it possible to get the masks without overlapping pixels?
If I have two adjacent cells. One ROI is a normal, round one and the other is a fusion of both cells. The extracted signal is separate, but the mask is not.

Is there a way around this?

**Comment by carsen-stringer** [comment]
good question. 'stat' should also have an 'overlap' key:
```
# non overlapping pixels of cell 100
n=100
ypix, xpix = stat[n]['ypix'][~stat[n]['overlap']], stat[n]['xpix'][~stat[n]['overlap']]
```

**Comment by adilgkhan** [comment]
Some more info and code sample in this earlier post
https://github.com/MouseLand/suite2p/issues/69

**Comment by carsen-stringer** [comment]
I will add this info to the wiki as this is a common question :)
