### ISSUE TITLE
run different sofware branches

### ISSUE THREAD

**Issue by tomMEM** [MouseLand/suite2p#167]
Thank you for the great fluorescence imaging analysis package and the GU interface.
As a non-programmer I wonder how to run the other branches of the software package (e.g. sparse-mode) without the impairment of the already installed one.

**Comment by carsen-stringer** [comment]
Yeah it's not straightforward :) 

You can run the "pip" installed package from any folder. You can run the github version (and its various branches) without "pip" installation, but you have to be in the repository folder to run suite2p. The github version will not mess with your "pip" installed version, it will just be a different folder on your computer. To be able to checkout different branches of suite2p you will need **git** installed. Once you have git installed, here are the instructions to follow:

1. Clone the repository using "git clone https://github.com/MouseLand/suite2p.git", and run "python -m suite2p" in that folder to check if it works. It may have some dependencies that are missing ("pip install scanimage-tiff-reader" might be necessary).

2. Now that you have the main github version of suite2p working (this is the master branch), you can change to a different code branch while in that folder with the commands:
```
git fetch --all
git checkout sparse_mode
``` 
Here are more detailed instructions [here](https://www.atlassian.com/git/tutorials/using-branches/git-checkout) under **git checkout a remote branch**

Now you're in the sparse_mode branch and can run "python -m suite2p" again, and you'll be running this branch's code.

**Comment by carsen-stringer** [comment]
I've added this info to the wiki here: https://github.com/MouseLand/suite2p/wiki/Installation so I'm closing this issue
