### ISSUE TITLE
Max projection

### ISSUE THREAD

**Issue by adilgkhan** [MouseLand/suite2p#168]
Hi
In the GUI it would be nice to have a 'Max projection' option as a background along with the mean. It can be quite useful to see the shape of cells that are often not clearly visible in the mean, they often pop-out much better in a max projection. One option might be to allow the user to add their own image as a background, and then they could make their own max projection or anything else and load it in.
Thanks
Adil

**Comment by carsen-stringer** [comment]
This is a good idea to add to the pipeline in general. I will also add to the to-do list the option to load an image.

**Comment by carsen-stringer** [comment]
I've added the max projection computation and the view to the GUI in the sparse_mode branch, it's saved in ops['max_proj']

**Comment by carsen-stringer** [comment]
this is now in the main branch, please see the new install instructions to ensure you get fast registration!

**Comment by carsen-stringer** [comment]
also it's a nice view of the data, so thanks for the great suggestion :D
