### ISSUE TITLE
Apply spike detection on existing time series of Ca trace

### ISSUE THREAD

**Issue by sebastiangapp** [MouseLand/suite2p#169]
Hi!
Is it possible to apply Suite2p spike deconvolution on Ca trace data, structured by [cell x time point], excluding further steps of the pipline such as ROI detection?
Many thanks in advance.
Best,
Sebastian

**Comment by carsen-stringer** [comment]
here is the code to do that (assuming you have your data called *Fc* loaded into a jupyter-notebook / python script):
```
# force single threaded numpy (call before numpy/scipy/suite2p import)
import os
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"

# compute deconvolution
from suite2p import dcnv

tau = 1.0 # timescale of indicator
fs = 30.0 # sampling rate in Hz
# for computing and subtracting baseline
baseline = 'maximin' # take the running max of the running min after smoothing with gaussian
sig_baseline = 10.0 # in bins, standard deviation of gaussian with which to smooth
win_baseline = 60.0 # in seconds, window in which to compute max/min filters

ops = {'tau': tau, 'fs': fs, 'baseline': baseline, 'sig_baseline': sig_baseline, 'win_baseline': win_baseline}

# baseline operation
# NOTE: Fc = F - 0.7 * Fneu  in suite2p pipeline
Fc = dcnv.preprocess(Fc, ops)

# get spikes
spks = dcnv.oasis(Fc, ops)

```

**Comment by sebastiangapp** [comment]
Many thanky!

**Comment by sebastiangapp** [comment]
Hi!
I just found out that the input (Fc) does not equal the output size (spks).
In my case the output ~ 2 times the input. Do you apply uppsampling within the spike detection?
Many thanks in advance.
Best,
Sebastian

**Comment by carsen-stringer** [comment]
are you using the latest version of suite2p (`pip install suite2p --upgrade`) or the github version?

is it the right size after the "preprocess" step?

**Comment by sebastiangapp** [comment]
Thank you for your fast reply. I just fund my bug.
Does it make a difference for the output _spks_ if the input Fc [cell x time point] is transposed?

**Comment by carsen-stringer** [comment]
yeah the matrix should be cells x timepoints - the operations are performed on the last axis

**Comment by sebastiangapp** [comment]
Thanks!

**Comment by sebastiangapp** [comment]
Hi!
Is it possible to inverse the spike convolution, providing spikes _spks_ as input and receive a non-noisy electrical signal _Fc_ as output?
Many thankst!
Best,
Sebastian

**Comment by makto-toruk** [comment]
Hi Carsen,

Just to confirm, is Fc the same as (delta F)/F traces?

Alternatively, if I have (delta F)/F traces, is the preprocessing step required or should I directly run deconvolution? Please let me know!

Sincerely,
Manasij

**Comment by carsen-stringer** [comment]
@sebastiangapp You can "invert" this model of spike deconvolution by filtering the traces with an exponential with the ops['tau'] * ops['fs'] timescale. e.g.
~~~
from scipy.signal import convolve
efilt = np.exp(- np.linspace(0,50,200) / (ops['tau'] * ops['fs']))
efilt /= efilt.sum()
sout = convolve(spks[0,:], efilt)
sout = sout[:spks.shape[1]]
~~~

@makto-toruk yeah, our preprocessing is temporal baselining - so if you've already temporally baselined when computing dF/F, then you can just input this directly into dcnv.oasis.

**Comment by sebastiangapp** [comment]
Thank you for the fast reply. When I run the code the output is ~ 2.5e-3 on everage whereas the actual input _Fc_ is approx. 0.7?

**Comment by carsen-stringer** [comment]
Oops try not normalizing the filter by its sum

**Comment by sebastiangapp** [comment]
Ok, so without _efilt /= efilt.sum()_?

**Comment by carsen-stringer** [comment]
Yeah

**Comment by sebastiangapp** [comment]
Ok. Plotting the data shows, that there is still a difference between _sout_ and _Fc_.
![grafik](https://user-images.githubusercontent.com/49304035/57296627-b6dc2c80-70cd-11e9-8f1f-b6d3fc8cecfd.png)

**Comment by carsen-stringer** [comment]
Yeah that's to be expected with your trace - I don't see transients. Check out this paper for more info about how it works: [Fast online deconvolution of calcium imaging data -
Johannes Friedrich, Pengcheng Zhou, Liam Paninski](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005423) 

It should ignore gaussian noise to some extent:
![image](https://user-images.githubusercontent.com/15067541/57300980-ebd48900-70a5-11e9-95da-fbb071acbdfd.png)

Here's an example in suite2p with decent SNR where you can see the transients:
![image](https://user-images.githubusercontent.com/15067541/57301339-c85e0e00-70a6-11e9-9cee-d41ac16e79a1.png)

**Comment by makto-toruk** [comment]
Do you have any suggestions for handling suppressive dF responses? Here's the output from suite2p, I've added the dF traces along with the spike detection.

![52_off](https://user-images.githubusercontent.com/33137157/57653250-65d1aa00-759f-11e9-8d3b-ea31fc758a2c.png)

Just to confirm, it seems to work well for the facilitative population:
![1_off](https://user-images.githubusercontent.com/33137157/57653402-b5b07100-759f-11e9-8ae0-de449b02f5c2.png)

Let me know if I should ask these questions elsewhere. Thanks in advance!

**Comment by carsen-stringer** [comment]
I would probably not recommend using the spike deconvolved version for suppressive responses. Using the neuropil-corrected might give you a better idea of what's going on
```
Fc = F - 0.7*Fneu
```
or if you want some baseline subtraction
```
from suite2p import dcnv

ops = {}
ops['fs'] = #sampling rate
ops['baseline'] = 'maximin' # maxmin filter
ops['sig_baseline'] = 10. # smoothing pre filter computation
ops['win_baseline'] = 60. # maximin window in seconds

Fb = dcnv.preprocess(Fc,ops)
```

I'm not sure if that off neuron 7 is an "off" neuron or just a neuron that is "inactive" in that window. it's very hard with calcium to see decreases in firing rate, so I'd be really careful with this.

**Comment by carsen-stringer** [comment]
I'm going to close this issue and add more info to the wiki, please let me know if you'd like to reopen this
