### ISSUE TITLE
merge selected neurons into single ROI

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#17]
Add merging ability to the GUI. Multi-neuron selection will be provided by issue #16.

**Comment by carsen-stringer** [comment]
must decide behavior but will use this: https://stackoverflow.com/questions/8772595/how-to-check-if-a-key-modifier-is-pressed-shift-ctrl-alt

a merge will show all cell traces? does the user have the option to reproject the combined mask onto the binary movie?
