### ISSUE TITLE
Applying classifier to new data

### ISSUE THREAD

**Issue by windgrazer** [MouseLand/suite2p#170]
Hi there!

I am a new user of suite2p and I have question about the classifier.
I am using Windows 10, Python terminal (using pip install).

I have built a classifier for my dataset but I am having difficulties applying this classifier to new datasets. I have tried loading this newly-built classifier onto my new dataset but I did not not observe any changes to the ROI classification. Apparently there is an "apply" button seen on a separate computer running on Mac OS which I do not see on the GUI in Windows.

How should I go about using my classifier without having to make it the default and re-processing the original images? (I am processing the data and curating the ROIs on separate computers)

**Comment by carsen-stringer** [comment]
On the latest suite2p version, the "apply" button is gone. I've made it now linked to the [ENTER] key on this button:
![image](https://user-images.githubusercontent.com/15067541/56751785-dcc01380-6754-11e9-86fd-684309618cb9.png)
where the number is the minimum probability of an ROI to be allowed on the "CELL" side of the GUI

**Comment by windgrazer** [comment]
It works perfectly! Thank you!
