### ISSUE TITLE
Installation issue - 2Peas and Pickles

### ISSUE THREAD

**Issue by ronan-dasilva** [MouseLand/suite2p#171]
Hello!

I have previously installed Suite2P on a couple of PCs and was able to run it without any problems.
However, when trying to install it in a new machine, I ran into an error stating that
"array objects cannot be loaded when allow_pickle=False" whenever I try to >>>run python -m suite2p

So I went to the line of Gui2p.py that was calling for np.load() and added the kwarg allow_pickle=True to force it to allow pickling. This solved the issue when trying to start up Suite2p, but the issue repeated itself when I tried to run the pipeline. This suggests to me that something, somewhere, is setting np.load(arg,allow_pickle=False) as a default. 

Any clue on how to fix this? I have tried uninstalling numpy and installing v1.14, but doing so I ran into a series of other packages that ceased to work properly inside of Suite2p.

Many thanks! I really loved using Suite2p!

**Comment by bradgy** [comment]
Same issue here; suite2p not loading at the moment.

Seems to be related to this: https://stackoverflow.com/questions/55824625/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-in-the-sketc

Not sure what needs to be done at this end, though.

My terminal output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/suite2p/__main__.py", line 34, in <module>
    gui2p.run()
  File "/usr/lib/python3.7/site-packages/suite2p/gui2p.py", line 1370, in run
    GUI = MainW()
  File "/usr/lib/python3.7/site-packages/suite2p/gui2p.py", line 518, in __init__
    model = np.load(self.classorig)
  File "/usr/lib/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/lib/python3.7/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by trjordan** [comment]
It looks like this behavior was changed [in numpy in 1.17](https://www.numpy.org/devdocs/release.html#unpickling-while-loading-requires-explicit-opt-in).

You can probably work around this by downgrading numpy to a lower version. Suite2p only requires numpy >= 1.13. This should probably work:

```
pip install numpy==1.16
```

**Comment by carsen-stringer** [comment]
thanks @trjordan for the help! I will add this info to the README and fix this so that suite2p is compatible with numpy in the next pip release. I would recommend
```
pip install numpy==1.14
```

**Comment by carsen-stringer** [comment]
actually it seems skimage is not compatible either, so I will have to require numpy==1.14 until they also update

**Comment by ronan-dasilva** [comment]
Not sure if it was because @carsen-stringer updated pip, but I tried installing numpy 1.14 before `pip install suite2p` and everything worked fine! I then tried uninstalling numpy and resintalling 1.16 and this did not have any impact in Suite2P.

**Comment by carsen-stringer** [comment]
Glad it's working! I didn't update the pip but if you install numpy first then suite2p won't reinstall it when you pip install it. Not sure why the second thing was okay - this broke things on my ubuntu machine

**Comment by carsen-stringer** [comment]
I'm going to close this issue since it's working for you and I've added this info to the readme

**Comment by carsen-stringer** [comment]
the sparse_mode branch is now compatible with the new numpy==1.16. But if you upgrade numpy you will also have to upgrade scikit-image if you haven't already (pip install scikit-image --upgrade) - the latest version is compatible with numpy==1.16
