### ISSUE TITLE
Runtime error on Windows

### ISSUE THREAD

**Issue by mich11** [MouseLand/suite2p#172]
Hi,

I'm getting a runtime error when I try to run the run_s2p pipeline. After run_s2p finds my tiff and writes the binary, it reports that it has found the ops1 and binary files 4 times and then produces this error:

RuntimeError:
    An attempt has been made to start a new process before the
    current process has finished its bootstrapping phase.

   This probably means that you are not using fork to start your
   child processes and you have forgotten to use the proper idiom
   in the main module:

       if __name__ == '__main__':
           freeze_support()
           ...

   The "freeze_support()" line can be omitted if the program
   is not going to be frozen to produce an executable.

This cycle of finding files and runtime error repeats indefinitely, forcing me to restart python.

I'm running suite2p on Windows, using the version installed with pip.  I googled around and saw that this might be related to Windows and multiprocessing, but that's as far as I got.  I attached the full error message -- it's very long.  Any ideas? 

[Suite2pRuntimeError.txt](https://github.com/MouseLand/suite2p/files/3122423/Suite2pRuntimeError.txt)

**Comment by carsen-stringer** [comment]
Sorry I've never seen this before. One possibility to try is to wipe clean the folder "suite2p" that the pipeline creates and try again.

You can try turning parallelism off, but this will likely make things slower (ops['num_workers']=-1, ops['num_workers_roi']=-1).

You could also try the sparse_mode branch. `git checkout sparse_mode` then `python -m suite2p` in the folder. In the main suite2p branch the threads might fight with each other. The sparse_mode branch uses single-threaded numpy/scipy so this error might not happen. To force numpy/scipy single-threaded when running in a notebook you need the commands BEFORE you import numpy/scipy/suite2p
```
import os
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1" 
```

See more info in this [thread](https://github.com/MouseLand/suite2p/issues/142#issuecomment-482107859)

**Comment by mich11** [comment]
Thanks for the suggestions!  I figured out that I can operate on my files with parallelism if I run it through the GUI.  I had been calling the pipeline from a script that I'd pulled from a Jupyter notebook, so I must not have been importing everything properly before calling run_s2p.

**Comment by carsen-stringer** [comment]
great glad to hear it's working! I'm going to close this issue
