### ISSUE TITLE
problem with export to image file from gui

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#175]
Running Python 3.7 on Windows 10, I get this error when attempting to export a viewbox or plot from the gui to either a jpg, tif, or png:

-----------------
File "C:\ProgramData\Anaconda3\lib\site-packages\pyqtgraph\exporters\ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer
---------------------

Can you help with this?

Thanks,

Evan

**Comment by carsen-stringer** [comment]
try this hack: https://github.com/MouseLand/suite2p/issues/44#issuecomment-462886126
```
pip install git+https://github.com/pyqtgraph/pyqtgraph
```
