### ISSUE TITLE
registered tiff

### ISSUE THREAD

**Issue by leedoyun** [MouseLand/suite2p#177]
Hi,

Registered tiff files look different from the original ones. Pixel values are different.
Is it meant to be like this? Or is it a problem just for us?
How will it affect extracted F values from ROIs?

Doyun

![example_reg_tiff](https://user-images.githubusercontent.com/50690951/57841473-90bd3780-7805-11e9-8af2-9f3a4a4600f0.png)

**Comment by carsen-stringer** [comment]
those outlier pixels are during registration unfortunately pushing some pixels outside of the max for int16 (which is 32767). when we convert back to int16 they get pushed to the negative values that you see at the left of your histogram. to fix this we now clip before we convert back to int16. this is implemented currently only in the sparse_mode branch.

to use this branch
```
git clone https://github.com/MouseLand/suite2p.git
git checkout sparse_mode
python -m suite2p
```

**Comment by leedoyun** [comment]
It works okay in the sparse mode. Thanks!

By the way, how is the sparse mode branch different from the master except the updated registration process?

**Comment by carsen-stringer** [comment]
the cell extraction algorithm is also updated -- it looks for cells of many sizes so you no longer need to worry about the diameter parameter. to try to get more cells decrease ops['threshold_scaling'] or if you're getting too much crap increase it

**Comment by carsen-stringer** [comment]
sparse_mode is now merged into the main branch - please see the new install instructions in the readme to get good speed ups with mkl_fft and registration
