### ISSUE TITLE
Error building a classifier

### ISSUE THREAD

**Issue by Tono2P** [MouseLand/suite2p#179]
I am trying to build a classifier based on the iscell.npy files from my data and encountered the following: after loading the files in the popup window called 'classifier training files' and selecting them (ctrl) if I hit the build classifier button nothing happens. 
Command line says:

Populating classifier: 
...

ValueError: Object arrays cannot be loaded when allow_pickle=false

Thanks again for your time.

**Comment by carsen-stringer** [comment]
thanks I missed a pickle in 'classgui.py', try now. for more info on this, see this [issue](https://github.com/MouseLand/suite2p/issues/171) . numpy now requires an "allow_pickle=True" for all object loading

**Comment by neurodroid** [comment]
> thanks I missed a pickle in 'classgui.py', try now. for more info on this, see this [issue](https://github.com/MouseLand/suite2p/issues/171) . numpy now requires an "allow_pickle=True" for all object loading

Ah sorry, failed to see that it's a duplicate.
