### ISSUE TITLE
iscell in the .mat result file does not change as you manually select cells vs non-cells 

### ISSUE THREAD

**Issue by yaolu028** [MouseLand/suite2p#183]
unlike iscell.npy

**Comment by carsen-stringer** [comment]
Unfortunately it's too slow to resave the matlab after each cell flip, see here for more info: https://github.com/MouseLand/suite2p/wiki/Outputs#matlab-output

**Comment by yaolu028** [comment]
I see. Thanks!

**Comment by carsen-stringer** [comment]
there is a new save button in the GUI (in the file menu) that allows you to save the iscell again to the Fall.mat file. please check out the readme for installation instructions
