### ISSUE TITLE
jupyter notebook link dead / missing

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#184]
Hi,

This link goes nowhere:

"
Jupyter notebook
We have written a jupyter notebook from which you can run suite2p, it's located in the github here.

It shows you how to create ops and db, which are python dict's.
"

(at "here")

Does this mean you are still working on this, or that it is done/it works but the link is just broken?

Thanks,

Evan

**Comment by carsen-stringer** [comment]
sorry all the notebooks are in the jupyter folder, I had just renamed that one, the link should work now [here](jupyter/run_pipeline_tiffs_or_batch.ipynb)

**Comment by vickerse1** [comment]
Hi,

The link on "here" in your last email didn't work.

I went here from the wiki:

https://github.com/MouseLand/suite2p/blob/master/jupyter/run_pipeline_tiffs_or_batch.ipynb

....it started to load, and then failed. I will try again later.

Thanks,

Evan

**Comment by carsen-stringer** [comment]
Yeah jupyter notebooks don't always load well in the browser you should download it

**Comment by carsen-stringer** [comment]
The link works fine for me from the github website version (not sure how they work in emails)

**Comment by vickerse1** [comment]
i cloned them in github desktop...and now i have them.

didn't open in chrome or firefox though after 3-4 attempts.

thanks

evan
