### ISSUE TITLE
Mac OS python 2 issue(?)

### ISSUE THREAD

**Issue by sneezeman** [MouseLand/suite2p#186]
I'm trying to run the suite2p, but after adding the directory to the data_path I have this error:

```
>>>ERROR<<<
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
>>>ERROR<<<
    mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "suite2p/__init__.py", line 1, in <module>
    import suite2p.register
  File "suite2p/register.py", line 305
    cc = frames @ np.transpose(frames)
                ^
SyntaxError: invalid syntax
Interrupted by error (not finished)

```
It seems like it is a problem of python version, but I have python3 installed, and I even have an alias in bash_profile (and it works in terminal). I've tried to reinstall python3 with brew and brew doctor doesn't show any issues.

I'm running Mac Os 10.12.6.

**Comment by marius10p** [comment]
Can you use the @ operator outside of suite2p? We are not familiar with the brew distribution, but it's been tested on Mac with Anaconda.

**Comment by marius10p** [comment]
Oh, can you please state again what python version you are using? The title of your issue says python2...

**Comment by sneezeman** [comment]
> Oh, can you please state again what python version you are using? The title of your issue says python2...

So I'm using 3.7.3, but Mac OS has pre-installed 2.7.15, and I suggest it interferes somehow, but I don't understand, how exactly

**Comment by sneezeman** [comment]
> Can you use the @ operator outside of suite2p? We are not familiar with the brew distribution, but it's been tested on Mac with Anaconda.

Ok, so I tried and it works with new conda env. Thanks for your comment!
