### ISSUE TITLE
Help with images

### ISSUE THREAD

**Issue by neon-gh** [MouseLand/suite2p#188]
Hi, 

I apologize in advance if this question is addressed somewhere else. 

I haven't been able to successfully upload any of my own images taken with PrairieView software, whereas I am able to upload a friend’s images which were taken using ScanImage software. 

Do you know if the software is the issue or is it something else?

**Comment by carsen-stringer** [comment]
hm not sure, these are tiffs that you're using? and do they end in *.tif or *.tiff?

**Comment by neon-gh** [comment]
Yes they are tiffs and they both images end with tif

**Comment by neon-gh** [comment]
or actually my images end in .ome.tiff

**Comment by carsen-stringer** [comment]
how big are the tiffs? I think they should work with `scikit-image` . what is the error message you receive in the "run window"?

**Comment by neon-gh** [comment]
scikit-image solved the issue. 
Thank you!
