### ISSUE TITLE
processing cropped tiff files from ImageJ

### ISSUE THREAD

**Issue by schoki0710** [MouseLand/suite2p#191]
First of all, thanks a million times for establishing this wonderful tool! Now I have encountered a problem about processing some tiffs files that I have cropped from Image J (Image->Crop). I ran the pipeline in suite2p GUI with these tiff files, but the error says:

Exception: the total number of frames should be at least 50 

There was no problem running with the original files with exactly the same frame number, more than a thousand. I have no idea why this is the case. Or is there other way to only register and process a small ROI?

Thanks in advance.

**Comment by trucho** [comment]
refer to: https://github.com/MouseLand/suite2p/issues/135
In short, the SciScanTiffReader can read compressed TiffFiles.
If you crop in ImageJ, save stack as OME-TIFF to skip any compression

**Comment by zcq0730** [comment]
@trucho 
Thanks a lot for the very useful hint. For my case, I used Plugins ▶ Bio-Formats ▶ Bio-Formats Exporter
I selected TIFF (tagged image file format), without additional options and uncompressed. Then suite2p python can read the exported file as it should be.
https://imagej.net/Saving_and_Exporting
