### ISSUE TITLE
preclassify not working with user-built classifier

### ISSUE THREAD

**Issue by atranvan** [MouseLand/suite2p#192]
Hi,

I just upgraded to suite2p 0.6.3 and I like a lot the new preclassify option. 
I was finding the built-in classifier a bit too stringent on my data even after lowering the preclassify parameter value (lowest value I tried was 0.05), so wanted to try it with my user classifier. Is it possible?

I tried to set my classifier file as default then run the pipeline, and I get this error:

```
{'h5py': [], 'h5py_key': 'data', 'look_one_level_down': False, 'data_path': ['/media/tranvaa/1TB Data/2P/Glt_somas_dendrites_coupledD/ERAH23.1d/2019-05-09/tiffs'], 'subfolders': [], 'fast_disk': []}
FOUND OPS IN /media/tranvaa/1TB Data/2P/Glt_somas_dendrites_coupledD/ERAH23.1d/2019-05-09/tiffs/suite2p/plane0
FOUND BINARIES: /media/tranvaa/1TB Data/2P/Glt_somas_dendrites_coupledD/ERAH23.1d/2019-05-09/tiffs/suite2p/plane0/data.bin
SKIPPING REGISTRATION FOR ALL PLANES...
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
----------- ROI DETECTION AND EXTRACTION
Binning movie in chunks of length 30
Binned movie [2933,440,440], 87.12 sec.
NOTE: estimated spatial scale ~12 pixels, time epochs 2.44, threshold 24.44 
0 ROIs, score=642.20
Found 69 ROIs, 112.73 sec
NOTE: applying classifier /home/tranvaa/anaconda3/envs/suite2penv/lib/python3.6/site-packages/suite2p/classifiers/classifier_user.npy
ERROR: incorrect classifier file

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-48-9bafe929dc13> in <module>
     15 
     16 # run one experiment
---> 17 opsEnd=run_s2p(ops=ops_somas,db=db)
     18 

~/anaconda3/envs/suite2penv/lib/python3.6/site-packages/suite2p/run_s2p.py in run_s2p(ops, db)
    199             t11=tic()
    200             print('----------- ROI DETECTION AND EXTRACTION')
--> 201             ops1[ipl] = roiextract.roi_detect_and_extract(ops1[ipl])
    202             ops = ops1[ipl]
    203             fpath = ops['save_path']

~/anaconda3/envs/suite2penv/lib/python3.6/site-packages/suite2p/roiextract.py in roi_detect_and_extract(ops)
    228             shutil.copy(classorig, classfile)
    229         print('NOTE: applying classifier %s'%classfile)
--> 230         iscell = classifier.run(classfile, stat, keys=['npix_norm', 'compact', 'skew'])
    231         if 'preclassify' in ops and ops['preclassify'] > 0.0:
    232             ic = (iscell[:,0]>ops['preclassify']).flatten().astype(np.bool)

~/anaconda3/envs/suite2penv/lib/python3.6/site-packages/suite2p/classifier.py in run(classfile, stat, keys)
     80     model = Classifier(classfile=classfile, keys=keys)
     81 
---> 82     flag = np.zeros(len(model.keys), 'bool')
     83     new_keys = []
     84     for j in range(len(model.keys)):

AttributeError: 'Classifier' object has no attribute 'keys'
```

This happens with classifier files built with either suite2p v0.5.5 or v0.6.3

thanks a lot in advance!

**Comment by carsen-stringer** [comment]
you built the classifier in the GUI? this bug has come up before. Can you please load your classifier in a python terminal and look at the keys of the dict?
```
import numpy as np

classifier = np.load('/home/tranvaa/anaconda3/envs/suite2penv/lib/python3.6/site-packages/suite2p/classifiers/classifier_user.npy', allow_pickle=True).item()

print(classifier.keys()
```

This should have a key called 'keys'. I'm not able to replicate this error building a classifier in the GUI by choosing "iscell.npy" files, nor by adding data to a current classifier. can you go through how you built it?

**Comment by atranvan** [comment]
Hi Carsen,

Indeed as you suspected this returns:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-576fe1bd149e> in <module>()
      3 classifier = np.load('/home/tranvaa/anaconda3/envs/suite2penv/lib/python3.6/site-packages/suite2p/classifiers/classifier_user.npy', allow_pickle=True).item()
      4 
----> 5 print(classifier.keys())

TypeError: 'list' object is not callable

```

This classifier was built in the GUI: 
Classifier>Build
load iscell.npy
build classifier

then used the GUI button "add current data to the classifier" a couple of times from other datasets.

I have the same error/absence of classifier keys when I try (just did that right now) to do the first steps in the GUI:
Classifier>Build
load iscell.npy
build classifier
then Save loaded as default
and not adding extra data.

Is there anything I am doing wrong while building the classifier?

**Comment by carsen-stringer** [comment]
can you try saving your classifier to a different path, loading it in the GUI (also on the command line if not working) and then saving it to the default path? I'm not sure what is wrong here :/ 

also `pip install suite2p --upgrade` because there are some (probably unrelated) bugs in 0.6.3

**Comment by atranvan** [comment]
Hi Carsen,

After upgrading suite2p to 0.6.8 I have now a different error with newly built classifiers:

```print(classifier.keys())```

now returns:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-ca49d8024df9> in <module>
----> 1 print(classifier.keys())

TypeError: 'list' object is not callable
```

for some reason saving the classifier elsewhere and then re-saving to the classifier directory seems to work, and so does adding new data directly to the built-in classifier (I'll probably stick to this latter method) - no idea what is the difference but it does the job!

thanks for your help!

**Comment by carsen-stringer** [comment]
thanks for your detailed error messages, the bug was in "save loaded as default"! I've fixed this in the github version, will pip in a few days

**Comment by carsen-stringer** [comment]
I've made a new pip, I'm going to close this. please comment if you're still having issues.

**Comment by saramanc** [comment]
Hi Carsen,

I'm using Suite2p v0.14.4 locally on my Mac and encountering the same issue:
loading classifier  /Users/saramancinelli/suite2p/classifier/L5_slice.npy
ERROR: incorrect classifier file

I checked the presence of the key in my file, and it seems to be there:
>>> model = np.load('/Users/saramancinelli/suite2p/classifier/L5_slice.npy', allow_pickle=True).item()
>>> print(model.keys())
dict_keys(['stats', 'iscell', 'keys'])

Would you be able to help me troubleshoot this?

Thanks in advance,
Sara
