### ISSUE TITLE
scrolling through each ROI quickly without typing in ROI number

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#194]
Hello, 
Is there a way to scroll through the ROIs quickly (i.e., forward and backward arrow buttons) to see the fluorescence traces without typing in the ROI number?

Thank you!

**Comment by marius10p** [comment]
No, but that's a good idea!

**Comment by carsen-stringer** [comment]
this is now in the latest pip (`pip install suite2p --upgrade`) the left and right arrow keys will scroll, make sure you're clicked in the suite2p window for them to work

**Comment by sarahapark** [comment]
It's nice to be able to scroll through the "good" ROIs in the "cells" window. Is there a way to scroll through the "bad" ROIs in the "not cells" window too?
