### ISSUE TITLE
Running registration outside pipeline

### ISSUE THREAD

**Issue by trucho** [MouseLand/suite2p#195]
I have been trying to run the registration algorithm outside the suite2p pipeline, but I have been getting different results for the "refImg" when running outside or inside the pipeline.
When running:
> from suite2p import register
> refImg = register.pick_init(ops)

can the ops['reg_file'] be a tiff stack directly? or is this function expecting binary data?
Is there a way to stop running the pipeline after registration without running into issues?

**Comment by marius10p** [comment]
If you set the cell detection option to 0, then it will stop after registration. 

reg_file needs to be binary, which you can create with `ops1 = utils.tiff_to_binary(ops)`. You need to give it `ops['data_path']` for the folder of tiffs, and `ops['reg_file']` for the full path to the binary file you want  created.

**Comment by carsen-stringer** [comment]
fyi the option to turn off cell detection is called `ops['roidetect']`, set this to 0 in the GUI or in your notebook

**Comment by carsen-stringer** [comment]
btw there is a randomness involved in creating the reference image - it takes a random `ops['nimg_init']` frames from the data and uses those, so it will be different each time you run it. I'm closing this for now, please comment if you're still having issues
