### ISSUE TITLE
Checking suite2p version 

### ISSUE THREAD

**Issue by windgrazer** [MouseLand/suite2p#196]
Hi there!

Thank you for this wonderful program - I have previously installed the python version on several Windows 7 and Windows 10 computers and recently got a new computer which I also tried to install the python suite2p. I have been installing suite2p through pip install.

However, suite2p seems to have been updated from the last time I installed them and having processed lots of data with the previous version already, I would like to know if there is a way to check the currently installed version of suite2p, and also if I will be able to retrieve/install previous versions from an archive?

Thank you!

**Comment by marius10p** [comment]
Sure, try `pip show suite2p`, and `pip install suite2p==0.5.5` or whatever version you need. The history is  [here](https://pypi.org/project/suite2p/#history). The main change has been to the cell detection algorithm. The other steps are algorithmically the same, with some efficiency updates throughout particularly for registration.

**Comment by windgrazer** [comment]
Thank you so much! This helps a lot!
