### ISSUE TITLE
NameError: name 'ndimage' is not defined 

### ISSUE THREAD

**Issue by gg9761** [MouseLand/suite2p#197]
Hi,

I have recently updated to the latest version of the pipeline. I tried to run a video through the pipeline using similar settings to what I had been using before but get the following error (see below). I have previously run this video using v 0.5.5 with no issues. Any suggestions on what might be going wrong?

The recording is 1P using GCaMP 6s.

Thanks in advance

** Found 1 tifs - converting to binary **
2000 frames of binary, time 38.86 sec.
4000 frames of binary, time 66.76 sec.
time 82.40 sec. Wrote tifs to binaries for 1 planes

----------- REGISTRATION
Reference frame, 36.04 sec.
2500/5054 frames, 109.57 sec.
5000/5054 frames, 213.93 sec.
5054/5054 frames, 216.78 sec.
Registration metrics, 43.94 sec.
----------- Total 298.74 sec
----------- ROI DETECTION AND EXTRACTION
Binning movie in chunks of length 05
Binned movie [1010,241,509], 14.56 sec.
===== 2019.06.20 16:06:10 =====
>>>ERROR<<<
Traceback (most recent call last):
AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\__main__.py", line 28, in <module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\run_s2p.py", line 201, in run_s2p
    ops1[ipl] = roiextract.roi_detect_and_extract(ops1[ipl])
AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\roiextract.py", line 216, in roi_detect_and_extract
    ops, stat = sparsedetect.sparsery(ops)
AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\sparsedetect.py", line 325, in sparsery
    rez, max_proj = get_mov(ops)
AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\sparsedetect.py", line 78, in get_mov
    mov[:,j,:] -= ndimage.gaussian_filter(mov[:,j,:], [ops['high_pass'], 0])
NameError: name 'ndimage' is not defined
Interrupted by error (not finished)

![s2p settings ](https://user-images.githubusercontent.com/50708259/59859715-2f910280-9375-11e9-92ea-61a92f1fa47c.jpg)

**Comment by carsen-stringer** [comment]
Thanks for catching this. I've made a new package without this error so please `pip install suite2p --upgrade`. And then try the "1P imaging" ops. if you're unhappy with the results change to the old cell classification (`ops['sparse_mode']=0`), but make sure you set the diameter to the approximate cell diameter in pixels if you do this
