### ISSUE TITLE
GUI not opening upon python -m suite2p

### ISSUE THREAD

**Issue by charlottearlt** [MouseLand/suite2p#198]
Hello, I have followed the installation instructions and am not getting any errors upon 'conda activate suite2p', but when running 'python -m suite2p', no GUI opens. I am using Windows 10 and have tried both in the Anaconda Prompt and the command line, same result. 
May you have any ideas what might be going wrong?
Thanks so much!

**Comment by carsen-stringer** [comment]
Can you type "pip list" and see if suite2p "pip" installed correctly? It should show up on that list if it has.

**Comment by charlottearlt** [comment]
Hi! Yes, suite2p 0.6.3 shows up on that list. I also tried running the anaconda prompt as an administrator and got the same results.

**Comment by carsen-stringer** [comment]
are you getting any error message after you type 'python -m suite2p'?

**Comment by charlottearlt** [comment]
No error message - it just takes some time seemingly doing something, and then returns nothing (see screenshot). 
![CondaScreenshot](https://user-images.githubusercontent.com/8094921/60282743-b003b600-98d5-11e9-9f7a-b987ba0fcf89.PNG)

**Comment by carsen-stringer** [comment]
I think you would have gotten errors before this point, but just to check, you've installed python3 anaconda?

**Comment by charlottearlt** [comment]
Yes, I have python 3.6.8  anaconda

**Comment by carsen-stringer** [comment]
I haven't seen this before, there weren't any errors during install? You could also try installing an earlier version `pip install suite2p==0.5.5`, or update to the latest one `pip install suite2p --upgrade`, I'm not sure if I had a bug in that one.

**Comment by charlottearlt** [comment]
I think I had an issue with mkl_fft during the installation, but fixed it by installing this separately. I tried the old and new suite2p version, still no errors with no GUI opening upon python -m suite2p.

**Comment by carsen-stringer** [comment]
:( I've put the help-wanted flag on this but I honestly don't know what is causing this. do you have a 32bit windows computer? there have been issues with 32bit windows in the past

**Comment by ronan-dasilva** [comment]
Hey!

I am just trying to install suite2p in a new machine in the lab and I also had a problem with mkl-fft during installation.

I tried to manually install it using pip (both from the internet and also by downloading the file), but neither worked. It seems that on Windows mkl-fft is only available for amd64 platforms (https://pypi.org/project/mkl-fft/1.0.6/#files), so I am guessing this error comes from trying to install it on an Intel based machine (that's the error I got when trying to install from file: `ERROR: mkl_fft-1.0.6-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.`.

Is mkl-fft a new requirement for S2P? Is there a workaround for this?

Cheers!

**Comment by ronan-dasilva** [comment]
Hey again!

Ok, dumb me: the problem of mkl-fft was not with the windows version, but rather with the python version. I just created a new environment with python 3.6 and everything worked fine... ^.^"

@charlottearlt, one thing that might be helpful then is to just update everything you can (anaconda included), create a fresh environment with python=3.6 and then pip install suite2p?

@carsen-stringer, this might be worth keeping an eye upon... if ever suite2p starts requiring python>=3.7 for any reason, mkl-fft will not work unless they release an update.

Hope this helps!

Ronan

**Comment by carsen-stringer** [comment]
Thanks, I think the conda package for mkl-fft is fine with python 3.7, I've tested and updated the environment to use python 3.7. I recommend using the [environment.yml](environment.yml) package to install suite2p so you don't have to worry about these dependencies yourself, and so you have the fastest mkl (for mkl-fft).

btw @charlottearlt there have been some updates to pyqt5 that may have resolved whatever your issue was, but not sure, you can try removing and creating the environment again:
```
conda env remove -n suite2p
conda env create -n suite2p
```

You may want to try uninstalling and reinstalling the latest Anaconda as well. I am going to close this issue due to inactivity but please comment if you're still having problems.

**Comment by charlottearlt** [comment]
Hi Carsen, apologies for this very late reply, but removing and then re-creating the environment did indeed help! Thanks a lot for your advice!
