### ISSUE TITLE
Error message appears in 0.6.6 version (if os.path.isfile(os.path.join(ops['data_path'][0], 'bad_frames.npy')): Index Error: list index out of range)

### ISSUE THREAD

**Issue by schoki0710** [MouseLand/suite2p#199]
I recently switched suite2p versions from 0.5.5 to 0.6.6 and tried running the same data. However in the latest version some unfamiliar error message came up as following:
>>>ERROR<<<
    if os.path.isfile(os.path.join(ops['data_path'][0], 'bad_frames.npy')):
IndexError: list index out of range

I used hdf5 files. The old version (0.5.5) worked very well with the same data set. Could you please explain what the error message means? Thanks a lot in advance!

**Comment by carsen-stringer** [comment]
sorry this is a new option that I hadn't tested with hdf5, thanks for catching that, should be working fine in the latest pip (`pip install suite2p --upgrade`)
