### ISSUE TITLE
issue saving registered tif aligned with channel 2

### ISSUE THREAD

**Issue by marcello1985** [MouseLand/suite2p#200]
Hello,

First of all thanks for making this amazing tool available!

I have data with one plane, two channels. I am setting the ops.npy so that registration is done via channel 2, and I would like to save each channel after registration as a tif file. The relevant options I put are the following:

 'nplanes': 1,
 'nchannels': 2,
 'functional_chan': 1,
 'combined': True,
 'do_registration': True,
 'keep_movie_raw': False,
 'align_by_chan': 2,
 'reg_tif': True,
 'reg_tif_chan2': True,
 
The output in the folder 'reg_tif_chan2' is two files:
file_chan000.tif  file_chan001.tif
both appear to be have data from channel 1 

If instead I set  'align_by_chan': 1
in the folder reg_tif
file_chan000.tif  file_chan001.tif
both appear to be have data from channel 2 

 is there a correct set of options to have the the tif of channel 1 and the tif from channel 2 both registered using the data in channel 2 for alignment? In the GUI the mean images for channel 1 and 2 have the expected data so I don't think there an issue there.

Thank you,

Marcello

**Comment by carsen-stringer** [comment]
Hmm there should be a second folder made called 'reg_tif_chan2', is this being created? At the end of the run can you see the 'mean img (chan2)' in the GUI?

**Comment by marcello1985** [comment]
thanks for the prompt reply!

Yes I can see both mean images in the GUI (channel 1 with cells, and channel 2 with vasculature in my case)

 but in terms of folders it creates either 'reg_tif_chan2' or ''reg_tif', depending if I set 'align_by_chan': 1 or 2, never both for the same run

Also what is the difference between the files file_chan000.tif file_chan001.tif ? There are meant to represent channel 1 and 2, correct?

**Comment by carsen-stringer** [comment]
No that is just some bad naming on my part, I make one tiff for each "batch_size" of frames so those correspond to the first "batch_size" frames and then the next "batch_size" frames and so on depending on recording size. I'll test this later tonight and get back to you. You should get both folders regardless of 'align_by_chan', in this case 'reg_tif' should be the folder for the *functional* channel, and 'reg_tif_chan2' should be the folder for the *anatomical* channel.

**Comment by marcello1985** [comment]
Ok understood! Thank you

**Comment by marcello1985** [comment]
Hello, I was wondering  if you had a chance to look into this issue further?

**Comment by carsen-stringer** [comment]
yeah I've fixed this in the github version of suite2p (not yet in the pip), let me know if it's not working, i'll make a new pip in a couple days after I resolve a few more issues

**Comment by carsen-stringer** [comment]
`pip install suite2p --upgrade` for this fix. let me know if there are still problems

**Comment by carsen-stringer** [comment]
I'm closing this, please comment if it's not working for you
