### ISSUE TITLE
no GPU with the python edition?

### ISSUE THREAD

**Issue by eskuebler** [MouseLand/suite2p#201]
This is by far the best free software I have ever had the pleasure of using!

I was using the Matlab version and there was an option for GPU (specifically Nvidia I think) and there doesn't appear to be this option with the python version that I've switched to (I maybe missed it?), suite2p doesn't seem to use it automatically. I'm just curious if there is a way to speed up the processing by adding the GPU?

**Comment by carsen-stringer** [comment]
thanks! yeah we have not managed to get speed ups with the GPU in python. registration should run as fast as in matlab+GPU with the parallelization we've done with numba. make sure you don't set the number of threads that python uses to 1 (so don't change the default settings).
