### ISSUE TITLE
Detect peaks without deconvolving

### ISSUE THREAD

**Issue by marcelbvv** [MouseLand/suite2p#202]
Hi,
First of all, thanks  lot for this software! It works quite nicely and it is saving me a lot of time. 

I'm currently using Suite2P only ROI detection and fluorescence extraction but I would also like to detect peaks (calcium events) without going into deconvolution. From what I read, before doing the deconvolution, oasis is detecting this events. The problem is that the deconvolution is not working great for my dataset. 

I'm imaging interneurons infected with GCaMP6f in layer 2/3 of the mouse barrel cortex. The sampling frequency is 30Hz.

Do you have any suggestions?
Sorry if the question is a bit basic...
Let me know if you need extra information!

Thanks a lot for your help

**Comment by carsen-stringer** [comment]
We are not enforcing any L0 or L1 sparsity penalties so all these events should be outputted, I'm tagging in @marius10p because he knows more about this

**Comment by marius10p** [comment]
Can you please tell us in what way it's not working great. See [here](https://www.jneurosci.org/content/38/37/7976.abstract) for the deconvolution method we use. Should work well in a variety of situations.

**Comment by marcelbvv** [comment]
![Deconvolved Trace](https://user-images.githubusercontent.com/27411758/65064527-f3c00600-d980-11e9-9b05-880c56eeab21.jpg)
Thank you so much for your replies. 
Independent of what parameters I put in the deconvolution I always end up with spikes being detected in what I would identify as baseline. 
(In the trace I show I would identify one clear calcium event and maybe a few small events).
Is this result normal or do you think I just didn't find the right settings yet?

**Comment by marius10p** [comment]
That result is normal, and corresponds to the small transients riding on top of your baseline. That big transient is probably a burst of tens or hundreds of spikes, and the smaller wiggles on the baseline are more in the range of 1-2 APs. Notice the big transient stays around for 200 frames, so 7s, which means it corresponds to very many APs spread out over that time period. 

Unfortunately it is hard to know how big a single AP should be, unless you have a priori information about how much your neuron should spike and what happens behaviorally in different recording epochs. Other algorithms (see OASIS) have a sparsity parameter which you can increase to sparsify the result. However, we found that parameter to always decrease the agreement between ground truth and deconvolved spikes, so we disabled it completely in our implementation of OASIS. See figure 2 of our paper:

![image](https://user-images.githubusercontent.com/3935246/65065767-0de1f000-d951-11e9-9c8a-64c7f1fcf3b3.png)

**Comment by marcelbvv** [comment]
Ok. That's good to know!

So for quantification purposes would you report the total number of spikes or would you set some kind of threshold?
I've seen people do both but I would like to know what you suggest...

**Comment by marius10p** [comment]
It depends if you need to report absolute or relative activity levels. Relative is easy: just take the deconvolved data, bin it however you need and compare between different recording periods / stimuli. Absolute activity levels (i.e. "0.1 Hz") would be very hard to estimate. People sometimes say "X transients per second", in which case I agree that you can just threshold the output, or use one of these other algorithms that automatically sparsifies the deconvolution. Just be aware that you are losing information by the thresholding operation.

**Comment by marcelbvv** [comment]
Thanks for your reply.

So if I would apply a threshold directly to the deconvolved trace how do you suggest I define that?
I would like it to be related to some parameter in the fluorescence trace (standard deviation of the baseline for example), however I'm not sure if the values of fluorescence and the deconvolved traces change linearly.
Would a threshold based on the average number of spikes during baseline periods make sense to you?

**Comment by marius10p** [comment]
I don't think there is a right answer to this. Whatever makes the most sense to you, just be aware of the biases you are introducing in your downstream analyses. If you find a result that seems suspicious, think through whether you may have introduced it in the thresholding and design appropriate control
