### ISSUE TITLE
Reading multiple arrays from single .h5 file

### ISSUE THREAD

**Issue by aprrenard** [MouseLand/suite2p#203]
Hi, I work with a single .h5 file per recording with successive trials stored under different keys (e.g. /loop_1, /loop_2, ..., /loop_n, each loop being a (time x pixel x pixel) array). To avoid data duplication, would it be possible to pass a list of keys to `df['h5py_key']` to read from `df['h5py']`? Thanks for this great work!

**Comment by carsen-stringer** [comment]
I've added this feature to the github version. see an example use case in the last block of this jupyter notebook: https://github.com/MouseLand/suite2p/blob/master/jupyter/run_pipeline_tiffs_or_batch.ipynb

You will have to run suite2p in the jupyter notebook (not the GUI). but then you can load the output into the GUI afterwards with the stat.npy file.

**Comment by carsen-stringer** [comment]
i'm closing this issue, please comment if it's not working and I'll reopen

**Comment by aprrenard** [comment]
It's working fine, thanks!
