### ISSUE TITLE
Not saving data_raw.bin so the "view registered binary" function gets blocked (version 0.6.8)

### ISSUE THREAD

**Issue by schoki0710** [MouseLand/suite2p#205]
Dear great suite2p developers, 

I think in suite2p 0.6.8 version the data_raw,bin is not saved even though I put "keep_movie_raw = 1" in the GUI. When I tried to view the registered binary, the program expects data_raw.bin but since this does not exist, I cannot view either registered or non-registered binary. This function is basically blocked because of that. But I found that I can actually view the registered binary of the same data using suite2p version 0.5.5. Could it be a bug in the latest version? For your information, I used hdf5 files. Million thanks in advance.

**Comment by carsen-stringer** [comment]
thanks for catching this, I think I've fixed this for h5 files (and tiffs potentially) and it should be backward compatible with these experiments that you've run with the messed up code. it's currently in the github version, not yet in the pip

**Comment by carsen-stringer** [comment]
`pip install suite2p --upgrade` for the fix, let me know if there are still problems
