### ISSUE TITLE
Missing shutil import in roiextract.py

### ISSUE THREAD

**Issue by neuromantic99** [MouseLand/suite2p#209]
Hi,

Thanks for the awesome software!

I think there may be a minor bug in roiextract.py.

Line 231: shutil.copy(classorig, classfile).

However the shutil package is not imported. For me, this caused an error to be raised.

**Comment by carsen-stringer** [comment]
thanks for reporting this, it's been fixed in the github version, I'll make a new pip this weekend

**Comment by carsen-stringer** [comment]
`pip install suite2p --upgrade` to fix this
