### ISSUE TITLE
50 frames error

### ISSUE THREAD

**Issue by neuronerd22** [MouseLand/suite2p#210]
I have this at least 50 frame error. I've tried all the recommendations in our strings of issues. I'm not sure how to go about it and if it's maybe that I have the latest version on my Mac? I am running a file with 77 tifs and I receive the error message every time. I've tried redownloading, saving the tif in different ways, and nothing has worked. I would really appreciate some guidance! Cheers!

**Comment by carsen-stringer** [comment]
so the folder has 77 tiffs? are their names ending in *.tif or *.tiff? it seems like suite2p isn't seeing them or something else. what program do you use to make the tiffs?

**Comment by neuronerd22** [comment]
The ending is .tif. I converted them from .lif to .tif using Fiji on my Mac.

**Comment by carsen-stringer** [comment]
did you try this trick from  @kylemxm ? are your tiffs big?
"I had the same problem today running a fresh install of Suite2P on Tif stacks larger than 4 GB saved from ImageJ (Exception: the total number of frames should be at least 50). It seems saving from ImageJ as "filename.tif" by going to "File->save as->OME-TIFF->compression type uncompressed" in FIJI solves the problem and Suite2P can handle the data (Found 1 tifs 3927)."
([issue](https://github.com/MouseLand/suite2p/issues/135))

**Comment by neuronerd22** [comment]
Yes i did try that. Didn’t work unfortunately

**Comment by neuronerd22** [comment]
1.1 MB each!

**Comment by carsen-stringer** [comment]
ah are these single-page tiffs?

**Comment by neuronerd22** [comment]
Yes

**Comment by carsen-stringer** [comment]
ack I haven't tested with single-page tiffs in a while, can you please upload them to this drive [folder](https://drive.google.com/drive/folders/1fomrp9_Vp5osPjoKAfAtp9wviznmxfaZ?usp=sharing) and I'll sort it out

**Comment by neuronerd22** [comment]
just uploaded them!

**Comment by carsen-stringer** [comment]
this was actually an issue with the type of the tiffs not that they were single plane. I've fixed the pipeline now that it will cast 'uint8' to 'int16' automatically. I'd also recommend that you run with `ops['sparse_mode'] = 1` with this sort of data (and with more frames if possible).

**Comment by neuronerd22** [comment]
Can I just use the suite2p I have or do I need to redownload?

**Comment by carsen-stringer** [comment]
if you're using github, `git pull` the repository to get the latest, or if you used pip, `pip install suite2p --upgrade` in the environment which has the required packages you've previously installed

**Comment by neuronerd22** [comment]
when i try the pip install suite2p upgrade i get 
ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade

**Comment by neuronerd22** [comment]
haha never mind, I had a space between dashes and upgrade, my fault

**Comment by carsen-stringer** [comment]
cool I'm going to close the issue please comment if you're still having problems and I'll reopen it
