### ISSUE TITLE
NameError in `sourcery.convert_to_pix`

### ISSUE THREAD

**Issue by efharkin** [MouseLand/suite2p#212]
Using pyflakes for static code analysis, I noticed that `Ly` and `Lx` are referred to in `sourcery.convert_to_pix` (see below) but not defined there. 

https://github.com/MouseLand/suite2p/blob/fbffcf21eae3e494c71b5f19d850b5e41e506ae8/suite2p/sourcery.py#L216

`convert_to_pix` doesn't seem to be used anywhere in `suite2p` at the moment, so this isn't an urgent issue, but it will probably cause a `NameError` if the function is incorporated into the pipeline in the future.

Thanks for all your work on this library!

**Comment by carsen-stringer** [comment]
thanks for pointing this out, I've deleted this function as it's no longer used
