### ISSUE TITLE
Conflicting information in Settings Wiki vs. default_ops() 

### ISSUE THREAD

**Issue by DgwFreeman** [MouseLand/suite2p#213]
In the default_ops() function, the comment next to ops['fs'] indicates that it's the sampling rate total across planes, while the settings wiki indicates that it's per plane. Which one is it? I'm assuming the latter, but I just thought I would let you know.

**Comment by carsen-stringer** [comment]
thanks for pointing this out! yes it's the PER PLANE sampling rate, I have fixed this comment
