### ISSUE TITLE
Option to change default export folder name 

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#214]
Would it be possible to include an option to attach a pre/suffix to the default export folder name `suite2p` or choose a custom name? 
This would be very convenient for cases in which you want to analyse the same dataset multiple times (with different options). So one folder could be 'suite2p_sparse_mode', next to 'suite2p_another_test', without having to create different top level folders.

**Comment by carsen-stringer** [comment]
yeah I agree, I think to remove complications with this method the user would have to specify a static "fast_disk" folder so that all these folders point to the same binary file (copying that would be slow and unnecessary). is this a feature you'd want in the GUI or in a notebook?

**Comment by horsto** [comment]
Great! Yes, that's right, maybe the 'fast_disk' could default to 'data_path' instead of 'save_path' (or data_path/temp_folder)? I (personally) don't need a GUI feature for that. Maybe it could be included as optional argument in the `db` dictionary (`run_s2p(ops,db)`)?

**Comment by carsen-stringer** [comment]
I've added it to the github version. see an example use case in the second to last cell of this jupyter notebook: https://github.com/MouseLand/suite2p/blob/master/jupyter/run_pipeline_tiffs_or_batch.ipynb

**Comment by carsen-stringer** [comment]
i'm going to close this - please comment if it's not working for you

**Comment by horsto** [comment]
Thanks a lot for doing this! 
It runs into a file not found error in `run_s2p.py` in line 171. I think the following line should change: 
https://github.com/MouseLand/suite2p/blob/0ec481eed53c19732927f94b0b907e4480088c75/suite2p/run_s2p.py#L108

**Comment by horsto** [comment]
also probably this one? https://github.com/MouseLand/suite2p/blob/46b801db41d7de9a40362f677834fcc908437dd2/suite2p/gui.py#L406

**Comment by horsto** [comment]
Just to follow up on this:
https://github.com/MouseLand/suite2p/blob/0ec481eed53c19732927f94b0b907e4480088c75/suite2p/run_s2p.py#L108

I think should change to 

```
    # check if there are files already registered!
    if len(ops['save_folder']) > 0:
        fpathops1 = os.path.join(ops['save_path0'], ops['save_folder'], 'ops1.npy')
    else:
        fpathops1 = os.path.join(ops['save_path0'], 'suite2p', 'ops1.npy')
```

**Comment by carsen-stringer** [comment]
I've added this change to run_s2p please comment if you have issues
