### ISSUE TITLE
registration metrics

### ISSUE THREAD

**Issue by neon-gh** [MouseLand/suite2p#215]
Hi 

I'm having an issue with seeing the registration metrics and I'm not sure if it has something to do with the settings or if I'm missing something else?
When I click "View registration metrics" I get something like this:

<img width="1230" alt="Screen Shot 2019-07-17 at 5 59 17 PM" src="https://user-images.githubusercontent.com/51467679/61414810-e755f900-a8bc-11e9-8e99-d1fd24d150e9.png">

**Comment by carsen-stringer** [comment]
there might be an error in the terminal that you can't see. please note that registration metrics are only computed if you have more than 1500 frames.
