### ISSUE TITLE
roi detection on only part of the data

### ISSUE THREAD

**Issue by jwdegee** [MouseLand/suite2p#216]
Thank you for this wonderful piece of software! I was wondering whether you considered adding an option to run the ROI selection on only a subset of the frames. I'm asking because in some sessions we are dealing with substantial motion after a while. See an extreme example attached, in which the blue traces correspond to 'xoff' and 'yoff' in ops. In this case, it would be nice to re-run the roi selection based on only the first 1000s (and also analyze the fluorescence time series up to that point). Of course I could cut the TIFF in a 2nd step and re-run everything, but that seems like a waste time.

![preprocess_C7A2_3](https://user-images.githubusercontent.com/3235493/61569479-26b34f80-aa4d-11e9-8af2-2324a8eb4d61.png)

**Comment by carsen-stringer** [comment]
Glad you're enjoying the software :) some of these frames may already be consider "bad" and excluded from cell detection. After registration, we look at the XY shifts and label frames as "bad" if the shifts are very large. These frames are then not used to determine the cropped size of the FOV for cell detection, and also not used during cell detection. A boolean of which frames were excluded is included in ops.npy as `ops['badframes']`. You can also explicitly specify the bad frames for exclusion as a numpy array (0-based, the first frame is zero) and save it as `bad_frames.npy` in the folder with your tiffs (if you have multiple folders, save it in the FIRST folder with tiffs, or if you have subfolders with 'look_one_level_down' it should be in the parent folder).

I've added documentation for this in the [wiki](https://github.com/MouseLand/suite2p/wiki/Input-format,-file-types,-and-frame-exclusion). You can check after running if it worked by checking that `ops['badframes']` has True values where you specified bad frames.
