### ISSUE TITLE
running registration and cell identification on only one of two planes

### ISSUE THREAD

**Issue by KuchibhotlaLab** [MouseLand/suite2p#221]
Quick question: is it possible to run the pipeline on only one plane of our two-plane data? We ran a massive multi-session dataset through suite2p and it generated the binaries for both planes and then only got through the rest of the pipeline for plane0 before our server had issues. So, we have binaries, registered binaries, cell identification, and extraction for plane0. It took approximately 2 days for this. For plane1, we have the binary files but nothing else (it had just started registering plane1 when the server issue occurred). Is it possible to launch the registration, cell detection and extraction pipeline for a single plane?

**Comment by carsen-stringer** [comment]
yes, and check out [run_s2p.run_s2p](https://mouseland.github.io/suite2p/_build/html/_modules/suite2p/run_s2p.html#run_s2p). You can load in `ops1.npy` and choose ipl, I've copied the relevant steps below:
```
ipl = 0 # <--- plane
fpathops1 = 'PATH_HERE/ops1.npy' #<--- path
ops1[ipl] = register.register_binary(ops1[ipl]) # register binary
np.save(fpathops1, ops1) # save ops1 to main root where it lives
ops1[ipl] = regmetrics.get_pc_metrics(ops1[ipl])
np.save(os.path.join(ops1[ipl]['save_path'],'ops.npy'), ops1[ipl])
print('----------- ROI DETECTION AND EXTRACTION')
ops1[ipl] = roiextract.roi_detect_and_extract(ops1[ipl])
ops = ops1[ipl]
fpath = ops['save_path']

print('----------- SPIKE DECONVOLUTION')
F = np.load(os.path.join(fpath,'F.npy'))
Fneu = np.load(os.path.join(fpath,'Fneu.npy'))
dF = F - ops['neucoeff']*Fneu
spks = dcnv.oasis(dF, ops)
np.save(os.path.join(ops['save_path'],'spks.npy'), spks)
```
