### ISSUE TITLE
Has the radius calculation changed in new version (v6.0) ?

### ISSUE THREAD

**Issue by gg9761** [MouseLand/suite2p#230]
Hi,

Thanks for your brilliant program and quickly responding to queries.

I was wondering if the methods used to calculate the cell radius has changed between versions 5.0 and 6.0? I have run the same timelapse recording through on each version with identical settings. Upon analyzing cell sizes extracted from the new version of the program, the cell areas, which are calculated from the radius, are a lot larger than they were before. I estimate that the new version of the program increases the size of each cell by an average of 30%.

thanks for your help,

George

**Comment by rajatsaxena** [comment]
Are you using the sparse-mode cell extraction (`sparse_mode`) or actually passing a value for diameter.  Note that the diameter value is ignored if `sparse_mode` is set to 1.

**Comment by gg9761** [comment]
I am using sparse mode = 0
Attached are the settings I have been using.

![Untitled](https://user-images.githubusercontent.com/50708259/64021647-5cf3ec80-cb2c-11e9-8838-bd75e68bbbba.jpg)

**Comment by carsen-stringer** [comment]
the radius computation may have changed and I'll check that it's working. It fits a multivariate gaussian to the pixel weights and sets the radius to 2 x standard deviation. But in general I wouldn't use it for determining cell size - use stat[n]['npix'] which gives you the total number of pixels.

**Comment by gg9761** [comment]
Ok thanks for your reply. I'll try using the number of pixels instead.
