### ISSUE TITLE
application crashes when using latest PyQt5==5.13.0

### ISSUE THREAD

**Issue by pescobar** [MouseLand/suite2p#235]
I was getting this error when trying to launch `python -m suite2p`

```
QLibraryPrivate::loadPlugin failed on "$HOME/anaconda3/envs/suite2p/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library $HOME/anaconda3/envs/suite2p/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory)"

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

googling a little bit I realized that the dependency on `libxkbcommon-x11.so.0` was introduced by `PyQt5==5.12.0`
https://www.riverbankcomputing.com/pipermail/pyqt/2019-February/041363.html

To workaround it I downgraded the PyQt5 version inside the conda environment doing `pip install PyQt5==5.11.3`. IMO it would be nice if the provided [environment.yml](https://github.com/MouseLand/suite2p/blob/master/environment.yml#L15) specifies the right PyQt5 version to avoid this issue.

Another workaround would be to install the missing library `libxkbcommon-x11.so.0` using system packages (e.g. rpm or deb) but this would require root access

**Comment by carsen-stringer** [comment]
thanks for catching this, I've modified the environment.yml

**Comment by carsen-stringer** [comment]
I want to note that ctrl+click for selecting multiple cells won't work in the latest pyqtgraph github version in **Linux** specifically. I've changed the dependence to be on the pip package for now until I change the click capturing.
```
pip uninstall pyqtgraph
pip install pyqtgraph
```
