### ISSUE TITLE
application crashes if the installation folder is not owned by the user launching the app

### ISSUE THREAD

**Issue by pescobar** [MouseLand/suite2p#236]
I am getting this error when launching `python -m suite2p` in a conda environment not owned by my user

```
(suite2p) [user1@login10 ~]$ python -m suite2p
===== 2019.09.05 08:09:16 =====
Traceback (most recent call last):
  File "/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 30, in <module>
    gui2p.run()
  File "/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/gui2p.py", line 1493, in run
    GUI = MainW(statfile=statfile)
  File "/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/gui2p.py", line 61, in __init__
    shutil.copy(self.classorig, self.classfile)
  File "/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/classifiers/classifier_user.npy'
```

the problem seems to be that I have no write permissions to file `Anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/classifiers/classifier_user.npy`

Many different users in this system needs to use the suite2p so we would like to have a single installation that is used by all them as we do with all the other applications. Is there any workaround for this?

This also prevents us to run the application inside a [Singularity container](https://en.wikipedia.org/wiki/Singularity_(software)) . If possible we would like to use singularity for portability and reproducibility.

**Comment by pescobar** [comment]
as workaround I did 

```chmod 777 /scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/classifiers/``` 

now I can launch the application and a new file `classifier_user.npy` is created inside the folder `/scicore/home/user2/GROUP/Anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/classifiers/` by the first user who launches the application. Other users can also launch the application also but no new files are created. It seems to work (at least multiple users can open the GUI) but I am not sure if this would affect the application behaviour or if it will be stable

**Comment by carsen-stringer** [comment]
Ah I see. That file should stay in that folder so the GUI knows where it is at all times. Does it now work in singularity with this work-around? 

An easy fix is that when this error happens, I force the GUI to use classifier.npy and not allow it to be modified by the user. Is this the behavior you'd want? I can then also make an option from the run window for choosing a user-specific classifier.

**Comment by pescobar** [comment]
the workaround doesn't work in singularity because the singularity containers are read-only. Once you create a container the user executing it cannot add new files to the container, no matter if the folder has `777` permissions

To be honest, I have no strong opinion about what would be the desired behaviour because I am not user of the application. I am a sysadmin installing the application for some users in my cluster. Based in my experience installing scientific software I would expect that the user's specific config files are stored in the user's home folder and not in the application's installation folder. e.g. in most linux applications when you launch an application for the first time a new folder storing the user configuration is created in `$HOME/.appname/` . This approach would also work when using singularity containers because the user's home folder is mounted inside the container by default.

**Comment by carsen-stringer** [comment]
I've changed this so that `$HOME/.suite2p` is where the user classifiers and ops files are stored
