### ISSUE TITLE
Spike rate from deconvolved data

### ISSUE THREAD

**Issue by jj7788** [MouseLand/suite2p#237]
First of all, thanks a lot for making the code availavle. It is remakably powerful and user-friendly. 

Apologies for my somewhat basic question regarding spike rate estimation. Values of deconvoluted traces from my data go up to a couple thousand. Do I interpret correctly that these values are essentially spike probability values in %? As such, anything below 100 should probably be discarded, which would fit, as these peaks are in the raw trace usually undistinguishable from noise by eye. A value of 1000 would represent an estimated rate of 10 spikes for that frame. Is my assumption correct? 

Also, I can reduce the amount of presumed false positives in the deconvoluted trace by increasing sig_baseline, but I am not sure whether it is a good strategy. 

Thanks a lot for the help!

**Comment by carsen-stringer** [comment]
the values are not spike probabilities, they are more like "quantities" of spikes.  For each neuron, the size of a calcium transient per spike will vary (and it will vary even from spike to spike), so we cannot directly convert these numbers into numbers of spikes. We do not apply any sparsity penalties (and recommend against it in our JNeurosci [paper](http://www.jneurosci.org/content/38/37/7976)). Also check out our review [paper](https://www.sciencedirect.com/science/article/pii/S0959438818300977) for more info about this.

Increasing sig_baseline will increase the smoothing before baselining, meaning that there will probably be less baselining. You can see what happens by running 
```
# compute deconvolution
from suite2p import dcnv
import numpy as np

tau = 1.0 # timescale of indicator
fs = 30.0 # sampling rate in Hz
neucoeff = 0.7 # neuropil coefficient
# for computing and subtracting baseline
baseline = 'maximin' # take the running max of the running min after smoothing with gaussian
sig_baseline = 10.0 # in bins, standard deviation of gaussian with which to smooth
win_baseline = 60.0 # in seconds, window in which to compute max/min filters

ops = {'tau': tau, 'fs': fs, 'neucoeff': neucoeff,
       'baseline': baseline, 'sig_baseline': sig_baseline, 'win_baseline': win_baseline}

# load traces and subtract neuropil
F = np.load('F.npy')
Fneu = np.load('Fneu.npy')
Fc = F - ops['neucoeff'] * Fneu

# baseline operation
Fc_baselined = dcnv.preprocess(Fc, ops)

plt.plot(Fc_baselined[0])
plt.plot(Fc[0])
plt.show()
```
and look at different baselining strategies, and see what makes sense for your data

**Comment by carsen-stringer** [comment]
I am going to close this due to inactivity, please feel free to reopen if you have questions
