### ISSUE TITLE
KeyError: 'badframes'

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#239]
Updated everything to newest github version and getting the following error:

```
FOUND OPS IN /home/generalubuntu/mnt/Muad/ca-imaging/exp164-20190626/1drg-on/suite2p/plane0
** Found 10500 tifs - converting to binary **
800 frames of binary, time 90.87 sec.
1600 frames of binary, time 205.09 sec.
2400 frames of binary, time 316.45 sec.
3200 frames of binary, time 430.30 sec.
4000 frames of binary, time 543.19 sec.
4800 frames of binary, time 652.84 sec.
5600 frames of binary, time 763.69 sec.
6400 frames of binary, time 873.31 sec.
7200 frames of binary, time 979.14 sec.
8000 frames of binary, time 1089.90 sec.
8800 frames of binary, time 1197.45 sec.
9600 frames of binary, time 1304.87 sec.
10400 frames of binary, time 1412.46 sec.
time 1428.32 sec. Wrote tifs to binaries for 1 planes
SKIPPING REGISTRATION FOR ALL PLANES...
NOTE: binary file created, but registration not performed
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-5e74ffea29ef> in <module>
     35 
     36     # run one experiment
---> 37     opsEnd=run_s2p.run_s2p(ops=ops,db=db)

~/Downloads/suite2p/suite2p/run_s2p.py in run_s2p(ops, db)
    242             if do_regmetrics and ops1[ipl]['nframes']>=1500:
    243                 t0=time.time()
--> 244                 ops1[ipl] = metrics.get_pc_metrics(ops1[ipl])
    245                 print('Registration metrics, %0.2f sec.'%(time.time()-t0))
    246                 np.save(os.path.join(ops1[ipl]['save_path'],'ops.npy'), ops1[ipl])

~/Downloads/suite2p/suite2p/register/metrics.py in get_pc_metrics(ops, use_red)
    154         mov  = sample_frames(ops, ix, ops['reg_file_chan2'])
    155     else:
--> 156         mov  = sample_frames(ops, ix, ops['reg_file'])
    157 
    158     pclow, pchigh, sv, v = pclowhigh(mov, nlowhigh, nPC)

~/Downloads/suite2p/suite2p/utils.py in sample_frames(ops, ix, reg_file, crop)
    150             frames x Ly x Lx
    151     """
--> 152     bad_frames = ops['badframes']
    153     ix = ix[bad_frames[ix]==0]
    154     Ly = ops['Ly']

KeyError: 'badframes'

```
Might be related to https://github.com/MouseLand/suite2p/issues/181

**Comment by Cumol** [comment]
Resolved by deleting the already present suite2p folder and starting fresh. 
It does seem to be connected with re-running the pipeline on already present data.

**Comment by ronan-dasilva** [comment]
The KeyError is happening because your last run of suite2p is skipping registration, likely because as you mentioned it found some pre-existing files. Do you know if your previous run was done until the end, or was it aborted before it could finish?

Essentially what happens is that if you abort the run before it can finish, suite2p never gets to the point of writing the entry ['badframes'] in the output ops file, so that when it tries to call this entry it creates an error. 

However, if your previous trial was complete, then it means that your new run is overwriting the ops output file with one that lacks ['badframes'], which shouldn't be happening and should get fixed.

Let us know so we can try to fix this!

**Comment by carsen-stringer** [comment]
thanks ronan for figuring that out, I've fixed it so that it's now backward-compatible hopefully

**Comment by senis000** [comment]
Hi there,

I've encountered a similar error (I've recently downloaded suite2p so I'm sure I have the last update)
I'm having issues with badframes,

When I try to just add the bad_frames.npy,  in the first folder of my data_path list, as described [here](https://suite2p.readthedocs.io/en/latest/inputs.html) 

with badframes being
`In [9]: badframes
Out[9]: array([28984, 28985, 28986, ..., 97725, 97726, 97727], dtype=int64)`

I encounter the following problem

`
bad frames file path: F:\data\raw\ago13\221112\D01\im\baseline\baseline_221112T092905-237\bad_frames.npy
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[27], line 1
----> 1 ops_2= run_s2p(ops, db)

File ~\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:429, in run_s2p(ops, db, server)
    426                 op[key] = ops[key]
    428     print('>>>>>>>>>>>>>>>>>>>>> PLANE %d <<<<<<<<<<<<<<<<<<<<<<'%ipl)
--> 429     op = run_plane(op, ops_path=ops_path)
    430     print('Plane %d processed in %0.2f sec (can open in GUI).' %
    431             (ipl, op['timing']['total_plane_runtime']))
    432 run_time = time.time()-t0

File ~\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:292, in run_plane(ops, ops_path, stat)
    289         f_reg_chan2.close()
    290         f_reg_chan2 = None
--> 292     ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
    294 if ops.get('move_bin') and ops['save_path'] != ops['fast_disk']:
    295     print('moving binary files to save_path')

File ~\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:78, in pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat)
     75 refImg = ops['refImg'] if 'refImg' in ops and ops.get('force_refImg', False) else None
     77 align_by_chan2 = ops['functional_chan'] != ops['align_by_chan']
---> 78 registration_outputs = registration.register.registration_wrapper(f_reg, f_raw=f_raw, f_reg_chan2=f_reg_chan2, f_raw_chan2=f_raw_chan2,
     79                                                                     refImg=refImg, align_by_chan2=align_by_chan2, ops=ops)
     81 ops = registration.register.save_registration_outputs_to_ops(registration_outputs, ops)
     82 # add enhanced mean image

File ~\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\register.py:643, in registration_wrapper(f_reg, f_raw, f_reg_chan2, f_raw_chan2, refImg, align_by_chan2, ops)
    641         badframes = badframes.flatten().astype(int)
    642         badframes = True
--> 643         print('number of badframes: %d'%ops['badframes'].sum())
    645 # return frames which fall outside range
    646 badframes, yrange, xrange = compute_crop(
    647     xoff=xoff,
    648     yoff=yoff,
   (...)
    654     Lx=Lx,
    655 )

KeyError: 'badframes'`



If I understand this correctly:

`        badfrfile = path.abspath(path.join(ops['data_path'][0], 'bad_frames.npy'))
        if path.isfile(badfrfile):
            print('bad frames file path: %s'%badfrfile)
            badframes = np.load(badfrfile)
            badframes = badframes.flatten().astype(int)
            badframes = True
            print('number of badframes: %d'%ops['badframes'].sum())
            
`
It opens the bad_frames.npy, but then it overwrittes the badframes to a bool True and then tries to access the ops['badframes'] that was never set in the first place? Am I missing something? 

I've also tried to initialize the badframes in ops but I got a different error, will post later if needed
