### ISSUE TITLE
Error extracting fluorescence traces from ROIS

### ISSUE THREAD

**Issue by mkm4884** [MouseLand/suite2p#240]
Hi, I'm experiencing an error when the pipeline gets to extracting F traces from the ROIs. A reference to `roiextract` is not found in chan2detect.py. It seems to be a reference to the 
masks imported in extract.py. 

If I change lines 62 and 63 of chan2detect.py from

`_, cell_pix, cell_masks = roiextract.create_cell_masks(ops, stat)`
`neuropil_masks = roiextract.create_neuropil_masks(ops, stat, cell_pix)`

to 

`_, cell_pix, cell_masks = extract.masks.create_cell_masks(ops, stat)`
`neuropil_masks = extract.masks.create_neuropil_masks(ops, stat, cell_pix)`

and recompile using `pip install suite2p --upgrade` everything seems to work. I'm running version 0.6.15, installed from Github, and the full error output is below. 

Thanks! 

`ERROR
Traceback (most recent call last):
File "C:\Users\admin\AppData\Local\Continuum\miniconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main`

`ERROR ("__main__", mod_spec): File "C:\Users\admin\AppData\Local\Continuum\miniconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code`

`ERROR exec(code, run_globals): File "C:\Users\admin\repos\suite2p\suite2p\__main__.py", line 24, in <module>`

`ERROR suite2p.run_s2p.run_s2p(ops, db) File "C:\Users\admin\repos\suite2p\suite2p\run_s2p.py", line 255, in run_s2p`

`ERROR ops1[ipl] = extract.detect_and_extract(ops1[ipl]): File "C:\Users\admin\repos\suite2p\suite2p\extraction\extract.py", line 134, in detect_and_extract`

`ERROR ops, redcell = chan2detect.detect(ops, stat): File "C:\Users\admin\repos\suite2p\suite2p\detection\chan2detect.py", line 62, in detect`

`ERROR _, cell_pix, cell_masks = roiextract.create_cell_masks(ops, stat): NameError: name 'roiextract' is not defined`

**Comment by carsen-stringer** [comment]
thanks for catching this I've fixed it
