### ISSUE TITLE
python -m suite2p error 'No module named suite2p'

### ISSUE THREAD

**Issue by PB2187** [MouseLand/suite2p#246]
Hi, I just tried to install suite2p using Anaconda prompt with the following steps: 

1) Downloaded the environment.yml file
2) Opened Anaconda prompt
3) Ran conda env create -f environment.yml
4) Ran conda activate suite2p. (suite2p) appeared on the left side of the terminal line
5) Ran python -m suite2p and got the following error: 
C:\Users\****\AppData\Local\Continuum\anaconda3\envs\suite2p\python.exe: No module named suite2p

Could you help me determine what I did wrong with the install? Thanks for your time.

**Comment by ronan-dasilva** [comment]
Hi Poojab,

You still have to install suite2p inside the suite2p environment that you have created.
So after step 4 (i.e. once you have activated suite2p environment), run `pip install suite2p`. Then you should be able to run `python -m suite2p` without issues!

Best,

Ronan

**Comment by ronan-dasilva** [comment]
Hi Poojab,

You still have to install suite2p inside the suite2p environment that you have created.
So after step 4 (i.e. once you have activated suite2p environment), run `pip install suite2p`. Then you should be able to run `python -m suite2p` without issues!

Best,

Ronan

**Comment by PB2187** [comment]
That fixed it, thanks! 
Best,
Pooja
