### ISSUE TITLE
cannot load registered binary, windows 10

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#247]
It looks like it's using the wrong direction slash toward the end...>?

"[Errno 2] No such file or directory: 'D:/Mesoscope_analysis/0299_E121_cSkull/0299_181115_E121_Hal/Suite2p_0299_181115_E121_0_1_2_3_0500pm_Jul2619_HAL/suite2p_out/suite2p/plane0\\data.bin'"

Thanks,

Evan

**Comment by ronan-dasilva** [comment]
The change of direction of the slash shouldn’t really matter regarding whether Python will be able to find the file or not...

Except when it is a backslash followed by some special characters. Sometimes special strings such as ‘\2’ or ‘\d’ are interpreted as something else (the former I think gets read as ‘0x02’, the byte encoding of the number 2). I have never seen this happen inside suite2p while handling files though.

Can you provide us some details of how to reproduce this error?

Cheers!

Ronan

**Comment by carsen-stringer** [comment]
unfortunately those slashes can be a problem depending on the operating system. I added os.path.abspath which should fix the slashes but I haven't tested it on windows yet. please try out the github version (run suite2p from the github folder)

**Comment by carsen-stringer** [comment]
I'm going to close this due to inactivity, please reopen if it's still a problem
