### ISSUE TITLE
how to use 'badframes' option?

### ISSUE THREAD

**Issue by kassailattice628** [MouseLand/suite2p#249]
Thanks a lot for grate software!

I'm starting to use suite2p from several days ago. I think that normal functionality should be work well for my data. Then, I'm trying to use badframe option to extract photo-stim artifact. I'm putting 'bad_frames.npy' in the 'data_path' folder. But it does not seem to work, like this pic.

![bad_rois](https://user-images.githubusercontent.com/8393093/67353534-beb15f80-f58d-11e9-90f4-4c4a73932f43.png)

Many stripes are detected.
'bad_frames.npy' contains a nd.array of the frame numbers that i don't want to use for registration and roi detection. Do I need to set other options to use badframes?

**Comment by kassailattice628** [comment]
I would be very appreciated, if anyone can find tell me something wrong in my settings.
So far, I could not get a result of "print('bad frames file path: %s'%badfrfile)" and ops['flames_include'] option was not work also...

My settings are below.

#data path
"
multi-tiff(5000frames) & bad_frames.npy are put on the 'data_path' directory.

"

#ops settings
```
ops = run_s2p.default_ops()
ops['data_path'] = ['/Volumes/Extreme_SSD/191010/1273opt/1_tif/2/']
ops['save_path'] = '/Volumes/Extreme_SSD/191010/1273opt/1_tif/2/'
ops['fast_disk'] = '/Volumes/Extreme_SSD/191010/1273opt/1_tif/2/'
ops['tau'] = 0.7
ops['fs'] = 1.740262
ops['preclassify'] = 0.5
ops['save_mat'] =  False
ops['nimg_init'] = 78
ops['batch_size'] = 200
ops['block_size'] = [64, 64]
ops['maxregshiftNR'] = 30
ops['spatial_hp'] = 25
ops['frames_include'] = 1000
```


#run suite2p
`
opsEnd = run_s2p.run_s2p(ops=ops)
`

#Results 
```
{}
** Found 1 tifs - converting to binary **
800 frames of binary, time 1.47 sec.
1600 frames of binary, time 2.82 sec.
2400 frames of binary, time 3.90 sec.
3200 frames of binary, time 4.95 sec.
4000 frames of binary, time 6.21 sec.
4800 frames of binary, time 7.36 sec.
time 7.85 sec. Wrote tifs to binaries for 1 planes
 >>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
----------- REGISTRATION
registering 5000 frames
Reference frame, 0.71 sec.
1000/5000 frames, 13.26 sec.
2000/5000 frames, 25.85 sec.
3000/5000 frames, 39.13 sec.
4000/5000 frames, 52.04 sec.
5000/5000 frames, 65.14 sec.
5000/5000 frames, 65.15 sec.
259
----------- Total 66.11 sec
Registration metrics, 12.90 sec.
----------- ROI DETECTION AND EXTRACTION
Binning movie in chunks of length 01
Binned movie [4741,316,318], 3.61 sec.
ROIs: 20, cost: 0.5565, time: 147.5789
ROIs: 32, cost: 0.4370, time: 190.9881
ROIs: 36, cost: 0.4143, time: 207.7788
ROIs: 41, cost: 0.3997, time: 221.5809
ROIs: 43, cost: 0.3940, time: 235.1055
ROIs: 45, cost: 0.3869, time: 250.3567
ROIs: 48, cost: 0.3828, time: 262.6975
ROIs: 49, cost: 0.3802, time: 275.5710
Binning movie in chunks of length 01
Binned movie [4741,316,318], 4.03 sec.
ROIs: 49, cost: 1.6363, time: 294.3804
ROIs: 49, cost: 0.5464, time: 336.7183
ROIs: 49, cost: 0.4938, time: 343.1475
Found 49 ROIs, 396.25 sec
NOTE: applying classifier ~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/suite2p/classifiers/classifier_user.npy
After classification with threshold 0.50, 0 ROIs remain
After removing overlaps, 0 ROIs remain
Masks made in 0.00 sec.
~/.pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
Extracted fluorescence from 0 ROIs in 5000 frames, 1.22 sec.
----------- Total 400.33 sec.
----------- SPIKE DECONVOLUTION
----------- Total 0.20 sec.
Plane 0 processed in 479.74 sec (can open in GUI).
total = 413.62 sec.
TOTAL RUNTIME 413.89 sec
```

**Comment by kassailattice628** [comment]
I finally found that the following two parameters should be set as "True"
ops['two_step_registration']
ops['keep_movie_raw']

and then, my 'bad_frames.npy' were recognized.
```
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
----------- REGISTRATION
registering 1000 frames
Reference frame, 0.72 sec.
1000/1000 frames, 13.81 sec.
1000/1000 frames, 13.82 sec.
bad frames file path: /Volumes/Extreme_SSD/191010/1273opt/1_tif/2/test/bad_frames.npy
number of badframes: 259
----------- Total 14.68 sec
True
True
----------- REGISTRATION STEP 2 (making mean image (exlcuding bad frames)
----------- REGISTRATION STEP 2 (copying raw binary)
----------- REGISTRATION STEP 2
registering 1000 frames
NOTE: user reference frame given
1000/1000 frames, 14.95 sec.
1000/1000 frames, 14.95 sec.
bad frames file path: /Volumes/Extreme_SSD/191010/1273opt/1_tif/2/test/bad_frames.npy
number of badframes: 259
```

But, I still got a regstration with all frames, like this image. 
<img width="1150" alt="スクリーンショット 2019-11-08 14 13 10" src="https://user-images.githubusercontent.com/8393093/68451437-17d9ee00-0232-11ea-8d73-8f4f20a75c6f.png">

If anyone knows how to treat the imags containing optognetic artifacts with this software, please tell me how to do it.

**Comment by carsen-stringer** [comment]
Sorry for the trouble you've had with this. You shouldn't have to activate those settings for it to work. Your bad_frames.npy is a list starting with 0 indexing? And it's only 259 frames in total? Considering how the mean image looks it seems like there might have been more frames with photostim?

**Comment by kassailattice628** [comment]
Thank you for your response!
> Your bad_frames.npy is a list starting with 0 indexing?

Ahhh, I didn't totally care about 0 indexing..., I'm very sorry. I usually use MATLAB for recording and analyzing data. "bad_frames.npy" was also made with MATLAB. 

Here is the the result with corrected "bad_frames.npy". The bacground image still has line (or band) like structures but the ROI detection works.

![スクリーンショット 2019-11-17 16 06 32-2](https://user-images.githubusercontent.com/8393093/69004379-aac30880-0955-11ea-9a16-74ac33fdc4ef.png)
