### ISSUE TITLE
error using pip install on windows10 in a python 3.7.4 environment

### ISSUE THREAD

**Issue by proneill** [MouseLand/suite2p#252]
I am trying to install suite2p on a new windows10 machine. I tried "pip install suite2p" from within a newly created _conda_ environment that has python 3.7.4 and pip 19.3.1. Many of the dependencies are being added successfully:
PyQt5-5.13.1, scikit-image-0.16.2, natsort-6.0.0, matplotlib-3.1.1, numpy-1.17.3, rastermap-0.1.2, pyqtgraph-0.10.0, scikit_learn-0.21.3, h5py-2.10.0
but when it gets to numba, I get the following errors:
ERROR: Could not find a version that satisfies the requirement mkl-fft (from suite2p)(from versions:none)
ERROR: No matching distribution found for mkl-fft (from suite2p)

**Comment by ronan-dasilva** [comment]
Hey!

This happens because mkl-fft does not have a distribution for Python 3.7. Downgrading you conda env to python==3.6 (or creating a new one with something like `conda create env -n suite2p python==3.6`) should do the job.

Hope it works!

**Comment by proneill** [comment]
Thanks! I created a new environment with Python 3.6, and then `pip install suite2p` worked without any errors. However, when I then tried running `python -m suite2p`, I get this error message:
```
Traceback (most recent call last):
  File "C:\Users\proneill\.conda\envs\suite2p\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\proneill\.conda\envs\suite2p\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\proneill\.conda\envs\suite2p\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\proneill\.conda\envs\suite2p\lib\site-packages\suite2p\__init__.py", line 1, in <module>
    import suite2p.register
  File "C:\Users\proneill\.conda\envs\suite2p\lib\site-packages\suite2p\register.py", line 12, in <module>
    from suite2p import nonrigid, utils, regmetrics
  File "C:\Users\proneill\.conda\envs\suite2p\lib\site-packages\suite2p\nonrigid.py", line 6, in <module>
    from skimage.transform import warp#, PiecewiseAffineTransform
  File "C:\Users\proneill\.conda\envs\suite2p\lib\site-packages\skimage\transform\__init__.py", line 2, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "C:\Users\proneill\.conda\envs\suite2p\lib\site-packages\skimage\transform\hough_transform.py", line 2, in <module>
    from ._hough_transform import (_hough_circle,
  File "__init__.pxd", line 918, in init skimage.transform._hough_transform
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

It looks like the environment, which did not have numpy prior to `pip install suite2p`, has numpy 1.17.3. Do you think a different version of numpy might resolve this issue?

**Comment by ronan-dasilva** [comment]
Yes, there is a chance that this issue is because of your numpy version. There have been a bunch of issues that came about when numpy 1.17 was released, but I don't remember what is the present status.

On my machine I am running suite2p on numpy 1.15. You could simply try reinstalling this version and see what happens?

**Comment by carsen-stringer** [comment]
Thanks for the help with this ronan, I'm going to close this, please reopen this if you're still having problems with the software @proneill

**Comment by carsen-stringer** [comment]
I installed the latest conda (10.2019 release with python 3.7.4). just FYI when I used the `environment.yml` file in the repository and did
~~~
conda env create -f environment.yml
~~~
it automatically downgraded python to python 3.7.3. please let me know if you used the environment file and still got this error.
