### ISSUE TITLE
Register a red channel image to the green channel refImage

### ISSUE THREAD

**Issue by KnightyOwl** [MouseLand/suite2p#255]
Hi,

Thanks for developing this software! I wonder if there's a way to register a static red channel image (with cells extracted/segmented) to the functional/dynamic green channel refImage? This way we are able to know which neurons are red and green co-localized.

Best,
Bowey

**Comment by carsen-stringer** [comment]
Is the red channel collected simultaneously with the green channel? If not then I'm not sure how to do this. There is different information in the green vs red channel so you cannot align them to each other with 100% certainty.

**Comment by carsen-stringer** [comment]
i'm going to close this due to inactivity
