### ISSUE TITLE
Meeting problem about extracting fluorescence value

### ISSUE THREAD

**Issue by Jiashu08** [MouseLand/suite2p#257]
Hey Carsen and Marius!

Thanks for sharing this software! I meet a problem after using the new version so I am wondering if you could help me about that.
I have 2 channels (GFP and RFP channels) during two-photon recording and I wish to use the RFP channel to correct the motion artifact in z axis for GFP channel. I separate two channels before process data in suite2p and make the GFP channel on the left and the RFP channel on the right (Please see the figure).
![figure 1](https://user-images.githubusercontent.com/56368102/68548400-1cc5ab80-03b2-11ea-8d83-5838a6989090.PNG)
 Then when the software extract the ROI, the neuron's pattern is not always same (because the fluorescent expression is different). So what we do is to calculate the shape of ROI in the RFP channel based on the shape of ROI in GFP channel. Then we extract Fluorescence value based on the shape that we calculated. (Please check the code)

` 

     for j=1:ROInum       
            xpix=stat{ROIindex(j)}.xpix;
            ypix=stat{ROIindex(j)}.ypix;
            lam=stat{ROIindex(j)}.lam;
            overlap=stat{ROIindex(j)}.overlap;
            eff_xpix=xpix(~overlap);
            eff_ypix=ypix(~overlap);
            eff_lam=lam(~overlap);
            for p=1:channelnum      % 1, GFP; 2, RFP
                indexpix=sub2ind(imsize, eff_ypix+1, eff_xpix+1+(p-1)*imsize(2)/channelnum);
                F_combine(i,j,p)=sum(temp(indexpix).*eff_lam);  %temp=read registered tif. i=framenum, j=ROI number, p=2 channels 
            end
        end
    end

Next, to verify if our calculation is correct, we compare the GFP's 'F' of original result and the F that we calculate. If our formula is correct, these two 'F' should be exactly same. So we subtract the 'calculated F' from 'original F' to find the difference between them. (These two data are normalized before subtraction.) When we use the previous version, the difference is nearly 0 (please see the figure).
![figure 2](https://user-images.githubusercontent.com/56368102/68548647-e89fba00-03b4-11ea-8bfe-ccc4db857799.PNG)

However, when I use the new version, the difference is not 0 anymore.
![figure 3](https://user-images.githubusercontent.com/56368102/68548727-d4a88800-03b5-11ea-9b1d-37990be0307c.PNG)

These two are from the same data but just be processed with different version of suite2p. I am sure that I used the register tif file that saved in 'reg_tif' folder. So I am wondering if we need to change the calculation formula while using the new version? Or if the formula is correct, do you have any idea about what cause this problem? 
Thank you so much!!

**Comment by carsen-stringer** [comment]
Actually this feature is available (to extract fluorescence from a non-functional channel). By default it happens if you set ops['nchannels']=2. But your green and red should not be stitched together as you've shown. You should interleave green and red (it will be like that automatically if you use scanimage or thorimage). If you use bruker (or other single-page tiff outputs), then they will not be interleaved, you will want to set ops['bruker']=1 and then it will take as second channel the tiffs that aren't '_Ch1'. What format are your tiffs originally in?

**Comment by carsen-stringer** [comment]
I am going to close this issue due to inactivity but please let me know if you're still having issues running multi-channel (bruker) tiffs
