### ISSUE TITLE
Error with two_step_registration

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#258]
Hi, I was eager to try the `two_step_registration` function, but suite2p seems to run into an error when I activate it:
`'Traceback (most recent call last):\n  File "C:\\Users\\horsto\\AppData\\Local\\conda\\conda\\envs\\analysis\\lib\\site-packages\\datajoint\\autopopulate.py", line 160, in populate\n    make(dict(key))\n  File "..\\dj_schemas\\jobs_suite2py.py", line 171, in make\n    opsEnd = run_s2p(ops=ops_,db=db_)\n  File "..\\dj_schemas\\..\\helpers\\suite2p-python\\suite2p\\run_s2p.py", line 239, in run_s2p\n    ops1[ipl] = register.register_binary(ops1[ipl], ops1[ipl][\'meanImg\'], raw=False) # register binary\n  File "..\\dj_schemas\\..\\helpers\\suite2p-python\\suite2p\\registration\\register.py", line 372, in register_binary\n    ops = apply_shifts_to_binary(ops, offsets, reg_file_alt, raw_file_alt)\n  File "..\\dj_schemas\\..\\helpers\\suite2p-python\\suite2p\\registration\\register.py", line 278, in apply_shifts_to_binary\n    raw_file_alt = open(raw_file_alt, \'rb\')\nTypeError: expected str, bytes or os.PathLike object, not list\n'`

I also had to still change `save_path` related things in `suite2p/suite2p/run_s2p.py`(not sure if they are related). I described what I did here: https://github.com/MouseLand/suite2p/issues/214#issuecomment-521118968

**Comment by carsen-stringer** [comment]
thanks I had not tested multi-channel tiffs. this is working now. Note the two step registration is currently assuming that you use the functional channel for registration, is this true in your case? I will fix sooner if so

I totally forgot about the 'save_folder' option - that is also not working?

**Comment by horsto** [comment]
Yes, I am using multi channel tiffs and the second channel (non functional) for alignment. 

The save_folder option is still not corrected I think? It ran into an error again after I pulled the latest changes. It works with the changes proposed in the comment above (#214).

**Comment by carsen-stringer** [comment]
You can now register to a non-functional channel with two-step registration, but it could be buggy so please let me know if it's not working. I will get to the savefolder issue next.

**Comment by carsen-stringer** [comment]
i'm going to close this please comment if you're still having issues with registration
