### ISSUE TITLE
Export visualization

### ISSUE THREAD

**Issue by sureshjesuthasan** [MouseLand/suite2p#259]
Thanks for making this software available and so easy to use. 

Is it possible to export the visualizations that are created from within Suite2p? I see that there is such a feature in rastermaps itself, but I can'f find the option in Suite2p.

**Comment by carsen-stringer** [comment]
I added an option to the menu "File", it's working in the latest version of suite2p but not sure if it's there in the pip package. I am going to make a new pip package soon, but if you want to try the latest software, instructions [here](https://github.com/MouseLand/suite2p#installation-of-github-version-for-developers-and-super-users-)

for the rastermap, you can right click (which I think you've discovered)
