### ISSUE TITLE
Upgrade error (pyqt5)

### ISSUE THREAD

**Issue by maxseppo** [MouseLand/suite2p#260]
When I run:
`pip install suite2p --upgrade`

I get the error:
ERROR: pyqt5-tools 5.13.0.1.5 has requirement pyqt5==5.13.0, but you'll have pyqt5 5.13.2 which is incompatible.

pip uninstall/install does not seem to help Any advice is appreciated. Thanks!

**Comment by carsen-stringer** [comment]
Haven't seen this before, have you tried
~~~
pip uninstall pyqt5-tools
pip install pyqt5
pip install pyqt5.sip
~~~

**Comment by maxseppo** [comment]
I tried that but to no avail. I ended up just fully uninstalling and reinstalling suite2p. Thank you!
