### ISSUE TITLE
Rerunning a batch

### ISSUE THREAD

**Issue by DoriMG** [MouseLand/suite2p#263]
Hi!

Thanks for all your awesome work on Suite2P! 

I just had a situation where I tried to batch analyse some data, and after the first run, had to rerun it (so I didn't close suite2p in between, I literally just clicked 'Run Suite2P' again). When I clicked it, it started analysing a previous batch from before the batch I actually had put in.

Obviously this is fixed by just closing and reopening the run suite2p window, but thought it would be good to make you aware!

**Comment by carsen-stringer** [comment]
thanks for pointing this out, I'll put the bug label on this

**Comment by carsen-stringer** [comment]
this should now be fixed, closing the issue, please comment if you still have problems
