### ISSUE TITLE
Output file name list when processing multiple hd5 files

### ISSUE THREAD

**Issue by ben-stafford** [MouseLand/suite2p#264]
Greetings-

Thanks so much for making and maintaining such wonderfully useful code!

I have been using Suite2P to process multiple hd5 files and then using the .mat file generated for subsequent analysis. When I do this, a list of all the hd5 file names appears in the GUI window when processing begins. For example:

NOTE: using a list of h5 files:
['C:/2P_data/Ben/b02/b02_001_XXX_ot_002\\b02_001_001_ot_002.h5', 'C:/2P_data/Ben/b02/b02_001_XXX_ot_002\\b02_001_002_ot_002.h5']

However, the full list of these names is not saved anywhere. In the .mat file as well as the ops.npy files, only the name of the first hd5 file encountered is saved. Is it possible for this list to be saved in some capacity in the .mat file? Or, at the very least, in the ops.npy file generated by Suite2P? In the Matlab version of Suite2P, these filenames were saved in a data structure as a cell array.

I apologize if this isn't an appropriate forum for requesting additional functionality such as this, but I am new to Github an python programming.

Thanks!!!!

**Comment by carsen-stringer** [comment]
this is exactly what github is for :) I've added this as an output in ops as ops['h5list']. You will need to install the github version to use this until I update the pip release: https://github.com/MouseLand/suite2p#installation-of-github-version-for-developers-and-super-users-

please comment if you have issues, I will close this for now
