### ISSUE TITLE
Suite2p randomly locking up PC

### ISSUE THREAD

**Issue by bill-connelly** [MouseLand/suite2p#266]
I'm running a newly installed version of suite2p in anaconda, on a relatively new Windows10 PC.

Suite2p opens fine, and begins to work on files, sometimes, *even if it is just open, and not doing anything* the PC locks up. No bugs. No CTRL-ALT-DEL or anything will revive the computer. I appreciate this is a bit of a weird problem. But any thoughts on how to begin trouble shooting this would be appreciated.

Thanks.

**Comment by carsen-stringer** [comment]
o.o does the memory usage increase slowly? Is it a 32-bit Windows 10? not sure what could cause this problem. do you know if having an anaconda prompt will mess it up too?

**Comment by carsen-stringer** [comment]
I'm going to close this due to inactivity
