### ISSUE TITLE
in reference.sampled_mean, if nchannels is 1, bin_file is not assigned

### ISSUE THREAD

**Issue by MaximilianHoffmann** [MouseLand/suite2p#270]
https://github.com/MouseLand/suite2p/blob/master/suite2p/registration/reference.py#L6-L17

bin_file is not assigned, if we don't enter the if statement

**Comment by MaximilianHoffmann** [comment]
btw, let me know if those kind of issues are not helpful. I understand, that these commits are not released, but thought in might be helpful to debug. Thanks for the great package.

**Comment by carsen-stringer** [comment]
thanks! these bug issues are definitely helpful!!
