### ISSUE TITLE
Negative value of F and/or Fneu

### ISSUE THREAD

**Issue by suhyunsu** [MouseLand/suite2p#271]
Hello,

I ran a large FOV data (1.98 x 2.5 mm, 14000 frames) in GUI suite2p and Some cells have negative F and/or Fneu values as in the figure below. Considering dF/F in which 70% of Fneu is subtracted from F, negative Fneu value results in higher dF/F than F itself. 

![Capture](https://user-images.githubusercontent.com/28590593/71939649-4c055880-3168-11ea-8a8f-6fb3dfaf7a1b.GIF)

I also have sessions in which baseline of F and Fneu is around 16000 as in the figure below. Have you had these problems or any ideas why these happen and how to solve them?

![image](https://user-images.githubusercontent.com/28590593/71940081-f2059280-3169-11ea-85b1-2f3244d99c9a.png)

Thank you,
Su

**Comment by carsen-stringer** [comment]
These values are small. Not sure if this is an issue with the type of tiff you're using, can you look at the raw values of your tiffs and see if they are negative? suite2p should not introduce any negative values during processing.

For the second case again is this the range of values that you see in your tiffs?

**Comment by suhyunsu** [comment]
I looked at the raw values of a couple of cells in my tiffs by drawing a square around each cell in imagej. Figures below are one example of them. The cell is a bright good cell, but still shows negative values. And it is same for the tiffs which showed the weird high F values.
![image](https://user-images.githubusercontent.com/28590593/72642383-0c393080-3921-11ea-9591-cdbfe1e5c3b8.png)
![image](https://user-images.githubusercontent.com/28590593/72642408-1f4c0080-3921-11ea-93d3-92e652ae7bf7.png)

Thank you so much for your suggestion!
Su

**Comment by carsen-stringer** [comment]
ah okay so this is the range of your tiff then. you could manually shift the values up, see advice [here](https://github.com/MouseLand/suite2p/issues/290#issuecomment-592967575) for rescaling
