### ISSUE TITLE
Errors with using data saved in ImageJ

### ISSUE THREAD

**Issue by dkushinsky** [MouseLand/suite2p#273]
Hi!

Thanks for the awesome software! I have been using suite2p to process data in the .RAW format from ThorLabs which has been working really well. Currently, I need to process images that have been saved as .tifs in ImageJ. After reading through others issues, I saved my movie as several tif stacks (each about 1GB). The registration of the movies seems to be working, but the later processing of the data is throwing errors (see attached image) 
![10 1 19 suite2p error](https://user-images.githubusercontent.com/56402452/72162245-427b2b00-33ca-11ea-96c7-83188623f3c3.PNG) . Can you please help with this?

Thanks so much for your help!

**Comment by carsen-stringer** [comment]
You set the diameter to 0 :) that's why it's erroring. You might want to try the latest cell detection algorithm though (by setting "sparse_mode"=1, this doesn't use the diameter) but do please set the diameter back to an integer like 10 so that nothing else potentially errors.

**Comment by dkushinsky** [comment]
ah, a silly mistake.. thanks!

I am having an issue with using the "bad_frames.npy" option -- I am running the gui on my data that is contained in a folder that also has a file called bad_frames.npy which contains an array of numbers with 0 indexing, but it does not seem that this is being integrated when doing the registration/extracting the F traces as seen in the image
![image](https://user-images.githubusercontent.com/56402452/72523336-3c70c880-3868-11ea-852d-2abed6109c00.png). The points in the bad_frames.npy are the same as the points with the issues (ie the places where you see jumping, like at point 16) and the number of points in bad_frames.npy is printed in the suite2p gui. My ops settings for this data is below:
![image](https://user-images.githubusercontent.com/56402452/72523676-f9fbbb80-3868-11ea-8f5f-a7018db5b83d.png)


Any idea what is happening? 

Thanks for your help!

**Comment by carsen-stringer** [comment]
bad_frames.npy are ignored during ROI detection, but we do not ignore frames during bad_frames in signal extraction. This is so that you as the user can decide what kind of interpolation to do with these frames if/when you throw them out.

**Comment by dkushinsky** [comment]
Hi Carsen,

Okay, I see. 
I was hoping that with the inclusion of the bad_frames.npy I would be able to detect more ROIs without cropping out the field of view but that does not seem to be the case. Do you have any tips on how to improve the detection?
![image](https://user-images.githubusercontent.com/56402452/72534392-67b2e200-387f-11ea-9bf2-829df9111007.png)



Thanks for the help!

**Comment by carsen-stringer** [comment]
can you include an image of your correlation map too please?

**Comment by dkushinsky** [comment]
of course!
I've included all of the views here:
![image](https://user-images.githubusercontent.com/56402452/72534929-574f3700-3880-11ea-9322-442eba3407d1.png)

**Comment by carsen-stringer** [comment]
that is some intense cropping, otherwise I think the cell detection looks good, at least in that small region :). 

There is a parameter to mitigate this issue which is ops['th_badframes'] (in the GUI under registration). This determines the frames that are excluded when determining the cropping region (in addition to the bad_frames.npy - you were right that would help if those were the only frames with big registration shifts). Decrease ops['th_badframes'] and more frames will be set as bad frames and NOT used when determining the cropping window.

Also, have you watched the binary ("Registration > View registered binary" in the main GUI)? The XY shifts are plotted in there. If there is actually drift over the whole recording then unfortunately there's nothing you can do. The above fix will only help if there are some abrupt large shifts.

**Comment by dkushinsky** [comment]
Hi Carsen!

Thanks for the quick responses! 
I took a look at the registered binary -- there are x-y shifts there, but these shifts only seem to be at the place where my bad_frames are, seen below (I again went through to check that these are happening at the same locations that I identified in my bad_frames array). 
![image](https://user-images.githubusercontent.com/56402452/72546464-7b684380-3893-11ea-9e0e-62b3ca352bc6.png)
I will try running the registration with a smaller value of th_badframes. Does this setting work similarly to bad_frames? As in, will the identified frames be not included for ROI detection but still be included in the extracted florescence, or are these frames dropped entirely? 

Thanks!

**Comment by carsen-stringer** [comment]
Yes it works the same as bad_frames and will be returned in `ops['badframes']` so you can see which frames it subselected.

**Comment by dkushinsky** [comment]
Hi Carsen,

I reduced th_badframes to 0, but the detection is still missing more than half of the FOV. 
![image](https://user-images.githubusercontent.com/56402452/72594275-bf992980-390f-11ea-966f-dcd54e9116d4.png) 
![image](https://user-images.githubusercontent.com/56402452/72594298-c9bb2800-390f-11ea-8a99-4dfea00d51f5.png)

I went through the registered binary and found that there were still many of these bad_frames with large x-y shifts, all identified in the 'bad_frames.npy' array. Anything else you think I can do with this to improve my outcome? 
![image](https://user-images.githubusercontent.com/56402452/72594392-f111f500-390f-11ea-8d26-54f29c7235bd.png)


Thanks!

**Comment by carsen-stringer** [comment]
You could just set the ops['maxregshift'] lower. By default it's 0.1 (so 10% of the FOV), but you could set it to 0.01 or something to get rid of these shifts.

**Comment by dkushinsky** [comment]
Hi Carsen,

This solution worked really well - thanks for all your help!

**Comment by carsen-stringer** [comment]
great! going to close this issue then :)
