### ISSUE TITLE
How to use with Bruker interleaved channels?

### ISSUE THREAD

**Issue by djoshea** [MouseLand/suite2p#274]
Hi Carsen & Marius,

I'm wondering how to use suite2p with Bruker/Prairie's ome.tiffs, where the files are named Ch1 and Ch2 accordingly. I see the field `'bruker'` in `ops`, but I can't seem to find it used anywhere in the repo. I also see the `test_tiff_loader.ipynb` notebook, which defines a function `ome_to_binary`, but I'm not quite sure how to use that either. And this one is slightly different from the `ome_to_binary` inside `tiff.py`, which isn't called from anywhere else in the code. With some minor tweaks, I'm able to get these `ome_to_binary` functions to run and create two binary files on disk, but neither writes an `ops1.npy file`, so the next time I run suite2p it just tries to load the tiffs again.

Any pointers on how to do this? I'm still poking around using PyCharm to debug and see if I can hack something together, but I suspect I'm missing something. 

For reference, I have:
- Two channels with Ch1 and Ch2 in their names like `Cycle00001_Ch2_000001.ome`.
- Ch1 is red, Ch2 is green
- Want to register using Ch1 and use Ch2 as the functional channel

Thanks for your help!
Dan

**Comment by djoshea** [comment]
Ah, okay, I seem to have gotten things to work using the version of `ome_to_binary` in the `test_tiff_loader.ipynb`, changing the import to `from suite2p.io.utils import init_ops, find_files_open_binaries`, and adding a line where the `ops` is saved in the right place. My final version looks like this:

```python
import gc
import time
from suite2p.io.utils import init_ops, find_files_open_binaries
def tic():
    return time.time()
def toc(i0):
    return time.time() - i0

def ome_to_binary(ops):
    '''
    converts ome.tiff to *.bin file for non-interleaved red channel recordings
    assumes single-page tiffs
    also assumes only single-plane recordings - will fail otherwise
    requires ops keys: nplanes, nchannels, data_path, look_one_level_down, reg_file
    assigns ops keys: tiffreader, first_tiffs, frames_per_folder, nframes, meanImg, meanImg_chan2

    '''
    t0=tic()
    # copy ops to list where each element is ops for each plane
    ops1 = init_ops(ops)
    nplanes = ops1[0]['nplanes']

    # open all binary files for writing
    # look for tiffs in all requested folders
    ops1, fs, reg_file, reg_file_chan2 = find_files_open_binaries(ops1, False)
    ops = ops1[0]
    
    fs_Ch1, fs_Ch2 = [], []
    for f in fs:
        if f.find('Ch1')>-1:
            if ops['functional_chan'] == 1:
                fs_Ch1.append(f)
            else:
                fs_Ch2.append(f)
        else:
            if ops['functional_chan'] == 1:
                fs_Ch2.append(f)
            else:
                fs_Ch1.append(f)
        
    if len(fs_Ch2)==0:
        ops1[0]['nchannels'] = 1
    nchannels = ops1[0]['nchannels']
        
    # loop over all tiffs
    which_folder = 0
    ntotal=0
    tif = ScanImageTiffReader(fs_Ch1[0])
    im0 = tif.data()
    Ly,Lx = im0.shape
    j=0
    nframes = len(fs_Ch1)
    ops1[j]['nframes'] = nframes
    ops1[j]['frames_per_folder'][0] = nframes
    ops1[j]['meanImg'] = np.zeros((Ly,Lx))
    ix=0
    for ik, file in enumerate(fs_Ch1):
        # open tiff
        tif = ScanImageTiffReader(file)
        im = tif.data()
        if type(im[0,0]) == np.uint16:
            im = im // 2
            im = im.astype(np.int16)
        if ik==0:
            ops['meanImg'] += im
                                    
        reg_file[j].write(bytearray(im))
        ix+=1
        if ix%(100)==0:
            print('%d frames of binary, time %0.2f sec.'%(ix,toc(t0)))
        gc.collect()
                                    
    if nchannels>1:
        ops1[j]['meanImg_chan2'] = np.zeros((Ly,Lx))   
        ix=0
        for ik, file in enumerate(fs_Ch2):
            # open tiff
            tif = ScanImageTiffReader(file)
            im = tif.data()
            
            if type(im[0,0]) == np.uint16:
                im = im // 2
                im = im.astype(np.int16)
                
            if ik==0:
                ops['meanImg_chan2'] += im

            reg_file_chan2[j].write(bytearray(im))
            ix+=1
            gc.collect()
                                    
    # write ops files
    do_registration = ops['do_registration']
    do_nonrigid = ops1[0]['nonrigid']
    for ops in ops1:
        ops['Ly'],ops['Lx'] = Ly,Lx
        if not do_registration:
            ops['yrange'] = np.array([0,ops['Ly']])
            ops['xrange'] = np.array([0,ops['Lx']])
        ops['meanImg'] /= ops['nframes']
        if nchannels>1:
            ops['meanImg_chan2'] /= ops['nframes']
        np.save(ops['ops_path'], ops)
    # close all binary files and write ops files
    for j in range(0,nplanes):
        reg_file[j].close()
        if nchannels>1:
            reg_file_chan2[j].close()
    
    # save ops1 in the right place so that binary files are found next time
    np.save(os.path.join(outdir, 'suite2p/ops1.npy'), ops1)
    return ops1
```

Then I can call: 
```python
ops1=ome_to_binary(ops)
run_s2p.run_s2p(ops=ops)
```

I think this fixes the issue for me, but perhaps this is the path that is supposed to be associated with `ops['bruker'] == True`?

Thanks!

**Comment by carsen-stringer** [comment]
Sorry for the trouble you're having, are you using the github version of the software? This should just be working from the GUI with bruker=1, is this the way you tried to run it?

**Comment by djoshea** [comment]
No worries, I do have it working by manually calling the above function myself to run things.

But no, it does not work for me to set `ops['bruker'] = True`. Scanning through the code, I don't see any place that the bruker key is read from ops, nor anywhere where `ome_to_binary` is called, aside from that one notebook, so I  don't see how this could work. 

I am using the Github master branch installed with `pip install -e`. Different issue, but I just pulled changes and am now getting this error because `zalign` isn't defined:

```python
Traceback (most recent call last):
  File "/Users/djoshea/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/djoshea/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/djoshea/code/suite2p/suite2p/__main__.py", line 5, in <module>
    from suite2p.gui import gui2p
  File "/Users/djoshea/code/suite2p/suite2p/gui/__init__.py", line 1, in <module>
    from . import (buttons, classgui, drawroi, graphics, io, masks, gui2p, menus,
  File "/Users/djoshea/code/suite2p/suite2p/gui/gui2p.py", line 13, in <module>
    from . import menus, io, merge, views, buttons, classgui, traces, graphics, masks
  File "/Users/djoshea/code/suite2p/suite2p/gui/menus.py", line 4, in <module>
    from . import reggui, drawroi, merge, io, rungui, visualize, classgui
  File "/Users/djoshea/code/suite2p/suite2p/gui/reggui.py", line 11, in <module>
    from ..registration import zalign
ImportError: cannot import name 'zalign' from 'suite2p.registration' (/Users/djoshea/code/suite2p/suite2p/registration/__init__.py)
```

**Comment by carsen-stringer** [comment]
oops I'm sorry I guess that flag wasn't being used. Can you try out the new GUI please (there is now a drop-down with a bruker option? I don't have any bruker tiffs to test but it does enter the ome_to_binary function. I've also fixed the missing import.

**Comment by djoshea** [comment]
Okay, great, thank you. I pulled the most recent version, and was able to get it working with one bug fix. In `tff.py` line 462, I think you're missing a `[0]` at the end:

```python
ops1[j]['frames_per_folder'][0] += 1
```

Or else perhaps you don't want the trailing `[0]` on line 444.

I can happily a pull request if you like, but I imagine it's less work for you to just make the change yourself if you have other edits going on.

**Comment by djoshea** [comment]
Ah, also, I forgot to mention that I also needed to set `ops['input_format'] = 'bruker'` rather than `ops['bruker'] = True` to hit the right code path in `run_s2p.py` line 216:

```python
            elif ops['input_format'] == 'bruker':
                ops['bruker'] = True
                ops1 = tiff.ome_to_binary(ops)
                print('time %4.2f sec. Wrote bruker tifs to binaries for %d planes'%(time.time()-(t0), len(ops1)))
```
