### ISSUE TITLE
Error using latest NumPy version

### ISSUE THREAD

**Issue by DoriMG** [MouseLand/suite2p#279]
Hi!

With the latest version of NumPy, Suite2p won't open, giving an error in the skimage in nonrigid.py (from skimage.transform import warp#, PiecewiseAffineTransform). Not sure from when this problem arises, but I have definitely had it with 1.18.1 (the latest version). Reverted back to NumPy 1.15.1 and all is fine.

**Comment by carsen-stringer** [comment]
Hmm can you try the latest suite2p? We no longer use the built in warp so this error shouldn't occur. Also it should be much faster because we numba accelerated that function in our implementation.

**Comment by ronan-dasilva** [comment]
I was also getting an error like that when installing the most recent version of suite2p just last week.
The problem was solved by installing scikit-image==0.16 (or at least that's how I managed to finish the installation...). Doing so also downgraded numpy to 1.15.1, but this hasn't posed any problem so far.

Ronan

**Comment by carsen-stringer** [comment]
can you tell me what line the error occurred on? it was an error with warp? there are no imports of that function in the current version

**Comment by DoriMG** [comment]
Sorry it took me ages to get back to you, but latest version of NumPy (1.18.1) is indeed fine with Suite2P (0.7.1) updated for me.
Thanks!

**Comment by ronan-dasilva** [comment]
I tried to reproduce the error to get you the precise line by creating a new conda environment and reinstalling suite2p, but doing so just installed suite2p==0.7.1 with numpy==1.18.1 with no issues during installation... so I guess whatever was happening just got fixed! Yay!

The only tiny issues that happened was that I had to manually install PyQt5 and rastermap after installing suite2p, but just running two easy pip installs got it up and running.

**Comment by carsen-stringer** [comment]
thanks both, I will add rastermap to the setup.py. I strongly recommend using the environment file so that many packages including pyqt are installed with conda, that's why I have removed it from the pip (so that it does not replace the conda version when you pip install suite2p)

**Comment by ronan-dasilva** [comment]
Ah, that's cool! I didn't know it was now running through conda.
Will keep that in mind for my future installs!

Ronan
