### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by radical2007** [MouseLand/suite2p#280]
Hello, 
I recently updated my computer to have an SSD and windows 10 and reinstalled Anaconda 3 and suite2p but keep running into the following error. Would be great if someone can help solve this error. 
![Suite2p installation error](https://user-images.githubusercontent.com/50458197/73170608-c6d1eb80-40f6-11ea-805c-d50e1dffbee5.PNG)

**Comment by carsen-stringer** [comment]
Run `pip install rastermap` and then try again. Sorry about that, I will update the pip and I've updated the environment.yml file

**Comment by radical2007** [comment]
Solved. Thanks!
