### ISSUE TITLE
Spike deconvolution turn off

### ISSUE THREAD

**Issue by elvisclains** [MouseLand/suite2p#281]
Hi,

Is it possible to switch off spike deconvolution when running the script? If so, how should I implement it when running Suite2p in Jupyter Notebook?

Best
Wojciech

**Comment by carsen-stringer** [comment]
no there is not currently a switch for this, but it is straightforward to add. is this due to the time for computation or memory limits? I ask because I will still save a 'spks.npy' that is full of zeros. Otherwise you can't load the recording in the GUI (it expects the 'spks.npy' file).

**Comment by elvisclains** [comment]
Thanks for the reply. Yes it is due to very long time of processing. Exactly, I was not able to load the rec to GUI without waiting for deconvolution to complete.

**Comment by carsen-stringer** [comment]
this has been added to the github code, not yet in the pip. going to close the issue, please comment if you still have problems.
