### ISSUE TITLE
Re-classifying ROIs

### ISSUE THREAD

**Issue by ronan-dasilva** [MouseLand/suite2p#282]
Hello everyone!

I am trying to reclassify some ROIs using a different classifier. I am loading my processed data on the GUI and then I load the classifier I wish to apply from the menu Classifier > Load from file, but doing this does nothing to the ROIs.

Looking through the issues I found that there used to be an "Apply" button that allowed you to reclassify ROIs, but that got removed in some update. Is there still a way to reclassify ROIs in the GUI? If not, is there a way to do it directly by code?

Thanks!

Ronan

**Comment by carsen-stringer** [comment]
hey sorry that the documentation isn't clear on this, if you press [enter] when you are in the classifier probability box (under the classifier menu) it should re-apply the classifier.
