### ISSUE TITLE
Error when trying to save .ops file from GUI

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#283]
When trying to save an ops file from the GUI ("Save ops to file") I get the following error message:
```
 File "C:\work\python\suite2p\gui\rungui.py", line 457, in save_ops
    name = QtGui.QFileDialog.getSveFileName(self,'Ops name (*.npy)')
AttributeError: type object 'QFileDialog' has no attribute 'getSveFileName'
```

**Comment by craddr** [comment]
it's a typo in the rungui.py code 
to fix, open the file in a text editor, go to line 457, find the command 
`name = QtGui.QFileDialog.getSveFileName(self,'Ops name (*.npy)')`
and put the 'a' in so it says 
`name = QtGui.QFileDialog.getSaveFileName(self,'Ops name (*.npy)')`

save the corrected script, you should be able to save ops to file now
