### ISSUE TITLE
Mesoscope data with multiple ROIs on multiple Z planes

### ISSUE THREAD

**Issue by suhyunsu** [MouseLand/suite2p#284]
Hello,

I created a json file to run mesoscope data using a matlab script you provided. It works great, but I have a question for mesoscope data with multiple ROIs on multiple Z planes. In one data set, there are three ROIs on five different Z planes (position of them are exactly the same on each plane), and I set nplanes=5, and json file has information about three ROIs. So, suite2p calculates it as 15 nplanes and shows good results. But five different Z planes overlapped in the combined result. I just wonder whether there is a way to set it as different Z planes or a way to see each Z plane separately,

Thank you,
Su

**Comment by carsen-stringer** [comment]
this has been fixed, not yet in the pip. going to close the issue, please comment if you still have problems.

if you want to run just combined again
~~~
from suite2p.io import save
import numpy as np

ops1 = np.load('suite2p/ops1.npy', allow_pickle=True)
save.combined(ops1)
~~~

**Comment by suhyunsu** [comment]
I really appreciate your support.

But, unfortunately, added one did not work for sessions with multiple ROIs on multiple Z planes. It created nplane x nROIs number of folders named plane0, plne1, etc., and one combined data folder. 

It would work for me and lab members if it is available to define multiple ROIs on each Z plane and to create combined data for each Z plane.
