### ISSUE TITLE
Suite2p usecase

### ISSUE THREAD

**Issue by akatav** [MouseLand/suite2p#285]
Dataset has 4 channels consisting of 3d stacks of images obtained along the axial plane of mice brain.So, the Field of View along z changes (thickness of brain slice=1 micron). Can i use suite2p to correct motion artifacts in each image (arising due to raster scanning) and correct alignment issues in every multichannel 3d stack (both inter frame and intra frame) ?
The dataset is 1024*1024 and z=44. We are imaging dendrites and looking to reconstruct the 3d view of dendrites from the 2d slices. There are no neurons.
Attached is a sample 3d stack of one of the channels.
![Substack (1-8)](https://user-images.githubusercontent.com/721570/75139266-871b1580-572f-11ea-83d7-c9b452200378.gif)

**Comment by carsen-stringer** [comment]
suite2p does not support this type of registration in, it is for registering a 2D slice across time. you could compare frames in your stacks using 2D rigid registration with these [functions](https://mouseland.github.io/suite2p/_build/html/autoapi/suite2p/registration/rigid/index.html), but you'd have to put them together yourself
