### ISSUE TITLE
GUI z-stack visualization

### ISSUE THREAD

**Issue by pkells12** [MouseLand/suite2p#286]
Hi,

Really simple question but couldn't find the answer on the Github page. Which displayed planes in the GUI are flyback frames for z-stack recordings? I assume they would be laid out in order with the first imaged plane in the upper left and the flyback frames in the lower right but Marius' video on youtube shows the flyback frame in the upper left. Just don't want to double count cells in my recording

Thanks for the amazing software and all your support!

**Comment by carsen-stringer** [comment]
this is totally dependent on what the plane ordering is in your tiffs - we take the first plane to be the first frame of the tiff and do not mess with the order. glad you like the software, going to close this issue, but feel free to comment if you have more questions
