### ISSUE TITLE
Artifacts in rigid motion correction

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#288]
In some recent imaging sessions I noticed that I kept getting many ROIs with weird, non-sensical artefacts. They affect a large majority of the ROIs in the image and I didn't understand why I was suddenly getting them. Some example are shown in the red square of the heatmap.

![Screenshot from 2020-02-25 18-09-58](https://user-images.githubusercontent.com/4943380/75270039-2f95ac00-57fa-11ea-8cbf-f9ac5599e191.png)

I already expected the reason to be the registration. Indeed, the video had movement artefacts, but nothing crazy, some xy shifts here and there. So I decided to manually do the XY-correction with moco (https://github.com/NTCColumbia/moco) and extract the mean fluorescence of some ROIs with Imagej to compare with the suite2p output.

Example 1: A cell where the motion artefacts seem to better than what moco+imagej extracted. 
![cell1](https://user-images.githubusercontent.com/4943380/75270211-7683a180-57fa-11ea-8bd9-b4603699385b.png)
![cell1](https://user-images.githubusercontent.com/4943380/75270367-b8ace300-57fa-11ea-8a19-74dcfcf0b0c7.jpg)

Example 2: A cell where the motion artefacts are definately still there and more "hacky" compared to moco.
![cell2-suite2p](https://user-images.githubusercontent.com/4943380/75270433-d5e1b180-57fa-11ea-9946-d93d169937da.png)
![cell2](https://user-images.githubusercontent.com/4943380/75270488-f0b42600-57fa-11ea-984a-8dffa4a95735.jpg)

Example 3: A cell where the artefacts are very strong in suite2p but less with moco. Additionally, the responses of example 2 and example 3 to be *identical* (I made sure those were different cells and from two opposite sides of the field of view). Additionally, the imagej trace shows a strong reduction in the fluorescence of the cell while the trace from suite2p does not. This was also confirmed when I examine the video by eye...
![cell7](https://user-images.githubusercontent.com/4943380/75270659-353fc180-57fb-11ea-9cd3-9f3a152e98f6.png)
![cell7](https://user-images.githubusercontent.com/4943380/75270714-4be61880-57fb-11ea-9042-c764f21b8480.jpg)

Any idea what is happening here and how I can improve the results?

My settings:
```

ops = {
##        'fast_disk': [], # used to store temporary binary file, defaults to save_path0 (set as a string NOT a list)
        'save_path0': [], # stores results, defaults to first item in data_path
        'delete_bin': True, # whether to delete binary file after processing
        'sparse_mode' : True,
        # main settings
        'nplanes' : 1, # each tiff has these many planes in sequence
        'nchannels' : 1, # each tiff has these many channels per plane
        'functional_chan' : 1, # this channel is used to extract functional ROIs (1-based)
        'diameter':6, # this is the main parameter for cell detection, 2-dimensional if Y and X are different (e.g. [6 12])
        'tau':  0.7, # this is the main parameter for deconvolution
        'fs': 4.,  # sampling rate (total across planes)
        # output settings
        'save_mat': False, # whether to save output as matlab files
        'combined': True, # combine multiple planes into a single result /single canvas for GUI
        # parallel settings
        'num_workers': 0, # 0 to select num_cores, -1 to disable parallelism, N to enforce value
        'num_workers_roi': -1, # 0 to select number of planes, -1 to disable parallelism, N to enforce value
        # registration settings
        'do_registration': True, # whether to register data
        'nimg_init': 200, # subsampled frames for finding reference image
        'batch_size': 200, # number of frames per batch
        'maxregshift': 0.1, # max allowed registration shift, as a fraction of frame max(width and height)
        'align_by_chan' : 1, # when multi-channel, you can align by non-functional channel (1-based)
        'reg_tif': True, # whether to save registered tiffs
        'subpixel' : 10, # precision of subpixel registration (1/subpixel steps)
        'nonrigid' : False,
        '1Preg' : False,
        # cell detection settings
        'connected': True, # whether or not to keep ROIs fully connected (set to 0 for dendrites)
        'navg_frames_svd': 1000, # max number of binned frames for the SVD
        'nsvd_for_roi': 1000, # max number of SVD components to keep for ROI detection
        'max_iterations': 20, # maximum number of iterations to do cell detection
        'ratio_neuropil': 6., # ratio between neuropil basis size and cell radius
        'ratio_neuropil_to_cell': 3, # minimum ratio between neuropil radius and cell radius
        'tile_factor': 1., # use finer (>1) or coarser (<1) tiles for neuropil estimation during cell detection
        'threshold_scaling': 5., # adjust the automatically determined threshold by this scalar multiplier
        'max_overlap': 1.0, # cells with more overlap than this get removed during triage, before refinement
        'inner_neuropil_radius': 2, # number of pixels to keep between ROI and neuropil donut
        'outer_neuropil_radius': np.inf, # maximum neuropil radius
        'min_neuropil_pixels': 350, # minimum number of pixels in the neuropil
        'nbinned' : 1000,
        # deconvolution settings
        'baseline': 'maximin', # baselining mode
        'win_baseline': 60., # window for maximin
        'sig_baseline': 10., # smoothing constant for gaussian filter
        'prctile_baseline': 8.,# optional (whether to use a percentile baseline)
        'neucoeff': .7,  # neuropil coefficient
        'allow_overlap': False
      }
```

**Comment by carsen-stringer** [comment]
are these cells on the edge of the recording? I would only expect a difference if these cells were on the edge of the FOV (because how the two algorithms handle edges would vary)

**Comment by Cumol** [comment]
Examples 1 and 2 are very close to each other in the inner part of first square (when considering the 9 squared you can split the FOV in). The third example is indeed a cell from the outer edge of the third square.

**Comment by carsen-stringer** [comment]
These cells are likely going out of the FOV, and when we rigid shift we use "np.roll" which means the pixels from the left go to the right so it could cause these artifacts. I'd recommend not using cells on the edges if the movements are so big. 

If you like the MOCO correction better, then you could run it first and then feed it into suite2p (and turn off registration in suite2p).

**Comment by Cumol** [comment]
These artefacts are, however, all over the FOV. If you have a look at the first picture I posted, its the heatmap of all the cells in the FOV and about half of them have these very "in-sync" artefacts. I marked them here.

![Group](https://user-images.githubusercontent.com/4943380/75621454-cd8bcc80-5b94-11ea-9ee7-31166c58654f.png)

I also looked at the video again and the movement is not so strong as to shift these cells so far out. Usually suite2p deals well with such movements but it failed for this video (and a few others) and I was wondering whether I need to change the parameters for such videos but not sure which one I could play with.

**Comment by carsen-stringer** [comment]
are you using the latest version of the pipeline? there was a bug with motion registration in one of the earlier releases. You can also try the 1P settings for registration (click the 1P ops button in the GUI to see them).

**Comment by carsen-stringer** [comment]
also if it's only subsets of the image, is this nonrigid registration? I'd recommend using that to take care of movements that are not full field

**Comment by Cumol** [comment]
My movements can only really be rigid as I am imaging cultured cells on a glass coverslip. The glass coverslip can move during the experiment (due to the perfusion) so the movement is 99% of the time due to the glass coverslip moving and 1% of the time due to cells moving (or detaching).

**Comment by Cumol** [comment]
I am using the 0.6.16 version installed through pip right now. Is that a version affected by the bug?

**Comment by carsen-stringer** [comment]
Maybe, I'd try upgrading

**Comment by Cumol** [comment]
I will upgrade and try to run the files again. Thank you for the help!

**Comment by Cumol** [comment]
Tried rerunning after upgrade with the same output.

I also tried running 1P registration. I get the same error whether pre_smooth is set to 0 or 2

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-3b0890e0666f> in <module>
     35 
     36     # run one experiment
---> 37     opsEnd=run_s2p.run_s2p(ops=ops,db=db)

~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py in run_s2p(ops, db)
    269             if do_regmetrics and ops1[ipl]['nframes']>=1500:
    270                 t0=time.time()
--> 271                 ops1[ipl] = metrics.get_pc_metrics(ops1[ipl])
    272                 print('Registration metrics, %0.2f sec.'%(time.time()-t0))
    273                 np.save(os.path.join(ops1[ipl]['save_path'],'ops.npy'), ops1[ipl])

~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\metrics.py in get_pc_metrics(ops, use_red)
    170         refImg = mov.mean(axis=0)
    171     X    = pc_register(pclow, pchigh, refImg,
--> 172                        ops['smooth_sigma'], ops['block_size'], ops['maxregshift'], ops['maxregshiftNR'], ops['1Preg'])
    173     ops['regPC'] = np.concatenate((pclow[np.newaxis, :,:,:], pchigh[np.newaxis, :,:,:]), axis=0)
    174     ops['regDX'] = X

~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\metrics.py in pc_register(pclow, pchigh, refImg, smooth_sigma, block_size, maxregshift, maxregshiftNR, preg)
    111         refImg = pclow[i]
    112         Img = pchigh[i][np.newaxis, :, :]
--> 113         refAndMasks = register.prepare_refAndMasks(refImg, ops)
    114         dwrite, ymax, xmax, cmax, yxnr = register.compute_motion_and_shift(Img, refAndMasks, ops)
    115         X[i,1] = np.mean((yxnr[0]**2 + yxnr[1]**2)**.5)

~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\register.py in prepare_refAndMasks(refImg, ops)
     37 
     38     """
---> 39     maskMul, maskOffset, cfRefImg = rigid.phasecorr_reference(refImg, ops)
     40     if 'nonrigid' in ops and ops['nonrigid']:
     41         maskMulNR, maskOffsetNR, cfRefImgNR = nonrigid.phasecorr_reference(refImg, ops)

~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\rigid.py in phasecorr_reference(refImg0, ops)
     40 
     41     if ops['1Preg']:
---> 42         refImg = utils.one_photon_preprocess(refImg[np.newaxis,:,:], ops).squeeze()
     43     maskOffset = refImg.mean() * (1. - maskMul);
     44 

~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\utils.py in one_photon_preprocess(data, ops)
      9 def one_photon_preprocess(data, ops):
     10     ''' pre filtering for one-photon data '''
---> 11     if ops['pre_smooth'] > 0:
     12         ops['pre_smooth'] = int(np.ceil(ops['pre_smooth']/2) * 2)
     13         data = spatial_smooth(data, ops['pre_smooth'])

KeyError: 'pre_smooth'
```
