### ISSUE TITLE
# Reference image

### ISSUE THREAD

**Issue by Antje-Birkner** [MouseLand/suite2p#289]
Can you help me to generate the reference image only? I tried to use "refImg = register.pick_init(ops)" but realized that names of the functions changed. Thus, I tried to use "pick_initial_reference" but couldn't figure out what inputs I need to provide. 

I recently started using Suite2p to analyse my 2P data and it works really nicely! 

Thank you!!

**Comment by carsen-stringer** [comment]
sure, the new commands are [here](https://mouseland.github.io/suite2p/_build/html/autoapi/suite2p/registration/reference/index.html)

you will want 
~~~
suite2p.registration.reference.compute_reference_image(ops, bin_file)
~~~
where `bin_file` is the string path to your binary file
