### ISSUE TITLE
multithread server for Suite2p

### ISSUE THREAD

**Issue by gyorgylur** [MouseLand/suite2p#291]
Hi,

This is more of a general interest question than an issue but I think it may benefit the community.
My lab has recently started using suite2p and it's working really well, huge thanks to the developers!

I am currently considering building a server for the lab to process imaging data (2p calcium imaging, typically single plain, one or two channels, 256x256 or 512x512, GCaMP6 / jRGECO, 30Hz, files are around 5Gb) and I am curious what type of resources would suite2p benefit from? My understanding is that it currently does not use GPU acceleration so dropping multiple high power GPUs in a system is not that useful (am I correct?). 
My question is whether it benefits from larger core count, or higher clock speeds, or more RAM. E.g.: would it make more sense to build a system with a 32 core threadripper CPU (higher clock speed) vs. an EPYC platform that can go up to 64 cores (128 threads) or sending it off to a high performance cluster (potentially even more cores but transfer speeds etc can be limiting). Alternatively, would more RAM make a bigger impact than core count? 
The idea would be to deploy suite2p on several virtual machines on a server where my students can log in and process the data instead of using their desktops. However, if there is no real benefit to go over, say, 16 threads (which could be easily deployed in a consumer desktop) with 32GB of RAM, it is probably more cost effective to deploy several consumer level workstations compared to building a high-power server.

Your insight as developers (or anyone from the community) would be much appreciated!
I apologize if this has been discussed before that I missed.

Best wishes,
Gyuri

**Comment by marius10p** [comment]
Our advice would be to have multiple 8-core computers with 32GB of RAM and a dedicated SSD (SATA is fine). Suite2p is heavily optimized for such setups. We don't see a significant speedup beyond this, though it depends a little on the configuration. See also this [hardware guide](https://github.com/MouseLand/Kilosort2/wiki/8.-Hardware-guide) which I maintain for spike sorting.

**Comment by gyorgylur** [comment]
Fantastic! Thank you for getting back to me, really appreciate your work!
