### ISSUE TITLE
ops issues

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#299]
Hello again!
The "save ops to file" button and the "1P imaging" and "dendrites/axons" buttons of Load Example ops isn't working. 

The error message for "save ops to file" is :
Traceback (most recent call last):
File "C:\....", line 457, in save_ops
name = QtGui.QFileDialog.getSveFileName(self,'Ops name (*.npy)')
AttributeError: type object 'QFileDialog' has no attribute "getSveFileName'

For "1P imaging", the error message is:
[Errno 2] No such file or directory: 'C:\\.....\\suite2p\\gui\\ops/ops_1P.npy'

And the same error message as 1P imaging for dendrites/axons, except the filename is ops_dendrite.npy.

**Comment by carsen-stringer** [comment]
again this is an issue that is not present in the github version, I will make a new pip soon, but for now please use the github version
