### ISSUE TITLE
Segfault on Mac inside PyQt5 QFileDialog

### ISSUE THREAD

**Issue by histed** [MouseLand/suite2p#300]
With latest version of suite2p, the QFileDialog leads to segfaults.

To reproduce:
Install github master into its own environment (conda -c defaults).  Latest anaconda.
MacOS 10.14.6
python -m suite2p
File -> Load Processed Data
Hit the left or right arrow key
Segfault:

> 2020-03-12 21:44:30.855 python[74319:273916] WARNING: The same NSModalSession was stopped twice. The app may be mixing endSheet:returnCode: with NSModalSession APIs. This is likely to break in the future.
> Segmentation fault: 11

I think the first warning is not relevant.
I put a breakpoint before and after

> name = QtGui.QFileDialog.getOpenFileName(
>         parent, "Open stat.npy", filter="stat.npy",
>         options=options,
>     )

in suite2p.gui.io.menus.py, load_dialog()

And it's definitely happening inside the Mac native QFileDialog.

I tried using the pip PyQt5, and downgrading, including to ver 5.12.3.  None of this changes the segfaults.

Workaround: don't use the native mac QFileDialog.  This isn't a great soln
![image](https://user-images.githubusercontent.com/176407/76582378-721ee000-64ac-11ea-890c-ffd2387a0c41.png)

**Comment by histed** [comment]
I doubt you want to make the above change, but let me know if you want a patch.

I don't see anyone else reporting this issue.  PyQt5 isn't exactly well-supported, but no bug reports there seem to apply either.  Perhaps it's fixed on Catalina?

**Comment by carsen-stringer** [comment]
Hmm I haven't seen a report of this issue before (all our GUIs use PyQt5). Note now you can drag and drop `stat.npy` files into the GUI (but this doesn't help for the run window). The options settings work fine on Windows so if you make a pull request I'm happy to accept it.

**Comment by carsen-stringer** [comment]
This seems to be an old problem? https://stackoverflow.com/questions/16194475/qfiledialoggetopenfilename-doesnt-set-the-initial-directory-on-mac-os-10-8-mo/16197427

You can try upgrading qt (the version in my anaconda environment is 5.9.7)

Going to close this for now due to inactivity

**Comment by histed** [comment]
It's a segfault I was hitting – inside the QT shared lib, so impossible to debug with just the python bindings.  So I don't think that linked SO question is the issue.  
Yes, I can imagine it's only a Mac issue.  We have a workaround so totally fine to close - thanks!
