### ISSUE TITLE
Issue running suite2p from code - dcnv parallel processing issue

### ISSUE THREAD

**Issue by ronan-dasilva** [MouseLand/suite2p#301]
Hello again!

This is a more broad issue that spawned from me trying to solve Issue #287.

It turns out that the problem I was having (i.e. run_s2p() entering some kind of infinite loop) is not specific to processing sbx files. From what I could gather, `run_s2p()` goes normally all the way up to `dcnv.oasis()`, when the whole suite2p processing restarts, but with 6 additional copies of the process (I assume one copy for each cpu my computer has).

So I have tried to debug this by running `dncv.oasis()` with previously extracted `F.npy` and `Fneu.npy`. This resulted in the following error being raised over and over:

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
Could it be that this error is what is causing the `run_s2p()` to restart?

Weirdly, this issue does not happen when I run suite2p from the GUI, which makes me think that somehow the problem is in my ops. However, all I am really using is the `run_s2p.default_ops()` along with a db dictionary so I really don't know how I could fix this...

Thanks for the help!

**Comment by ronan-dasilva** [comment]
Here is the code that I used to generate the error mentioned above. I am using suite2p 0.7.1, installed in an anaconda env using the environment file.

```python
from suite2p import run_s2p
from suite2p.extraction import dcnv
import numpy as np

data = 'D:\\Ronan\\Imaging_Scope_1\\RdS_028\\img10k\\RL-fake\\part2\\a01'
ops = run_s2p.default_ops()
#ops = np.load('C:\\Users\\Ronan\\Miniconda3\\envs\\suite2p\\Lib\\site-packages\\suite2p\\ops\\ops_user.npy',allow_pickle=True).item()
 
db = {
      'data_path' : [data],
      'fast_disk' : 'c:/suite2p',
      'tau' : 0.7,
      'subfolders': [], #maybe unnecessary
      'delete_bin' : True,
      'input_format' : 'h5',
      'h5py_key': 'data', #maybe unnecessary
      'save_path0': data #maybe unnecessary
      }

ops = {**ops,**db}

F = np.load('D:\\Ronan\\Imaging_Scope_1\\RdS_028\\img10k\\RL-fake\\part2\\a01\\suite2p\\plane0\\F.npy')
Fneu = np.load('D:\\Ronan\\Imaging_Scope_1\\RdS_028\\img10k\\RL-fake\\part2\\a01\\suite2p\\plane0\\Fneu.npy')
dF = F - ops['neucoeff']*Fneu
spks = dcnv.oasis(dF, ops)
np.save(data+'\\suite2p\\plane0\\spks.npy')
```

**Comment by ronan-dasilva** [comment]
Another interesting observation:

Since I was able to run the process via the GUI and not by directly using `run_s2p.run_s2p()`, I decided to investigate how is it that the GUI calls the process. 
Funny thing, when instead of calling `run_s2p()` I used `os.system('python -u -W ignore -m suite2p --ops ops.npy --db db.npy')`, the process ran smoothly all the way through.

Any clues why this would happen? I am happy I found a work around, but it kind of bugs me that `run_s2p()` doesn't work as intended...

**Comment by carsen-stringer** [comment]
ughhh yeah I think some update with numpy or python and now multiprocessing no longer works for parallelization in the jupyter-notebook. I'm going to fix this ASAP.

**Comment by ronan-dasilva** [comment]
That's cool, thank you!

Just to mention, the issue was not limited to jupyter-notebook or IPython. It also happens when I executed the script from console (i.e. by running `python sbx_s2p.py` from Anaconda Prompt)

Hope this helps resolving the issue!

**Comment by carsen-stringer** [comment]
It must be multiprocessing not playing nice somehow in the deconvolution. I've removed the last thread of multiprocessing from suite2p (bad pun :P) and replaced it with numba, it's much faster! currently in github version not yet in pip
