### ISSUE TITLE
missing "iplane" variable after merging ROIs

### ISSUE THREAD

**Issue by schoki0710** [MouseLand/suite2p#305]
Dear Suite2p developpers,

We noticed in Suite2p version 0.7.1 after we merged ROIs, the "iplane" in "OPS" for those merged ROIs became empty. iplane of all the other ROIs remain intact.  

Thanks in advance!

**Comment by carsen-stringer** [comment]
thanks for the bug report, I'll fix this.

**Comment by carsen-stringer** [comment]
I've fixed this in the github version and am going to close this for now, comment if you're still having issues.
