### ISSUE TITLE
Unresponsive area in manual labelling GUI

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#306]
Nothing breaking. Just a little annoying.

When trying to create a ROI with alt+click inside that red box, it GUI doesn't respond and doesn't create the ROI. Creating a ROI somewhere else and moving it into the area works though.

Editing a ROI inside that are also doesn't work.

![dead-area](https://user-images.githubusercontent.com/4943380/77689361-d27c4a00-6fa1-11ea-8a4a-7bd02f0e418f.png)

**Comment by dba91** [comment]
Hi Cumol,

did you ever run into a problem as described here:
https://github.com/MouseLand/suite2p/issues/313
