### ISSUE TITLE
Hi, I'm having a pr

### ISSUE THREAD

**Issue by mich11** [MouseLand/suite2p#307]
Hi,
I'm having an issue with the GUI.  I've just installed Suite2p, once on Windows and once on Mac using environment.yml and Anaconda with Python 3.7.  With both installations, when I open data that I've analyzed with an earlier version of Suite2p, the "not cells" ROI window shows up tiny (picture below), and I can't enlarge it, which prevents me from doing any manual validation.

Any ideas for why this might happen? It looks like it's not a Mac-specific issue, so maybe it's because I'm loading data that was analyzed with an earlier Suite2p version? 
 
![WindowSizingExample](https://user-images.githubusercontent.com/283777/77706159-d34fb480-6f7e-11ea-9ffd-2952d488aecc.png)

**Comment by ronan-dasilva** [comment]
Hey!

Just click on the button "Both" that is just above the image and you should see both Cells and Non-cells windows equally.

Best

**Comment by mich11** [comment]
Works perfectly -- thanks so much!
