### ISSUE TITLE
Question regarding aspect ratio

### ISSUE THREAD

**Issue by xwchia** [MouseLand/suite2p#312]
Thank you for this wonderful software!

We have started processing our data, and we are using a specific aspect ratio ( X:500, Y:200 pixels).

After running suite2p and processing the data, what we see on the suite2p GUI is this distorted image (photo attached, aspect 2.5).

I was wondering if this is correct and what we are supposed to see? On the GUI parameters, we keyed in **Aspect: 2.5**. Given that our X: 1um/pixel and Y: 2.5um/pixel. However we noticed that when we used Aspect 2.5 vs Aspect 0.4, the image looks the same on the GUI.

Seeking your kind clarification on this issue.

Thank you.

![Suite2p_output_image](https://user-images.githubusercontent.com/48054750/77988759-ae2cbe80-734f-11ea-8f9c-4c8ad77e6a12.PNG)

**Comment by carsen-stringer** [comment]
Is your `diameter` parameter a list? That will overwrite the `aspect` parameter (to keep backwards compatibility)

**Comment by xwchia** [comment]
Hi Carsen,

Thanks for the response. My diameter parameter is a single number, 12.

**Comment by xwchia** [comment]
Dear Carsen,

Was wondering if there are any updates to this issue that i faced? I've currently updated the version to the latest v0.9.2.

I've tried more parameters settings (using the same files as mentioned ( X:500, Y:200 pixels where  X: 1um/pixel and Y: 2.5um/pixel.) ) , and i've noticed that the diameter parameters affects the aspect ratio when displayed in the GUI.

So far, the use of aspect ratio = 1 and diameter 10,4 seems to do the trick of displaying my ROI as the correct square image (500x500um). However, as seen in the screenshot below, the ROI's masks when clicked on seems distorted. Is this correct?

In addition, can i check how does the diameter parameter works? Is it a list where i can input several diameter values (e.g. 8,9,10,11) or a list to input the aspect ratio of the diameter (e.g. 10,4).

Thank you.



![Screenshot 2020-11-06 at 1 57 07 PM](https://user-images.githubusercontent.com/48054750/98331658-fb84b300-2037-11eb-871f-9e6b1355499f.png)

**Comment by carsen-stringer** [comment]
for the diameter parameter you can input two values and it will use them to resize. are the ROIs distorted or just the circles that the GUI draws in meanImg view? the other ROIs look good

**Comment by carsen-stringer** [comment]
how's it going with this? going to close for now due to inactivity
