### ISSUE TITLE
Errors when Trying to Use Manual Curation

### ISSUE THREAD

**Issue by dba91** [MouseLand/suite2p#313]
Was excited to use the new Manual Add ROI feature. When trying to add the ROI you see at the right side of the image, it got hung up for a while, then I ran into the errors shown on top left of the console. The ROI did not appear and now I cannot open up the stat to curate either. Seems like maybe the ROI got added to the end of a list that's expected to stay the original size? 
Wondering if anyone has had experience with this and might know what's going on or is having better luck with the Manual Add?

![image](https://user-images.githubusercontent.com/31355751/78289953-cb8c9480-74d7-11ea-99c1-b02c8b025ccf.png)

**Comment by Cumol** [comment]
I haven't but lets try to troubleshoot.

Did you upgrade to the latest version?` pip install suite2p --upgrade`

When you add ROIs manually you first need to "extract ROIs" and then "save and exit". This, depending on where your binary file sitting will take more or less time. I am storing my files on a remote machine so this takes a few minutes if I have many ROIs (sometimes up to 300) and the GUI will freeze. But don't worry, it will resolve.

Now to the screenshots. There are two things that look weird.
1) In the console it looks like you have clicked "extract ROIs" twice and not letting it finish until extracting. Maybe there is an issue.
2) The extracted trace looks weird. It seems like your video is only 2000ish frames long but the extracted trace is exactly double that size. I get these kinds of errors when I mess with the pipeline (like stopping it before it finishes). My advice would be to delete the suite2p folder for this recording and rerun it.

Let me know if that helps

**Comment by dba91** [comment]
Hi Cumol, Thanks for taking a look I appreciate it. You make good observations. I think the screen shot example I have does have some of these issues you point out, I will show a different case here that doesn't have those issues but still runs into the same ultimate error. I am running the latest version, but I could try prior ones too.

I do follow the extract ROI -> save and exit. I run into problems on that second step.

The extraction step works. To extract 1 ROI on my machine it takes around 25 min, and I've noticed it freezes then resolves as well! I have the same where my data is on a remote server. But no matter. See this example where I didn't press the button twice and the data was the correct size. 
![plane_1 1 ROI extracted, took ~25 min](https://user-images.githubusercontent.com/31355751/78377280-47dcb180-7584-11ea-9b16-94f87a13f342.PNG)



But after extraction is done, at the save and exit step, s2p runs into the familiar issue.
![plane_1 1 ROI save and quit ultimately fials, took ~25 min](https://user-images.githubusercontent.com/31355751/78377449-7b1f4080-7584-11ea-9deb-768fbd894460.PNG)



This seems like it could be a bug, but it's interesting you aren't running into any such issue.

**Comment by dba91** [comment]
Just adding a few more details in case it's helpful for S2P people to debug or others have similar issues:

- Upgrading to the newest version doesn't result in different behavior

- This whole problem may be due to the fact I'm dealing with a multi-channel file since the error message points to something about a field relating to the red cell probability not being properly instantiated (I think this is the bug, and multi-channel just wasn't planned for)

- Despite the error I think the stat file definitely is getting updated because it doesn't allow me to open that stat file on the GUI after trying (and failing) to add the manual ROI. This happens even if I close S2P and restart and try to load in the stat file.

- On a multiplane recording where you are examining both planes at once, even the extraction step runs into issues:

![manual add ROI after s2p update, failed on extraction](https://user-images.githubusercontent.com/31355751/78381581-6d6cb980-758a-11ea-89b5-d5c463193e35.PNG)

So my current thought is that the Manually Added ROI works in the simplest case of one channel one plane, but is buggy in all other instances. Getting a fix for this would be awesome!

**Comment by Cumol** [comment]
Yeah, the error seems to point into that direction.

I am only using one-plane, one-channel recordings and there it works.

**Comment by carsen-stringer** [comment]
Thanks for the detailed bug report, I will fix this in the next couple of days!

**Comment by dba91** [comment]
Awesome, thanks Carsen! When hacking it for my own version, I also added a max projection image for the second channel on the Manual Add ROI screen. Think that would be helpful for people.

**Comment by carsen-stringer** [comment]
oh cool, did you fix this bug too? could you make a pull request with your version of the code then? :)

**Comment by dba91** [comment]
Happy to share it, wasn't exactly sure how to pull with git on this repo. Sent you an email!

**Comment by carsen-stringer** [comment]
it's been more than a couple days -.- but I've fixed the issue with red channel manual files. Also added check when you close manual GUI (to make sure you don't close without saving). 

the issue with not drawing ROIs in outside area is because that area is INVALID based on the registration. I've made that area BLACK for all views.

Currently in github, will make new pip soon.

please let me know if it's not working, going to close this issue for now

**Comment by Cumol** [comment]
Will try it this week and let you know. Thanks!

**Comment by abedghanbari2** [comment]
Hi, I'm facing a similar issue when trying to add my manual ROIs. I'm using suite2p straight from github (0.7.5)

- I have a 400 x 460 x 16000 tif that I processed from command line and later open processed dat in GUI
- it's missing about 50% of cells that I see in correlation map:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/22683143/83283540-5d97dd00-a1a9-11ea-9c80-b60c27c0a5a1.png">
- I wanted to see how manual labeling works so I tried File --> manual labelling
- I add my ROI and when I click the extract roi option I get this error:

```
no channel 2 labels found (redcell.npy)
0.1301255226135254
Traceback (most recent call last):
  File "C:/Users/prototype/Downloads/suite2p-master\suite2p\gui\drawroi.py", line 403, in proc_ROI
    F, Fneu, F_chan2, Fneu_chan2, spks, ops, stat = masks_and_traces(self.parent.ops, stat0, self.parent.stat)
  File "C:/Users/prototype/Downloads/suite2p-master\suite2p\gui\drawroi.py", line 26, in masks_and_traces
    stat_all, cell_pix, _ = extraction.create_cell_masks(ops, stat_all)
TypeError: create_cell_masks() missing 1 required positional argument: 'Lx'
```

should I add a second channel?

Thank you!
Abed
