### ISSUE TITLE
problem running the code

### ISSUE THREAD

**Issue by aripakman** [MouseLand/suite2p#314]
I installed suite2p in linux mint 19.3 using anaconda.
When running the GPU version on the provided sample tif files, the shell shows
----------- REGISTRATION
registering 4000 frames
Reference frame, 26.12 sec.
Opening in GUI (can close this window)

but at that point an error box opens that says: "Incorrect file, not a stat.npy, choose another?"

Runnning from jupyter the kernel crashes at a similar point.

Any ideas?
Thanks

**Comment by carsen-stringer** [comment]
Maybe you're getting a memory error? Watch your memory usage while running suite2p, you may need to decrease the `ops['batch_size']`. A large batch size means many frames processing simultaneously which may be eating your memory and crashing the process (Linux doesn't allow overwriting RAM to disk like Windows).

**Comment by carsen-stringer** [comment]
going to close this issue due to inactivity, please comment if you're still having issues and I'll reopen it

**Comment by aripakman** [comment]
sorry for the slow reply. indeed, it seems to have been a memory problem, since the issue disappeared when I run it on a similar system with more memory. thanks!
