### ISSUE TITLE
Support Neurodata Without Borders?

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#316]
Thanks for this package! I've mostly been using CaImAn and wanted to give suite2p a try. It would be great if suite2p would support Neurodata Without Borders `.nwb` for reading & writing data, as that would make it much easier for researchers to try new/different pipelines. Thanks for your work, and consideration!

https://pynwb.readthedocs.io/en/stable/

**Comment by carsen-stringer** [comment]
Agree this is a good idea, I am attending the hackathon in a couple weeks and will add support then!

**Comment by eann** [comment]
Hi! I'm attending the hackathon too, and I was wondering if I could help with adding NWB support

**Comment by carsen-stringer** [comment]
that would be awesome yes! current plan is to support in order of priority
1. exporting to NWB format
2. loading NWB format into GUI
3. (optional - not preferred/priority) loading NWB format for processing

**Comment by carsen-stringer** [comment]
1 + 2 are done!

is there an example of a file for 3? is that what you wanted @tbenst ?
