### ISSUE TITLE
GUI: can't select .h5 files

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#317]
On Ubuntu 18.04 using the repo's [`environment.yml`](https://github.com/MouseLand/suite2p/blob/master/environment.yml), I run `python -m suite2p`. Then `File -> Run suite2p`. The `input_format` dropdown only contains `tif`, and when I `add directory to data_path`, my `.h5` file is not recognized. I believe I've properly followed https://mouseland.github.io/suite2p/_build/html/inputs.html?highlight=hdf5#hdf5-files-and-sbx, but apologies if I'm missing something obvious...

**Comment by carsen-stringer** [comment]
the dropdown should contain h5, did you `pip install suite2p --upgrade`? maybe `h5py` is not installed?

are there any error messages when you start suite2p?

**Comment by carsen-stringer** [comment]
I'm going to make a new pip asap and this should be fixed there, it's working in the github, going to close this for now please comment if you're still having issues
