### ISSUE TITLE
Old vs new Suite2p versions

### ISSUE THREAD

**Issue by xiaonansun** [MouseLand/suite2p#319]
Hello,

I'm trying to update scripts written (no by me) several years ago which relied on the output of an older matlab version of Suite2p to accomodate for the output from the newest python suite2p. One legacy field i've come across is dat.ops.DS. Is the output ops.corrXY a replacement for this variable?
Another field that is no longer part of the suite2p output is dat.cl.dcell. Would you (1) happen to have any documentation on this field and (2) is there a way to recreate this field?

Thank you!

**Comment by carsen-stringer** [comment]
DS are the shifts (yoff, xoff). Here is the old documentation: https://github.com/cortex-lab/suite2p

dcell has something to do with the old classifier I think? Don't remember. The probability of an ROI being a cell is the second column of `iscell.npy`:
~~~
iscell = np.load('iscell.npy')
probcell = iscell[:,1]
~~~
