### ISSUE TITLE
MultiChannel, single page tiffs using "Bruker" option

### ISSUE THREAD

**Issue by carolyngs** [MouseLand/suite2p#320]
Hello,

Using the "Bruker" option for single page tiffs no longer works for multi-channel recordings. For example, it assumes that 2000 single pages arise from one channel as opposed to 1000 from Ch1 and 1000 from Ch2. There used to be a work-around for this; however, it does not seem to work in subsequent updates.

Thanks.

**Comment by carsen-stringer** [comment]
can you share a google drive link with a subset of these tiffs please for testing?

**Comment by carolyngs** [comment]
Thanks for looking into this

An example dataset can be found here
https://drive.google.com/drive/folders/10JElmOCPvzXvl-dvV1EU6iXTBW6mtOkT?usp=sharing



When Bruker's Prairie View softward converts files to Tiffs, it generates
single page .ome.tiffs.
All Ch1 tiffs are listed before all Ch2 tiffs.

Ch1_Time1
Ch1_Time2
Ch1_Time3
Ch2_Time1
Ch2_time2
Ch3_time3



For our system, Ch1 is red and Ch2 is green; however I can imaging that
could differ
among labs depending on how they setup their PMTs with the system.

**Comment by carsen-stringer** [comment]
sorry that folder only has one file in it, can you add more please?

**Comment by carolyngs** [comment]
Sorry, I think the permissions for sharing the files was wrong.

This folder should work:
https://drive.google.com/open?id=1rqmE1VhhlTDZv_-tWzLqjyexoNRfy5sM


Thanks!

**Comment by carsen-stringer** [comment]
![image](https://user-images.githubusercontent.com/15067541/81501853-80b92600-92a8-11ea-81eb-2c06921a99af.png)
still only one tiff here that I can see :(

**Comment by carsen-stringer** [comment]
weird can only see one tiff but downloading the folder grabbed all of them, thanks!

**Comment by carsen-stringer** [comment]
it's working fine for me in the pip and the github version, here's a picture of my settings (note you have to say 'nchannels'=2)
![image](https://user-images.githubusercontent.com/15067541/81502086-d3dfa880-92a9-11ea-98a6-40905a3a4a63.png)

(note I made duplicates of your tiffs to run it because the pipeline won't run with less than 50 frames)

**Comment by carolyngs** [comment]
That's interesting. I am receiving the following error:
{'data_path': ['Z:/Carolyn/2P Imaging data/VxAC031419M1/2019-07-10/Bruker
multiChannel singlepage Tiffs_2'], 'subfolders': [], 'save_path0':
'Z:/Carolyn/2P Imaging data/VxAC031419M1/2019-07-10/Bruker multiChannel
singlepage Tiffs_2', 'fast_disk': 'Z:/Carolyn/2P Imaging
data/VxAC031419M1/2019-07-10/Bruker multiChannel singlepage Tiffs_2'}
** Found 160 tifs - converting to binary **
time 29.27 sec. Wrote tifs to binaries for 1 planes
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
----------- REGISTRATION
registering 0 frames
===== 2020.05.10 10:05:53 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "D:\anaconda\envs\suite2p\lib\runpy.py", line 193, in
_run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "D:\anaconda\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sweenec\suite2p_new\suite2p\__main__.py", line 24, in
<module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\sweenec\suite2p_new\suite2p\run_s2p.py", line 230, in
run_s2p
    ops1[ipl] = register.register_binary(ops1[ipl]) # register binary
  File "C:\Users\sweenec\suite2p_new\suite2p\registration\register.py",
line 347, in register_binary
    raise Exception('ERROR: the total number of frames should be at least
50 ')
Exception: ERROR: the total number of frames should be at least 50
Interrupted by error (not finished)




Below are all of my settings. This is with the PIP version.
Thanks again for the help!




[image: image.png]

**Comment by carsen-stringer** [comment]
I think you need to upgrade to the latest version of suite2p (that will have the working bruker dropdown option as you see in my picture), your db doesn't have an 'input_format'

**Comment by carolyngs** [comment]
Updating with PIP still gives me a version without an input format
drop-down menu; however, the latest github version runs! Thanks so much for
the help!

**Comment by carsen-stringer** [comment]
weird thanks for letting me know, I'll update the pip soon!
