### ISSUE TITLE
Cannot "Export as image" except for Entire Scene

### ISSUE THREAD

**Issue by marysethomas** [MouseLand/suite2p#322]
Hello,

When I try to "Export as image" from the main GUI using the GitHub version of Suite2p it only works if I have Entire Scene selected. Thinking this might be a bug!

Here is the error message I get in the terminal:

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\exporters\Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\exporters\ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer`

Thanks!

Maryse

**Comment by carsen-stringer** [comment]
This is an issue with pyqtgraph not suite2p, only svg export is supported in the pip version. You can upgrade to the latest dev version of pyqtgraph with
`pip install git+https://github.com/pyqtgraph/pyqtgraph`

**Comment by marysethomas** [comment]
Thanks!

**Comment by or-naim** [comment]
Hey, had the same issue with exporting the screen. Remains the same after the upgrading (only svg works). Any suggestions?
