### ISSUE TITLE
Saving failing because of missing dx key

### ISSUE THREAD

**Issue by vigji** [MouseLand/suite2p#323]
I am processing multiplane .h5 files (a folder with n 4D stacks -t,z,y,x - to be concatenated in time), all default parameters, changing only fn, tau and planes and disabling deconvolution.
All the processing run smoothly, but at the and, when saving, I get the following error:

```
KeyError                                  Traceback (most recent call last)
<timed exec> in <module>

~/lab_code/suite2p/suite2p/run_s2p.py in run_s2p(ops, db)
    327     #### COMBINE PLANES or FIELDS OF VIEW ####
    328     if len(ops1)>1 and ops1[0]['combined'] and roidetect:
--> 329         save.combined(ops1)
    330 
    331     # running a clean up script

~/lab_code/suite2p/suite2p/io/save.py in combined(ops1)
     10     '''
     11     ops = ops1[0].copy()
---> 12     dx = np.array([o['dx'] for o in ops1])
     13     dy = np.array([o['dy'] for o in ops1])
     14     unq = np.unique(np.vstack((dy,dx)), axis=1)

~/lab_code/suite2p/suite2p/io/save.py in <listcomp>(.0)
     10     '''
     11     ops = ops1[0].copy()
---> 12     dx = np.array([o['dx'] for o in ops1])
     13     dy = np.array([o['dy'] for o in ops1])
     14     unq = np.unique(np.vstack((dy,dx)), axis=1)

KeyError: 'dx'
```

In the saving function some lines below you address the condition of no dx entry (`in io.save.combined`):

```
ops = ops1[0].copy()
dx = np.array([o['dx'] for o in ops1])
dy = np.array([o['dy'] for o in ops1])
unq = np.unique(np.vstack((dy,dx)), axis=1)
nrois = unq.shape[1]
if ('dx' not in ops) or ('dy' not in ops):
```

So I wonder whether this is a bug that I am seeing b/c of some combination of parameters that doesn't instantiate dx? I would be happy to fix it in a PR but just putting another conditional won't work as that `nrois` parameter is required in the subsequent elif clause.

**Comment by carsen-stringer** [comment]
sorry about that, I've fixed this in the github, will make a new pip this weekend

**Comment by vigji** [comment]
Thank you very much!
