### ISSUE TITLE
~\Suite2p\Plane0\ops.npy file empty

### ISSUE THREAD

**Issue by Saksham20** [MouseLand/suite2p#325]
After running the pipeline, when I load the file from ~\Suite2p\Plane0\ops.npy, it seems to be empty for some reason. 
However there is another file created outside Plane0, directly in the parent folder as suite2p\ops1.npy.  This file is a dict containing keys from the ops dict (`run_2p.default_ops()`) and the keys from what the tutorial says Suite2p\Plane0\ops.npy should contain ([Here](https://mouseland.github.io/suite2p/_build/html/outputs.html#ops-npy-fields)) 
I'm not sure if this was intended or is a bug? Or am I misreading the tutorial? 
Thanks!

**Comment by carsen-stringer** [comment]
Did the pipeline run all the way through? That should be saved during binary file creation and registration. What type of files are you running?

also just double-checking you know to use `.item` when you load `ops.npy`:
~~~
ops = np.load('ops.npy', allow_pickle=True).item()
~~~

**Comment by Saksham20** [comment]
Yes, it works this way. Thanks!
