### ISSUE TITLE
Export the enhanced mean image

### ISSUE THREAD

**Issue by scbsli** [MouseLand/suite2p#327]
Dear suite2p developers, 

Is there a way that we can export the ehanced mean image in 1:1 xy dimensions as the registered movie? The reason we are interested in this is that we are collecting data in two channels, one of them is Ca+ (we use for registration), and the other is a neuromodulator sensor that expresses mostly on the somatic membrane (hence, faint). We would like to use the enhanced mean image calculated in the Ca channel to define membrane-ROIs (in ImageJ) for processing the other channel. We tried the export image function in the GUI but that image is a screenshot of a portion of the GUI (containing the mean image together with bunch of other things). Of course, we can manually crop and scale the screenshot but since the GUI is displaying that image, it would be great if we can find a way to access it. Is this possible? 

Thanks for your help in advance!

**Comment by carsen-stringer** [comment]
the image in the GUI is not in fact super-resolution, but it is the mean over the registered channels. You can find the mean image and the mean image in the second channel in ops (see python example below):
~~~
import numpy as np
ops = np.load('ops.npy', allow_pickle=True).item()
meanImg = ops['meanImg']
meanImg_chan2 = ops['meanImg_chan2']

# save image
import skimage
skimage.io.imsave('meanImg.tif', meanImg)
skimage.io.imsave('meanImg_chan2.tif', meanImg_chan2)
~~~

**Comment by scbsli** [comment]
> the image in the GUI is not in fact super-resolution, but it is the mean over the registered channels. You can find the mean image and the mean image in the second channel in ops (see python example below):
> 
> ```
> import numpy as np
> ops = np.load('ops.npy', allow_pickle=True).item()
> meanImg = ops['meanImg']
> meanImg_chan2 = ops['meanImg_chan2']
> 
> # save image
> import skimage
> skimage.io.imsave('meanImg.tif', meanImg)
> skimage.io.imsave('meanImg_chan2.tif', meanImg_chan2)
> ```

Thanks! That worked. Btw, is the enhanced mean image (meanImgE) the so-called "super-resolution" image? Anyway, we find the calcium version of it very helpful for defining somatic membrane ROIs!
