### ISSUE TITLE
number of ROIs dont match the total cells in all planes combined

### ISSUE THREAD

**Issue by Saksham20** [MouseLand/suite2p#328]
Thanks for creating an extension to save the data in an NWB file, however, in the nwb file, the number of rois in the PlaneSegmentation table ( number of cells in all planes) dont match the rois number in the RoiResponseSeries in the Fluorescence container. 
`nwbfile.processing['ophys']['ImageSegmentation']['PlaneSegmentation'].iscell.shape[0]` is not equal to `nwbfile.processing['ophys']['Fluorescence']['roi_response_series'].rois.shape[0]`.
I think, if the F traces are appended along the 0 dim, they should represent the response of all rois?

**Comment by carsen-stringer** [comment]
maybe I'm not using response series correctly then?
~~~
with NWBHDF5IO(os.path.join('GT1/', 'suite2p', 'ophys.nwb'), 'r') as fio:
    nwbfile = fio.read()
    
    # masks
    try:
        masks = nwbfile.processing['ophys']['ImageSegmentation']['PlaneSegmentation']['pixel_mask']
        multiplane = False
    except:
        masks = nwbfile.processing['ophys']['ImageSegmentation']['PlaneSegmentation']['voxel_mask']
        multiplane = True
    print(len(masks))
    F = np.array(nwbfile.processing['ophys']['Fluorescence']['roi_response_series'].data)
    print(F.shape)
~~~
^^^
those are the right shape

**Comment by carsen-stringer** [comment]
oh I see the bug, it's with the number of cells in the series, just fixed this in the github, but the output data is right
~~~
F = np.array(nwbfile.processing['ophys']['Fluorescence']['roi_response_series'].data)
~~~

you have multiplane data correct?

**Comment by Saksham20** [comment]
yes, my Fluorescence data was of the right length. 
It matches with the no of cells now with the bug fix. 
Thanks!
