### ISSUE TITLE
Suite2P won't save in NWB format

### ISSUE THREAD

**Issue by sdaste** [MouseLand/suite2p#330]
Hi Carsen,
First thanks a lot for the amazing work you've done with Suite2P.
I've updated the Suite2P version in order to save the output files in NWB format. I've set the save_NWB input to 1. It runs well and saves all the planes in npy but not in NWB. I get this message at the end:
----------- SPIKE DECONVOLUTION
----------- Total 0.18 sec.
Plane 2 processed in 318.48 sec (can open in GUI).
total = 993.70 sec.
pip install pynwb OR don"t use mesoscope recording
TOTAL RUNTIME 994.50 sec
Interrupted by error (not finished)

Do you have any idea what the problem would be ? It seems like a trivial problem, sorry for that..

Thanks a lot!
Simon

**Comment by carsen-stringer** [comment]
Yeah I should write a better error message, you need to 'pip install pynwb'

If you're using mesoscope recordings, it's currently not supported

**Comment by sdaste** [comment]
Awesome, yes it worked! Many thanks!
