### ISSUE TITLE
'wrong' registered channel gets saved when aligning by non-fun channel

### ISSUE THREAD

**Issue by samihassan84** [MouseLand/suite2p#331]
Hi Carsen,
thanks for the latest updates. It's really such a great tool and an enormous help!
I think there is a bug in the reg_tif flag. In my recording chan 1 is functional, so 'functional_chan' is 1. When I set 'reg_tif' to 1 (reg_tif_chan2 is set to 0) and set 'align_by_chan' to 2, it is actually the non-functional channel that gets saved. Is there an error with the [0 1] and [1 2] indexing or am I doing something wrong?
Thanks

Another question of minor importance - I guess it is easy to implement outside the GUI, but I haven't started running suite2p by a notebook: do you think it would be beneficious in terms of longitudinal registration to register against the template image of session e.g. 'day 1' rather then calculating a new template every session, or would it not have much of an influence regarding the identification of ROIs but rather impair the motion correction?

**Comment by carsen-stringer** [comment]
thanks I've added the bug label. for now please set reg_tif_chan2 to 1. It seems like you're doing everything right - if you watch the registered binary in the GUI, it's correctly the functional channel?

For longitudinal recordings, you can use the same reference image in the code, but it would take a bit of hacking. If you think that the same reference image will work for all recordings, we recommend running all sessions together. If there is substantial nonrigid movement between recording sessions then you will want to run suite2p on each session separately with different refImg's and then use a tool like the one in the docs to align.

**Comment by nickdelgrosso** [comment]
This conversation is starting to duplicate that of #295 .  Closing this issue to keep conversation around longitudinal roi tracking co-located in the same forum.
