### ISSUE TITLE
Docs: "register.prepare_masks()" not found in source code

### ISSUE THREAD

**Issue by nickdelgrosso** [MouseLand/suite2p#351]
Hi, 

The (registration tutorial)[https://suite2p.readthedocs.io/en/dev/registration.html] describes how to use prepare_masks() to make masks independently from the pipeline, but I cannot find the function in the source code.  Is there a new function for doing this, or is prepare_refAndMasks() the only way?

Best wishes,

Nick

**Comment by carsen-stringer** [comment]
yeah, that function name has been changed, thanks for catching that

**Comment by nickdelgrosso** [comment]
Okay, thanks.
