### ISSUE TITLE
F_chan2.npy and Fneu_chan2.npy

### ISSUE THREAD

**Issue by sdaste** [MouseLand/suite2p#355]
Hi Carsen,
I realized that when I manually select "cells" and "not cells" in the GUI after running Suite2p, both F_chan2 and Fneu_chan2 files are not updated (as of F and Fneu files). Is there something that I'm missing or is it a bug ?

Many thanks!
Simon

**Comment by carsen-stringer** [comment]
Yeah they will not change they contain ALL ROIs' traces, you need to load in `iscell.npy` and use that to index into those arrays for further processing.

**Comment by sdaste** [comment]
Hi Carsen, thanks for your answer. I'm wondering if they should not be updated for example when I'm adding an ROI manually labeled or when I merge two ROIs (which is what is happening with F.npy and Fneu.npy).

**Comment by carsen-stringer** [comment]
if by manual labelling you mean drawing new ROIs, they should be added to F and Fneu if you "SAVE"

if by manual labelling you mean right and left clicking, then no they won't update, that would be too slow and also we want you to be able to keep all ROI traces in case you want them in the future

**Comment by sdaste** [comment]
Yes, I meant drawing! Would it be possible to have F_chan2.npy and Fneu_chan2.npy also updated in this case?
