### ISSUE TITLE
Test Data Download for Devs

### ISSUE THREAD

**Issue by nickdelgrosso** [MouseLand/suite2p#356]
Hi, 

I need to run the pipeline tests through the gui to check that everything still works, which meant calling the functions to get the test data to use.  Could we simplify the test data download code and server?  Write now we have added ~100 lines of code for what essentially amounts to "Download the files off a server".  My understanding is that this is because the server requires an exact URL to get each individual file.  

We could change this (e.g. by putting all the test data in a zip file for a single download call from the Flask server's end, thereby requiring only a single endpoint for each dataset) and using a higher-level package to do the download (e.g. requests), it would keep that side of the code a lot more manageable.  As it is now, there's a lot of hard-coded values and indirection that will make managing our test data a real challenge, and the server code isn't available online.

**Proposal**: Use (DVC)[https://dvc.org/] for data versioning.  This will let us track data files as part of out git repo (without blowing out Git) and download the correct verison of the data from wherever we want (Janelia servers, ssh, etc) so we can run the pipelines without having to manage server code at all.   A nice summary talk here (start at 7:30): https://youtu.be/jkfh2PM5Sz8?t=441

**Comment by chriski777** [comment]
I do agree that the tests can be modified to be made a lot more streamlined and generalizable. The download code for the tests right now can't really do much other than download the different plane/channel data. I think this would definitely be really nice to have when writing new tests that require other types of test data.

Does the DVC provide an endpoint (with the most current data) that we can download from? Also, how easy is it to work with `requests`?

**Comment by nickdelgrosso** [comment]
Yes, exactly.  Yes, DVC provides that in two ways:
   1. As a terminal command:  ``dvc pull``
   2. As a Python function: ``dvc.api.read("myfile.txt")``

Requests is extremely easy (``requests.get(url).content``), but with dvc it wouldn't even be necessary, since it already provides the same level of download commands.

**Comment by nickdelgrosso** [comment]
Merged, closing.
