### ISSUE TITLE
Ordering of ROIs in output stat.npy

### ISSUE THREAD

**Issue by 7rebor** [MouseLand/suite2p#361]
How are the ROIs ordered in the output stat.npy?

The subjectively better ROIs are found at lower indexes, plotting all of the key values from the stat.npy dict shows some correlation with each key and the order of the indexes, but it isn't completely obvious.

It also doesn't appear to correlate with the default classifier cell probability? Although I haven't looked in to that for very long. 

The reason for asking this question is to determine if the quality of each ROI has already been ordered in some way and try to get the simplest explanation for this ordering if so.

**Comment by carsen-stringer** [comment]
Yeah the cells with the most skewed/large signals will be detected first and thus the first entries in stat, you may want to keep those regardless of what the classifier says. The classifier is looking for compact circular ROIs.

**Comment by Moosehorse123** [comment]
Hi @carsen-stringer can you possibly elaborate on "most skewed/large signals will be detected first"? Seeing some consistently high correlations between the first few neurons in the ROI order and wondering what this could mean based on how the ROIs are ordered by suite2p.
