### ISSUE TITLE
Create regression tests for each module

### ISSUE THREAD

**Issue by chriski777** [MouseLand/suite2p#363]
We're going to need tests for each module so that we can continue with refactoring. Since a major part of the refactoring will involve having each module produce an actual output, it's necessary to have tests that check to make sure the outputs are correct and in the right format. The modules we need tests for:

- [x] Registration
- [x] classification
- [x] extraction
- [x] io

**Comment by nickdelgrosso** [comment]
Sounds good!  For this, do you mean (unit tests or acceptance tests)[https://sites.google.com/site/unclebobconsultingllc/tdd-with-acceptance-tests-and-unit-tests]?  

In either case, it would be good to have separate issues for each module (maybe even more than one, for example for the io module, for which the reading and writing of certain file formats are meaningful on a high level in this field; that is, they would be mentioned in a methods paper on the package.)

**Comment by chriski777** [comment]
Ooh, when I initially wrote this, I didn't know about acceptance tests but I think(?) that's what I'm heading towards. 

The module tests I currently have in mind will be treating each module as a black box and just checking to make sure each output matches a ground truth file. The test will be similar to the regression tests we had in `test_pipeline.py` but be narrower in scope and as of now, should fail (since none of the modules have actual outputs yet). 

As for the separate issues, that sounds great to me! For right now then, this issue will just be for the tests I mentioned above.

**Comment by marius10p** [comment]
We need to split cell detection (sourcery, sparsedetect, masks) off of "extraction". Extraction is meant to cover fluorescence extraction, demixing, baselining, deconvolution and other operations on traces. Detection should just find the appropriate masks given a pre-registered binary file or direct input.

**Comment by nickdelgrosso** [comment]
Working on the registration module now.

**Comment by chriski777** [comment]
I'm currently working on registration acceptance tests right now, too. Thinking of and writing these non-regression tests have been taking longer than expected as I've been trying to understand what each function is doing in each module. I've also been working on creating simple datasets that can help verify if rigid/non-rigid registrations are working properly.

My fork has updates that I've been working on for these past few days if you'd like to see some of the tests I have so far!

**Comment by chriski777** [comment]
Refer to #371, #372, #373, #374.
