### ISSUE TITLE
Test Coverage Visibility

### ISSUE THREAD

**Issue by nickdelgrosso** [MouseLand/suite2p#364]
Hi,

We have our first couple of tests running now, but no visibility on how much or which parts of the code are actually tested.  For this, we should use a test coverage tool and run it alongside the CI tool.

Best wishes,

Nick

**Comment by nickdelgrosso** [comment]
Still needed is activation on www.coveralls.io.   Current code coverage can be found on my fork in the meantime.  https://coveralls.io/github/nickdelgrosso/suite2p

**Comment by nickdelgrosso** [comment]
@carsen-stringer could you activate it on coveralls.io ?  I'm not a member of the Mouseland github org and don't have sufficient privilages to add it.

**Comment by carsen-stringer** [comment]
Just did, see if it works now

**Comment by nickdelgrosso** [comment]
It works! https://coveralls.io/github/MouseLand/suite2p?branch=dev

Merged and closing issue.
