### ISSUE TITLE
test_pipeline tests have low coverage.

### ISSUE THREAD

**Issue by nickdelgrosso** [MouseLand/suite2p#367]
The current coverage stats show clearly that we only inter-tester reliability for about 25% of the code.  This includes the gui, though, which isn't part of our short-term change plans.  Probably it's closer to 40%.  

https://coveralls.io/github/nickdelgrosso/suite2p

If we can get the amount of non-gui code to be >80% covered by the test_pipeline functions (basiclaly, by calling run_s2p() with different settings in ops), then we'll know that that code doesn't include any simple bugs (NameError, SyntaxError, AttributeError, etc--), and that any refactoring we do is likely to be checked for them.  At that stage, we'll have a good regression test going and can more safely perform refactoring without introducing run_s2p-breaking bugs that will have immediate impacts on users.

**Comment by carsen-stringer** [comment]
Options that will help with coverage:
`ops['sparse_mode']=0` will use sourcery
`ops['1P_reg']=1` will use some filtering functions
`ops['reg_tif']=1` and `ops['save_NWB']=1` for io functions

we would need h5 files for instance for coverage of io.h5. but still surprised it's so low

**Comment by nickdelgrosso** [comment]
Thanks!  I'll add those parameters.

**Comment by nickdelgrosso** [comment]
These merged pull requests have made a big difference in coverage.  There's still some io missing (mostly sbx and nwb--reg_tif was added in the new tests), but these deserve more specific focus in the future.  

Still to be done is adding tests for sourcery.  Working on it now.

**Comment by nickdelgrosso** [comment]
I think the regression test coverage of the non-gui code is high enough for this refactoring phase for us to make the changes we need.  Close this issue?
