### ISSUE TITLE
redprob not using bleedthrough corrected image

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#369]
Hi, I have a question about the detection of red cells. A bleed through corrected version of the second channel is calculated, but finally does not seem to be used to obtain the red cell probabilities. Is this intended / could you explain why? Thanks! https://github.com/MouseLand/suite2p/blob/f5fbe98c1a4da0d9030d0d804697830ba299fd72/suite2p/extraction/chan2detect.py#L45

**Comment by carsen-stringer** [comment]
I can change that back, sometimes I think the bleedthrough correction is too strong. Would you prefer it to be on the corrected image? We are going to put cellpose in here soon and it should work better than the current detection system.

**Comment by horsto** [comment]
Great, thanks for explaining. Yes, I also noticed that the correction does seem quite strong sometimes. Do you have any ideas why / how to improve? 
It would be nice to directly compare results on bleedthrough corrected vs. uncorrected (for selection of cutoffs). Maybe you could you export those results in parallel to the current ones?
I am looking forward to the cellpose integration!

**Comment by nickdelgrosso** [comment]
This issue appears to be inactive.  Closing the issue; it can be reopened when conversation around the topic begins again.
