### ISSUE TITLE
registration.rigid.shift_data() doesn't always shift data

### ISSUE THREAD

**Issue by nickdelgrosso** [MouseLand/suite2p#380]
Hi,

The rigid.shift_data() function says it shifts data in-place, but this doesn't happen if the number of dimensions is two or less (https://github.com/MouseLand/suite2p/blob/master/suite2p/registration/rigid.py#L169), which results in a function that often does nothing at all.

Suggestion:  make shift_data() return the data, not do it in place, to ensure that it always works.  While this may have a performance impact, it should be relatively minor and will ensure that the function is testable.

**Comment by carsen-stringer** [comment]
Why isn't it working for 2D? Part of the reason it's in place is because it is for nonrigid I think? Those copy commands mean it can be done not in place at same speed. But in place operations definitely make nonrigid faster

**Comment by nickdelgrosso** [comment]
The `X = X` line re-scopes the X variable into the function, making it so the global X variable isn't modified.  The line essentially blocks the in-place operation from affecting anything outside the function, but only inside that if-statement.

**Comment by chriski777** [comment]
Closing.
