### ISSUE TITLE
KeyError: 'pre_smooth'

### ISSUE THREAD

**Issue by maxrioux100** [MouseLand/suite2p#390]
Suite2p : 0.7.4
OS: Win10
python: 3.7.7

I sometime get the error below 
![pre_smooth](https://user-images.githubusercontent.com/40430512/84043702-a3f0f700-a974-11ea-94d6-65f13aaf336c.PNG)

If I restart suite2p, it continue and finish. 

If I try to access ops['pre_smooth'] it show the correct value.

Error happen both with the Gui and the python module

**Comment by maxrioux100** [comment]
The error append just after 
![bad frames](https://user-images.githubusercontent.com/40430512/84049383-60998700-a97a-11ea-9ce2-4d343a1bb2ea.PNG)

**Comment by nickdelgrosso** [comment]
Thank you for the report!  Could you provide the configuration file (ops) so we can replicate the error message?

**Comment by chriski777** [comment]
Hey @maxrioux100, do you still have this issue with the latest version of suite2p?

**Comment by chriski777** [comment]
There hasn't been a response yet so I'll close this due to inactivity. @maxrioux100, feel free to reopen if this problem persists!
