### ISSUE TITLE
Input argument error for create_cell_masks when extracting from manually drawn ROIs

### ISSUE THREAD

**Issue by jpakan** [MouseLand/suite2p#391]
When I try to 'extract ROIs' after manually drawing ROIs with the GUI, I get the following error:

Traceback (most recent call last):
  File "C:\...\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 404, in proc_ROI
    F, Fneu, F_chan2, Fneu_chan2, spks, ops, stat = masks_and_traces(self.parent.ops, stat0, self.parent.stat)
  File "C:\...\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 27, in masks_and_traces
    stat_all, cell_pix, _ = extraction.create_cell_masks(ops, stat_all)
TypeError: create_cell_masks() missing 1 required positional argument: 'Lx'

I could be wrong, but I believe the inputs for extraction\masks.py `def create_cell_masks` seemed to have been changed with a May 14th update (5098715a818b03948e85c82c5ed7d319f323fac0) but the drawroi.py file was not updated with new inputs/outputs for this (???). 

P.S. thanks for the excellent resource and all the updates!

**Comment by jpakan** [comment]
For anyone interested, I fixed this with the following code replacing `def create_cell_masks` in the suite2p\gui\drawroi.py file. I will not create a pull request though as I don't yet know the code too well and I am not confident that this isn't screwing something else up - or that there isn't a more elegant fix for this issue. In case others are having the same problems though, for now this is working for me. 

def masks_and_traces(ops, stat, stat_orig):

    ''' main extraction function
        inputs: ops and stat
        creates cell and neuropil masks and extracts traces
        returns: F (ROIs x time), Fneu (ROIs x time), F_chan2, Fneu_chan2, ops, stat
        F_chan2 and Fneu_chan2 will be empty if no second channel
    '''

    t0 = time.time()
    # Concatenate stat so a good neuropil function can be formed
    Ly = ops['Ly']
    Lx = ops['Lx']
    stat_all = stat.copy()
    for n in range(len(stat_orig)):
        stat_all.append(stat_orig[n])
    stat_all = extraction.get_overlaps(stat_all,ops)
    cell_pix, cell_masks = extraction.create_cell_masks(stat, Ly, Lx, ops['allow_overlap'])
    stat = stat_all[:len(stat)]
    
    neuropil_masks = extraction.create_neuropil_masks(ops, stat, cell_pix)
    neuropil_masks = np.reshape(neuropil_masks, (-1, Ly * Lx))

    print('Masks made in %0.2f sec.' % (time.time() - t0))

    F, Fneu, ops = extraction.extract_traces(ops, cell_masks, neuropil_masks, ops['reg_file'])
    if 'reg_file_chan2' in ops:
        print('red channel:')
        F_chan2, Fneu_chan2, ops2 = extraction.extract_traces(ops.copy(), cell_masks, neuropil_masks, ops['reg_file_chan2'])
        ops['meanImg_chan2'] = ops2['meanImg_chan2']
    else:
        F_chan2, Fneu_chan2 = [], []

    # compute activity statistics for classifier
    npix = np.array([stat_orig[n]['npix'] for n in range(len(stat_orig))]).astype('float32')
    for n in range(len(stat)):
        stat[n]['npix_norm'] = stat[n]['npix'] / np.mean(npix[:100])  # What if there are less than 100 cells?
        stat[n]['compact'] = 1
        stat[n]['footprint'] = 2
        stat[n]['Manual'] = 1  # Add manual key

    # subtract neuropil and compute skew, std from F
    dF = F - ops['neucoeff'] * Fneu
    sk = stats.skew(dF, axis=1)
    sd = np.std(dF, axis=1)
    for n in range(F.shape[0]):
        stat[n]['skew'] = sk[n]
        stat[n]['std'] = sd[n]
        stat[n]['med'] = [np.mean(stat[n]['ypix']), np.mean(stat[n]['xpix'])]
    stat = extraction.roi_stats(ops, stat)    
    if not isinstance(stat, list):
        stat = np.ndarray.tolist(stat)

    dF = F - ops['neucoeff'] * Fneu
    spks = extraction.oasis(dF, ops)

    # print('Ftrace size', np.shape(Fneu), np.shape(F))
    return F, Fneu, F_chan2, Fneu_chan2, spks, ops, stat

**Comment by dkushinsky** [comment]
Hi @jpakan !

I am having the same issue -- have you still been using this fix, and if so does it cause any issues with any of the other functions of the software? Just want to be sure before I implement it. 

Thanks!

**Comment by jpakan** [comment]
Hi @dkushinsky - so far so good. I have not discovered any problems with this fix yet. The only issues I can foresee is that here I had to implement some functions to get 'missing' parameters (like the radius), which I think are normally not calculated until later in the code. I used the `stat = extraction.roi_stats(ops, stat)` to get this information in the fix but it seems to output an ndarray and so then I had to convert back to a list. I am not sure if there is a better way of doing this, and hopefully it does not change any specific parameters of the stat.npy output. For me it was okay and the data still loads into the GUI etc properly, but I would just check the stat.npy output after and make sure everything looks okay for your processing. 

Otherwise, I have been running the fix across multiple sessions now and adding manual ROIs with no further issues (it does seem to only like to add a certain number of ROIs at a time - usually 4 - before I have to extract and save the new manual signals, otherwise it seems to get hung up and freeze, but I am not sure if this is new behaviour or not).

**Comment by chriski777** [comment]
Hey @jpakan and @dkushinsky, thanks for letting us know about this bug. As @jpakan said, `drawroi.py` wasn't updated to include the refactored code in the `extraction` and `detection` subpackages. This issue should be resolved in the PR above.

**Comment by chriski777** [comment]
Merged in #442
