### ISSUE TITLE
Fast Z movements

### ISSUE THREAD

**Issue by nelsonrebola** [MouseLand/suite2p#392]
I am really worried about movement in my prep (barrel cortex), specially Z movements during locomotion.
This is really difficult to identify even by eye. I was wondering if in the suite2P we could use the value of pixel shift in PCA analysis as an indication of Z drift. What do we expect as mean pixel shift in a movie with mininum Zdrift?  Thanks a lot for your help.

**Comment by marius10p** [comment]
By PCA analysis do you mean the registrations metrics in the GUI? The absolute value of the PCs are not very informative. You can get a sense of the amount of movement by comparing the field of view then the zdrift PC is low vs high (like [this](https://twitter.com/marius10p/status/1051494535677788161?s=20)). If completely new cells come into focus, then the movement is more than 10-20um and at that point the whole thing is hopeless. If it's the same cells but getting smaller and larger, then zdrift is <10um which means you can use the data, and take the PC activity as a control: whatever effect you are measuring in your task, is it always on frames for which the PC is high?

**Comment by nickdelgrosso** [comment]
This question seems to have been answered.  Closing it now.  @nelsonrebola , if you would like to follow up on this please feel free to re-open the issue and reply.
