### ISSUE TITLE
Silent cells Suite2P

### ISSUE THREAD

**Issue by nelsonrebola** [MouseLand/suite2p#393]
I noticed that some neurons can be particularly silent during 2Photon calcium imaging sessions (I use short imaging periods - 5 min). Is it possible to make suite2P detect those silent cells? Thanks a lot for the help.

**Comment by rajatsaxena** [comment]
You can try using this new software Cellpose (https://github.com/MouseLand/cellpose) developed by the suite2p group

**Comment by marius10p** [comment]
If you take multiple 5 minute videos from the same cells, it is preferable to concatenate and run them together in Suite2p.
