### ISSUE TITLE
Registering cells across multiple recordings

### ISSUE THREAD

**Issue by soobpark** [MouseLand/suite2p#405]
Good morning,

I am trying to load multiple TIF files (the first with 20,000 frames, second and third with 30,000 frames each) that are located in a single folder. Is it possible to distinguish the order of which file suite2p has registered first?

The goal is to compare the same cells in the three recordings and eventually be able to compare the data longitudinally. Is there a way to register which traces are from the same cells across multiple videos after running suite2p in order to compare with future recordings?

**Comment by nickdelgrosso** [comment]
Hi, @soobpark,

Yes, it is possible to distinguish the file order that Suite2p processes multiple tiff tiles in.  This is found in the 'filelist' parameter of the suite2p/ops1.npy file. 

Here's a snippet that should give you the list (from the output folder):

```python
import numpy as np
ops1 = np.load("suite2p/ops1.npy", allow_pickle=True)
filelist = ops1[0]['filelist']
print(filelist)
```

**Comment by soobpark** [comment]
@nickdelgrosso Fantastic! Thank you so much!
