### ISSUE TITLE
Unable to locate neuropil (ipix_neuropil) mask output

### ISSUE THREAD

**Issue by johnw-25** [MouseLand/suite2p#409]
Hi,

Suite2p has been very helpful with processing our data however we are unable to recreate the neuropil that suite2p is detecting. In the Suite2p MATLAB output there doesn't appear to be a variable for the neuropil mask. Is this a known issue or am I doing something incorrect with Suite2p?

Here is a screen capture of one of the stat structures in MATLAB:
![image](https://user-images.githubusercontent.com/62902060/85321278-ab8ac280-b481-11ea-8e42-bb286723d88d.png)

Thank you!

**Comment by nickdelgrosso** [comment]
Hi @johnw-25 ,

Apologies for the slow reply.  You're correct, the neuropil mask is not present in the suite2p output files.  Sure, this can certainly be added.

Best wishes,

Nick

**Comment by johnw-25** [comment]
Thank you for the reply, Nick! The addition of that output would be very helpful and appreciated.

**Comment by chriski777** [comment]
Fixed in #493, will close.

**Comment by chriski777** [comment]
Whoops, sorry about that. Forgot that it was merged to dev.

**Comment by nickdelgrosso** [comment]
If it's merged to dev, the issue should be closed, as it's resolved. It will be included in the next release of suitep.
