### ISSUE TITLE
manual labeling issues

### ISSUE THREAD

**Issue by or-naim** [MouseLand/suite2p#413]
Hello again,

Just started using the manual labeling option and loved it! Nevertheless, I bumped into two issues I would like to address:

1. I can't see the new labeled cells in the "view registered binary option". After I check "view masks", I see some of the cell masks but very blurry.  A picture of the originally identified cells and another picture of the same cells in the "view registered binary" option, "view masks" checked are attached below.  
Is it possible to see it more smoothly? 

![image](https://user-images.githubusercontent.com/59688604/86022485-1fedd480-ba33-11ea-81db-356f480b7b47.png)

![image](https://user-images.githubusercontent.com/59688604/86022466-19f7f380-ba33-11ea-9054-c66e2620a434.png)

2. Is there a way for the algorithm to learn how to choose similar cells as the manual labeled ones? I remember such option was possible, but couldn't find the way.

Many thanks!

**Comment by or-naim** [comment]
Any suggestions?

**Comment by mathildelpx** [comment]
Hi !

I had kind of the same need and what I found to work pretty well is to change the ops Cell Detection parameters. 
If you put sparse_mode = 0, you can then specify a list of diameters you expect your cells to be in the 'diameter' ops key. Pay attention to which diameter suits more to your cells when you manually label them, then you can enter them as a list. It's pretty basic but it worked fine for me.

Not directly your question but related, you can also look at what the classifier is: https://suite2p.readthedocs.io/en/latest/gui.html?highlight=classifier#classifying-cells

Hope this helps !

**Comment by or-naim** [comment]
Hey thanks a lot! Will try this one out and let you know :)

**Comment by or-naim** [comment]
Just noticed I didn't give any update on this, so it works! Thanks in delay :)
