### ISSUE TITLE
error when running suite2p

### ISSUE THREAD

**Issue by soobpark** [MouseLand/suite2p#417]
Good morning,
I recently upgraded my suite2p, but I seem to hit an error when running the gui.. Specifically, this error occurs when I change the value of preclassify from 0 to 0.3:
[error.txt](https://github.com/MouseLand/suite2p/files/4865614/error.txt)

I apologize in advance, as I am not very familiar with programming yet. Perhaps this may be a simple fix that I am just not understanding...

Many thanks,

**Comment by soobpark** [comment]
For anyone who has this issue, I downgraded to a previous version as a temporary fix.

Best,

**Comment by chriski777** [comment]
Fixed in #422.
