### ISSUE TITLE
sampled_mean function

### ISSUE THREAD

**Issue by xiaonansun** [MouseLand/suite2p#418]
Hello,

In line 261 of run_s2p.py, the sampled_mean function is called upon. However, running run_s2p.py led to an error where the registration.sampled_mean attribute could not be found. However, I did find the sampled_mean function in suite2p.registration.utils.sampled_mean. In the end, I just added .utils into line 261 of run_s2p.py. 

Is this a bug in the code or did I install an older version of suite2p?

Thank you,

Richard

**Comment by chriski777** [comment]
Hey Richard, which version of suite2p are you using right now?

**Comment by chriski777** [comment]
Hey Richard, good catch! This is indeed a bug in the code. The `sampled_mean` function in `registration.utils` is the one it should be calling.

**Comment by carsen-stringer** [comment]
I fixed this issue today on the dev branch will be pushing it in soon

**Comment by chriski777** [comment]
Fixed in latest PR #442
