### ISSUE TITLE
Some issues manual labelling 

### ISSUE THREAD

**Issue by Hanbing1999** [MouseLand/suite2p#419]
Hi, I confronted with some troubles in manual labelling: 1. I cannot save manual selected ROIs (Figure 1), and the bottom seems not work. 2. I am unable to extract signals from selected ROIs (Figure.2)
Figure 1: 
![image](https://user-images.githubusercontent.com/67142892/86476574-61ef8100-bd79-11ea-8957-a5eb807ac7f7.png)
Figure 2:
![image](https://user-images.githubusercontent.com/67142892/86476589-6ae05280-bd79-11ea-8bfb-5e236fa83521.png)

Thanks for your time!

**Comment by chriski777** [comment]
This is a bug and seems related to #391. `Create_cell_masks` seems to be missing the `Lx` parameter

**Comment by chriski777** [comment]
Hey, the PR above fixes the two issues you mentioned. The fixed code will be available soon when the PR is merged and the master branch is updated. Thanks for letting us know about the bug!

**Comment by Hanbing1999** [comment]
> Hey, the PR above fixes the two issues you mentioned. The fixed code will be available soon when the PR is merged and the master branch is updated. Thanks for letting us know about the bug!

Thanks!

**Comment by chriski777** [comment]
Merged in #442
