### ISSUE TITLE
error launching GUI on #dev branch

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#424]
ERROR: 'function' object has no attribute 'default_ops'
could not load default ops, using built-in ops settings
Traceback (most recent call last):
  File "D:\Github\suite2p\suite2p\gui\rungui.py", line 51, in __init__
    self.reset_ops()
  File "D:\Github\suite2p\suite2p\gui\rungui.py", line 76, in reset_ops
    ops0 = run_s2p.default_ops()
AttributeError: 'function' object has no attribute 'default_ops'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Github\suite2p\suite2p\gui\menus.py", line 13, in <lambda>
    runS2P.triggered.connect(lambda: run_suite2p(parent))
  File "D:\Github\suite2p\suite2p\gui\menus.py", line 153, in run_suite2p
    RW = rungui.RunWindow(parent)
  File "D:\Github\suite2p\suite2p\gui\rungui.py", line 56, in __init__
    self.ops = run_s2p.default_ops()
AttributeError: 'function' object has no attribute 'default_ops'

**Comment by carsen-stringer** [comment]
not sure I understand this -- run_s2p is a module not a function

**Comment by carsen-stringer** [comment]
oh I found it this is a problem with the __init__.py function changing, going to fix this now for the GUI

**Comment by Cumol** [comment]
I am getting the same error with the clean install of the most recent release.

I am running the jupyter notebook for multiple tiffs/batch
https://github.com/MouseLand/suite2p/blob/main/jupyter/run_pipeline_tiffs_or_batch.ipynb

**Comment by Cumol** [comment]
This is how the error looks like
```
AttributeError                            Traceback (most recent call last)
<ipython-input-6-b25c3373ab98> in <module>
     74 
     75         # run one experiment
---> 76         opsEnd=run_s2p.run_s2p(ops=ops,db=db)

AttributeError: 'function' object has no attribute 'run_s2p'
```

**Comment by nickdelgrosso** [comment]
Looks like an import relationship--maybe there is a `from run_s2p import run_s2p` that wasn't there before.  Changing it to `opsEnd=run_s2p(ops=ops, db=db)` should fix that problem.

**Comment by brandonStell** [comment]
It seems that this fix hasn't been merged yet?

```
In [1]: from suite2p.run_s2p import run_s2p

In [2]: ops = run_s2p.default_ops()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-3a141e6b455b> in <module>
----> 1 ops = run_s2p.default_ops()

AttributeError: 'function' object has no attribute 'default_ops'

In [3]:                                                                                                                                     
Do you really want to exit ([y]/n)? 
(suite2p) 
~ ⌚ 14:03:40
$ ipython      
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from suite2p import run_s2p

In [2]: ops = run_s2p.default_ops()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-3a141e6b455b> in <module>
----> 1 ops = run_s2p.default_ops()

AttributeError: 'function' object has no attribute 'default_ops'
```

Is there a work around in the meantime?

**Comment by nickdelgrosso** [comment]
It's merged now.  But the workaround is this:

```python
from suite2p import run_s2p, default_ops
In [2]: ops = default_ops()
```

**Comment by brandonStell** [comment]
thanks!
