### ISSUE TITLE
default_ops as a test variable + function

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#425]
default_ops is a function name but is used as a variable in the testing scripts, please update this

**Comment by chriski777** [comment]
the `default_ops` in the testing script is referring to the `default_ops` fixture in `conftest.py`:

```
@pytest.fixture()
def default_ops(tmpdir, data_dir):
    """Initializes ops to be used for test. Also, uses tmpdir fixture to create a unique temporary dir for each test."""
    ops = suite2p.default_ops()
    ops['data_path'] = [data_dir]
    ops['save_path0'] = str(tmpdir)
    return ops
```
In the testing scripts, `default_ops` is referring to the output of the fixture above

**Comment by carsen-stringer** [comment]
Sorry for the confusion but this is the problem, there is already a function called default_ops in suite2p, can we change the name of the fixture? Sorry for not knowing the terminology :)
