### ISSUE TITLE
baseline correction

### ISSUE THREAD

**Issue by coco941** [MouseLand/suite2p#430]
Dear all,

I am new to programming and I am happy to your advices and please let me know if you need to know more details. 
Here is my problem: I keep having a baseline shift in my data. In the documentation I saw that there are two options for baseline (either maximin or constant). But I do not have this baseline option in the GUI. Is this still available? Or is the baseline correction used just for spike detection and all the output files are raw data?

version of suite2p - downloaded 09.07.2020

Thank you in advance :)

Best,
Corinna

**Comment by chriski777** [comment]
Hey Corinna, you are right as the GUI does not provide the option to switch. By default, the `baseline` parameter is set to `maximin`. The changes you make to `sig_baseline` and `win_baseline` should still have an effect as they'll be used in the deconvolution step.

If you'd like to change the baseline option, you can do so by running your analysis on a script/ jupyter notebook. Here's a block of code you can try running (make sure to change the strings that say `insert_...`):

```
import suite2p
ops = suite2p.default_ops()
ops['data_path'] = [Path('insert_path_to_folder_that_contains_tif')]
# Change the parameters in ops to what you want
... 
ops['baseline'] = 'insert_setting_you'd_like_here' # default is 'maximin'. You can use 'constant' and 'constant_prctile'.
suite2p.run_s2p(ops)
```

You can then drop the produced `stats.npy` file into the GUI if you'd like to check out your results on it.

**Comment by chriski777** [comment]
Hey @coco941, just wanted to check in with you and see if you have additional questions. If not, could you close the issue? We'll close this issue in a couple of weeks if there's no response.

**Comment by chriski777** [comment]
Closing, due to no response
