### ISSUE TITLE
missing exception in building classifier

### ISSUE THREAD

**Issue by rozmar** [MouseLand/suite2p#432]
I was loading in a bunch of iscell.npy files to build a classifier in the gui and this error popped up:
===== 2020.07.13 21:07:26 =====
Traceback (most recent call last):
  File "/home/rozmar/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/gui/classgui.py", line 257, in <lambda>
    save.clicked.connect(lambda: self.build_classifier(parent))
  File "/home/rozmar/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/gui/classgui.py", line 314, in build_classifier
    loaded = load_data(parent, keys, parent.trainfiles)
  File "/home/rozmar/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/gui/classgui.py", line 144, in load_data
    ypix = stat[0]['ypix']
IndexError: index 0 is out of bounds for axis 0 with size 0

I didn't investigate which file caused the problem.

Adding IndexError in line 146 fixed the issue

**Comment by chriski777** [comment]
Hmm, what's the length of the `iscell.npy` file you're adding before you get this error? It seems no cells were found for that run and you don't have to include it when building your new classifier.

**Comment by rozmar** [comment]
That's what I thought, too, since it's empty there are probably no ROIs detected. I have hundreds of movies that I manually curated over weeks, gathered all the iscell.npy file locations and tried to build the classifier and encountered this error. Since suite2p didn't report which file produced the error, I can't tell you what is the length of the file. I can investigate if you insist.
Just wanted to let you know that this happened and might happen to others, too.

**Comment by carsen-stringer** [comment]
Hey Marton working on this now - also will send you code to apply
classifier to all your data once it's done

**Comment by carsen-stringer** [comment]
fixed this
