### ISSUE TITLE
default classifier is not default?

### ISSUE THREAD

**Issue by rozmar** [MouseLand/suite2p#436]
I have ran suite2p on several hundred movies. Next, I categorized the cells in some FOVs and built a classifier, set it as the default classifier.
When I load  another movie, it's not the default classifier that is loaded but something else so I have to load the default classifier from the menu. Is this how it is supposed to work? 
If so, what should I edit so the GUI will load the default classifier after opening a movie? 
(For several hundred movies it's a significant wait time and clicking I'd like to avoid.)
Thanks!

**Comment by rozmar** [comment]
Or maybe is there a method to just batch run the default classifier on the processed data and update the iscell.npy files accordingly?

**Comment by chriski777** [comment]
How do you know something else other than the default classifier is loaded? 

To my knowledge, you shouldn't have to keep setting the default classifier. Once you set it as the default classifier, it will overwrite the `classifier_user.npy` classifier file that is used every time you run suite2p.

**Comment by rozmar** [comment]
Hi,
Sorry, I am new to suite2p expressions. I have already ran suite2p on all of the movies. When I said I load another movie I meant that I just load the suite2p pipeline output in the suite2p GUI.
I know something else is loaded because if I color the cells based on the classifier, I see how cells are classified based on their color, I can also draw a threshold and divide them as cells on non-cells. If I load the default classifier, the colors change and if I apply the same decision threshold, there is a different clustering of cells and non-cells.

I see. So the classifier is loaded only when you run the suite2p pipeline.
I have no classifier_user.npy in the directory where the suite2p output is, only the iscell.npy. Where is the classifier specified? How do I batch-change it?
Thanks!

**Comment by carsen-stringer** [comment]
Hey Marton,

Yeah this is sort of counter-intuitive behavior. When you load a 'stat.npy' file with an 'iscell.npy' file into the GUI, the 'iscell.npy' file has two columns, the second of which is the cell probability. That second column gets put into the classifier GUI colors and will only change if you load a classifier. We could add a shortcut for loading the default classifier.

To run the current default classifier (saved in $HOME/.suite2p/classifiers/classifier_user.npy) on many files you will need to loop over your ops and stat files and run:
```
import numpy as np
from suite2p import classification

ops = np.load('ops.npy', allow_pickle=True).item()
stat = np.load('stat.npy', allow_pickle=True)
iscell = classification.classify(ops, stat)
```

you can also specify classfile as an optional argument to that function
```
iscell = classification.classify(ops, stat, classfile='class.npy')
```

**Comment by rozmar** [comment]
Hi Carsen,
Thanks for the code, works out of the box!
Marton
