### ISSUE TITLE
ScanImageTiffReader on MacOS

### ISSUE THREAD

**Issue by nhat-le** [MouseLand/suite2p#438]
I'm processing a .tif image with a batch size of 500 on MacOS, using the jupyter notebook. The images are 512 x 512.
In utils.py, choose_tiff_reader function, when im = tif.data(beg = 0, end=...) is being executed, I get a notification that says "The kernel appears to have died".

**Comment by chriski777** [comment]
What conda version are you using? Is your macOS up-to-date?

**Comment by nhat-le** [comment]
I'm using conda version 4.8.2. Yes, my macOS should be up to date.

**Comment by chriski777** [comment]
What version of `scanimage-tiff-reader` is installed on your machine? If it is `1.4.0`, can you try running suite2p again after upgrading to `1.4.1`?

**Comment by nhat-le** [comment]
You are right. I was using version 1.4.0. After upgrading to 1.4.1 the issue seems to have been resolved. Thank you!
Sorry for the confusion. I am using version 0.7.5 of suite2p and `choose_tiff_reader` was indeed called in `tiff.py`, not `utils.py`.

**Comment by chriski777** [comment]
That's great to hear! Thanks for letting us know about this issue. I'll close this since everything is fine.
