### ISSUE TITLE
pyqtgraph has bug in PNG exporter

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#44]
will be fixed in next release
https://github.com/pyqtgraph/pyqtgraph/issues/722

for now, please export to *.svg

**Comment by KnightyOwl** [comment]
Hi, I met a similar issue when I tried to export the mean image to tiff, here's the error message in the terminal:

Traceback (most recent call last):
  File "/home/marc/anaconda3/lib/python3.7/site-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/home/marc/anaconda3/lib/python3.7/site-packages/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer

How can I fix this?

Thanks in advance!

**Comment by carsen-stringer** [comment]
unfortunately the author of pyqtgraph has not yet released 0.11.0 which fixes this bug (see https://pypi.org/project/pyqtgraph/). but you can install the development version with 

`pip install git+https://github.com/pyqtgraph/pyqtgraph`

it worked for me for tiffs and png's :)

**Comment by KnightyOwl** [comment]
> unfortunately the author of pyqtgraph has not yet released 0.11.0 which fixes this bug (see https://pypi.org/project/pyqtgraph/). but you can install the development version with
> 
> `pip install git+https://github.com/pyqtgraph/pyqtgraph`
> 
> it worked for me for tiffs and png's :)

Thank you very much, the issue has been solved!

**Comment by carsen-stringer** [comment]
sweet :) I'm going to close this then
