### ISSUE TITLE
Issue on motion correction in hippocampal imaging 

### ISSUE THREAD

**Issue by fangyue1992** [MouseLand/suite2p#448]
I have been using 2-photon imaging to image hippocampal neurons and there are some motions when I image the mouse in awake state. I tried your Suite2P to correct motions. The result I got is that the registered images seem to have more vibrations than the raw images ( as attached gif file, left is registered image, right is raw image). I have played around with the rigid, non-rigid parameters, and it turns out the vibrations are different when the parameters are different but they all show that the registered images have some artificial vibrations. Would you like to give some advice on how may I fix this artificial vibration problem in tornado images? Thanks a lot.

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/52596746/88002376-f9ecb900-cb34-11ea-9a2e-c0c19e57468c.gif)

**Comment by carsen-stringer** [comment]
Hey can you share this tiff so that @chriski777 can debug the motion registration? I'm wondering if that inner circle is the problem

**Comment by fangyue1992** [comment]
Dear Carsen and Chriski,

Thank you for your reply. The tiffs are big so I put inside the following link.

https://entuedu-my.sharepoint.com/:f:/g/personal/fang0079_e_ntu_edu_sg/ElYfEoDyMxNEhq1MCAcAVqUBBN2GAxKqSxCJUqk58Q_evw?e=h722cB

I make the link access to anyone, but would you like to let me know if you cannot access it? Thanks a lot for your help!

Best Regards,
Fang Yue

**Comment by chriski777** [comment]
Hey Fang Yue, thanks for sending the link! I can access it but for some reason, it seems all the frames are saved individually. Would it be possible to consolidate all the tifs into a single file?

**Comment by fangyue1992** [comment]
Dear Chris,

I changed them into 1 tiff file using ImageJ as in the link. Please let me know if this file doesn’t work. Before I all used these individual frames to run suite2p, so I am not sure whether it may be the reason but I guess most probably not? I will use this one tiff file to run again now.

https://entuedu-my.sharepoint.com/:f:/g/personal/fang0079_e_ntu_edu_sg/EkkH449GmkFIgjHcarMp5DsBMlP5b5v7MnSb3aPOECxQvw?e=u745kH

Thank you for your help!

Best Regards,
Fang Yue

**Comment by chriski777** [comment]
Hey Fang Yue, thanks! I can access/open the file perfectly fine. It shouldn't matter whether you use one tif file or a folder of individual frames for suite2p.

**Comment by chriski777** [comment]
Hey Fang Yue, would it be possible to remove the superimposed circle in the center and the black triangular(?) regions in the corners of the tif (the non-tissue background in the box I've selected)?
![Screen Shot 2020-07-22 at 11 58 11 PM](https://user-images.githubusercontent.com/10649054/88259494-42ac8b00-cc77-11ea-9b3b-b6d0d638a0c3.png)
There's a lot of movement in the recording and the registration process is having trouble with aligning the moving tissue and the stationary black circle/corner parts.

Out of all the parameters I've tried modifying, I saw the best results (registration metrics-wise and visual inspection-wise) with just increasing `smooth_sigma` to 2.0. Even then though, the metrics showed that the top PCs still contained a lot of motion from the inner circle and black corner edges. So, I'd recommend removing the circle and the triangular regions if possible.

**Comment by fangyue1992** [comment]
Dear Chris Ki,

Thanks a lot for helping me debug and your recommendations! Yes, I believe that removing these things will solve the problem. But my side’s problem is that our 2-photon system currently can image fattest (8frames/s) at this spiral scanning mode which generate this tornado shape images. If I use normal scan it will generate the normal rectangle images, but the imaging speed is only 1frame/s if I want to have a relative large field of view and enough resolution. 1frame/s is too slow for Calcium imaging. This is the reason that I want to use this tornado-shape images to collect data. Is there any other possible solution to it? Thank you a lot!

Best Regards,
Fang Yue

**Comment by chriski777** [comment]
Hmm, I see. Have you tried increasing `smooth_sigma` to 2.0?

**Comment by fangyue1992** [comment]
> Hmm, I see. Have you tried increasing `smooth_sigma` to 2.0?

Hi Chris, i just tried, but still there are vibrations in between. May I look at other analysis tools? Do you have any recommendation?

**Comment by marius10p** [comment]
I've taken a look and I'm sorry but I don't think Suite2p can work well. This kind of imaging would require specialized registration tools to take into account the hole and corners, and I doubt they would be easy to do. If you have to use this, I'd recommend cutting rectangles like in the image and running each rectangle separately through suite2p using rigid registration only (nonrigid = 0). 

![image](https://user-images.githubusercontent.com/3935246/88358062-88cb2280-cd3b-11ea-9301-25035eb3a80b.png)

**Comment by chriski777** [comment]
Hey @fangyue1992, given what Marius said above, I'll be closing this issue. Feel free to reopen and comment if you have any questions for implementing what Marius suggested/ anything else!

**Comment by fangyue1992** [comment]
> Hey @fangyue1992, given what Marius said above, I'll be closing this issue. Feel free to reopen and comment if you have any questions for implementing what Marius suggested/ anything else!

Hi Chris, okay, i will try Marius idea, thank you so much for your help!
