### ISSUE TITLE
README page link is dead

### ISSUE THREAD

**Issue by bendichter** [MouseLand/suite2p#455]
The README links to a new GitHub page: https://mouseland.github.io/suite2p which is currently a dead link.

**Comment by nickdelgrosso** [comment]
Whoops!  Good catch, @bendichter.  Fixed!

**Comment by sneezeman** [comment]
The NEW detailed github page link that leads to https://mouseland.github.io/suite2p/ is also a 404

**Comment by chriski777** [comment]
Fixed in #457
