### ISSUE TITLE
backwards compatibility due to new key names

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#456]
there is a new key called 'spatial_hp_reg' and this means that old and new suite2p files won't play well together - can we revert to the old key name? there is no spatial_hp not for registration right now

**Comment by carsen-stringer** [comment]
ah now there are two -- ran into the second error running new files - 'spatial_hp_detect' needs to also have a catch statement

is there a reason to set these at different values?

**Comment by nickdelgrosso** [comment]
Hi, yes.  The spatial_hp key was used in two different places (registration and detection), which meant their behavior was coupled together (if spatial_hp needed to be increased for registering frames, then it would also result in increased blurring during the neuropil substraction step).  These are, at their core, different needs, so splitting them gives the user control over both parameters.

There may be a need for changes in ops keys in the future (whether new parameters, removed parameters, or simple name changes).  If backwards compatibility is needed between different versions of suite2p and their configuration files, maybe we could add a system for that?

**Comment by carsen-stringer** [comment]
good point -- I think we don't need to keep the keys backwards compatible - we would need too much mapping. I should have just run the new default_ops in my run_plane script and combined the dictionary (I'm currently parallelizing multiplane processing across cluster cores).

I very much like the idea of adding a version key to the ops dictionary!

**Comment by nickdelgrosso** [comment]
Added pull request #471, which makes it possible for suite2p to access its own version.  Once this is merged, we can add the version number to ops
