### ISSUE TITLE
Split ops configuration parameters into pipeline-specific configurations

### ISSUE THREAD

**Issue by nickdelgrosso** [MouseLand/suite2p#458]
Hi,

the ops dictionary contains quite a lot of parameters that can be quite overwhelming until the docs are studied.  Would it be possible to split up the parameters into smaller pieces, for example into parts that are pipeline-specific?  If a level of nesting was added, then ops could be split into seperate parameters for each of the steps in the pipeline.  

### Example

Instead of this:

- nonrigid: True
- blocksize: [128, 128]
- roidetect: True
- diameter: 12

It could be organized something like this:

- registration
  - nonrigid: True
  - blocksize: [128, 128]
- detection
  - roidetect: True
  - diameter: 12

### Benefits 

  1. ensuring clear functional separation between pipeline stages (no accidental reuse of a parameter)
  2. a simpler structure to handle within the stage (fewer parameters!)
  3. Easier to find the parameter you need
  4. (if implemented as a dataclass or similar): auto-documentation in sphinx and parameter validation upon read.
  5. direct mapping to the ops GUI view (which does split them into parts) from the data structure itself, ensuring that all the options available in the python library and command-line interface are automatically available in the GUI.

Would something like that be possible?

**Comment by marius10p** [comment]
We cannot do this, it will break everyone's configuration files. They are organized nicely in the GUI, which almost everyone uses, and they are organized in the docs (right?).
