### ISSUE TITLE
how to treat neuropil for dense extraction

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#46]
Sometimes the ROIs are packed so tight that there are few neuropil pixels left. This is not too bad, as it often happens when there is not a lot of neuropil contamination, perhaps as a consequence. We should still have a way to treat such dense recordings. There are a few options, in order of difficulty:

1) have explicit user-defined flag for processing a dense recording
2) detect dense recordings automatically and switch to dense mode automatically
3) integrate dense extraction seamlessly into the algorithm somehow

**Comment by Cumol** [comment]
I wonder if there is any suggestions to deal with dense recordings?

**Comment by Cumol** [comment]
ROIs of activate cells are not well detected in this example. The main issue is merging of ROIs into one big blob. This is not solved though reducing the bin size... In this particular example I ended up manually labeling 217 of the of the final 618 cells. Below is a zoom in with some examples 

![Screenshot 2020-03-26 at 18 25 26](https://user-images.githubusercontent.com/4943380/77689550-20914d80-6fa2-11ea-84d4-e77e8ac7d0e2.png)

![Screenshot 2020-03-26 at 18 27 25](https://user-images.githubusercontent.com/4943380/77689776-8aa9f280-6fa2-11ea-9cbe-b6d01d930407.png)

**Comment by carsen-stringer** [comment]
I don't think this recording is too dense for good neuropil correction, also in slice you may have less of a problem with neuropil.

**Comment by carsen-stringer** [comment]
this is now implemented, parameter associated with this is `ops['lam_percentile']`
