### ISSUE TITLE
Possible bug in reject_frames()? 

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#467]
In a recent suite2p run, the following error occured at this line: 
https://github.com/MouseLand/suite2p/blob/66a044ec270d135930bb706fcdcbe7af423f5bbd/suite2p/detection/utils.py#L27

`IndexError: index 954 is out of bounds for axis 0 with size 182`

suite2p version="0.8.0"

Do you have any idea what happened there?

**Comment by carsen-stringer** [comment]
sorry this has been fixed in the dev branch I'm going to pull it into master later today

**Comment by nickdelgrosso** [comment]
If it's fixed, then closing.

**Comment by horsto** [comment]
Thanks a lot, seems to be fixed!
