### ISSUE TITLE
Error when running Suite2p GUI on dev & master for Mac 

### ISSUE THREAD

**Issue by chriski777** [MouseLand/suite2p#475]
Trying to run suite2p via the GUI but this error pops up when using it. `Run_s2p` goes through all the stages but doesn't finish due to the error below which shows up at the beginning of the output. This error shows up for both versions of suite2p on master and dev. 

```
>>>ERROR<<<
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
```

This issue seems to be specific to Macs.

**Comment by nickdelgrosso** [comment]
May be an OpenMP or GCC installation issue (as discussed in this [thread](https://github.com/flatironinstitute/finufft/issues/55#issuecomment-555166829)).  I don't know why this would be specific to the GUI, though.

**Comment by chriski777** [comment]
Thanks, I'll take a look at that link. It's GUI-specific in the sense that this error interrupts the `run_s2p` command and doesn't load the stats.npy

**Comment by chriski777** [comment]
Hmm, so this ended up taking a long time to debug. 

It turned out that there were two versions of `tbb` being installed (via conda and pip). For some reason, pip was installing the wrong version of tbb (2019.0) on my Mac (pip installs the correct version on ubuntu...). It turns out this is also the case in the Mac environment for Travis. 

The fix was simply uninstalling tbb on pip and just relying on conda's tbb (which is installed as the correct version). I've added a PR that removes tbb from `setup.py`.

**Comment by nickdelgrosso** [comment]
Good catch, @chriski777 .  Looks like it's a much broader problem--there are many duplicate entries between the environment.yml and setup.py files (looks like it happened on commit 620214d).  Let's fix that here so that similar compatibility issues don't arise in the future.
