### ISSUE TITLE
Default classifier error with regression tests

### ISSUE THREAD

**Issue by chriski777** [MouseLand/suite2p#476]
If a user sets a default classifier using Suite2p's GUI, this overrides the `classifier_user.npy` file that is saved in .suite2p. If this classifier is different from the default classifier provided with suite2p, this will cause all regression tests that involve classification to fail.

**Comment by nickdelgrosso** [comment]
Good catch on the issue, @chriski777!  The pull request certainly reduces the issue with a workaround in the test side (as I understand it, but pre-copying the default somewhere else, then copying it back after the test is over), but I feel like it doesn't address the core problem--that when the default classifier is overridden, the original file is lost.  This is a problem for both user and developer, and it might be simpler to use a different approach and remove the problem entirely.

Does this make sense?  Could we try and see if we can find another solution, before adding this workaround?

**Comment by chriski777** [comment]
Yep, I agree with you. It also turns out that copying it over (at least with shutil.copy) leads to some truncation of the classifier file which just messes the user's classifier up...  suite2p actually has two "default" classifiers: one that the user sets: `classifier_user.npy` and the default one that comes with the package in `suite2p.classifiers`. So, overriding the user's classifier in the gui works as intended. The issue mainly rises when running the tests and the tests select the user's classifier instead of the default one that comes with the package. I managed to get a much simpler implementation working and have pushed the commits to the PR #477.

**Comment by carsen-stringer** [comment]
wait so should we not be using shutil.copy for the classifier when initializing the user's classifier? this naming is confusing - there is a "built-in" suite2p classifier and a "default" classifier for the user, apologies if I messed up this naming convention somewhere

**Comment by chriski777** [comment]
Oh yeah, I think I got it completely wrong with shutil. Shutil.copy works fine and the truncation was probably introduced when I quit the tests before the teardown sequence happened

**Comment by carsen-stringer** [comment]
Ah thanks for letting me know I got very worried! :)

**Comment by chriski777** [comment]
Fixed in #477
