### ISSUE TITLE
small typo in run_s2p.py causing error

### ISSUE THREAD

**Issue by jpakan** [MouseLand/suite2p#478]
There is a small typo (bracket out of place) in the code to print the time in run_s2p.py line 338-340 causing an error when running.

`print('time {:4.2f} sec. Wrote {} files to binaries for {} planes').format(
                (time.time() - t0), ops['input_format'], len(ops1)
            )`

should be

`print('time {:4.2f} sec. Wrote {} files to binaries for {} planes'.format(
                (time.time() - t0), ops['input_format'], len(ops1)
            ))`

**Comment by nickdelgrosso** [comment]
Good catch, thank you @jpakan !

**Comment by chriski777** [comment]
Fixed in #479
