### ISSUE TITLE
Removal of print statements in library

### ISSUE THREAD

**Issue by nickdelgrosso** [MouseLand/suite2p#481]
As a general rule, prints shouldn't be there at all in library functions.  There are a lot of print statements in the library which are serving various purposes:

  - **User Interface (for confirmation of successful action)**
           - example in rungui.py: `print('saved current settings to %s' % (name))`
           - example in gui.py: `print('ERROR: this is not a *.npy array :( ')`

  - **Logging (for reporting behavior)**
           - example in io.sbx.py: `print('Removing {0} dead columns while loading sbx data.'.format(ndeadcols))`
  
  - **Error reporting (for informing that something has gone wrong or undesirably)**
           - example in run_s2p.py:  `print("WARNING: skipping spike detection (ops['spikedetect']=False)")`
           - old example that has been removed, but still illustrates the idea: `'print(ERROR: best scale was 0, everything should break now!')`

  - **Debugging (for checking that a value is correct and that code works correctly)**
           -  example in io.utils.py:  `print(input_format)`
           -  example in io.utils.py: `print(fold_list)`
           - example in io.binary.py: `print(size)`

  - **Performance metrics (how long did it take to run a step):**
           - example in run_s2p.py: `print('time {:4.2f} sec. Wrote {} files to binaries for {} planes'.format( (time.time() - t0), ops['input_format'], len(ops1) ))`
           - example in detection.detect.py: `print('Binned movie [%d,%d,%d], %0.2f sec.' % (mov.shape[0], mov.shape[1], mov.shape[2], time.time() - t0))`
           - example in io.tiff.py (done in a loop): `print('%d frames of binary, time %0.2f sec.' % (ik, time.time() - t0))`

My proposal is:

  -  to remove the debugging print statements (some discussions of using prints for debugging and alternatives can be found [here](https://realpython.com/python-print/#print-debugging), [here](https://www.infoworld.com/article/2074974/are-you-still-using-print-statements-for-debugging-.html), and [here](https://inventwithpython.com/blog/2012/04/06/stop-using-print-for-debugging-a-5-minute-quickstart-guide-to-pythons-logging-module/)).  

   - To change warnings and errors in print statements to python errors that are raised (and caught, if the program can handle them) and warnings that are raised (using the built-in [warnings](https://docs.python.org/3/library/warnings.html) module).

   - To keep the user interface print statements, but ensure they are only present in the gui code (which, for the most part, they already are)

   - To keep the logging print statements, but they are only present in the application code (i.e. at the moment, essentially run_s2p() function).  Mainly this means moving things up from the io module to the run_s2p function.

   - To move the performance reporting up to the application code and use a more-informative progress tracker like [tqdm](https://tqdm.github.io/).  Besides providing details on performance, this will make it easier for users to estimate when a certain step will be completed, keep the performance prints on a single line on the console.  It will also allow users and devs to silence it when they want a simpler log, or when they want to do clean benchmarking tests.

This will keep a clean division between suite2p's usage as a library and an application, and make it simpler to provide informative and easy-to-understand message logs during analysis.

**Comment by marius10p** [comment]
A lot of those print statements are sanity checks that are good to see every time. They confirm to the user that the right data formats and shapes are found, that cells are found, that the code is still running as fast as it should etc. They should all stay on by default, but some additional text should be added to them if they are not sufficiently informative.

**Comment by nickdelgrosso** [comment]
Right.  I'm not disputing the importance of presenting the user with that information, it's mainly a code reorganization that I am suggesting here.  Aside from removing minor debugging data (which is often only there because it was added during coding and forgotten to be removed when committing), the only changes are the location (to application-level code) and library usage (raise, warnings.warn(), and tqdm) of prints for different purposes.

**Comment by marius10p** [comment]
The print statements inside the functions also give a sense of progress, in a way that tqdm wouldn't be able to report. For example, the first 1000 cells extracted in detection usually take as long as the next 5000, and this depends on the user's data. Other functions combine different types of steps, which have different relative run times on different types of data, and which can each independently go wrong. Without the log for fine timings, a user wouldn't be able to do comparisons between versions of suite2p or between different datasets. 

Library useage for raising warnings is fine. I am not sure what you mean by debugging data, those might be the quantities that we need to add more text to describe.  These are not there to check that the code is correct, they are to check that a user's data and settings are correct, and only the user can know that.

**Comment by nickdelgrosso** [comment]
Okay, it sounds like this issue can be closed.  Thank you for the discussion!
