### ISSUE TITLE
using bad_frames

### ISSUE THREAD

**Issue by dkushinsky** [MouseLand/suite2p#490]
Hi,

I have a number of recordings where "bad_frames" where identified by the software. Do these frame numbers get saved so that I may use them in my further analysis? How can I access this information?

Thanks, and thanks for the awesome software!

**Comment by nickdelgrosso** [comment]
Hi @dkushinsky ,

Yes, the frame numbers get saved as an array of True/False values indicating whether the frame was a "bad_frame", one for each frame.  This can be found in the `ops.npy` file under the key "badframes".

Some information can be found on this in the [FAQ Section of the Online Docs](https://suite2p.readthedocs.io/en/dev/FAQ.html#cropped-field-of-view).  We're also in the process of making a notebook that demonstrates some simple ways to interact with this data, which can be found here:  https://github.com/MouseLand/suite2p/blob/pipeline-notebook/jupyter/Run%20Suite2p.ipynb
