### ISSUE TITLE
sampled_mean function #418 - code not updated

### ISSUE THREAD

**Issue by ayallavi** [MouseLand/suite2p#492]
Hi,

First of all - thank you for this amazing tool - it is so useful!

I just wanted to let you know I downloaded the code 10 days ago and '.util' is still missing in line 261 of run_s2p.py.

Thank you,
Ayal

**Comment by nickdelgrosso** [comment]
Hi @ayallavi,

Thank you for your bug report!  Following up on it, I'm not able to find the source of the error, as the latest version of the software  (updated 7 days ago) doesn't reference .util in run_s2p (on [that line](https://github.com/MouseLand/suite2p/blob/d08f1a82561330d45142c0b6192ec779254e4533/suite2p/run_s2p.py#L261) or elsewhere in the file.)

There may be an out-of-date installation on your system or a duplicate installation--sometimes two different versions of a package can be installed, with the older version of the package "hiding" the newer version.  If you could try making a new conda environment and installing it fresh (terminal code snippet below), could you confirm that the error still comes up, and copy the full output into the issue for us?  It will make it easier to diagnose and fix.

```
conda env remove -n suite2p
git clone https://github.com/MouseLand/suite2p
cd suite2p
conda env create -f environment.yml
conda activate suite2p
pip install suite2p
```

**Comment by nickdelgrosso** [comment]
This discussion seems to have gone stale.  Closing it now.  @ayallavi , feel free to re-open it if you have new information.
