### ISSUE TITLE
stuck in spike deconvolution

### ISSUE THREAD

**Issue by katjaReinhard** [MouseLand/suite2p#497]
I have a relatively long recording and suite2p always gets stuck in the spike deconvolution step. It doesn't seem to be a memory or CPU issue and it happens independently of whether I have 5 or 500 ROIs. Do you have an idea what the problem might be? Is there a possibility to run only the deconvolution on data sets that got stuck there so I don't always have to redo all the previous steps?

**Comment by carsen-stringer** [comment]
Hey Katja what version of suite2p are you running? We recently switched from using multiprocessing (which was bad and hung a lot like you described) to numba (which is hopefully less error prone and faster :)) 

To run only deconvolution, check out this doc page: https://suite2p.readthedocs.io/en/latest/deconvolution.html

**Comment by katjaReinhard** [comment]
Hi Carsen,
Thanks for the fast reply! I think we installed it a few months ago, so might still the be older version. I'll look into this. Thank you!
