### ISSUE TITLE
Difference between ROI and masks

### ISSUE THREAD

**Issue by fangyue1992** [MouseLand/suite2p#499]
What is difference between **ROI shown in the GUI main page** and **view masks in the View registered binary page**? 
ROIs all look like neuron shape but many masks have only few pixels which didn't form a boundary.  The following picture shows one example, the neuron indicated by yellow arrow only have several pixels in masks and these pixels don't form a boundary. I wonder whether the traces show the fluorecence in these pixels of masks or fluorecence of ROI area?  Thank you! 
![Picture 1](https://user-images.githubusercontent.com/52596746/89532985-3ef73780-d825-11ea-9c85-9e9f736f46ca.png)

**Comment by nickdelgrosso** [comment]
@carsen-stringer

**Comment by fangyue1992** [comment]
> What is difference between **ROI shown in the GUI main page** and **view masks in the View registered binary page**?
> ROIs all look like neuron shape but many masks have only few pixels which didn't form a boundary. The following picture shows one example, the neuron indicated by yellow arrow only have several pixels in masks and these pixels don't form a boundary. I wonder whether the traces show the fluorecence in these pixels of masks or fluorecence of ROI area? Thank you!
> ![Picture 1](https://user-images.githubusercontent.com/52596746/89532985-3ef73780-d825-11ea-9c85-9e9f736f46ca.png)

Another question about this picture is: the orange neuron, right at the left below direction of arrowed red neuron and can be seen in the ROI image on the right, cannot be seen on the masks on the left image?

**Comment by Moosehorse123** [comment]
Also having this issue, but it seems to be especially an issue with manually drawn ROIs. They don't show up properly in the registered binary page.

**Comment by carsen-stringer** [comment]
I think this should be fixed, please let me know if not
