### ISSUE TITLE
.TIF vs .tiff prevents Suite2p from running in RedHat

### ISSUE THREAD

**Issue by lensjok** [MouseLand/suite2p#502]
Have been running Suite2p on Windows for a while with no issues. We recently set up an analysis computer running on RedHat, and here it turns out Suite2p needs a specific file extension to read the files. Our output format from imaging is ".TIF" and in Suite2p on RedHat we get 'Error: could not find any tiffs.' when using this extension. The same files are read and working on Windows.
When I change it to .tif or .tiff everything works. Anyone else seen similar issues? 
We currently generate >100 such files per day with imaging to not go above the 4GB file size limit, so hoping its possible to have the files read correctly with any version of the .tif extension.

Thanks!

**Comment by nickdelgrosso** [comment]
Hi @lensjok , looks like .TIF is not in the list of searched file extensions:

https://github.com/MouseLand/suite2p/blob/d08f1a82561330d45142c0b6192ec779254e4533/suite2p/io/utils.py#L148-L155

**Comment by nickdelgrosso** [comment]
I guess it's because linux is case-sensitive always, and windows not so much regarding file extensions.  Good catch, @lensjok !  I've added a pull request that should fix this issue in the next suite2p release.

**Comment by chriski777** [comment]
Fixed in #504 which has been merged to dev. Closing.
