### ISSUE TITLE
enhanced image 

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#52]
Add this computation to the pipeline, rather than during GUI set up, which is slow.

**Comment by marius10p** [comment]
This slows down loading every time which is annoying. I should fix it asap.

**Comment by marius10p** [comment]
It also uses a ton of RAM for large combined views, so it should be done tile by tile in that case, i.e. assembled from the individually enhanced mean images.

**Comment by carsen-stringer** [comment]
once you do this, please give me an example dataset to test in GUI

**Comment by marius10p** [comment]
I tested, it works. if meanImgE is not a key in ops, then it recomputes it. Something is still slow when loading mesoscope data with 20,000 ROIs.
