### ISSUE TITLE
'date_proc' is empty list?

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#523]
The attribute `ops['date_proc']` (potentially quite useful!) is an empty list before opening the suite2p output in the GUI and afterwards. What is the intended behavior?

**Comment by nickdelgrosso** [comment]
Hi @horsto,

`ops['date_proc']` should contain the date and time that the analysis was run.  However, when it gets saved to `ops.npy`, it is currently being overwritten to an empty list.  

This is most certainly a bug.  Good catch, @horsto! I'll fix it now and add a description to the docs.

Best wishes,

Nick

**Comment by horsto** [comment]
Thanks, Nick!
