### ISSUE TITLE
Any plans for manual classification of red cells through the GUI? 

### ISSUE THREAD

**Issue by nmlynaryk** [MouseLand/suite2p#528]
I see that we can currently view the "mean img chan2" and the "mean img chan2, corr" (this looks like max projection?), and you can change the threshold for calling a cell RED with the number next to the chan2 prob button (though this doesn't produce major changes to my data so far), but I'm wondering if there are any plans to be able to edit the redcell.npy file directly through the GUI, in the same way we edit the iscell.npy by moving cells to the left or right panel? A separate set of panels to manually classify detected ROIs as red or not could be very useful.

**Comment by marius10p** [comment]
This was a feature in the Matlab version that we should be able to bring back, but it'll probably have to wait a bit.

**Comment by Diegoalvarezar** [comment]
Just a remainder that this would be very useful!
Thanks!
Diego

**Comment by marius10p** [comment]
Could you please try to implement it yourself and contribute it back to Suite2p as a pull request?

**Comment by marysethomas** [comment]
Made a pull request here: https://github.com/MouseLand/suite2p/pull/785
