### ISSUE TITLE
Question about outputs (F, spks,...)

### ISSUE THREAD

**Issue by tiago-nyc** [MouseLand/suite2p#530]
Hi

I have some questions about the output files. Feel free to tell me off if this is well described in the Suite2p paper, but I couldn't quite find the answers to this.

For the fluorescence (F): Is this raw fluorescence or deltaF/F and what are the output units? I take it that this data is not neuropil subtracted? Is there any baseline correction?

For the spikes: Are these arbitrary units? How do they relate with deconvolved firing rates in Hz (Yaksi & Friedrich 2005)?

Many thanks

Tiago

**Comment by marius10p** [comment]
This is raw fluorescence, i.e. a weighted average of the pixels inside the ROI. The neuropil is in Fneu.npy, take a look here: https://suite2p.readthedocs.io/en/latest/outputs.html. There is no baseline correction, but there is a dcnv.preprocess function that can do that (see [here](https://suite2p.readthedocs.io/en/latest/api/suite2p.extraction.html)). Finally, the spikes are deconvolved assuming a unit-norm response function, so more or less arbitrary units. There is no relation implied to firing rates in Hz, and there is currently no way of obtaining such information from current generaiton calcium sensors.

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!

**Comment by tiago-nyc** [comment]
Thanks for your reply, Marius!
