### ISSUE TITLE
another question regarding the output

### ISSUE THREAD

**Issue by annie2013** [MouseLand/suite2p#531]
I have run suite2p using python version and saved the output to .mat file. 

I am now trying to plot the corrected mean image in matlab. In your previous matlab version of suite2p, I need to correct the image position using ops.DS. However, the variable is no longer there in the new python version. Do I assume it is now ops.xoff and ops.off instead? Is there any other parameters involved?

thanks,
Guifen

**Comment by marius10p** [comment]
I am not sure what you're trying to do. All the outputs of suite2p are on registered movie data. If for any reason you need them in the original coordinates, you need to look at the registration offsets, i.e. xoff and yoff. Those are discrete pixels offsets (there are also nonrigid, sub-pixel offsets in there).

**Comment by annie2013** [comment]
I am trying to understand the registration offsets, so that I can replot
the mean images based on your image registration unless you have saved the
registered/offseted images somewhere (I meant each individual frames of
images).

I assume xoff and yoff are the offsets for the entire image, since they are
both 1xn arrays and n= the total frame number.

Where can I find the variables for the nonrigid offsets?

Thanks,
G

**Comment by marius10p** [comment]
Sorry, this does not clarify to me what you're trying to do, can you please explain what it is for? The mean image has already been "registered", because it is computed as the average of all frames *after* registration.

**Comment by carsen-stringer** [comment]
Sorry Guifen we can't see the attached image. If you are worried that registration is doing poorly, I'd recommend looking at the registration metrics and at the registered binary in the GUI. I'm going to close this issue for now but please comment with questions (and images) and we'll answer
