### ISSUE TITLE
Controlling number of threads

### ISSUE THREAD

**Issue by xiaonansun** [MouseLand/suite2p#532]
Hello,

I am currently running suite2p on our institution's HPC and the systems administrator is complaining that suite2p is setting off more than 100 threads (even though my bash script specifies 16 threads). Is there anywhere in the code for me to change the number of threads to be used?

Thank you for your help,

Richard

**Comment by nickdelgrosso** [comment]
Hi @xiaonansun ,

We don't have any interfaces currently for controlling the number of threads in suite2p, and it's not specified in our code anywhere.  Depending on your institution's HPC system, they may have some way to enforce a limit of thread number for your job.  Perhaps your systems administrator can help with this?

**Comment by xiaonansun** [comment]
Hi Nick,

Thank you for the response. I have tried several methods (e.g. core binding) in limiting the number of threads activated on the HPC but unfortunately I haven't had any success so far. It appears to me that the most likely culprit is numpy used during the [registration](https://github.com/MouseLand/suite2p/blob/d1c5d514fdd71b31e0a5893301d6295ce94a657f/suite2p/registration/register.py) phase of the pipeline. And it seems like this (https://github.com/joblib/threadpoolctl) library may help with this issue. Do you have additional intuitions into which other libraries utilized by suite2p may be multithreaded?

Thank you,

Richard


> Hi @xiaonansun ,
> 
> We don't have any interfaces currently for controlling the number of threads in suite2p, and it's not specified in our code anywhere. Depending on your institution's HPC system, they may have some way to enforce a limit of thread number for your job. Perhaps your systems administrator can help with this?

**Comment by nickdelgrosso** [comment]
Hi @xiaonansun,

The fft2 and ifft2 functions from mkl_fft, used in the [registration.utils](https://github.com/MouseLand/suite2p/blob/main/suite2p/registration/utils.py) module are certainly multithreaded, as may be the numba functions in the same module.  The image filtering functions from scipy-ndimage in the detection subpackage may also be multithreaded, but I'm not sure about that.

Great find on the [threadpoolctl](https://github.com/joblib/threadpoolctl) library, that seems to me like a good potential solution.  One approach may be to use it directly on the main `suite2p.run_s2p()` function in your own python script order to limit the threads for the whole pipeline.  Something like this, for example, might work:

```python
from threadpoolctl import threadpool_limits

with threadpool_limits(limits=10, user_api='blas'):  
    suite2.run_s2p(ops=my_ops)
```

When running the treadpool_info() function as described in the readme threadpoolctl file after importing suite2p:

```python
import suite2p
from pprint import pprint
from threadpoolctl import threadpool_info

pprint(threadpool_info())
```

 I get this:
```
[{'filepath': 'D:\\miniconda\\envs\\suite2p\\Library\\bin\\mkl_rt.dll',
  'internal_api': 'mkl',
  'num_threads': 4,
  'prefix': 'mkl_rt',
  'threading_layer': 'intel',
  'user_api': 'blas',
  'version': '2019.0.3'},
 {'filepath': 'D:\\miniconda\\envs\\suite2p\\Library\\bin\\libiomp5md.dll',
  'internal_api': 'openmp',
  'num_threads': 4,
  'prefix': 'libiomp',
  'user_api': 'openmp',
  'version': None},
 {'filepath': 'C:\\Windows\\SYSTEM32\\VCOMP140.DLL',
  'internal_api': 'openmp',
  'num_threads': 4,
  'prefix': 'vcomp',
  'user_api': 'openmp',
  'version': None}]
```

Total that looks like 12 threads, but it could be more.  At the very least, it shows that you might need to test the `threadpool_limits` function out with both the `'openmp'` and `'blas'` user_api options and see if either of those works best.  I'll be interested to know your findings!

Best wishes,

Nick

**Comment by carsen-stringer** [comment]
I'm going to close this due to inactivity, please comment if you're still having issues with this

**Comment by jmdelahanty** [comment]
Hello @schloegl ! I was wondering if you could help me with this thread specification. I exported the OMP_NUM_THREADS variable like so in my `bash.rc` file:

`export OMP_NUM_THREADS=3`

When I check in my command line, it looks like it did indeed work:

```
echo $OMP_NUM_THREADS
OMP_NUM_THREADS=3
```

Suite2p is still using up all the cores available on the server I'm messing around on.


Any advice on how to limit it properly?

**Comment by schloegl** [comment]
Did you add the line 
   import threadpoolctl
as indicated above ? That was sufficient for me.

**Comment by jmdelahanty** [comment]
I did add that, but still no luck it seems. There might be something about the server that doesn't interact well with threadpoolctl maybe... I'll ask our IT admin and see what they say.
