### ISSUE TITLE
Updating both channels when merging ROIs

### ISSUE THREAD

**Issue by hmacomber** [MouseLand/suite2p#535]
Hi,

Thank you for making and maintaining Suite2p, it's been an incredible tool for my research. I record axons in two channels, a dynamic green and a static red, which I use to check my recordings against small Z-plane movements. After recording, I merge together a number of ROIs that are clearly part of the same axonal structure both using automerge and manual merging before further analysis, and append these merges to the end of the tile. However, I've noticed that the second channel's F_chan2.npy doesn't similarly update, and I can't find a record of what original ROIs I merged anywhere in the Suite2p outputs to be able to accordingly update the red, making it impossible to use the red channel as I had hoped and also use suite2p's ROIs merge feature. Would it be possible to add a setting so that both channels of a recording can be updated after appending merges? 

Thanks again for making this great tool!
Heather

**Comment by carsen-stringer** [comment]
thanks for noticing this, this has been added to the dev branch to use it,
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```

btw the original ROIs that are merged are in the key 'imerge': `stat[-1]['imerge']`. I've added this info to the documentation.
