### ISSUE TITLE
cannot run a new suite2p trial after changing the classifier (" Invalid argument: 'ops0.npy'")

### ISSUE THREAD

**Issue by or-naim** [MouseLand/suite2p#536]
Hi,

So I tried to play a bit with the default classifier and add some new manual labeled data to it. Unfortunately after I'm doing so, I cannot run a new suite2p trial, and get the following error right after I click "run suite2p": 

`Traceback (most recent call last):
  File "c:\users\orna\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 371, in run_S2P
    self.add_ops()
  File "c:\users\orna\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 340, in add_ops
    np.save('ops%d.npy'%L, self.ops)
  File "c:\users\orna\anaconda3\envs\suite2p\lib\site-packages\numpy\lib\npyio.py", line 524, in save
    fid = open(file, "wb")
OSError: [Errno 22] Invalid argument: 'ops0.npy'
loaded default ops`

I tried to reset the default classifier to the built-in one, but nothing seems to change. 

Thanks

**Comment by nickdelgrosso** [comment]
Looks like there is some problem with the filename "ops0.npy" in the built-in open() python function, though I don't currently see why.  It doesn't look like a permissions issue or anything.

**Comment by nickdelgrosso** [comment]
Okay, this seems to be related somehow to the recent ops issue--perhaps the "ops0.npy" filename is getting contaminated somehow during a bad save.  Updating to the latest dev version (should be in the next release may solve this problem)  https://github.com/MouseLand/suite2p/issues/534

**Comment by or-naim** [comment]
Many thanks! Will try to update and check this out again afterwards.

**Comment by carsen-stringer** [comment]
Is this working now? I'm going to close the issue due to inactivity but let us know if there are still problems

**Comment by or-naim** [comment]
Unfortunately it didn't :/ But I will try again tomorrow and see if anything has changed. Many thanks.

**Comment by carsen-stringer** [comment]
I think your default ops is filled with neuropil_masks now? I've added a button to `revert default ops to built-in` in the run GUI

**Comment by or-naim** [comment]
Hmmm perhaps. I'll give it a try, thanks! (By the way should I update to see it?)
