### ISSUE TITLE
Mean images empty?

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#541]
Hi, I noticed that in my latest suite2p runs, mean images (in GUI: `mean img`, `mean img (enhanced)`, `mean img chan2, corr`, `mean img chan2`) are all empty (all zero), while other images (in GUI: `correlation map`, `max projection`) do have appropriate content. Any idea what that could be?

**Comment by horsto** [comment]
This seems to specifically happen when `nchannels = 2` and` align_by_chan = 2` is chosen.` align_by_chan = 1` runs through fine (and contains all mean images in first and second channel).

**Comment by carsen-stringer** [comment]
oops forgot to respond but I fixed this in release v0.9.2 - let me know if it's still buggy
