### ISSUE TITLE
Input format error

### ISSUE THREAD

**Issue by neuralPatterns** [MouseLand/suite2p#545]
Hello,
I updated to the current version of Suite2p and I’m now unable to load tiffs under the bruker input_format option. If I concatenate frames and run with tiff input_format the pipeline runs normally. Loading tiffs under the bruker input_format option wasn’t an issue with my previous versions of Suite2p. Please see error below.
Thanks!

** Found 6000 tifs - converting to binary **
>>>ERROR<<<
Traceback (most recent call last):
  File "…suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "…suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "…suite2p\__main__.py", line 78, in <module>
    main()
  File "…suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "…suite2p\run_s2p.py", line 372, in run_s2p
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "…suite2p\io\tiff.py", line 402, in ome_to_binary
    ops1[ix]['meanImg'] += im
TypeError: Cannot cast ufunc add output from dtype('int32') to dtype('uint16') with casting rule 'same_kind'
Interrupted by error (not finished)

**Comment by nickdelgrosso** [comment]
Hi @neuralPatterns,

This is definitely an issue.  Thanks for the bug report; we'll get this fixed.

Best wishes,

Nick

**Comment by carsen-stringer** [comment]
this has been fixed on the dev branch, to use it
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```
