### ISSUE TITLE
How to get first image in registered binary?

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#549]
I was to get the first image of the registered binary (to use for cellpose) instead of the mean image as the mean image can sometimes be a little blurry due to z-drift etc.

I tried to find the answer in the code but couldn't figure out how the GUI accesses the registered binary and plots the image.

**Comment by nickdelgrosso** [comment]
Hi @Cumol,

To get the first image of a suite2p binary file in Python for 512 x 512 frames, the following code will work:

```python
from suite2p.io import BinaryFile

f = BinaryFile(Ly=512, Lx=512, read_filename="mybinaryfile.bin")
first_frame = f.read()
f.close()
```
`BinaryFile` is a pretty flexible class.  This will also work:

```python
with BinaryFile(Ly=512, Lx=512, read_filename="mybinaryfile.bin") as f:
    first_frame = f[0]
```

**Comment by Cumol** [comment]
Thanks, will try it out and report

**Comment by Cumol** [comment]
@nickdelgrosso had to correct the call `first_frame = f.read()[1]` instead as for some reason doing `f.read()` alone resulted in a list of two arrays. The first was empty and the second contained the correct image.

**Comment by nickdelgrosso** [comment]
whoops, that's right.  Good catch!  In batch reads, the first one will contain the indices of the data.

**Comment by Cumol** [comment]
A small follow-up. 

Is there a smarter way to calculate mean or standard deviation of each x/y pair over the whole video apart from turning the binary into a numpy file and then using numpy?

**Comment by nickdelgrosso** [comment]
Perhaps; you could do a running-mean approach with multiple chunked reads from the binary file, but that may not actually speed up your code.  Unless you're running out of memory, just loading it into numpy is usually both fast and straightforward.  There's also [numpy.memmap](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html), which can sometimes be a good way to do out-of-ram computations on numpy array-like objects, and there's [Dask Array](https://docs.dask.org/en/latest/array.html),  which is similar but can chain operations together.  But the parsimonious approach is probably just to load it as a normal numpy array.
