### ISSUE TITLE
Is there a way to know why an ROI was selected as a "bad" ROI?

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#555]
Hi Carsen,
After the automated ROI selection, I will be manually cleaning up the ROIs by switching the "good" ROIs from the "bad" ROI list and vice versa. However, I would like to do the manual ROI selection based on specific parameters, rather than just eye-balling the calcium transients to make the decision. Is there a way to know why an ROI is listed as "bad"? Is there a way to know which parameters were failed by a ROI to end up on the "bad" ROI list? 

The question would apply in reverse as well. What parameters were passed by a "bad" ROI to fall under the "good" ROI list?

Or, maybe there is a different way of approaching the manual ROI clean up? If so, what do you suggest?
Thank you!
Sarah

**Comment by CedricStefens** [comment]
Hey,
All the properties of components are present in stat.npy. If I'm not
mistaken, the properties used for the classifier are only spatial
attributes. It is possible to populate stat.npy with signal-related quality
metrics like number of evoked responses, peak signal to noise ratio,
entropy, fit to a bimodal distribution (first bell is baseline points,
second bell is event points), et cetera.

You can sort the components by any metric and decide of a cut-off for that
metric to classify components as bad. e.g. iscell [ np.where( metric <
cutOff )[0], 0 ] = 0 , effectively putting these cells as "bad".

It's in my to-do-list, here's my starting point, you can explore each
metric for all cells, sorted or unsorted:

def doubleScalePlot(data1,data2,name1="name1",name2="name2",color1=
'tab:blue',color2 ='tab:red' ,xlabel='',alpha=0.8):
    if isinstance(data1, list):
        t = np.arange(data1[0].shape[0])
    else:
        t = np.arange(data1.shape[0])
    fig, ax1 = plt.subplots()
    ax1.set_xlabel(xlabel)
    ax1.set_ylabel(name1, color=color1)
    if isinstance(data1, list):
        for data1_ in data1:
            ax1.plot(t, data1_,alpha=alpha)
    else:
        ax1.plot(t, data1, color=color1,alpha=alpha)
    ax1.tick_params(axis='y', labelcolor=color1)

    ax2 = ax1.twinx()  # instantiate a second axes that shares the same
x-axis
    ax2.set_ylabel(name2, color=color2)  # we already handled the x-label
with ax1
    if isinstance(data2, list):
        for data2_ in data2:
            ax2.plot(t, data2_,alpha=alpha)
    else:
        ax2.plot(t, data2, color=color2,alpha=alpha)
    ax2.tick_params(axis='y', labelcolor=color2)
    #remove blank space left and right of trace
    ax1.margins(0,0)
    ax2.margins(0,0)
    fig.tight_layout()# otherwise the right y-label is slightly clipped
    plt.show()

def getMetricPerCellFromStat(ops,metricName="npix",dtype="float32"):
    stat=np.load(ops['save_path']+'/stat.npy',allow_pickle=True)
    metric=np.zeros(stat.shape[0],dtype=dtype)
    for i in range(stat.shape[0]):
        metric[i]=stat[i][metricName]
    return metric

#you need these:
opsPath="your path to ops.npy"
ops= np.load(opsPath,allow_pickle=True).item()
iscell = np.load(ops["save_path"]+'/iscell.npy')
metricsToCheck=['compact','npix',"radius","aspect_ratio","skew","std"]

###figures that gives metric and classification probability for each
components

#components are sorted according to the probability in iscell[:,1]
# for metricName in metricsToCheck:
#     metric=getMetricPerCellFromStat(ops,metricName)
#     data1 = np.sort(iscell[:,1])
#     data2 = metric[np.argsort(iscell[:,1])]
#     doubleScalePlot(data1,data2,name1="isCell prob",name2=metricName)

#components unsorted
# for metricName in metricsToCheck:
#     metric=getMetricPerCellFromStat(ops,metricName)
#     data1 = iscell[:,1]
#     data2 = metric
#     doubleScalePlot(data1,data2,name1="isCell prob",name2=metricName)

#components are sorted according to the metric
for metricName in metricsToCheck:
    metric=getMetricPerCellFromStat(ops,metricName)
    data1 = iscell[np.argsort(metric),1]
    data2 = np.sort(metric)
    doubleScalePlot(data1,data2,name1="isCell prob",name2=metricName)

Best regards

Le mer. 14 oct. 2020 à 18:32, sarahapark <notifications@github.com> a
écrit :

**Comment by sarahapark** [comment]
Hi Cedric!
Thanks for your reply. I think it would be great to be able to see the
parameters that determine a "good" cell and "bad" cell. I am familiar with
MatLab but not python. It will take a bit for me to read your python code.
Any chance we can get on a call and you can explain your code? If not, I
can work on reading your code.

Thank you!
Best regards,
Sarah
