### ISSUE TITLE
Baseline subtraction and neucoeff estimation while deconvolving spikes

### ISSUE THREAD

**Issue by JanakiSheth** [MouseLand/suite2p#556]
Hi,

I am new to suite2p and have been looking at both the matlab (because my lab uses this) and python - v0.9.2 - versions (because this seems to be the more updated version).

I am having trouble understanding the role of subtracting baseline and the role of neuropil coefficients for spike deconvolution. Moreover, since most of the pipeline has already been run, I am primarily only working with the stand-alone code for the deconvolution. In Matlab, in wrapperDECONV, 
```
if getOr(ops, 'estimateNeuropil', 0)
    niter = 5;    
    ops.runningBaseline = 0;  
else
    niter = 1;
end
```
with default ops.runningBaseline = 0 

with ops.estimateNeuropil = 1, this would imply that the final spikes are obtained without subtracting any drift in the F (cell) trace, but the neucoeffs would differ across neurons based on the reconstruction of the individual Ca trace.  If ops.estimateNeuropil = 0, then neucoeffs are not updated and we use default values, also we don't subtract any drift baseline.

In python, in suite2p.run_2p and suite2p.extraction.dvnc.preprocess,
```
dF = F - ops['neucoeff']*Fneu
            dF = extraction.preprocess(
                F=dF,
                baseline=ops['baseline'],
                win_baseline=ops['win_baseline'],
                sig_baseline=ops['sig_baseline'],
                fs=ops['fs'],
                prctile_baseline=ops['prctile_baseline']
            )
            spks = extraction.oasis(F=dF, batch_size=ops['batch_size'], tau=ops['tau'], fs=ops['fs'])
```
Also I don't see the ops['neufoeff'] being updated anywhere, which seems to be as though the above code uses the default value of 0.7.
This would imply that the spikes are obtained by subtracting drift but with the same neucoeffs across all neurons.  

Since these are all three different methods, could you please help me understand what is the correct approach to take? I would personally think that ops['neucoeff'] should be updated for each cell and then one would subtract the baseline from  F - ops['neucoeff']*Fneu prior to executing extraction.oasis. Although updating ops['neucoeff']  as done in Matlab in wrapperDECONV requires detection of underlying spikes, those spikes are irrelevant and the correct deconvolution would be obtained post removal of baseline. I would also like to mention that another part of my analysis also uses dF and thus it would be helpful to know if ops['neucoeff'] should be a constant or variable across neurons. I am happy to write my own custom code but would like to make sure my understanding is complete.

**Comment by carsen-stringer** [comment]
You are correct that the python version of suite2p does not estimate the neuropil coefficient and instead uses the same coefficient for all traces. It is difficult to estimate the neuropil coefficient on a neuron-by-neuron basis (the matlab version had several failure modes), so we set it to a single value for all cells in the python version. After subtracting the neuropil we subtract the baseline to remove any slow drift in the fluorescence across time and as you've said this is important to do before running spike detection.
