### ISSUE TITLE
Module note found error during installation

### ISSUE THREAD

**Issue by tharmon0118** [MouseLand/suite2p#558]
Hello, I'm having trouble installing suite2p version 0.9.2. I've been following the instructions from https://pypi.org/project/suite2p/ . I downloaded the file repository and put it in a folder on my hard drive separate from my anaconda folder. I'm able to use the environment.yml file to generate the suite2p environment and to activate the environment. When I use the 'python -m suite2p', I get an error message:  

File "C:\suite2P\suite2p\version.py", line 1, in <module>
    from importlib_metadata import metadata as _metadata
ModuleNotFoundError: No module named 'importlib_metadata'

From the instructions at in the documentation (https://suite2p.readthedocs.io/en/latest/installation.html), I tried the installation using the command: pip install suite2p. This approach seemed to work, but I wasn't able to start the program (I got the same error message as above). When I entered 'suite2p --version', I got the same error. The installed files were in the anaconda3>envs>suite2p folder that was generated when I set the suite2p environment. I'm new to python, so any guidance you could give for troubleshooting from here would be useful. I'm using Python 3.7.9 and Anaconda 4.8.3. I added the anaconda folder to my PATH during installation. 

Thanks!

**Comment by nickdelgrosso** [comment]
Hi @tharmon0118,

I'm not sure why `importlib-metadata` isn't installed, as it's there in the 0.9.2 environment.yml file.   It sounds like you did all the steps correctly; something must be off.  Is the `suite2p` environment active when you call `python -m suite2p`?  

Also, if you could take a look inside that anaconda3/envs/suite2p folder and search for `importlib-metadata` (with either a hyphen or an underscore) and `suite2p`, (should be in the site-pacakges subfolder, but may be outside), we could confirm whether the library was fully installed in the conda environment or not.

Best wishes,

Nick

**Comment by tharmon0118** [comment]
Thanks for the reply. Just now, I was able to get the installation to work on a different computer, so this is no longer an issue. The first computer had some changes made to the operating system that might have been the issue. Regardless, I appreciate the help.

Tom

**Comment by nickdelgrosso** [comment]
Okay, great to hear!
