### ISSUE TITLE
merging ROIs in GUI doesn't make the same changes to F.npy and F_chan2.npy

### ISSUE THREAD

**Issue by rozmar** [MouseLand/suite2p#560]
After merging tow ROIs, suite2p appends the new merged ROI at the end of the ROI list in F.npy but for some reason F_chan2.npy doesn't change the same way. I made one merge and as a result, F_chan2.npy is 1 entry shorter than F.npy. Same for the neuropil traces.

**Comment by nickdelgrosso** [comment]
Hi @rozmar, 

This is certainly a bug; the chan2 data isn't mentioned in the merge function.  It seems to be happening inside the gui merge module.  

https://github.com/MouseLand/suite2p/blob/main/suite2p/gui/merge.py#L36-L164

Best wishes,

Nick

**Comment by carsen-stringer** [comment]
I've added this to the dev branch, I'm going to close this issue for now but please let me know if it's not working

to use dev branch
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```
