### ISSUE TITLE
Applying non-rigid transformation matrix on another session

### ISSUE THREAD

**Issue by ziyizhu1996** [MouseLand/suite2p#565]
I am aligning two sessions of the same FOV that I recorded a week apart. My solution is to first align within each session (alignment #01), then align the reference images of each session using non-rigid alignment, using session 1 as reference (alignment #02), and finally apply alignment #02 on aligned movie of session 2 (in alignment #01). 

Q1: Do you know how I can revise the code so that I can save transformation matrix of alignment #02 and apply it onto each frames of the movie of session 2?

Q2: I have revised my local runs2p functions to allow alignment given a user-defined reference image. Would you include such functionality in your future release?

Here is a more detailed description of my issue:

I am aligning two sessions of the same FOV that I recorded a week apart. The first approach is to process these two sessions together in suite2p, using non-rigid alignment to correct for changes in the shape of the brain. Example mean image of each day (before non-rigid registration) is below (you can see that there are some changes in the shape of the brain) :

![meanImg_session](https://user-images.githubusercontent.com/26942783/97118394-08241580-16e0-11eb-94d2-cee43965be0c.gif)

When I directly align the movie of the two session together, suite2p tends to produce reference image of session 1, and align session 2 to that reference image. The alignment of session 1 is good; the problem is that the alignment of session 2: while the center of the image is usually properly aligned, non-rigid alignment often introduce additional distortions in the surrounding areas. This happens with different non-rigid alignment parameter. In addition, I tried aligning the mean image of each session (i.e. 2 images shown above) using the same parameter, and the alignment of these 2 images are perfect. Thus, my solution is to first align within each session (alignment #01), then align the reference images of each session using non-rigid alignment (alignment #02), and finally apply alignment #02 on aligned movie of each session (in alignment #01). 

Thank you so much again for providing this software package!

**Comment by carsen-stringer** [comment]
rather than morphing the entire video could you instead morph the masks from one session to the next? we do not have plans to support this type of alignment ourselves, but are happy to take pull requests.

I've added a reference image option to run_s2p in the dev branch, that was a good idea to add it in general. To use it, save your reference image into the ops for your plane and set `ops['force_regImg']=True`. To run the dev branch
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```
