### ISSUE TITLE
Compute Z-position with different size/resolution stacks

### ISSUE THREAD

**Issue by chaplinta** [MouseLand/suite2p#568]
I just tried to see if I could compute the z-position of recording session using z-stack acquired with a different resolution. The z-stack is the full FOV of the microscope, the recording session uses a smaller FOV and a smaller pixel size. I ran into some errors and looking at the code it appears it is not really supported, there is some code in zalign.py that looks like it was going to pad the z-stack when the number of pixels don't match, but N is not defined and dsmooth goes unused:

`if Zreg.shape[1] != Ly or Zreg.shape[2] != Lx:
        # padding
        if Zreg.shape[1] > Ly:
            Zreg = Zreg[:, ]

        half_pad = N // 2
        dsmooth = np.pad(Zreg, ((0, 0), (half_pad, half_pad), (half_pad, half_pad)), mode='constant', constant_values=0)`

I was thinking though that supporting different resolutions might be a bit tricky to address in general and not a simple few lines of code to fix, so I was wondering if there is any plan to support this use case (presuming I have understood the code correctly that is). It seems it would be useful to acquire a big lower res z-stack that is larger than your intended FOV so you have a standard z-stack for all recording sessions (at least it is for me).

**Comment by nickdelgrosso** [comment]
Hi @chaplinta ,

That certainly seems like a useful feature!  Agreed that it's a bit tricky to get working.  The `zalign.py` module, however, is unused in the suite2p package, with no plans to incorporporate it into the workflow (you can visualize this [here](https://coveralls.io/builds/32867445/source?filename=suite2p/registration/zalign.py); yellow lines show the lines tested in our main pipeline tests, and red lines are skipped.  The zalign package is almost entirely excluded, while the [rigid registration](https://coveralls.io/builds/32867445/source?filename=suite2p/registration/rigid.py) module is entirely tested.)   As far as I understand, there's nothing in suite2p that addresses multi-resolution images, either; another interesting but complex feature.  

Contributions are very welcome, though!  I'll label this here as a feature request so it's included in future development discussions.  Thanks, @chaplinta !

Best wishes,

Nick

**Comment by carsen-stringer** [comment]
we do not have plans to support different resolutions, but supporting different sizes is certainly reasonable. I'm happy to accept a pull request where you implement the padding properly -- I had tiffs + Z-stack of the same size so didn't implement and test this functionality
