### ISSUE TITLE
question: can I change the blue color of the raw fluorescence trace

### ISSUE THREAD

**Issue by xujiajieon** [MouseLand/suite2p#569]
Hi Carsen, 

The blue raw fluorescence trace is difficult for me to see on a black background. Is there a place in the source code I can change the color to magenta or some other brighter color?

Thanks a lot!
Jiajie

**Comment by nickdelgrosso** [comment]
@carsen-stringer

**Comment by carsen-stringer** [comment]
good point, I've changed it to cyan on the dev branch
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```
