### ISSUE TITLE
get connected region

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#57]
Should bring this back as an option. Default is ON for cells, OFF for dendrites and other processes.

**Comment by marius10p** [comment]
This is now done twice: during refinement, just before dropping overlapping cells, and after refinement, just before computing overlaps.

**Comment by Cumol** [comment]
For some reason this option is not working anymore as I get ROIs like these:

Here is the same cell:
![Screenshot 2020-03-31 at 08 27 26](https://user-images.githubusercontent.com/4943380/78257053-a6108280-74f9-11ea-98f7-d0ac28a06141.png)
![Screenshot 2020-03-31 at 08 27 19](https://user-images.githubusercontent.com/4943380/78257069-ac066380-74f9-11ea-85f8-42774e522dfd.png)


And some other examples:
![Screenshot 2020-03-31 at 15 09 50](https://user-images.githubusercontent.com/4943380/78257030-9b55ed80-74f9-11ea-97c0-2775e9c93bd8.png)
![Screenshot 2020-03-31 at 08 58 10](https://user-images.githubusercontent.com/4943380/78257041-9f820b00-74f9-11ea-8976-cbf5f1e9cd56.png)
