### ISSUE TITLE
Empty meanImg_chan2 and can't get appropriate RED cells.

### ISSUE THREAD

**Issue by kassailattice628** [MouseLand/suite2p#570]
I'm running suite2p (v0.9.2) on the latest macOS Catalina.

I started to use red channel options and wanted to identify the "redcells". My original images were taken by Olympus system and saved as tiff stacks by Fiji. There were no obvious errors in the console, but when I load stat.npy in the GUI there were no backgroud images in "mean img chan2.corr" and "mean img chane2".  The ops.meanImg_chan2 is zero-matrix in the Fall.mat.

I also have trouble with detecting red cells. The ops[chan2_thres] is very peaky. For example, ops[chan2_thres]: 0.999999970196 results all ROIs are indicated as redcell (= 1), 0.999999970197. One possible cause would be the difference of the brightness.  The red channel is 10 times brighter than the GCaMp channel. So I normalized these images by expanding their histogram and run the suite2p.  However the meanImg_chan2 was still zero matrix and couldn't detect redcells.

Does anyone knows the reason why chan2 option did not work well and the workaround of these problems?

**Comment by kassailattice628** [comment]
I tired Ubuntu. Unfortunately, I don't have available PCs, I linstalled Ubuntu20.10 on Virtualbox6.1 on my macbook pro (macOS Catalina10.15.7). The suite2p (0.9.2) environment were created with Anaconda3 as show in the manual, and running suite2p with newly acquired dataset (2-ch tiff image). Of course, suite2p GUI is nicely worked on this enviroment; however the "meanImg_chan2" was still empty. Image registration based on chan2-images would be work, but the identification of redcells did not work.

**Comment by kassailattice628** [comment]
I'm sorry, I closed this issue by mistake.

**Comment by carsen-stringer** [comment]
this has been fixed on the dev branch, closing for now, please comment if it's still not working
