### ISSUE TITLE
ROI 

### ISSUE THREAD

**Issue by LaureKCL** [MouseLand/suite2p#574]
Hi everyone,

on Suite2p interface after running the video we got numbers associated for each ROI. But when I open the F file and I plot the cells on a graph I don't see the same fluorescent traces compare to what I see on the Suite2p interface when I look for the same ROI number (example: cell n40 on the interface and 41 on the file, as the first ROI number is 0 on the interface). Does it mean that between the interface and the matlab file the ROIs don't have the same number?
Could you tell me if there is a way to find out who is who on the image and on the file?
And if there is a way to extract the ROI as Zip file to be able to see them with imageJ?

I hope it makes sense, 
thanks for your help,
Laure

**Comment by carsen-stringer** [comment]
Yes you are correct, python uses 0-based numbering so the first ROI is 0, but in MATLAB it would be 1. There is not currently an option to convert ROIs to imageJ format, but we are happy to incorporate pull requests with conversion code.
