### ISSUE TITLE
Multiple issues using two-channel data

### ISSUE THREAD

**Issue by rswilliamson** [MouseLand/suite2p#575]
Hi guys,

we've been using the current development version of Suite2P and have identified the following bugs when nchannels=2.

With align_by_chan = 2:
1- reg_tiff_chan2 = 1 (and reg_tiff = 0) saves the registered tiffs of the first channel (file names correct, folder is reg_tiff and files are chan0)
2- reg_tiff = 1 (and reg_tiff_chan2 = 0) saves the registered tiffs of the second channel (file names correct, folder is reg_tiff_chan2 and files are chan1)
3- GUI has no mean img chan2 or mean img chan 2 corr
4- chan2_prob colors does not work in the GUI
5- "random" colors for ROIs are all red (used to be various colors) in the GUI

In comparison, with align_by_chan = 1:
1- reg_tiff and reg_tiff_chan2 save files correctly
2- the GUI does have mean img chan2 or mean img chan 2, corr
3- chan2_prob colors works (but scale is -1.85 to 2 which seems odd, and most ROIs have colors corresponding to ~1 but a couple were ~2)
4- GUI "random" colors for ROIs are red for ROIs strongly overlapping with chan2 and random everywhere else

Thanks,
Ross

**Comment by carsen-stringer** [comment]
this has been fixed on the dev branch, closing for now, please comment if it's still not working
