### ISSUE TITLE
No data in ops['regDX'] for rigid registration, despite large movements

### ISSUE THREAD

**Issue by chaplinta** [MouseLand/suite2p#576]
Hi,

I wanted to examine the movement in the PC component images but for some reason I always get zero values in ops['regDX'][0, :], which as I understand should be the rigid registration delta for the high vs low PC components. I get values in the ops['regDX'][1:2, :] for non rigid and non rigid max. To confirm it's not just brilliantly stable recordings, I ran suite2p without any registration and the PC components are dominated by movement, yet ops['regDX'][0, :] is still all zeros.

Would you happen to know what might cause this or how to work out what is going? I've attached an example ops.npy file in case that helps. I run suite2p through python (by cloning the git repository and importing) and also call metrics.get_pc_metrics, but it also seems to happen if I use the GUI.

[ops.npy.zip](https://github.com/MouseLand/suite2p/files/5510867/ops.npy.zip)

Any insight would be much appreciated.

**Comment by chaplinta** [comment]
Sorry just to clarify I think actually I am using suite2p from pip, I had this at the start of my code (taken from an example notebook):

sys.path.insert(0, path_to_git_repo)
from suite2p import run_s2p

So I thought was how suite2p was being imported, but I see now it was actually installed with pip, and that insert doesn't seem to be needed.

**Comment by carsen-stringer** [comment]
I've loaded the data here:
![image](https://user-images.githubusercontent.com/15067541/100375481-17420000-2fcb-11eb-9056-ab06b0463970.png)

You are right the "rigid" movement is detected to be zero, and in the GUI that looks correct -- it doesn't look like the top and bottom PC images are off from each other in a rigid way. 

There is some non rigid movement (those are `ops['regDX'][:,1:]` as you've noticed), but it's hard to tell how bad it is without having the raw binary. In particular, the non-rigid movement in PC4 (plotted above) looks like the whole FOV expanded and/or there was some Z movement, which are movements that suite2p cannot fix.

I'm going to close the issue for now as it doesn't look like a bug, but please feel free to comment with questions.

**Comment by chaplinta** [comment]
Hi Carsen,

Thanks for your reply. As I mentioned I tried a run where there was no registration and so the PCs are dominated by movement. 

https://www.dropbox.com/s/1p08mk882utsl6e/ops.npy.zip?dl=0

When I do that, the rigid pixel shifts are still all zero. Strangely, the non-rigid pixel shifts are also zero, it's like it didn't even try to register the PCs. Is it possible that the code uses the registration options of the movie to also register the PCs? Or is there something else going on? Do you ever see data in ops['regDX'][0, :] in any dataset with the current suite2p? If so it's probably me just doing something incorrectly.

Cheers,
Tristan
