### ISSUE TITLE
Manual Labelling issue - no deconv trace

### ISSUE THREAD

**Issue by xwchia** [MouseLand/suite2p#577]
Hi,

I've been attempting to manually label some ROIs that have been wrongly labelled (the ROI is larger than the actual cell).

However, i noticed that there are some ROIs that do not display a deconv trace despite the cell being obviously present.

Do refer the the screenshot below. Note that the ROI selected is an ROI that has been manually labelled by me.
![Screenshot 2020-11-10 at 4 59 46 PM](https://user-images.githubusercontent.com/48054750/98652225-46733300-2376-11eb-8077-23f00f331269.png)

Wondering if anyone has any suggestions or idea why this is happening?

Thank you!

**Comment by marysethomas** [comment]
Hello, I am having the same issue with manually labelled cells. I am using the dev version of Suite2p.

The deconvolution does not get performed for a small subset of the manually labelled cells, let's say 3 out of 10. When I load the fall.mat in MATLAB the spks values for those cells are all "NaN"

**Comment by carsen-stringer** [comment]
Are you running sparse_mode? The shape of the ROI is determined by the frames on which it's active so it shouldn't be a too unconservative estimate.

My guess for the NaN's is that you chose a cell that was fully overlapping with another cell and `ops['allow_overlap']` is set to False, so all those pixels were excluded => no pixels in cell => F is all zeros (as in plot) => NaN's in spike detection. If you want to draw overlapping ROIs you need to set `ops['allow_overlap']=True`.

**Comment by carsen-stringer** [comment]
I'm going to close this issue for now but please comment if this approach fails

**Comment by xwchia** [comment]
Hi Carsen,

Thank you for the reply. My ops['allow_overlap'] is indeed set to False. And as shown in the photo, you are right that the ROI that i attempted to draw was fully overlapping with another ROI. I'll update again if i encounter the same issue after changing ops['allow_overlap']  = True.

If i were to set ops['allow_overlap'] = True, would that change the result of suite2p? For example, would the F change for other cells?
