### ISSUE TITLE
Skip neuropil extraction?

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#578]
Thanks for all the work in making this package easy to use!

I have a recording from a dense nuclear localized GCaMP. Since there is no labeled neuropil, wondering if possible to skip this step? Right now my workaround is to set min_neuropil_pixels to be very high.

I’ve also noticed that most neurons are missed, while many background pixels are detected as cells. I wonder if I’m just using bad settings? I did try sparse_mode = 0, as well as 1, and set a reasonable average size of for ROI 6 pixels. Any tips appreciated!

![3BFE9D7B-FB17-4271-A2AA-569BF0B527C7](https://user-images.githubusercontent.com/863327/98777603-ee542500-23a5-11eb-8263-50469f5f76c5.jpeg)

![suite2p-0 5](https://user-images.githubusercontent.com/863327/98778542-60793980-23a7-11eb-9b6e-ba74ac2859ca.png)

![suite2p-0 8](https://user-images.githubusercontent.com/863327/98778573-6ec75580-23a7-11eb-95ca-bc7fe6f8a1ef.png)

**Comment by carsen-stringer** [comment]
have you tried decreasing threshold_scaling to find more neurons?

I've added a flag 'neuropil_extract' that you can set to zero in the dev branch:
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```
