### ISSUE TITLE
Comment for spatial_hp_detect is not correct?

### ISSUE THREAD

**Issue by orena1** [MouseLand/suite2p#583]
Hi,
I'm trying to understand the comment for `spatial_hp_detect`
https://github.com/MouseLand/suite2p/blob/0cc416f71391985a781a9a0622d3c70d5aacf9ec/suite2p/run_s2p.py#L91

It state that it is "window for spatial high-pass filtering **before registration**", but when I look at the usage of this variable: 
https://github.com/MouseLand/suite2p/blob/17501ef3d4f03ec4c6ca89d3b9186078a640c4f6/suite2p/detection/detect.py#L74

It is after the registration.
Can you please help me to understand it?
Thanks

**Comment by nickdelgrosso** [comment]
Hi @orena1 ,

You're right, the comment isn't correct.  It should read "for neuropil subtraction before detection".

**Comment by orena1** [comment]
Great, thanks.

**Comment by nickdelgrosso** [comment]
Sure, no problem.  If you see any other comments and want to correct them, feel free to make a PR; it helps a lot!

Best wishes,

Nick
