### ISSUE TITLE
z-correlation computation for second channel

### ISSUE THREAD

**Issue by nschubert** [MouseLand/suite2p#587]
Hi team! I have a question regarding the registration in suite2p. 

We want to use suite2p's registration algorithm to register our 3D timeseries data. We are using a stable GFP (no GCaMP) expressed in microglia and want to assess microglia morphology. Suite2p already does a pretty good job registering only based on the GFP signal. However, we are trying to improve it using a stable vessel marker (Dextran TexasRed). Do you have any experience with this? Would using the stable vessel marker likely have better registration results over the GFP of the microglia? 

Moreover, I had a go with Z-registration module. Is it also possible to apply the Z-correction? Would this also be able to work with 2-channels (maybe in the future)?

Thanks for all the great work on the software!

**Comment by carsen-stringer** [comment]
We have never used a vessel marker so not sure how well it would work. you can set align_by_chan=2 (if it's the second channel) to try it out. We have used labelling like nuclear tdTomato for registration with success.

Applying the Z-correction is tricky and pretty dependent on plane spacing and movement size. We don't have plans to support it directly but if you write some code we can link to it. The second channel addition would not be so hard -- just choose the 2nd channel in the GUI. I've added the enhancement label. Let me know if this is something you're still interested in

**Comment by nschubert** [comment]
Thanks for your response! I am going to look into it and will contact you again when needed.

**Comment by carsen-stringer** [comment]
all good here? closing this issue for now but comment if you need more help or have a processing pipeline that users could use for this sort of thing
