### ISSUE TITLE
Can't find where neuropil masks are stored

### ISSUE THREAD

**Issue by chaplinta** [MouseLand/suite2p#588]
Hi,

I can't seem to find where the neuropil masks are stored in the outputs of suite2p. The docs say there should be a field in stat.npy called ipix_neuropil, and the view_neuropil_masks example jupyter notebook says there should be a field in ops called neuropil_masks, but neither are in my data. Is there option I am supposed to set or is this feature just disabled? Or am I just looking in the wrong spots?

Cheers,
Tristan

**Comment by pkells12** [comment]
I'm doing some analysis in matlab with the Fall.mat output and am also unable to find where the masks are stored. Hope this can get clarified soon.

Thanks!

**Comment by carsen-stringer** [comment]
I've added this as a key in the github version due to the demand. it's a list of pixels in Ly*Lx coordinates, to display e.g.:
```
stat = np.load('stat.npy', allow_pickle=True)
ops = np.load('ops.npy', allow_pickle=True).item()

neuy, neux = np.unravel_index(stat[0]['neuropil_mask'], (ops['Ly'], ops['Lx']))
neumask = np.zeros((ops['Ly'], ops['Lx']))
neumask[neuy, neux] = 1
plt.imshow(neumask)
```
