### ISSUE TITLE
Issue with display of mean image in gui

### ISSUE THREAD

**Issue by diegoasua** [MouseLand/suite2p#589]
Hi!

I can't get either the `mean img` or `mean img (enhanced)` functionality to work. I am running suite2p in an enviroment created with the `environment.yml` file. The enviroment runs python 3.8.3.

The issue is that, either after running suite2p on some data, or loading processed data, when clicking `mean image` nothing happens, and when clicking `mean img (enhanced)` the background turns beige. `max projection` and `correlation map` work well, however. Playing with saturation does not solve it.

Side note (don't know if this is relevant) the raw data files were `.tif`.

**Comment by carsen-stringer** [comment]
hmm I think I've now fixed the environment with python<3.8. I'd recommend trying the latest version. also any errors during running/loading into the GUI? closing for now but please comment if these solutions don't work
