### ISSUE TITLE
ops file issue in GUI since v0.9.3

### ISSUE THREAD

**Issue by samihassan84** [MouseLand/suite2p#592]
Hi,
just a minor bug report. In your latest version 0.9.3, loading an 'ops' file in the GUI isn't working anymore. Also, when saving an 'ops' file, the explorer window gets opened twice.
Thanks for your constant efforts to improve suite2p,
Sami

**Comment by carsen-stringer** [comment]
sorry about this, this is fixed now in the github version

**Comment by samihassan84** [comment]
works great, thanks fir the fix!
