### ISSUE TITLE
Use cellpose ROI drawing for manual labelling

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#596]
Just an enhancement. The cellpose-way of drawing ROIs is easier and more precise than the elliptical ROI tool used in suite2p.

Not sure how easy it is to implement though.

**Comment by carsen-stringer** [comment]
for most users I don't think this is necessary and it would be non-trivial to add. I will add an issue for loading masks for processing (that you can draw in cellpose for instance)
