### ISSUE TITLE
new error message

### ISSUE THREAD

**Issue by cgrienberger** [MouseLand/suite2p#597]
Hey guys.
since I updated suite2p to version 0.9.3 I am getting this new error message on my mac : 
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
suite2p seems to be starting fine... does anyone else get this error? what can I do?

**Comment by carsen-stringer** [comment]
can you try?
```
conda install nomkl
```
I'm going to close this issue and link it to #608
