### ISSUE TITLE
Error when trying to open NPY files

### ISSUE THREAD

**Issue by charlesphi** [MouseLand/suite2p#600]
Hello,

I am still trying to understand how suite2p works, and also trying to learn python. This is probably a very basic question but I cannot open the npy files in jupyter notebook after running Suite2p.

I get a similar error for all the npy files:
suite2p\plane0\iscell.npy is not UTF-8 encoded saving disabled.
see console for more details.

Thank you

**Comment by nschubert** [comment]
Do you load the files with numpy.load? Did you use the allow pickle argument? Hope this is helpful.

`import numpy as np`
`np.load('ops.npy', allow_pickle=True)`

**Comment by carsen-stringer** [comment]
thanks @nschubert , here is some code from the documentation: https://suite2p.readthedocs.io/en/latest/outputs.html
