### ISSUE TITLE
problem importing cellpose with 'anatomical_only' detection

### ISSUE THREAD

**Issue by alemessurier** [MouseLand/suite2p#604]
Hi,

It looks like you guys recently added some functionality to use cellpose to detect ROIs in the anatomical marker channel. I'd love to use this feature, since cellpose works beautifully on my stuctural marker images, but I'm getting an error that cellpose isn't installed. However it's installed in my conda environment for suite2p...any ideas? 

Thanks!
Amy

**Comment by carsen-stringer** [comment]
hmm can you try in the environment starting python and importing cellpose? e.g.
```
import cellpose
```

**Comment by alemessurier** [comment]
yep, it looks like it imports fine.

**Comment by alemessurier** [comment]
(this is version 0.9.3)

**Comment by brandonStell** [comment]
Same problem with version 0.9.3.

I can run cellpose fine from the environment but suite2p asks me to install it with pip. 
pip replies that it's already installed.

I had a working suite2p environment and just added cellpose to it to give it a try on some Purkinje somas. 


```
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not running registration, plane already registered
NOTE: applying default /home/bs/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 26
Binned movie [4917,208,208], 20.68 sec.
~~~ tried anatomical but failed, install cellpose to use: ~~~
$ pip install cellpose
```

cellpose works fine when called:

```
~ ⌚ 11:22:12
$ python -m cellpose
TORCH CUDA version not installed/working.

**Comment by brandonStell** [comment]
fixed with 
```
pip install mxnet

**Comment by camille-lab** [comment]
I had the same issue and "pip install mxnet" also fixed it

**Comment by carsen-stringer** [comment]
sorry about this, I've removed the mxnet dependency, please try the latest github version, closing this issue for now but let me know if there are still issues
