### ISSUE TITLE
Z-correction issue

### ISSUE THREAD

**Issue by nschubert** [MouseLand/suite2p#605]
Hi! I am trying to use the Z-correction functionality in suite2p. After I've performed the Z-registration in suite2p I would like to reconstruct the corrected image stack in spyder/python. As I understand the I have to retrieve the ops['zcorr'] from every plane separately to reconstruct the image. 

I import an ops.npy as follows:
`import numpy as np`
`ops = np.load('/.../suite2p/plane15/ops.npy', allow_pickle=True)`

When inspecting the object with `ops` I clearly see the zcorr results. See image: 
<img width="551" alt="Screenshot 2021-01-08 at 13 02 31" src="https://user-images.githubusercontent.com/14890713/104014833-f9fc7600-51b3-11eb-9634-6c244318bcc9.png">

However I have issues indexing the numpy array. When trying to index the numpy array to retrieve the zcorr results I get an error were is stated that this is a 0-dimensional array. 
<img width="558" alt="Screenshot 2021-01-08 at 13 24 40" src="https://user-images.githubusercontent.com/14890713/104015438-edc4e880-51b4-11eb-8ecc-bcd145a7400c.png">

I have tried to search for a solution but I haven't found ways to index, or even convert, 0-d numpy arrays. Am I importing the array using the wrong command? Or shouldn't the ops.npy file be a 0-d array? Thanks in advance!

**Comment by carsen-stringer** [comment]
`ops` is a python dictionary and `'zcorr'` is a key that you can access with `ops['zcorr']`, e.g.
```
ops = np.load('xxx/suite2p/plane0/ops.npy', allow_pickle=True).item()
zcorr = ops['zcorr']
````

**Comment by marysethomas** [comment]
@carsen-stringer Is zcorr currently saved in Fall.mat? After I compute Z position, I click File > Save to mat, but afterwards I do not see the zcorr variable in ops. Thank you!

**Comment by marysethomas** [comment]
Update, I was able to solve this issue by cloning the most recent developer version of suite2p.
