### ISSUE TITLE
cannot import suite2p from latest github version

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#606]
---------------------------------------------------------------------------
PackageNotFoundError                      Traceback (most recent call last)
<ipython-input-5-baae7ab6216b> in <module>
----> 1 import suite2p

D:/Github/suite2p\suite2p\__init__.py in <module>
----> 1 from .version import version
      2 from .run_s2p import run_s2p, default_ops
      3 from .gui import run as run_gui
      4 from .detection import ROI
      5 

D:/Github/suite2p\suite2p\version.py in <module>
      2 
      3 
----> 4 version = _metadata('suite2p')['version']

~\anaconda3\lib\site-packages\importlib_metadata\__init__.py in metadata(distribution_name)
    573     :return: An email.Message containing the parsed metadata.
    574     """
--> 575     return Distribution.from_name(distribution_name).metadata
    576 
    577 

~\anaconda3\lib\site-packages\importlib_metadata\__init__.py in from_name(cls, name)
    213                 return dist
    214         else:
--> 215             raise PackageNotFoundError(name)
    216 
    217     @classmethod

PackageNotFoundError: No package metadata was found for suite2p

**Comment by nickdelgrosso** [comment]
Sounds good
