### ISSUE TITLE
Loading ops file issue

### ISSUE THREAD

**Issue by saramoberg** [MouseLand/suite2p#607]
Hi, I recently upgraded to the new version (v 0.9.3) and I cannot load an ops file and get this message: 

Traceback (most recent call last):
  File "c:\users\sara-larkumlab\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 466, in load_ops
    if len(name)>0:
TypeError: object of type 'bool' has no len()

I also get 2 pop-up windows when I try to save ops file. I saw that this issue has been raised already but no comment on it or solution to it.  Is this issue addressed? If so, what should I do to fix this?

**Comment by carsen-stringer** [comment]
Apologies for introducing this error, it is fixed in the latest github version and a new release of suite2p will be made soon
