### ISSUE TITLE
Image registration hanging in 0.9.3 with two channels

### ISSUE THREAD

**Issue by brandonStell** [MouseLand/suite2p#612]
In 0.9.3 with two-channel data

After image registration, suite2p stops and does not move to the next steps in the pipeline.  When running suite2p a second time it finds the previous registration and skips the registration step but the registered image looks like it is a combination of the two channels.

`pip install suite2p==0.9.2` and everything (except anatomical_only) works fine again.

**Comment by carsen-stringer** [comment]
weird, not sure what would have changed to cause that, can you try the latest github version of the pipeline and let me know if this still happens? 

I would guess it may be hanging during registration metric computation and then maybe not saving the ops file?

**Comment by brandonStell** [comment]
thanks, the changes pushed this morning seem to have solved the hanging problem.
(but now cellpose doesn't seem to run regardless of whether I set anatomical_only to 1 or 2...would you like me to create a new issue?)

```
(suite2p) 
~/repositories/suite2p on  master! ⌚ 12:31:45
$ suite2p --version
suite2p v0.9.3
```

**Comment by carsen-stringer** [comment]
thanks for letting me know I'll close the issue for now, please open a new issue if you have more problems

**Comment by brandonStell** [comment]
This is happening again periodically and I'm wondering if it's because of the large number of frames?

```
~ ⌚ 15:35:09
$ ll /media/bsinvivo2/poste_bs_invivo2/vinh/2021_02_19/033/01/suite2p/plane0
total 32G
-rwxr-xr-x 1 bs bs 16G Feb 23 13:21 data.bin
-rwxr-xr-x 1 bs bs 16G Feb 23 13:12 data_chan2.bin
-rwxr-xr-x 1 bs bs 17M Feb 23 13:21 ops.npy
```

![image](https://user-images.githubusercontent.com/11091919/108858559-96f06280-75ec-11eb-8bfb-f405cb9fa5aa.png)

**Comment by brandonStell** [comment]
So much for the too many frames hypothesis...

![image](https://user-images.githubusercontent.com/11091919/108903462-9fad5c80-761d-11eb-8243-28127e8f5271.png)
