### ISSUE TITLE
Subfolders not sorted when using `look_one_level_down`

### ISSUE THREAD

**Issue by dhb2128** [MouseLand/suite2p#614]
I have a folder structure where I have a `rootdir` and then within it I have session folders (organized by date) and then within each session folder I have tiffs for each trial. Therefore, I have been setting the `rootdir` as my 'data_path' in the `db` and `ops['look_one_level_down'] = True`. 

I was expecting that the resulting `file_list` would be sorted (aka `sorted(Path(rootdir).rglob("*.tif"))`), but it looks like that's not what the call to `list_files` in `get_tif_list`does. Currently, it only sorts within each subfolder, but it doesn't sort the order of the subfolders returned by glob on this line:

https://github.com/MouseLand/suite2p/blob/3eeb5ccd12352bb62a3fe621de5093a111af3571/suite2p/io/utils.py#L83

I believe changing that line to `fdir = natsorted(glob.glob(os.path.join(froot, "*/")))` would fix this issue.

Best,
David

**Comment by carsen-stringer** [comment]
good point, I've added this fix to the github version, please let me know if you're still having issues with it
