### ISSUE TITLE
bidiphase.py error when the height of the image is an odd number

### ISSUE THREAD

**Issue by jkim0731** [MouseLand/suite2p#615]
Hi,

I ran into an error during bidiphase.

>  File "C:\Users\shires\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\register.py", line 214, in register_binary
>    ops['bidiphase'] = bidiphase.compute(frames)
>
>  File "C:\Users\shires\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\bidiphase.py", line 30, in compute
>   cc = np.real(fft.ifft(d1 * d2, axis=2))
>
>ValueError: operands could not be broadcast together with shapes (1000,343,387) (1000,344,387) 

I guess a simple workaround would be forcing d2 to have the same size as d1 in "bidiphase.py" after they are defined, like:

> # compute phase-correlation between lines in x-direction
>    d1 = fft.fft(frames[:, 1::2, :], axis=2)
>    d1 /= np.abs(d1) + 1e-5
>
>    d2 = np.conj(fft.fft(frames[:, ::2, :], axis=2))
>    d2 /= np.abs(d2) + 1e-5
>
> # Matching sizes
>    d2 = d2[:,:d1.shape[1],:]

Thank you,
Jinho

**Comment by carsen-stringer** [comment]
thanks good catch, I've added your fix to the github version, please let me know if you're still having issues
