### ISSUE TITLE
Load ops not possible in suite2p 0.9.3

### ISSUE THREAD

**Issue by kclgeorge** [MouseLand/suite2p#616]
I can't seem to load ops files in the latest version.

See error below

loading ops
Traceback (most recent call last):
  File "C:\Users\ME\anaconda3\lib\site-packages\suite2p\gui\rungui.py", line 466, in load_ops
    if len(name)>0:
TypeError: object of type 'bool' has no len()

I reinstalled 0.9.2 for now and works fine.

Thanks,

George

**Comment by dhb2128** [comment]
I believed this was fixed in 3eeb5cc but it hasn't been released. Installing from the master branch with `pip install .` should also work.

**Comment by carsen-stringer** [comment]
thanks @dhb2128 yes this has been fixed, new pip coming soon, closing issue in the meantime
