### ISSUE TITLE
Channel 2 probability not updated

### ISSUE THREAD

**Issue by saraysoldado** [MouseLand/suite2p#617]
Dear Suite2p team,

First of all thanks so much for bringing to the community this wonderful software, its really amazing :) 

I am having an small issue with the Channel 2 classifier output. I am on last version, 0.9.3. When changing the probability on the GUI, there is no update of the classified red cells on the GUI (red cells on the "random" colors display do not change). The change is also not updated in the output redcell.npy, but in contrast, the matlab output file is updated.

Thanks for the help,
Saray

**Comment by carsen-stringer** [comment]
oops sorry about that, it is now fixed in the github version, I will make a new pip version soon. please let me know if there are still problems
