### ISSUE TITLE
Bad performance using cellpose in suite2p

### ISSUE THREAD

**Issue by camille-lab** [MouseLand/suite2p#620]
Hi!
Thanks again for this fantastic software.
I am trying the "anatomical only" feature in suite2p v0.9.4 but it performs badly compared to running cellpose directly (see snapshots attached).
To run cellpose, I simply took a snapshot of the meanImg in suite2p GUI (hence the saturation in the image).
Any idea how to improve that?

Thanks!

![image](https://user-images.githubusercontent.com/53828465/107553016-20a33780-6bcc-11eb-8df3-972fc9100dfe.png)

Here is what I get in the logs:
Cellpose:
```
using model cyto
processing 1 image(s)
time spent: running network 23.28s; flow+mask computation 3.09
estimated masks for 1 image(s) in 26.39 sec
>>>> TOTAL TIME 26.39 sec
168 cells found with cellpose net in 26.432 sec
plane 0 outlines processed
```
Suite2p:
```
>>>> CELLPOSE finding masks in max_proj / mean_img
>>>> using CPU
Running test snippet to check if MKL-DNN working
see https://pytorch.org/docs/stable/backends.html?highlight=mkl
** MKL version working - CPU version is sped up. **
processing 1 image(s)
computing styles from images
time spent: running network 3.10s; flow+mask computation 0.59
estimated cell diameters for 1 image(s) in 6.46 sec
>>> diameter(s) =  [16.77456227]
time spent: running network 19.59s; flow+mask computation 1.07
estimated masks for 1 image(s) in 20.67 sec
>>>> TOTAL TIME 27.14 sec
>>>> 34 masks detected, median diameter = 11.56 
```

**Comment by brandonStell** [comment]
Same problem here. 
Changing (decreasing) `ops['tau'`] in suite2p produces masks similar to those produced by cellpose alone...

**Comment by carsen-stringer** [comment]
you have chosen `ops['anatomical_only']=1` which uses the max_proj / mean_img, not the mean_img. to use the mean_img set `ops['anatomical_only']=2`. sorry this isn't documented yet, you can see this info in the tooltip (the hover text in the run GUI).

also you can now set the diameter for the cellpose estimation as `ops['diameter']` in the github version of the code.

please let me know if these things don't solve the issue for you, closing for now

**Comment by camille-lab** [comment]
it is way better but is still missing obvious cells.
Would it be possible to use the enhanced mean imaged instead of meanImg? Cellpose does a better job in my hand this way.
And would it be possible to change the "model match" and "cell detection" thresholds?
Many thanks again for the fantastic tools

**Comment by carsen-stringer** [comment]
I can't add these to the GUI but I've added these options to ops (cellprob_threshold and flow_threshold) and you can change them when you run in a jupyter-notebook. You can also use the enhanced mean image now `ops['anatomical_only']=3`. closing for now, please let me know if you have issues with these.

**Comment by camille-lab** [comment]
thanks, I works very well (see below).
If I understand correctly, the ops["diameter"] is now referring to the anatomical detection and ["spatial_scale"] is for activity-based? And ["sparse_mode"] is now the default option?

![image](https://user-images.githubusercontent.com/53828465/108548613-fea06800-72e3-11eb-9a9c-18bfd369f534.png)
