### ISSUE TITLE
unable to choose a classifier in run_s2p

### ISSUE THREAD

**Issue by kevinksit** [MouseLand/suite2p#621]
It appears that there is no classifier_path key in the default ops dictionary, which leads to the user being unable to change the classifier used when running suite2p through the terminal. If a classifier is added to a created ops file via `ops['classifier_path'] = path`, it does not work. It seems like lines 208 - 220 in run_s2p.py allow selection of a classifier, but line 399 - 402 seem to remove the classifier_path key because it does not exist in the default ops. Adding an empty classifier_path key to default ops seems to resolve this issue. 

Please let me know if it is intended to be used a different way.

**Comment by carsen-stringer** [comment]
oops good catch, I've fixed this in the github version by adding it to default_ops, please let me know if it's still not working
