### ISSUE TITLE
Zcorr save to mat bug

### ISSUE THREAD

**Issue by marysethomas** [MouseLand/suite2p#622]
Thank you for adding the z-correlation feature to Suite2p! This has been really helpful for us.

I noticed that the zcorr variable won't appear in Fall.mat unless the user reloads stat.npy before clicking Save to Mat. Is it possible to change this so that you can use Save to Mat immediately after computing z-correlations instead?

**Comment by carsen-stringer** [comment]
good catch, I've fixed this in the github version, please comment if it's not working

**Comment by marysethomas** [comment]
It works, thank you @carsen-stringer!
