### ISSUE TITLE
Y Values for spk (deconvolved) in Matlab vs. GUI 

### ISSUE THREAD

**Issue by Moosehorse123** [MouseLand/suite2p#623]
Hi, 

When working with the Fall.mat file I was wondering about the y values for the spk output. On the GUI the y values for the deconvolved trace appear differently than when plotted in matlab (hopefully you can see attached images). For example the highest y value in the screenshot from the GUI appears to be at about 1400, and more importantly crosses past the raw fluorescence trace but in the plotted matlab figure this same event is at about 1200 and does not cross past the raw flourescence. It appears that on the GUI all the y-values are shifted by about +200... Is this just a visualization bug on my machine, or are the values actually an issue in the saved matlab spk array. 

Thanks so much for all your help! 

<img width="905" alt="suite_2p_scaling_GUI" src="https://user-images.githubusercontent.com/18012559/108161229-9b7ebd80-70b8-11eb-9306-06c0a8df7398.png">

![suite2p_scaling_matlab](https://user-images.githubusercontent.com/18012559/108161245-a33e6200-70b8-11eb-9f20-89e43e8b9d35.png)

**Comment by Moosehorse123** [comment]
Hi, just to follow up on this, it does actually appear to be a bug in the matlab export of the traces, and NOT a scaling issue in the GUI. 

When plotting the same data in jupyter notebook I get the image below that matches the GUI. 

![python_example](https://user-images.githubusercontent.com/18012559/108270424-6ec0b980-713d-11eb-9bc7-b69d94b24168.png)

**Comment by carsen-stringer** [comment]
Hmm I'm confused about a potential matlab vs python difference, but the matlab plot looks right?

I rescale the deconvolved traces in the GUI so they are easier to see by:
```
fmax = np.maximum(f.max(), fneu.max())
fmin = np.minimum(f.min(), fneu.min())
sp_trace = sp/sp.max() * (fmax-fmin) + fmin
```
where `f` is the fluorescence trace `fneu` is the neuropil and `sp` is the deconvolved

closing for now but please follow up with questions if this doesn't resolve it

**Comment by Moosehorse123** [comment]
\yup that explains it thank you!
