### ISSUE TITLE
I cannot use corr with 1D var

### ISSUE THREAD

**Issue by tkmymgc** [MouseLand/suite2p#625]
![image](https://user-images.githubusercontent.com/79255031/108342801-2de8a380-7216-11eb-928c-1ab33f8c2630.png)

I would like to visualize neuronal activity correlated with 1D data.
For that, I prepared 1D data ("position" in an attached screenshot, format: npy file) which is same length as F.shape[1] as showed in the screenshot.
Then, I loaded the 1D data into suite 2p by clicking 'File' => 'Load behavior or stim trace (1D only)' and then choosing the data file. 
However, the function 'corr with 1D var, bin=^^^' is not activated.
I don't know how to solve this problem now. I would appreciate if you could help me solving the problem. Thank you.

**Comment by carsen-stringer** [comment]
found a bug here, it's fixed in the github version now, please let me know if it's still not working
