### ISSUE TITLE
frames_include missing in the GUI

### ISSUE THREAD

**Issue by TheUwe** [MouseLand/suite2p#628]
Hi together,
I am running the latest version of suite2p on win10 mainly from the GUI as I am not familiar with python coding, but use MatLab instead. It seems, the the frames_includes field is missing in the GUI. I am sure one can easily change the ops.npy file manually, but it would be more convenient to change the parameter in the GUI. Furthermore, the 'Load ops file' button doesn't work.

Error:                                                                                     
File "C:\Users\uwele\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 466, in load_ops              
  if len(name)>0:          
    TypeError: object of type 'bool' has no len() 

Thanks :)

**Comment by orena1** [comment]
Try this:
`pip install suite2p==0.9.2`
maybe it would help...

**Comment by carsen-stringer** [comment]
ops loading is fixed, but frames_include is no longer implemented (I don't think since 0.7.5?) 

we are happy to support a pull request to re-add this feature. if you only want to run on a subset of data I'd recommend making a folder with only a subset of your tiffs
