### ISSUE TITLE
Error in loading ops file

### ISSUE THREAD

**Issue by LeonardoLupori** [MouseLand/suite2p#629]
Hi,
I'm getting the following error after clicking the button for loading an ops file in the "run pipeline" options menu'

I'm on windows 10
I already tried deleting the conda env, re-cloning the repo, and creating a new conda env from scratch but I get the same error.
It could be a bug or maybe I'm missing something obvious.

Here's the error I get when clicking on the button:
```
loading ops
Traceback (most recent call last):
  File "c:\users\leonardo\.conda\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 466, in load_ops
    if len(name)>0:
TypeError: object of type 'bool' has no len()
```

**Comment by orena1** [comment]
Hi,
Just to be clear, when you click "Load ops file" you get this error?
This is how it should look:

![github_1](https://user-images.githubusercontent.com/8983713/109180756-e1f8aa00-7793-11eb-9328-63f27eed4073.gif)

**Comment by LeonardoLupori** [comment]
Yeah!
The error comes up just after I click the button and no dialog box appears.  

If you need any other kind of information or if I can be helpful in any other way please let me know :)
I really appreciate the software and your effort.

I noticed that a similar problem was reported [here](https://github.com/MouseLand/suite2p/issues/628)

**Comment by orena1** [comment]
I checked a bit, I think 0.9.3 has some bugs, try installing an older version:
`pip install suite2p==0.9.2`

**Comment by LeonardoLupori** [comment]
Thanks a lot.
It worked! 
I also tried to install it from the most recent cloned repository 
```
>> suite2p --version
suite2p v0.9.4.dev1+g3eeb5cc
```

The bug is also solved in this version, so I guess it's just a matter of waiting for this version to release on pip.
Thanks a lot for the effort!

**Comment by carsen-stringer** [comment]
the pip is now made, thanks for the help @orena1
