### ISSUE TITLE
Save ops to file runs twice

### ISSUE THREAD

**Issue by LeonardoLupori** [MouseLand/suite2p#630]
Hello,

I'm experiencing the following behavior in the GUI, which I think was not intended:  
After clicking the button `save ops to file` the software presents me a dialog box for saving the file. After saving it, the software shows the same dialog box again.  
Not really a huge issue but maybe worth looking into.

running on win10

best!

**Comment by carsen-stringer** [comment]
can you try the latest version please? I think this has been fixed
