### ISSUE TITLE
Feature Request: option to have ROI color mask not disappear on selection

### ISSUE THREAD

**Issue by penguingiraffe2** [MouseLand/suite2p#635]
Hi, 

Loving the tool, thank you so much.
Wondering if it would be possible to have the option for the ROI mask of the cells to not disappear when selected in the GUI? It makes it quite hard to judge the quality of an ROI since you can only really judge the shape of the mask against background when the ROI is not selected. Thanks so much!

**Comment by carsen-stringer** [comment]
what would be the alternative? you want to be able to see what's underneath in the mean image or max proj
