### ISSUE TITLE
Feature Request: Option to use the same colormap from the manual segmentation in the general window

### ISSUE THREAD

**Issue by penguingiraffe2** [MouseLand/suite2p#636]
I find the standard colormap that is used in the manual segmentation window to be MUCH easier to see than the colormap in the general window. The colors are much darker and defined. Would it be possible to apply this same colormap to the general window? Thanks so much!

**Comment by Moosehorse123** [comment]
<img width="358" alt="Screen Shot 2021-03-06 at 12 52 41 PM" src="https://user-images.githubusercontent.com/18012559/110216045-f1a27d80-7e7a-11eb-966c-efdffee4610f.png">

<img width="401" alt="Screen Shot 2021-03-06 at 12 53 06 PM" src="https://user-images.githubusercontent.com/18012559/110216049-f5360480-7e7a-11eb-817b-7220381d6f3e.png">

**Comment by carsen-stringer** [comment]
do you have a red channel? are you selecting a certain colormap in the main view? sorry I need more info here

**Comment by penguingiraffe2** [comment]
Nope no red channel unfortunately. 
I am not selecting a certain colormap in the main view, using the default. 
Thank you!

**Comment by carsen-stringer** [comment]
are you using the latest version of the code? I can't reproduce this

**Comment by carsen-stringer** [comment]
closing now due to inactivity
