### ISSUE TITLE
default_ops() problem

### ISSUE THREAD

**Issue by darioringach** [MouseLand/suite2p#639]
>>> import numpy as np
>>> import sys
>>> # option to import from github folder
>>> sys.path.insert(0, 'C:/Users/dario/github/suite2p/')
>>> from suite2p import run_s2p
>>>
>>> # set your options for running
>>> ops = run_s2p.default_ops() # populates ops with the default options
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'default_ops'

**Comment by carsen-stringer** [comment]
try `from suite2p import default_ops`, we changed `run_s2p` to be a function
