### ISSUE TITLE
Can the reference image be saved as an output? 

### ISSUE THREAD

**Issue by darioringach** [MouseLand/suite2p#640]
It would be helpful to (a) have the microscope go back to the same population in a different session, (b) match cells between recordings across different days.

**Comment by carsen-stringer** [comment]
it's in `ops['refImg']`, or you can get the mean image as `ops['meanImg']`. see some of the outputs listed here: https://suite2p.readthedocs.io/en/latest/outputs.html#ops-npy-fields
