### ISSUE TITLE
custom colormap won't load unless rastermap already run

### ISSUE THREAD

**Issue by alihaydaroglu** [MouseLand/suite2p#646]
Thanks for the great software! I have a minor issue running version 0.9.3 on Windows 10. 

I'm trying to load a custom colormap for my cells from an *.npy file using the "Visualizations > Load custom hue for ROIs" option. If I do this after having run rastermap within suite2p (through "Visualizations > Visualize selected cells") there is no issue. However, if I try to load the colormap without having run rastermap already (and the "M: rastermap/custom" button on the left sidebar is not clickable since rastermap wasn't run), nothing changes in the GUI and I can't see my custom colormap. 

Thanks again!

**Comment by carsen-stringer** [comment]
this is fixed in the dev branch, will be merged soon
