### ISSUE TITLE
Change z-plane in GUI?

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#649]
Perhaps I'm missing something obvious, but I can't figure out how to view ROIs for planes other than the first plane in the GUI nor find a reference to this in the documentation... If not yet possible, I'd love to request this feature :) 

Edit: adding screenshot in case a rendering issue on Ubuntu
![Screenshot from 2021-04-01 23-54-10](https://user-images.githubusercontent.com/863327/113389884-9febf680-9345-11eb-838c-c41a7b96208d.png)

**Comment by carsen-stringer** [comment]
you have to either make a combined view folder and load that (using ops['combined']=1) or there's a new option in the GUI File menu called "load folder with planeX folders" that should do the trick, let me know if it errors though it's not super well tested
