### ISSUE TITLE
Registration fails with low SNR data

### ISSUE THREAD

**Issue by aprrenard** [MouseLand/suite2p#653]
Hi,

I have some data with low SNR and number of cells (but without much xy movement) for which registration fails at the cropping FOV step with this error:

> ** Found 1 tifs - converting to binary **
> time 1.04 sec. Wrote 746 frames per binary for 1 planes
> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
> NOTE: not registered / registration forced with ops['do_registration']>1
>       (no previous offsets to delete)
> ----------- REGISTRATION
> registering 746 frames
> Reference frame, 16.94 sec.
> ERROR<<<
> Traceback (most recent call last):
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> ERROR<<<
>     "__main__", mod_spec)
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
> ERROR<<<
>     exec(code, run_globals)
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module>
>     main()
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main
>     run_s2p(ops, db)
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 428, in run_s2p
>     op = run_plane(op, ops_path=ops_path)
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 196, in run_plane
>     ops = registration.register_binary(ops, refImg=refImg) # register binary
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/registration/register.py", line 470, in register_binary
> ERROR<<<
>     Lx=ops['Lx'],
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/registration/register.py", line 52, in compute_crop
>     ymin = np.ceil(np.abs(yoff[np.logical_not(badframes)]).max())
>   File "/home/anthony/anaconda3/envs/suite2p/lib/python3.7/site-packages/numpy/core/_methods.py", line 30, in _amax
>     return umr_maximum(a, axis, None, out, keepdims, initial, where)
> ValueError: zero-size array to reduction operation maximum which has no identity
> Interrupted by error (not finished)

It seems that all frames are considered as badframes, resulting in an empty array at:
`ymin = np.ceil(np.abs(yoff[np.logical_not(badframes)]).max())`

I'm using the latest version of Suite2p on pip, and run the pipeline with the default ops.
Adjusting _maxregshift_ and _th_badframes_  doesn't help. When skipping registration with do_registration = 0, the pipeline terminates without error.

As the raw tiffs contains several planes on each image, I split the planes and interleaves them in one ome-tif file with tifffile. Doing it with imageJ gives the same error.

Here are two example stacks (1 plane): one bad reproducing the error, and one good with a little more signal and cells that doesn't give the error. Both are ome-tif files written with the same script.
https://drive.google.com/drive/folders/16-xBKKhEB3BBhKxo3z4tzhjmxq9xkICZ?usp=sharing

I didn't see this error with better recordings, so I'm wondering if it is expected that registration breaks for that kind of data, or if it due to something else like the tif format.

Thank you for your help.

Here is a screenshot of the error showing the default ops and one of the FOV after running suite2p without registration:

![Capture d’écran de 2021-04-07 13-05-16](https://user-images.githubusercontent.com/31535099/113857765-35064980-97a3-11eb-866f-0bb295ba734b.png)
![Capture d’écran de 2021-04-07 13-08-43](https://user-images.githubusercontent.com/31535099/113857781-3b94c100-97a3-11eb-9733-ee0408267abe.png)

**Comment by carsen-stringer** [comment]
the latest github version will no longer error in the way you described, I've added a fix. BUT the registration still is very bad for your tiff and I'm not sure why. I need to debug more.
