### ISSUE TITLE
Multiplane analysis - crashes with div by zero

### ISSUE THREAD

**Issue by kostasl** [MouseLand/suite2p#660]
Hello,

First, I am new to suite2p many thanks for sharing this tool. I am using the latest version on pushed on github (2c060bd) commit (2c060bd09d2e7942eccb4b4597546d83d790ddde)
I am trying to run an analysis to extract ROIs on 20 planes, which have already been binarized on a previous run. 
This is a screen shot of my settings and log output after program crashes / analysis stops prematurely
![Suite2pSettings_screenShot](https://user-images.githubusercontent.com/210050/115002292-78943e00-9e9c-11eb-808a-dcd4f839d695.png)

no error is reported in the suite2p log, but analysis stops before reaching last plane (20). I ve tried this 3 times and it seems to stop at different planes each time. 
The command line output shows the Traceback:
<code>
/media/kostasl/ARXEIO1TB/2pDataAnalysis_zfish/2p_Hypothalam_Trial_1hr/suite2p_C/suite2p/plane0/stat.npy
no channel 2 labels found (redcell.npy)
0.4871847629547119
Traceback (most recent call last):
  File "/home/kostasl/suite2p/suite2p/suite2p/gui/rungui.py", line 417, in finished
    io.load_proc(self.parent)
  File "/home/kostasl/suite2p/suite2p/suite2p/gui/io.py", line 303, in load_proc
    load_to_GUI(parent, basename, output)
  File "/home/kostasl/suite2p/suite2p/suite2p/gui/io.py", line 328, in load_to_GUI
    make_masks_and_enable_buttons(parent)
  File "/home/kostasl/suite2p/suite2p/suite2p/gui/io.py", line 102, in make_masks_and_enable_buttons
    parent.mode_change(2)
  File "/home/kostasl/suite2p/suite2p/suite2p/gui/gui2p.py", line 402, in mode_change
    nb = int(np.floor(float(self.Fcell.shape[1]) / float(self.bin)))
ZeroDivisionError: float division by zero
</code>

My python version is 3.8.5
conda version:  4.10.0

Hope the above helps. 
I also have a seemingly separate issue that requires me to delete the ops folder in the .suite2p on startup/ and then reinstate it. But that is likely unrelated and for another issue to be raised.

Many thanks

**Comment by carsen-stringer** [comment]
oh no, there's an error loading the data because the bin size in the gui is set to zero, maybe you set the binsize yourself at some point? but we shouldn't allow this in the code regardless. thanks for the detailed bug report.

I've pushed the fix to the github version, going to close the issue for now but let me know if it's not working still

**Comment by kostasl** [comment]
Thank you for getting it fixed!
