### ISSUE TITLE
'Save and quit' after manual labelling

### ISSUE THREAD

**Issue by adenine-koo** [MouseLand/suite2p#663]
Hi! Thank you so much for this amazing program!

I have faced some problems with manually labelling. I tried to label some of the cells that were missed by the program in this way: add ROI --> extract ROIs --> save and quit. The 'save and quit' button doesn't seem to work and the 'extract ROI activity' window never close by itself. I tried to close the window manually, but when I checked on the GUI, the new ROI does not have any fluorescent signals with it (but it has deconv signals). It was not added to the npy files nor mat file (I also clicked the 'save to mat file' button in 'File' before checking the mat file).

I would appreciate it if you could show me the right way of doing the manual labelling.

**Comment by carsen-stringer** [comment]
are you using the latest version?

`pip install suite2p --upgrade`

I can't reproduce your problem. Also note you need to have write access to the files you have loaded into the GUI for this to work.

**Comment by adenine-koo** [comment]
Hi Carsen. I just updated suite2p to the latest version, and the manual labelling is working now. Thank you so much!
