### ISSUE TITLE
Is multicore parallelism only enabled if there are multiple planes in the data?

### ISSUE THREAD

**Issue by touloumes** [MouseLand/suite2p#666]
First of all, I love this software. Thanks for your hard work!

From the docs there are several areas where num_cores can be specified for multicore parallelism (i.e., suite2p.registration, suite2p.io). However, it seems from the code/GUI that this parameter is only used if the data contains multiple planes. Is this true? Or is there a way to force segment the binarization/registration/extraction steps across cores of the CPU?

**Comment by carsen-stringer** [comment]
yes there is an option to submit each plane as a separate job to a compute cluster and have them run on separate CPUs, but in general for a single plane all steps are automatically multi-threaded through numpy and numba (numba will for sure fill up your cores)
