### ISSUE TITLE
suite2p_version no longer available in ops output

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#668]
We noticed that the version string (`suite2p_version`) is no longer exported into `ops` in the latest version for suite2p (pip). 
Could it be enabled again?

**Comment by simon-ball** [comment]
Appears to be a regression added in 326eae50a , which commented out the version key/value in the default dictionary

https://github.com/MouseLand/suite2p/blob/bdd7aee9a898c153b7f664b1efe8f3e853662f3f/suite2p/run_s2p.py#L27

**Comment by kabilar** [comment]
Agree that it would be useful to have the version saved in `ops.npy`.  Thank you for your consideration.
@ttngu207 @shenshan

**Comment by carsen-stringer** [comment]
The versioning code was failing and unfortunately I didn't implement that code, so I ended up removing it. Maybe @nickdelgrosso has ideas on how to fix it?

I am very very happy to accept a pull request reimplementing this, I agree it's very useful :)

**Comment by nickdelgrosso** [comment]
If it happened out of the blue, it could be related to a setuptools-scm update (it's the library that manages the version, they had both a 5.0 and 6.0 release in the last 6 months).  Maybe pinning the version to 4.X would help?  Can't really say without seeing the error

Release schedule here: https://pypi.org/project/setuptools-scm/#history

**Comment by carsen-stringer** [comment]
thanks I'll try this!

**Comment by carsen-stringer** [comment]
this is fixed now in the github version
