### ISSUE TITLE
Import predefined ROI in suite2p GUI 

### ISSUE THREAD

**Issue by SimonZamora** [MouseLand/suite2p#669]
Hi! 
First of all, thank you for making this software open source, it is working well and helping a lot of neuroscientist around the world ! :)

I'm currently working on neuron cultures, and the ROI detection of suite2p only detects a handful of the cells I have in my tiff files. Would it be possible to import predefined mask on the GUI (or on a notebook) and then let suite2p extract the traces? 

I am working with Cellpose for cell detection/ROI drawing. 

Thank you for your help! 

Simon Zamora

**Comment by penguingiraffe2** [comment]
was this incorporated in new releases? Is it possible to import existing ROIs from cellpose into suite2p for ts extraction? Thanks so much!!

**Comment by carsen-stringer** [comment]
we now have cellpose integration, but plan to release more code for this, it will be in a notebook not in the GUI
