### ISSUE TITLE
Seeing entire path in the "choose run options window"?

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#673]
Hello,
Is there a way to see the entire path that has been selected in the "choose run options window"? I can only see portions of the selected paths, so it's hard to check that I selected the correct paths. Thank you!

**Comment by carsen-stringer** [comment]
good request, column is now larger and if you hover over the text you can see the full path (this hover text called a tooltip)

**Comment by sarahapark** [comment]
Thank you for adding the tooltip! Strangely, I am unable to see the full path as a tooltip when I hover over the path. My suite2p version is the most recent. What can I do to make the tooltip work for me?
Thank you!
Sarah

**Comment by sarahapark** [comment]
Hi,
I did [this ](https://github.com/MouseLand/suite2p/issues/689#issuecomment-885703258)and now I can see the tooltips!

Sarah
