### ISSUE TITLE
GUI - loading  OPS from file

### ISSUE THREAD

**Issue by kostasl** [MouseLand/suite2p#674]
Hello,
I wanted to share a problem I have that is rather salient and persistent.  I am suspicious this could be particular to my installation and not common.  

My python version is 3.7.10
conda version: 4.10.1

It seems that saving and loading of options (ops.only) does not work for all properties I set in suite2p. For example, the _ignore_flyback_ setting is not reinstated to the saved value.
Loading of existing ops.npy gives command line output:

>loading ops
>could not load ops file
>list index out of range

I hope this helps.
Thank you for all the hard work you put in suite2p.

**Comment by kostasl** [comment]
Update:

I found the source of the bug in rungui.py line 636: 
```
dstr+= str(int(ops[key][i]))
```
needs to be changed to :
```
dstr += str(int(i))
```

This allows for flyback plane setting to be loaded and then the suite2p run options dialogue appears just fine. I can issue a pull request with this change if that helps.

**Comment by carsen-stringer** [comment]
thanks for catching this, this is now in the github version of the code, soon to be in pip
