### ISSUE TITLE
Extracted ROIs with constant F=0

### ISSUE THREAD

**Issue by LeonardoLupori** [MouseLand/suite2p#676]
Hey,

I'm encountering a small issue where, in a subset of recordings, a few, sparse, cells are extracted with a normal-looking neuropil signal but with a flat F=0 fluorescence trace
These cells don't appear to be particularly close to the borders of the frame for the crop to be an issue and moreover, some cells that are even closer to the border have a normal F trace.

What could be the reason for this?

![image](https://user-images.githubusercontent.com/39329654/120810664-889ad680-c54b-11eb-8913-0900e535ce49.png)

**Comment by carsen-stringer** [comment]
I think that cell may be overlapping with another cell almost entirely? Are you setting `ops['max_overlap'] < 1`? If a cell is overlapping too much (>`ops['max_overlap']` of it's total number of pixels) it will be thrown out, but it looks like this didn't happen here.

**Comment by carsen-stringer** [comment]
going to close due to inactivity but let me know if it's still an issue and I can reopen

**Comment by TomSuarezO** [comment]
Hello! I have been having the same issue that some cells show completely flat Fluorescence traces. In my settings `ops[allow_overlap] = False` and `ops[max_overlap] = 0.75`. What puzzles me the most is that some of these "flatline" cells are initially classified as good cells and in some of them it can be clearly seen that there is a cell in the background (images attached below).

On one occasion that it seemed to be a cell in the ROI, I used the manual labeling and extracted a cell that was actually useful for the analysis (not just noise). What can I do to prevent this from happening?

![image](https://user-images.githubusercontent.com/45014122/150368517-75770a20-651d-489b-adea-8fe0dc71d678.png)

Example cell in the upper left
![image](https://user-images.githubusercontent.com/45014122/150368661-b4ee23ff-059d-4609-8d10-b39c624d6eeb.png)
![image](https://user-images.githubusercontent.com/45014122/150368772-2b0ee731-8a32-411a-801b-cfd1de1ba8f2.png)
![image](https://user-images.githubusercontent.com/45014122/150368863-12bf3b0e-bd1c-457a-96c8-db0f7e902986.png)
