### ISSUE TITLE
Analyzing data with negative-going calcium transients

### ISSUE THREAD

**Issue by mheinrich99** [MouseLand/suite2p#677]
Hello,

I'm trying to analyze data collected from cells loaded with a commonly used calcium dye, fura-2 AM. Unlike most calcium indicators, fura-2 AM fluoresces at rest and undergoes a decrease in fluorescence when calcium binding occurs. This results in negative-going transients during neuronal activity. Despite successfully eliciting these negative transients and extracting them via manual labeling in suite2p, the algorithm cannot seem to automatically detect them as cells.

Any suggestions for finding a solution to this?

Thanks,
Max

**Comment by tvajtay** [comment]
So this is also an issue in tonically active cells that experience inhibition which gets resolved as a drop in basal calcium florescence which suite2p sees as below neuropil background and ignores, and doesn't output the data. Also see https://pubmed.ncbi.nlm.nih.gov/33488363/

**Comment by tvajtay** [comment]
But in my immediate case it was due to neuropil subtraction of below threshold fluorescence creating false negatives.

**Comment by carsen-stringer** [comment]
we don't have any plans for this, you could try inverting the data
