### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by Virginia9733** [MouseLand/suite2p#679]

**Comment by Virginia9733** [comment]
Hi,

I am trying to run suite2p on google colab, since I am using a laptop without GPU.

However, after setting up conda env and install suite2p properly, I try to run output_ops = suite2p.run_s2p(ops=ops, db=db), but got this error message which I don't understand.

The only solution that I find to activate conda env in colab is:

%%shell
eval "$(conda shell.bash hook)" # copy conda command to shell
conda activate suite2p # activate conda env
python  # run code in python

output_ops = suite2p.run_s2p(ops=ops, db=db)
![Screen Shot 2021-06-12 at 11 13 52 PM](https://user-images.githubusercontent.com/61534754/121780698-1a51b600-cbd4-11eb-94c3-82df96f01b02.png)


Any help would be much appreciated!

**Comment by carsen-stringer** [comment]
suite2p python does not have any GPU requirements, are you planning to use cellpose with it? that would be helped with the GPU but again isn't necessary. 

btw we are moving away from using conda environments for suite2p, so you should be able to install suite2p only with pip soon (update within the week). closing this issue but please comment if you have questions
