### ISSUE TITLE
Running cellpose through suite2p

### ISSUE THREAD

**Issue by ngf7** [MouseLand/suite2p#681]
I am attempting to perform anatomical identification of ROIs in suite2p using 'anatomical_only' parameter. On my first try, setting the parameter to a non-zero value and running suite2p, I received an error that cellpose could not be found and was not used. I then installed cellpose, created an environment for it, and re-ran suite2p but the same error occurred. Are there additional steps in this installation I have missed? Thanks in advance!

**Comment by carsen-stringer** [comment]
hmm is cellpose in the environment you're running suite2p in? things you install in your base environment aren't available to other environments. In your suite2p environment, you can say `pip install cellpose` (there's no need to make a new environment unless you're having issues)

**Comment by dba91** [comment]
Can confirm this worked for me!

**Comment by ngf7** [comment]
`pip install cellpose` in suite2p environment worked. My understanding of python environments was lacking. Thanks for the help!
