### ISSUE TITLE
Option to load z-stack and compute z-corr in run menu?

### ISSUE THREAD

**Issue by marysethomas** [MouseLand/suite2p#683]
I have been using the View Registered Binary tab to compute z-corr on a reference z-stack, however this becomes quite time intensive with multiplane data. Would it be possible to add an option to the Run Suite2p menu to load a z-stack and automatically run z-corr on all planes in the recording?

Alternatively, would there be another way to run z-corr on all planes at once?

Appreciate all the work you're doing!

**Comment by carsen-stringer** [comment]
I'd recommend doing this in a jupyter-notebook:
```
from suite2p.registration import compute_zpos
for iplane in range(nplanes):
    ops=np.load('plane%d/ops.npy'%iplane, allow_pickle=True).item()
    ops, zcorr = compute_zpos(zstack, ops)
```

**Comment by marysethomas** [comment]
Thank you!
