### ISSUE TITLE
Bruker bidirectional multiplane recordings

### ISSUE THREAD

**Issue by marysethomas** [MouseLand/suite2p#684]
Hello, we are using a Bruker 2p system where we can record multiplane data in either sequential (1 2 3 1 2 3) or bidirectional mode (1 2 3 3 2 1). I understand that Suite2p loads multiplane data sequentially. Would it be possible to accommodate bidirectional Bruker data?

**Comment by carsen-stringer** [comment]
I've added this option as  ops['bruker_bidirectional']. I'll close the issue, but please test it out. I haven't added it to the GUI but can if it's working

**Comment by marysethomas** [comment]
Hi @carsen-stringer, I'm so sorry but I don't know how to test this out without the GUI. Would you have a link to a tutorial anywhere about how to run Suite2p outside of the GUI?

**Comment by marysethomas** [comment]
Thank you. Sorry I have not had a chance to try this, I have not learned how to run Suite2p without the GUI yet. I will write back when I do.
