### ISSUE TITLE
Error When Trying to Run a Tiff through Suite2p 

### ISSUE THREAD

**Issue by DevCooper831** [MouseLand/suite2p#686]
Hi :)
I only have very beginner coding skills and am a bit beyond my depth in this project. 

A little background on the data I'm working with - I have taken a kinetic image from one of our microscopes, which exports from Gen5 as an mp4 video, and converted it to individual pngs using ffmpeg so that I can open it in Fiji. Once I opened the pngs as a stack in Fiji, I saved it as a single Tiff file. This is the file I am trying to run through the suite2p pipeline. 

The tiff file is alone in its own folder on my desktop because I wanted to try and keep the pathway as simple and clean as possible; especially since I don't really know what I'm doing. I also didn't change any of the default setting except the fs; I tried that as both 10 (default) and 1 (I think that's what mine is supposed to be).  Either way, I received the below output & error when I tried to run suite2p:

{'data_path': ['/Users/devoncooper/Desktop/ms4a1_1-tif'], 'subfolders': [], 'save_path0': '/Users/devoncooper/Desktop/ms4a1_1-tif', 'fast_disk': '/Users/devoncooper/Desktop/ms4a1_1-tif', 'input_format': 'tif'}
tif
** Found 1 tifs - converting to binary **
>>>ERROR<<<
Traceback (most recent call last):
  File "/Users/devoncooper/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/Users/devoncooper/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/devoncooper/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module>
    main()
  File "/Users/devoncooper/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/Users/devoncooper/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 404, in run_s2p
    ops0 = io.tiff_to_binary(ops.copy())
  File "/Users/devoncooper/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/io/tiff.py", line 184, in tiff_to_binary
    ops1[j]['meanImg'] += im2write.astype(np.float32).sum(axis=0)
ValueError: operands could not be broadcast together with shapes (860,1198) (860,1198,3) (860,1198) 
Interrupted by error (not finished)

As I said previously, I have only very basic skills so I'm not sure what is causing the issue. Maybe its my file format, or some setting somewhere, or something completely different that I just don't have the expertise to know that it may cause an issue. I am hoping there is a fairly simple explanation. My goal is to be able to use this pipeline so that my lab mates and I don't have to circle cells/ROIs by hand in Fiji anymore when analyzing Calcium Imaging data, so any help is very much appreciated! 

Thank you so much :)
~Devon

**Comment by carsen-stringer** [comment]
ah I think you're saving your tiffs with multiple channels? is there a way to save a grayscale tiff in fiji? if you split the color channels, you can save one of them (they should all be the same if they are grayscale), or you can combine them if you need to: https://sites.google.com/site/learnimagej/tutorials/converting-image-formats

closing the issue but please let me know if it's not working
