### ISSUE TITLE
ROI dtx parameter questions: diameter

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#688]
Hello!
I'm doing a systematic assessment to determine the ROI dtx parameters for my data set. My question is in regards to RIO "diameter" in this post:
- Is "diameter" one factor that is used to determine the "good" from "bad" cells?
- If different "diameter" values are used on the same data set to grow the ROIs, in what ways would the ROIs differ? For instance, I ran suite2p with diameter = 12 (default). Then, I ran suite2p with diameter = 16. Then, I ran suite2p with diameter = 20. In this situation, how should the ROIs differ between the runs after processing?
- Where can I find the ROI diameters after processing?
- When I set diameter = 12,16,20 how is suite2p using this input to grow the ROIs? When I tried this, the post-processed imaging results were no longer a square but larger horizontally. Why is this? 

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
diameter is no longer used in the pipeline (unless you want to run cellpose). However if you have two diameters in a list, the pipeline will use that as the "aspect ratio" of the imaging field of view (like you imaged more um/pixels in one direction) and will reshape for post-processing (like classifying, but only for good vs bad aspect_ratio, not for anything else) and visualizing in the GUI

if you want to set the approximate spatial scale, please use the "spatial_scale" parameter. to get more ROIs, decrease the "threshold_scaling" parameter

**Comment by sarahapark** [comment]
Hmmm... What is "cellpose"?

**Comment by kir0ul** [comment]
> Hmmm... What is "cellpose"?

http://www.cellpose.org/

**Comment by sarahapark** [comment]
Very cool! Thanks for the link to cellpose!

**Comment by sarahapark** [comment]
For spatial_scale, 1=6 pixels, 2=12, 3=24, 4=48. Can we use non-integer inputs, like 1.5? 

For threshold_scaling, is this referring to thresholding the ROI size (number of pixels), or thresholding the fluorescent transient of the ROI?
