### ISSUE TITLE
ROI dtx parameter question: connected

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#689]
Hello!
I'm doing a systematic assessment to determine the ROI dtx parameters for my data set. My question is in regards to "connected." 
- The suite2p manual says "connected" is to determine "whether or not to require ROIs to be fully connected (set to 0 for dendrites/boutons)." When connected = 1 (default), what can we expect to be true for all the ROIs? Will all the pixels of each ROI be connected? When connected = 0, what can we expect to be true for all the ROIs? Can we expect ROIs with holes in the middle? Can we expect pixels of an ROI to be disconnected? Can we expect 2 disconnected ROIs to be a single ROI?

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
hey sarah, your interpretation is correct, but this parameter only works for the old detection algorithm. 

In the new algorithm which is now default and recommended, we grow ROIs a few pixels at a time, so it is unlikely to produce unconnected ROIs, although it is possible

**Comment by carsen-stringer** [comment]
hey sarah, your interpretation is correct, but this parameter only works for the old detection algorithm. 

In the new algorithm which is now default and recommended, we grow ROIs a few pixels at a time, so it is unlikely to produce unconnected ROIs, although it is possible

**Comment by sarahapark** [comment]
Hi Carsen,
Thanks for the response! Will I be running the most recent algorithm if I run the usual update (pip install suite2p --upgrade)?

Thanks!
Sarah

**Comment by sarahapark** [comment]
Hi Carsen,
I saw another issue posted by another user (https://github.com/MouseLand/suite2p/issues/695#issue-948762391) that showed the suite2p parameter dialog box. Mine looks very different. I think mine is the older version. How do I get the updated version?

![image](https://user-images.githubusercontent.com/51828933/126494058-7a501733-2023-405b-9319-1a7affb33841.png)

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
clone the github repo and install it directly:
```
git clone https://www.github.com/mouseland/suite2p.git
cd suite2p
pip install -e .
```

**Comment by sarahapark** [comment]
Hi Carsen,
On Git Bash, should I be in the old suite2p directory (cd suite2p) before I run the code you shared with me? Or, does it not matter? Should I uninstall the old version of suite2p?

Thanks,
Sarah

**Comment by sarahapark** [comment]
Hi,
I was able to install the new suite2p!
I named the old suite2p directory as "suite2p_old" and on Git Bash, ran "git clone https://www.github.com/MouseLand/suite2p.git" which downloaded a new "suite2p" directory.
Then on Anaconda, I "cd suite2p" and then "pip install -e ."

The suite2p parameter dialogue box looks like  the one [here](https://github.com/MouseLand/suite2p/issues/695#issue-948762391) and I can now see the full directory with the tooltip like you mentioned [here](https://github.com/MouseLand/suite2p/issues/673). 

Sarah
