### ISSUE TITLE
Is the ROI image available in the output?

### ISSUE THREAD

**Issue by darioringach** [MouseLand/suite2p#69]
Is the image with detected ROI locations available in the output files?

**Comment by carsen-stringer** [comment]
You can export an svg of it by right clicking on the fluorescence trace plot and then choosing export. The top plots with the cells are the 'view box' views.  You can do the same in the visualize window.

**Comment by tomsains** [comment]
In addition to this the location of each of the segment centers is stored in the output file - stats.npy. This is a python dict where the key "mid" gives the x,y coordinates of the cell. 

Thought I would put this this here in case someone clicks on this issue searching for the segmentation output.

**Comment by carsen-stringer** [comment]
thanks Tom, I've added the documentation of all the outputs to the [wiki](https://github.com/MouseLand/suite2p/wiki/Outputs). please reopen this if there are more issues

**Comment by adilgkhan** [comment]
Thanks for the great work guys! 
I'd like to re-open this issue about outputting ROI images. It would be great if you could output the actual ROI masks as defined on the image. I don't mean the SVG image, or just the centre, diameter etc, as descried above. Instead, if your recording was 512x512 pixels then the 512x512 matrix with a 1 in each pixel where roi 1 exists, 2 for each pixel with roi2 etc. Pixels with multiple ROIs could be set to NaNs for simplicity (they are not used for extraction of signals anyway). This would be super useful!

**Comment by carsen-stringer** [comment]
The masks are output in stat in 'ypix' and 'xpix'. The non-overlapping pixels are the ones not in overlap (~stat[n]['overlap']). To produce the image described, 
```
stat = np.load('../../TX4/stat.npy')
ops = np.load('../../TX4/ops.npy')
ops = ops.item()

im = np.zeros((ops['Ly'], ops['Lx']))

for n in range(0,ncells):
    ypix = stat[n]['ypix'][~stat[n]['overlap']]
    xpix = stat[n]['xpix'][~stat[n]['overlap']]
    im[ypix,xpix] = n+1
    
plt.imshow(im)
plt.show()
```

**Comment by adilgkhan** [comment]
Thank you, this is perfect!
