### ISSUE TITLE
Registration question: Using imaging data of one data set to register the imaging data of another data set

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#690]
Hello,
I would like to use the imaging data of one data set, which I will call "data 1," to register the imaging data of another data set, which I will call "data 2." So, "data 1" would represent the frames for "nimg_int." I would like the results of the registration to exclude "data 1" since "data 1" is not part of the original "data 2." Is this possible? How should I setup the registration parameters to make this possible?

If it's not possible to exclude "data 1" from the suite2p results, is there a way to decipher the results only for "data 2"?

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
so you want to use the reference frame from "data 1"? You can do this in a jupyter-notebook using the `ops.npy` created from "data 1" on "data 2" (first when running "data 1" set ops['roidetect']=0 if you don't want ROI detection and trace extraction to run, when running "data 2" set ops['roidetect']=0 and ops['do_registration']=0 so only the binary is created):
```
from suite2p.registration import register_binary

ops1 = np.load('data1/suite2p/plane0/ops.npy', allow_pickle=True).item()
ops2 = np.load('data2/suite2p/plane0/ops.npy', allow_pickle=True).item()
ops2 = register_binary(ops2, refImg=ops1['refImg'])
```

if you don't want to run anything on data1 and know how to get the random frames (like from the tiffs), you can use the compute_reference function directly

```
from suite2p import default_ops
from suite2p.registration.register import compute_reference
ops = default_ops()
# load frames somehow
refImg = compute_reference(ops, frames)
```
