### ISSUE TITLE
PyQT error with new install

### ISSUE THREAD

**Issue by chaplinta** [MouseLand/suite2p#691]
Hi,

I am getting PyQT errors straight out of a new install of suite2p when running the GUI. Specifically:

AttributeError: module 'PyQt5.QtGui' has no attribute 'QPushButton'

This is with conda 4.10.3 and Windows 10.

Any idea what is going on here? It seems like there was a recent change to PyQt5, not sure if conda is getting the right version.

Thanks,
Tristan

**Comment by kabilar** [comment]
Hi @chaplinta,

I had this issue today as well on Ubuntu 18.04 and python 3.7.5.  I'm not exactly sure what is going on, but the following python package versions seemed to solve the problem for me.  

```
PyQt5==5.15.1
PyQt5-sip==12.8.1
pyqtgraph==0.11.0
```
Hope this helps.

Kabi

**Comment by chaplinta** [comment]
Thanks! That seems to work!

**Comment by carsen-stringer** [comment]
that was a fun import change :) I think I found all the problematic imports, closing the issue but let me know if you have problems

**Comment by kclgeorge** [comment]
Thanks for the suggestion. I have been trying to install version 0.9.3 (after uninstalling v0.10.1) and was getting the same error. 

Installing the versions of those packages worked :)
