### ISSUE TITLE
Registration Issue with Multiplane-Multichan Dataset, only on newer versions of S2P

### ISSUE THREAD

**Issue by dba91** [MouseLand/suite2p#692]
Hi there!

I'm trying to access a newer version of S2P to be able to use cellpose but running into issues during registration.

Dataset:
Several 2P tiff files that have been recorded with 3 planes and 2 channels. Running into the same issue whether I process multiple tiffs together (they were sequentially recorded from the same locations) or a single one.

S2P:
An older version of the program (so far older that the "suite2p --version" command doesn't work) handles the registration just fine.

Because I wanted to access cellpose to pick up non-responsive cells, I tried upgrading s2p. When I upgrade on pip, I run into this bug: https://github.com/MouseLand/suite2p/issues/645

But if I revert back to v0.9.03 then I can run the program (and have cellpose) until the registration stage when I get this error: 
![image](https://user-images.githubusercontent.com/31355751/124978118-346d9100-dfe6-11eb-9072-96df1d56ad3e.png)
Any ideas of why this shape error comes about? Like I said, this data process just fine with the old version of s2p. (I am deleting the files in between runs by the way, so it's not that issue).

**Comment by carsen-stringer** [comment]
sorry I can't reproduce this error we have a line, just prior, that forces the shape to be the same to avoid this problem:
```
    d1 = fft.fft(frames[:, 1::2, :], axis=2)
    d1 /= np.abs(d1) + 1e-5

    d2 = np.conj(fft.fft(frames[:, ::2, :], axis=2))
    d2 /= np.abs(d2) + 1e-5
    d2 = d2[:,:d1.shape[1],:]

    cc = np.real(fft.ifft(d1 * d2, axis=2))
```

can you try the latest github version of the code?

**Comment by carsen-stringer** [comment]
(and also give a pip list)

**Comment by dba91** [comment]
I got it to work! I tried the latest version (by changing my username I got around the bug I referenced in the code). Having some other issues running cellpose that I'll put into a post.
