### ISSUE TITLE
PyQt5 v.5.15.2

### ISSUE THREAD

**Issue by assolisc** [MouseLand/suite2p#693]
PyQt v.5.15.2 has divided the QtGui module into, QtGui, QtWidgets, and QtPrintSupport. Most of the GUI parts used in current  suite2p v.0.10.0 uses QtGui as if it still had all the modules together. Which causes the GUI interface to not launch.

**Comment by jennifer-sun** [comment]
Same issue here.

**Comment by alihaydaroglu** [comment]
same here. does anyone have a workaround? installing earlier versions of PyQt5 instead of 5.15.2 doesn't seem to solve it, the same error persists as early as 5.12, and earlier versions have other errors.

**Comment by brandonStell** [comment]
This worked for us:
https://github.com/MouseLand/suite2p/issues/691#issuecomment-876728260

**Comment by carsen-stringer** [comment]
this should be working now on the github version of the code, will make a new pip soon too

**Comment by alihaydaroglu** [comment]
Thank you @brandonStell for the workaround and @carsen-stringer for the fix!
