### ISSUE TITLE
Cellpose failing for unknown reason

### ISSUE THREAD

**Issue by dba91** [MouseLand/suite2p#695]
I am trying to run cell pose on my dataset but it is failing on a late step of the process. Here is what the console says when I run it on the GUI:
![image](https://user-images.githubusercontent.com/31355751/126349575-934333d5-7f04-4ca1-ac3b-2048e2d58d3b.png)
This is happening on multiple datasets, but notably they all have multiple planes (not close together) and multiple channels. I run them with the following settings, and it otherwise works (it just skips the cellpose step)
![image](https://user-images.githubusercontent.com/31355751/126349913-192a4fd0-c698-469b-ab5c-a97141a8a1f6.png)
Wondering if there is any way to fix this? I want to use cellpose because the max projection image shows me a lot of cells that aren't being segmented out with the normal s2p algorithm.

**Comment by dba91** [comment]
Dang, now I'm getting this error:

**Comment by carsen-stringer** [comment]
hmm did you get any error messages when creating the environment? you could try `conda upgrade scipy`

**Comment by carsen-stringer** [comment]
oh actually may be a bug with the latest scipy: https://stackoverflow.com/questions/67377972/filenotfounderror-could-not-find-module-when-using-jupyter-notebook

could you try `conda install scipy=1.6.2`

**Comment by carsen-stringer** [comment]
can you try `pip install scipy==1.6.2`?

I think it's an issue with the conda version of scipy on windows

**Comment by shihje** [comment]
It says that requirement is already satisfied. I did realize that I have 2 suite2p folders in my directory. `pip install -e .` still does not work with the setup files in either folder, but running `suite2p` in the most recently installed one does work and the GUI is back. It seems like I was having a slightly different issue. Thanks for helping with the troubleshooting!

**Comment by carsen-stringer** [comment]
@shihje it looks like you didn't clone the repo? if you want to use the latest version from any directory you need to clone the github repository using git or github desktop, then run pip install -e . there. Going to close this issue for now let me know if this doesn't work, glad you have it working!

**Comment by alemessurier** [comment]
I'm having the same issue - seems like cellpose finds ROIs, but then I get an error: 

> 
> creating new log file
> 2021-09-16 17:58:45,133 [INFO] WRITING LOG OUTPUT TO C:\Users\aml717\.cellpose\run.log
> {'data_path': ['C:/DATA/raw/NDNF6172/20200802'], 'subfolders': [], 'save_path0': 'C:/DATA/reduced/NDNF6172/20210802', 'fast_disk': 'C:/DATA/reduced/NDNF6172/20210802', 'input_format': 'tif'}
> FOUND BINARIES AND OPS IN ['C:/DATA/reduced/NDNF6172/20210802\\suite2p\\plane0\\ops.npy']
> >>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
> NOTE: not running registration, plane already registered
> binary path: C:/DATA/reduced/NDNF6172/20210802\suite2p\plane0\data.bin
> NOTE: applying default C:\Users\aml717\.suite2p\classifiers\classifier_user.npy
> ----------- ROI DETECTION
> Binning movie in chunks of length 18
> Binned movie [4914,494,476] in 271.72 sec.
> Binned movie denoised (for cell detection only) in 589.48 sec.
> >>>> CELLPOSE finding masks in max_proj / mean_img
> !NOTE! ops['diameter'] set to 12.00 for cell detection with cellpose
> 2021-09-16 18:13:17,126 [INFO] >>>> using CPU
> 2021-09-16 18:13:17,456 [INFO] ~~~ FINDING MASKS ~~~
> 2021-09-16 18:14:38,035 [INFO] >>>> TOTAL TIME 80.58 sec
> >>>> 161 masks detected, median diameter = 9.30 
> Detected 161 ROIs, 80.98 sec
> >>>> CELLPOSE estimating masks in anatomical channel
> 2021-09-16 18:14:41,036 [INFO] >>>> using CPU
> 2021-09-16 18:14:41,106 [INFO] ~~~ ESTIMATING CELL DIAMETER(S) ~~~
> 2021-09-16 18:14:52,766 [INFO] estimated cell diameter(s) in 11.66 sec
> 2021-09-16 18:14:52,766 [INFO] >>> diameter(s) = 
> 2021-09-16 18:14:52,766 [INFO] [ 20.93 ]
> 2021-09-16 18:14:52,766 [INFO] ~~~ FINDING MASKS ~~~
> 2021-09-16 18:15:32,864 [INFO] >>>> TOTAL TIME 51.76 sec
> >>>> 32 masks detected, median diameter = 18.80 
> ERROR importing or running cellpose, continuing without anatomical estimates
> ----------- Total 1010.81 sec.
> ----------- EXTRACTION
> Masks created, 0.72 sec.
> Interrupted by user (not finished)

This is with a fresh install of suite2p today, from the github repo. I ran:

conda env remove -n suite2p
git clone https://github.com/MouseLand/suite2p.git
conda env create -f environment.yml
conda activate suite2p
pip install -e suite2p  (I get an error if I run 'pip install -e' without 'suite2p')
pip install cellpose  (I tried running without pip installing cellpose at first and got an error that cellpose wasn't installed)
pip install scipy=1.6.2
python -m suite2p

any ideas appreciated -thanks!
Amy
