### ISSUE TITLE
GUI suite2p options

### ISSUE THREAD

**Issue by jrclimer** [MouseLand/suite2p#70]
The GUI should allow for registration to be optional
The GUI doesn't appear to allow for GPU acceleration of registration
Setting maxregshift to 0 should prevent registration from executing

**Comment by carsen-stringer** [comment]
This has now been added - the option is called 'do_registration', set it to 0 to stop registration from running.

Yeah, we currently don't have GPU acceleration, but it is still relatively fast. Make sure that you choose the 'fast_disk' path to be an SSD, this will speed things up.
