### ISSUE TITLE
How to turn off sparse_mode

### ISSUE THREAD

**Issue by morfojin** [MouseLand/suite2p#703]
Hello! 
Sparse_mode is now activated by default, but there is no field to select/deselect it in the GUI. So how does one switch sparse_mode off?  
Thanks!

**Comment by carsen-stringer** [comment]
you will need to run suite2p in a jupyter-notebook, here's a link to one: https://github.com/MouseLand/suite2p/blob/main/jupyter/run_suite2p_colab_2021.ipynb
