### ISSUE TITLE
Deconvolution Settings

### ISSUE THREAD

**Issue by dkushinsky** [MouseLand/suite2p#704]
Hi suite2p team!

We are hoping to use the deconvolved data output from Suite2p but are wondering how to decide on and optimize the parameters of the baseline window and the kernel timescale to best fit our data in order to minimize the error rate between the true and inferred spiking. Do you suggest using a comparison of correlation coefficient between repeats of stimulus presentation (as from your paper) across different parameters in order to optimize the parameters to our data?
Just as background, we are recording in awake, head fixed mice in the visual cortex using GCaMP7f. 
Thanks for your help!

**Comment by carsen-stringer** [comment]
Good question, yeah we recommend maximizing the correlation coefficient between stimulus presentation repeats for finding tau. For finding the baseline window you can use a similar strategy but it in theory shouldn't make a large difference, but make sure it's at least as long as 5-10x tau.
