### ISSUE TITLE
Installation issues with llvmlite.dll

### ISSUE THREAD

**Issue by AbyFlores** [MouseLand/suite2p#708]
I'm trying to install, and I have the newest version of anaconda. I get this error:

  File "C:\Users\LurLab\anaconda3\envs\suite2p\lib\site-packages\llvmlite\binding\dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "C:\Users\LurLab\anaconda3\envs\suite2p\lib\site-packages\llvmlite\binding\ffi.py", line 191, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: llvmlite.dll

I've tried the following:
(suite2p) C:\Apps\suite2p-main>pip install llvmlite --upgrade
Requirement already satisfied: llvmlite in c:\users\lurlab\anaconda3\envs\suite2p\lib\site-packages (0.36.0)

Please advise?

**Comment by AbyFlores** [comment]
Found a solution for now :)

conda install -c numba numba
conda install -c numba llvmlite

https://github.com/numba/llvmlite/issues/650

**Comment by carsen-stringer** [comment]
hmm I didn't have this problem on windows but this has happened twice so I'm going to put the numba channel in the  environment.yml, that should fix it out of the box
