### ISSUE TITLE
Issue with custom classifier

### ISSUE THREAD

**Issue by elisabusha** [MouseLand/suite2p#709]
I built my own classifier using my iscell files; however, I cannot seem to get it to work. I tried loading it by doing Classifier>load>from file and selecting the file, but none of the ROIs change categories. Please assist.

**Comment by carsen-stringer** [comment]
did you apply the classifier by clicking the classifier probability box, entering your probability threshold, and clicking enter there? loading it does not immediately apply it, you have to trigger it with that box. if that's not working let me know and I'll reopen the issue

**Comment by landoskape** [comment]
I had trouble with this issue too and couldn't figure out how to apply my new classifier. I added an explanation reflecting @carsen-stringer's response to the documentation so it is easy to find.
