### ISSUE TITLE
running suite2p on 1p miniscope imaging

### ISSUE THREAD

**Issue by rajatsaxena** [MouseLand/suite2p#719]
I wanted to check the development and testing of suite2p on the 1p dataset. I have many datasets collected using UCLA miniscope and would be more than happy to share the data. For now, `meanImg` and `enhanced meanImg` don't look great for me. What works is using `cellpose` (anatomical only=1) on the max projection

**Comment by carsen-stringer** [comment]
I have used the standard detection algorithm in suite2p with success on some open datasets. I've also tried making the spatial high-pass filtering sharper when doing that with `ops['spatial_hp_detect']`, the default is 25, but you can make this even smaller if want. But if you're finding all the cells with anatomical detection that's great
