### ISSUE TITLE
Scipy requirement should be >=1.4.0

### ISSUE THREAD

**Issue by DoriMG** [MouseLand/suite2p#721]
I just did a clean install of suite2p in Anaconda. However, upon running it, I got the following error:

`  File "C:\Users\User\Anaconda3\lib\site-packages\suite2p\registration\utils.py", line 8, in <module>
    from scipy.fft import next_fast_len#, fft2, ifft2
ModuleNotFoundError: No module named 'scipy.fft'`

I believe this is due to the change from `from scipy.fftpack import fft` to `from scipy import fft` in SciPy 1.4.0. Could you add the requirement scipy>=1.4.0?

**Comment by mcarbotano** [comment]
I got the same issue after upgrading to latest version.
