### ISSUE TITLE
manual ROIs have no signal or extremely low SNR

### ISSUE THREAD

**Issue by tthgithub** [MouseLand/suite2p#722]
Hi, I have found that when I manually label cells, often I will end up with 0 signal in the F output for those cells, and instead I will see robust signal in the neuropil output for those manually picked cells.. And it seems to maybe be related to whether the manual ROI is smaller or larger than the cell body? 

Then secondly, in the cases where I do get signal in the F output, the SNR of the manually picked cells seems to be much much worse than automatically picked cells. I have tested this so if I remove a nicely automatically picked cell, then re-pick it manually, the signal and SNR are way worse for the same cell… 

Maybe this has something to do with the round manual ROIs not tracing the cell outline better or something? But I would have thought the raw F data, as opposed to deconvolved, should still be okay.

Do you have any idea why this might be happening and how to fix it?

Thanks!!

**Comment by tthgithub** [comment]
Hi, just wanted to ping on this issue, please help! thanks!

**Comment by carsen-stringer** [comment]
I think this is related to this issue #651 , please comment there if you have more questions
