### ISSUE TITLE
lost cells on edges of field of view

### ISSUE THREAD

**Issue by tthgithub** [MouseLand/suite2p#723]
Hi, I have found that on some runs I have found that the area for automatically picked cells, and also when I go to manually pick, is a square that is smaller than the entire field of view for some reason? So I end up losing a lot of cells around the edges? For instance, in mean image view, the picked cells are in this smaller square within it, and the circular edges around the square have cells but none that are picked (or can be picked manually). Then on the enhanced image it only shows that square region and not even the missing edges. Do you happen to have any idea why this happens and how to fix it?

Thanks!!

**Comment by tthgithub** [comment]
Hi, just wanted to ping on this issue, please help! thanks!

**Comment by carsen-stringer** [comment]
this is a commonly recurring issue, please check out this info: https://suite2p.readthedocs.io/en/latest/FAQ.html#cropped-field-of-view
