### ISSUE TITLE
Error when running zcorr

### ISSUE THREAD

**Issue by marysethomas** [MouseLand/suite2p#726]
Hello, I have a new error when I try to run zcorr from the View Registered Binary menu. I can load my z-stack as usual, but when I click compute z position, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 724, in <lambda>
    self.computeZ.clicked.connect(lambda: self.compute_z(parent))
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 795, in compute_z
    ops, zcorr = registration.compute_zpos(self.zstack, self.ops[0])
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\registration\zalign.py", line 162, in compute_zpos
    cfRefImag = rigid.phasecorr_reference(
TypeError: phasecorr_reference() got an unexpected keyword argument 'pad_fft'
```

This is happening even with files that I have previously been able to compute zcorrs on. I am running the most recent version of suite2p from github.

Thanks in advance!

-Maryse

**Comment by owenrandlett** [comment]
Hi - I am getting the same error.

Thanks,
Owen

**Comment by carsen-stringer** [comment]
sorry about that, please try installing the latest github version and see if it works. closing because hopefully it's fixed

**Comment by marysethomas** [comment]
Update: I was able to resolve the second error message (TypeError: can't convert np.ndarray of type numpy.uint16) by adding Line 26: data = data.astype(np.float32) in registration\utils.py
