### ISSUE TITLE
ROI results look strange with updated suite2p

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#728]
Hello!
I updated suite2p recently, and with it, the ROI results look very strange compared to the ROI results with the older suite2p version. Are these results expected? What should I change in the parameters to improve the ROI selection with the updated suite2p version?

Results with updated suite2p. Only diameter was changed to 16,16:
![image](https://user-images.githubusercontent.com/51828933/133628421-da6d71e5-6150-464c-8e35-db3451fa4de8.png)

Corresponding ops.npy file (updated suite2p version):
![image](https://user-images.githubusercontent.com/51828933/133628552-3d8086c8-0a9b-49ec-84ee-50a4a02ac170.png)

Results with old suite2p version:
![image](https://user-images.githubusercontent.com/51828933/133628667-fef0afca-66a1-4224-bb39-8712476ac9bf.png)

Corresponding ops.npy file (old suite2p version):
![image](https://user-images.githubusercontent.com/51828933/133628836-a6ae96e6-01e1-4ba2-8a99-1f9aa20191ac.png)

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
hmm can you load the `ops.npy` that is output at the end for each and see if there are any other differences? There are hidden parameters here potentially that changed

**Comment by sarahapark** [comment]
Hi Carsen,
These images are from File > Run Suite2p > Load ops file. Did you mean load the ops.npy another way (i.e., Classifier > Load > from file)?

Sarah

**Comment by sarahapark** [comment]
Hi,
Just checking in with you about a resolution to this problem. 

Sarah

**Comment by sarahapark** [comment]
I uninstalled and reinstalled Anaconda3 and then downloaded suite2p v0.7.0. Then, I ran the following on the command line:
>>cd suite2p
>>conda env create -f environment.yml
>>conda activate suite2p
>>pip install suite2p
>>python -m suite2p
Then, I got this error message: 
![image](https://user-images.githubusercontent.com/51828933/139917740-f66c36d4-9cc5-4e88-99b2-768cd7a9f2f2.png)

Is there a way to run the older versions of suite2p?
Thank you!

**Comment by carsen-stringer** [comment]
Hey Sarah, have you tried running the new suite2p with the settings you found were advantageous? it looks like you had ops['sparse_mode']=0 (this runs the old sourcery algorithm) for the segmentation you deemed optimal. Other than the ops['denoise'] parameter, the suite2p results should be similar across releases, if the input parameters are the same.

**Comment by sarahapark** [comment]
Hi Carsen,
I saved an ops.npy file from the old suite2p version and ran it on the new suite2p (v.0.10.3). The ROI dtx looks a lot better and more promising! (In the below figure, I ran only 500 of 6000 frames, so there are only a few ROIs detected. I will run the full 6000 frames to see if the ROI dtx is the same with the new suite2p compared to the old suite2p results!)

![image](https://user-images.githubusercontent.com/51828933/139946972-3ac83399-4049-45b8-9f1b-832e13685225.png)


It definitely seems like there are hidden parameters that are affecting my ROI detection. Could you provide instructions on how I can edit ops['sparse_mode']=0 in my version of the suite2p code?

Thank you!

**Comment by sarahapark** [comment]
Hi Carsen,
I ran the full 6000 frames using the ops.npy from the old suite2p. The results are different, however. The new suite2p using the old ops.npy yield different numbers of good and bad ROIs compared to the results with the old suite2p. The ROIs are also not as crisp and the mean image is also blurry with the new suite2p using the old ops.npy compared to the results with the old suite2p. The registration metrics are the same for the results using the old suite2p and new suite2p. 

MOUSE 1:
Results with old suite2p (ROIs only):
![image](https://user-images.githubusercontent.com/51828933/140067499-ee003d11-8830-41ad-9f85-9cec131a1c78.png)
Results with old suite2p (ROIs + mean image):
![image](https://user-images.githubusercontent.com/51828933/140067522-3848e8a0-0b06-435f-b1b9-553544841b23.png)

Results with new suite2p + old ops.npy (ROIs only):
![image](https://user-images.githubusercontent.com/51828933/140067571-b7dafa82-f65a-4a17-be9a-4174eca6b136.png)
Results with new suite2p + old ops.npy (ROIs + mean image):
![image](https://user-images.githubusercontent.com/51828933/140067590-37917199-7fa8-4152-bb66-d99d28bc4c7c.png)

MOUSE 2:
Results with old suite2p (ROIs only):
![image](https://user-images.githubusercontent.com/51828933/140069180-860144e4-728f-425b-9f70-45a1e5df248c.png)
Results with old suite2p (ROIs + mean image):
![image](https://user-images.githubusercontent.com/51828933/140069220-64308a3b-3f49-443e-9766-1bf121257d6b.png)

Results with new suite2p + old ops.npy (ROIs only):
![image](https://user-images.githubusercontent.com/51828933/140069104-cafad60f-0f5f-48dc-bb7d-762593fb2f3c.png)
Results with new suite2p + old ops.npy (ROIs + mean image):
![image](https://user-images.githubusercontent.com/51828933/140069276-166f10ba-42ed-4ff2-b1fe-b2f3c7e9b8d5.png)

The results using the new suite2p with the old ops.npy are usable. However, I am concerned that the ROI detection has changed and is not as crisp and the mean image is blurry. Could you provide some insight into these changes? What has changed in the code to cause the ROI detection to yield less crisp ROIs? Should I be concerned by the blurry mean image? Does a blurry mean image indicate worse registration? Is there is a way to return to the old ROI detection quality and old registration quality? 

To repeat a question from the previous post: It definitely seems like there are hidden parameters that are affecting my ROI detection. How do I edit my version of the suite2p code so that ops['sparse_mode']=0?

Thank you!

**Comment by carsen-stringer** [comment]
Hmm is the registration messed up? Have you watched the binary movie. There are 3 features that have been added since release v0.7 and are on by default, to turn them off, set `ops['norm_frames']=False, ops['denoise'] =False, ops['soma_crop']=False`.

To set these parameters, you do the same thing you did in that notebook, you can say e.g.

```
ops=default_ops()
ops['sparse_mode']=0
```

**Comment by sarahapark** [comment]
I checked the binary movie. Yes, the registration is messed up with the new suite2p. There is a lot of motion in the new suite2p result. There is basically no motion in the old suite2p result. For the results with the new suite2p, in the GUI ops, denoise = 0 and soma_crop = 0.

When running suite2p as a GUI using Anaconda3 (not through Linux on HPC), where do I enter `ops['norm_frames']=False, ops['denoise'] =False, ops['soma_crop']=False, ops['sparse_mode']=0`? Do I enter it before `python -m suite2p` in conda?

**Comment by carsen-stringer** [comment]
you cannot enter these in the GUI, you need to enter them in your
jupyter-notebook

**Comment by sarahapark** [comment]
Should I hard code the changes then using Jupyter Notebook? (I am trying to figure out how to access the suite2p code on Jupyter Notebook. What is the filename that needs the edits?)

I guess another way to go about this is to install an older version of suite2p. I've tried installing and running all the different versions available (i.e., `pip install suite2p==0.9.3` then `python -m suite2p`) on github with no success (i.e., ROIs looked weird). I'm wondering, is there a way to install an older version of suite2p that does not include recent changes to the code?

**Comment by carsen-stringer** [comment]
The jupyter-notebook you sent me before looked correct, you can run suite2p
from that notebook directly. Alternatively you can continue using this
older version

**Comment by sarahapark** [comment]
Which older version? I don't see a link or anything.

I think I created some confusion with my posts. My apologies if that's the case. The jupyter-notebook [code](https://github.com/MouseLand/suite2p/issues/758#issue-1035530443) that I sent before was to send suite2p jobs through a Linux VDI node to a HPC. This current post is me trying to get suite2p working as a local GUI on Windows. Eventually, I would like to make it possible to run suite2p through Linux on the HPC and as a local GUI on Windows. 

So, again, this post is about problems with using suite2p as a local GUI on Windows. If you could provide instructions on what I can do to fix the registration and ROI dtx problem, I would really appreciate it! Thank you!

**Comment by sarahapark** [comment]
Hi Carsen,
I was able to pull up the ops.npy files on Jupyter Notebook. Here are the files for old suite2p (nice ROIs, good registration), new suite2p (weird ROIs), new suite2p + old ops.npy (ok ROIs, bad registration). The parameters colored in cyan are different between runs and those colored in yellow are missing in one or both of the other runs. What is your take on the ops.npy comparison? Thank you!

[Old suite2p 0p9p3.docx](https://github.com/MouseLand/suite2p/files/7478348/Old.suite2p.0p9p3.docx)

[new suite2p 0p10p3.docx](https://github.com/MouseLand/suite2p/files/7478352/new.suite2p.0p10p3.docx)

[New suite2p 0p10p3 w old ops.docx](https://github.com/MouseLand/suite2p/files/7478353/New.suite2p.0p10p3.w.old.ops.docx)

**Comment by carsen-stringer** [comment]
The only thing that has changed for registration (which is what was
worrying me) is the 'norm_frames' parameter, you need to set that to False
to replicate the old registration.

But otherwise, what it looks like from your runs, you aren't using the
newest suite2p version in "new+old" (it says 0.9.2), and also you didn't
re-run registration, so I don't know why the mean image changed, maybe
there's a bug in that version with the mean image. You have to delete the
whole suite2p folder to force re-run registration. Otherwise you are double
running registration if you do force it to run (suite2p is running on that
"data.bin" file and overwrites it during registration).

**Comment by sarahapark** [comment]
Hi Carsen,
How do I change "norm_frames"? I don't see it as a parameter that can be changed in the ops GUI window.

For "new+old ops" results, I was confused about the version (0.9.2) also. I assumed ops.npy had stored the old ops file suite2p version instead of the version of suite2p it's running on. Before entering `python -m suite2p` and running new+oldops, I checked the suite2p version and it was the most recent one, 0.10.3.

I did re-run registration. In the ops parameter window, I left do_registration=1 before running "new+oldops." This (do_registration=1) is default and I have not changed it for any jobs while we've been troubleshooting. (In the attached .docx files in my previous post, the ops.npy output shows do_registration=1.) Before running any job, I delete any old suite2p results from the old save_path or create a brand new save_path directory. I do not think "new+oldops" was reading an old data.bin file. 

I will re-run these same conditions again and run some extra tests to make sure I didn't make any mistakes. 

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
You need to run suite2p in a jupyter notebook to gain access to all the
parameters.

That will not trigger registration if suite2p sees that registration is
already run, you have to delete the output files to force registration to
run again. In the log you'll see it say it skipped registration.

**Comment by sarahapark** [comment]
Which file is the log file among the output files?

**Comment by sarahapark** [comment]
I installed suite2p 0.9.3 and re-ran suite2p. The ROIs were weird and registration looked good. The output files were saved into a new directory. The ops.npy shows that _'suite2p_version': '0.10.3'_ was used. (I don't know why it says it used version 0.10.3. Could you please explain why?) I see registration is listed in _'timing': {'registration': 787.5496752262115, 'registration_metrics': 66.0528314113617, 'detection': 103.0404782295227, 'extraction': 51.269567012786865, 'classification': 0.03774666786193848, 'total_plane_runtime': 1011.2071104049683}}, dtype=object)._, which means registration was performed.

![image](https://user-images.githubusercontent.com/51828933/140795547-1c1cfadc-0d3a-4bf9-be7b-638d3cd8e38c.png)
![image](https://user-images.githubusercontent.com/51828933/140795564-bdf11061-0e19-4c47-ae32-acba698e710f.png)

When suite2p 0.9.3 was re-run with an old ops.npy file, the ROIs were decent and registration looked bad. The output files were saved into a new directory. The ops.npy shows that _'suite2p_version': '0.9.2'_ was used. I don't see registration listed in _'timing': {'detection': 393.4436733722687, 'extraction': 59.931156873703, 'classification': 0.03054189682006836, 'total_plane_runtime': 454.58800435066223}_, which means registration was **not** performed.

![image](https://user-images.githubusercontent.com/51828933/140795589-8fe68104-7ff3-4934-9528-1c688f192791.png)
![image](https://user-images.githubusercontent.com/51828933/140795608-2a372b22-3523-49e5-a16d-da38f4a40bcf.png)

I don't fully understand which output files I'm supposed to delete. Could you please elaborate? I have a feeling if I delete the correct files as you instruct me to and learn to run suite2p in a jupyter notebook, then my weird ROI problem will be resolved. At least I hope so! Thank you!
Sarah

**Comment by maya-hopkins** [comment]
Hi @sarahapark I'm new to suite2P and having problems with ROI detection. Correct me if I'm wrong, but it looks like your imaging CA1? I am also imaging there - would you be open to sharing the old ops file you have been using that seems to be somewhat working? I'm only getting about 50% of my cells detected.

![image](https://user-images.githubusercontent.com/72874725/144295194-cc766ffa-9ee6-4712-b80b-b4552b9fc70b.png)

**Comment by sarahapark** [comment]
Hi Maya,
Yes, I'm imaging CA1. I'm happy to share my old ops.npy file. I am unable to attach it to this github message though because .npy files are not supported as attachments. Is there an email to which I can send the file? (I don't know if it's okay to share email addresses on github?? Please feel free to suggest a method of sending the file.)

An observation about your image. Your ROIs don't look like they are having the same problem as mine. Mine were donut-shaped and in small bits and pieces. Your ROIs are filled-in. It looks like not many cells were detected. Did you have a sparsely active CA1 image? The Suite2p algorithm detects only active cells that are above a threshold. 

In case this is helpful with your troubleshooting, can you send me a screenshot of the ops parameters that you used when suite2p detected the ROIs in your example data?
Thanks!
Sarah

**Comment by maya-hopkins** [comment]
Hi Sarah,

Sorry for the delay on this - you can email me the ops to maya.hopkins@nyulangone.org. After tinkering with it I think they were just sparsely activated and decreasing the threshold seemed to just increase the number of non-cells detected. 

Thanks so much,
Maya
