### ISSUE TITLE
Won't accept files if 'roidetect'=0

### ISSUE THREAD

**Issue by dbmulcahy** [MouseLand/suite2p#729]
Regardless of other parameters set in the ops file, if 'roidetect' = 0, registration will occur and it will display that the program has halted. However, in the GUI a window will pop up reading "Incorrect file, choose another?". I would like to do my ROI selection manually, how can I get suite2p to successfully process the image without doing automatic ROI detection?
![Error 2](https://user-images.githubusercontent.com/91093405/134068822-06883893-1dab-40af-9f5e-510d7d57b072.png)
 
![Error window](https://user-images.githubusercontent.com/91093405/134068826-0e52158b-17d7-4899-ab83-e9c51f7b9f38.png)

**Comment by carsen-stringer** [comment]
That error pops up because `stat.npy` doesn't exist exactly because you didn't run ROI detection. The GUI doesn't currently support empty files, but if you implement it we'll accept it as a pull request. this is not a priority though since most users run ROI detection
