### ISSUE TITLE
Allowing other image formats?

### ISSUE THREAD

**Issue by darioringach** [MouseLand/suite2p#73]
Is there a uniform interface to other image formats?  
Would it be difficult of offer one?
--
Dario

**Comment by marius10p** [comment]
Right now it's only tiff and h5. 

Step one of the pipeline is to write data into a binary file on a fast local ssd. We can offer an option to plugin your own function for doing this conversion. Would that work?

**Comment by darioringach** [comment]
That may work... but let me see first if I can add native h5 or big Tiff to Scanbox.

**Comment by darioringach** [comment]
How should data be organized in h5/tiff for more than one channel and more than one optical plane?

**Comment by carsen-stringer** [comment]
We currently don't have incremental loading for big tiff, but that should be easy to add. h5 may be your best option if it's straightforward.

The organization of multiplane and multichannel that is currently supported is interleaved:
plane1_chan1_time0, plane1_chan2_time0, plane2_chan1_time0, plane2_chan2_time0, ...

**Comment by darioringach** [comment]
Do I need to do anything special for suite2p to process h5 files?  

I have:

h5disp('gq2_000_000.h5')
HDF5 gq2_000_000.h5 
Group '/' 
    Dataset 'data' 
        Size:  512x796x3892
        MaxSize:  512x796xInf
        Datatype:   H5T_STD_U16LE (uint16)
        ChunkSize:  512x796x1
        Filters:  none
        FillValue:  0

This is the only file in the data path.  But I get an index out of bounds error in get_tif_list (there are not tifs in the data path -- just h5)

**Comment by marius10p** [comment]
pip install suite2p --upgrade 
There is a separate button for using h5 files.

**Comment by darioringach** [comment]
Thanks...  Hmmm...  Button does not allow selection of a folder.  Do I need to select the file?

**Comment by carsen-stringer** [comment]
Yes it accepts only the file name, then use the default key name 'data' (you'll see it pop up)

**Comment by carsen-stringer** [comment]
sorry the shape of the matrix should also be time x pixels x pixels. I'll add this to the documentation

**Comment by darioringach** [comment]
Ok...  file dimension is now [3892 x 512 x 796].

So now, I get:

time 103.7649. Wrote h5py to binaries for 1 planes
computed reference frame for registration
time 545.7987. Registration complete
[12 12]
===== 2018.08.27 11:08:01 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\dario\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\dario\Anaconda3\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\dario\Anaconda3\lib\site-packages\suite2p\__main__.py", line 32, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\dario\Anaconda3\lib\site-packages\suite2p\run_s2p.py", line 138, in run_s2p
    ops1[k] = utils.get_cells(ops1[k])
  File "C:\Users\dario\Anaconda3\lib\site-packages\suite2p\utils.py", line 284, in get_cells
    ops, stat = celldetect2.sourcery(ops)
  File "C:\Users\dario\Anaconda3\lib\site-packages\suite2p\celldetect2.py", line 552, in sourcery
    U,sdmov, u      = getSVDdata(ops) # get SVD components
  File "C:\Users\dario\Anaconda3\lib\site-packages\suite2p\celldetect2.py", line 101, in getSVDdata
>>>ERROR<<<
    mov = get_mov(ops)
  File "C:\Users\dario\Anaconda3\lib\site-packages\suite2p\celldetect2.py", line 87, in get_mov
    mov[inds,:,:] = dbin[:, ops['yrange'][0]:ops['yrange'][-1], ops['xrange'][0]:ops['xrange'][-1]]
ValueError: shape mismatch: value array of shape (50,263,3639) could not be broadcast to indexing result of shape (50,528,7281)
Interrupted by error (not finished)

Same file, in Tiff, works fine...

**Comment by darioringach** [comment]
Array size is 3892 (frames) x 512 (row) x 796 (cols) (just one plane and one channel)
Is this not right?

**Comment by carsen-stringer** [comment]
Should be fine... Let us know if you get the error again.

**Comment by neurodroid** [comment]
PR #74 supports some additional non-tiff image formats (ThorImage, PrairieView) but requires an additional module.

**Comment by carsen-stringer** [comment]
there is a 'save_mat' option now in the GUI.

**Comment by darioringach** [comment]
For multiple planes & channels, how should the h5 file be formatted?

We run a two plane experiment with one PMT channel and interleaved the planes, but kept the format the same as before:

>> h5disp('zd42_000_000.h5','/data')
HDF5 zd42_000_000.h5 
Dataset 'data' 
    Size:  796x512x7101
    MaxSize:  796x512xInf
    Datatype:   H5T_STD_U16LE (uint16)
    ChunkSize:  796x512x200
    Filters:  none
    FillValue:  0

But we got an error when running with nplanes = 2:

===== 2018.09.06 18:09:49 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\conda\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\conda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\conda\lib\site-packages\suite2p\__main__.py", line 32, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\conda\lib\site-packages\suite2p\run_s2p.py", line 118, in run_s2p
    ops1 = utils.h5py_to_binary(ops)
  File "C:\conda\lib\site-packages\suite2p\utils.py", line 127, in h5py_to_binary
    ops1[j]['meanImg'] += im2write.astype(np.float32).sum(axis=0)
KeyError: 'meanImg'
Interrupted by error (not finished)

Is the data size correct?  

Or should it have been nplanes x ncols x nrows x frames ?

What about multiple planes and channels?

**Comment by carsen-stringer** [comment]
Sorry there was a bug in the h5py multi-plane, multi-channel processing. It's been fixed now on the github and in the pip package. I've started writing the wiki which explains the file ordering that the pipeline expects: https://github.com/MouseLand/suite2p/wiki/Run-the-pipeline
