### ISSUE TITLE
Manual labelling - GUI stops responding, have to close/restart suite2p

### ISSUE THREAD

**Issue by generalciao** [MouseLand/suite2p#744]
File->Manual labelling. Draw 1 or 2 ROIs. At that point the "Save and Quit" button feels unclickable - clicks have no effect. Clicking on the "extract ROIs" button prints a short statement to the command line, to the effect of "extracted 2 ROIs in 2.5 seconds" or similar. After that the Manual labelling window gets a "waiting" spinner, or just becomes unresponsive, then Windows report "Not responding", and ultimately the entire suite2p GUI needs to be closed. 

Is this user error? I'm not sure what the correct procedures are, nor what to expect.

Related question: if I create new ROIs for missed cells, will suite2p learn from this? Akin to the classifier? I figure the classifier can only learn to classify what is detected, so probably the answer is "no". Then am I better off playing with the detection settings so that it finds too many, rather than too few cells, and then train the classifier from there? Thanks!

**Comment by marysethomas** [comment]
@generalciao In my experience the manual extraction can take tens of minutes (it scales with how much data you have). Once you click "Extract ROIs", go have a coffee and come back. Eventually the traces will appear in the right side of the window, that's when "Save and Quit" becomes clickable again.

**Comment by generalciao** [comment]
Dear @marysethomas thank you for the info. In your experience, does the command-line message such as "extracted 2 ROIs in 2.5 seconds" appear before or only after that waiting time you describe? I'll give this a try again shortly.

**Comment by carsen-stringer** [comment]
yes the duration is entirely dependent on the number of ROIs, because the slowest part is reading in the data, the multiplication of the masks with the data is not a limiting step unless you have many more ROIs. there is no usage of the original (non-manual) ROIs in this step.

I'm going to close this issue for now, thanks for the help @marysethomas
