### ISSUE TITLE
F_chan2 and Fneu_chan2 are not saved to .mat file

### ISSUE THREAD

**Issue by generalciao** [MouseLand/suite2p#747]
Fall.mat seems to contain all .npy outputs, except F_chan2 and Fneu_chan2. For convenience and consistency, it would be nice to include those in the Matlab out as well.

**Comment by carsen-stringer** [comment]
happy to take a pull request that implements this!

**Comment by marysethomas** [comment]
Pull request: https://github.com/MouseLand/suite2p/pull/785

**Comment by carsen-stringer** [comment]
this will be fixed with the red cell so closing this issue for now

**Comment by carsen-stringer** [comment]
actually implemented this separately for now since there was some refactoring since then
