### ISSUE TITLE
Tiff reading error on large dataset

### ISSUE THREAD

**Issue by jamscoopa** [MouseLand/suite2p#749]
Hey, I've been using S2P to process fairly large longitudinal GCamp7f data. I have previously had no issues running around 1.2 million frames loaded as multiple folders of single .OME files from a Bruker 2P system. I've increased this to around 1.5 million frames and now I cannot get through the initial conversion to binary without an error (below). I have tried running this on the previous working version and in a fully updated version of the software and dependencies with no luck. It crashes at different points each time often towards the end of the import (1 million + frames). There are no obvious differences in any frames around this point, and they were all acquired with the same settings. ScanImageTiffReader is version 1.4.1 for reference. Any help would be greatly appreciated.
Thanks
James

> >>>ERROR<<<
Traceback (most recent call last):

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main

>>>ERROR<<<
    "__main__", mod_spec)

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\runpy.py", line 85, in _run_code

>>>ERROR<<<
    exec(code, run_globals)

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>

>>>ERROR<<<
    main()

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main

    run_s2p(ops, db)

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 409, in run_s2p

>>>ERROR<<<
    ops0 = convert_funs[ops['input_format']](ops.copy())

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 440, in ome_to_binary

>>>ERROR<<<
    with ScanImageTiffReader(file) as tif:

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\site-packages\ScanImageTiffReader\__init__.py", line 173, in __init__

>>>ERROR<<<
    self.open(filename)

  File "C:\Users\johnsonjad\.conda\envs\suite2p\lib\site-packages\ScanImageTiffReader\__init__.py", line 222, in open

>>>ERROR<<<
    raise Exception(self.__ctx.log.decode("utf-8","strict"))

Exception: Invalid tiff.  Endian-ness check returned an invalid id.

**Comment by jamscoopa** [comment]
Hey Carsten. Yeah I've tested groups of individual tif folders in which the crash occurs (~200k files). and it works fine. It does appear to be a size or scale issue with the data set once it reaches 1million + files), and ideally due to the longitudinal aspect of the data it would be much more convenient (with the next steps) to run as a single set. I know there is an external tool which can align and index match but I'd rather get this working as is. 
Any ideas to help would be most appreciated.
James

**Comment by carsen-stringer** [comment]
please try ops['force_sktiff']=True so that it uses the `tifffile` package. you could also stack your tiffs, although that's really annoying.

could you also open an issue here: https://gitlab.com/vidriotech/scanimage-tiff-reader/-/issues

**Comment by jmdelahanty** [comment]
Hello @jamscoopa and @carsen-stringer ! I'm currently trying to build chunked datasets into HDF5/zarr from the individual tiff files that I can then run through Suite2p but am currently stuck on doing this properly. Since navigating/analyzing/moving around our image datasets (only 47k, hard to imagine 1 million images!!) as individual tiffs has been slow I'm hoping that we can just supply chunked datasets to Suite2p and run those instead. Have either of you done this chunking before/does it make sense to do so?
