### ISSUE TITLE
Batch processing + options files?

### ISSUE THREAD

**Issue by darioringach** [MouseLand/suite2p#75]
Is it possible to do batch processing?
Is it possible to save/load option files?

**Comment by carsen-stringer** [comment]
I've written a notebook for this. The ops are the settings that you would use for each recording, and then db is experiment specific (anything you assign to db overwrites the ops): https://github.com/MouseLand/suite2p/blob/master/jupyter/run_pipeline_batch.ipynb

Also please upgrade your pip, there were some bugs if some of the db fields were empty.

**Comment by marius10p** [comment]
This can be done running Suite2p from a script. 

For the GUI save/load, this is issue #80 and we'll do it soon. For GUI batch processing, this is issue #85, and is considered low priority.
