### ISSUE TITLE
Running suite2p on HPC server with Linux

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#753]
Hi,
I'm trying to run suite2p on a High Performance Computing system with Linux as the OS. I installed suite2p following [these ](https://suite2p.readthedocs.io/en/latest/installation.html)instructions. I got this message after typing **python -m suite2p**:
![image](https://user-images.githubusercontent.com/51828933/138130423-3964f76b-1393-4e6c-880f-7567f4580003.png)

Will this be a problem when running suite2p on Linux?

Also, some of the default parameters (i.e., **diameter**, **spatial_scale**) are not entered in the ops dialogue box, making me wonder whether I have the correct version of suite2p installed. Is there a way to find out whether I have the correct version installed?
![image](https://user-images.githubusercontent.com/51828933/138130893-59b8efec-966c-4d3e-ac94-0e996a8b28d8.png)

Thank you!
Sarah

**Comment by sarahapark** [comment]
Hi,
Suite2p is not completing the data processing on Linux, actually. It terminates prematurely. This might be a different problem, but I'm appending it to this post.

Thank you,
Sarah

**Comment by carsen-stringer** [comment]
if you type "pip list" please see what version of suite2p you have installed in that list, it does not look like you're using the latest version

please upgrade with "pip install suite2p --upgrade"

going to close this issue for now but I can reopen it if you still have issues with the latest version.
