### ISSUE TITLE
adding ROIs that are not found

### ISSUE THREAD

**Issue by anubhuthi** [MouseLand/suite2p#754]
Hi Carsen,
We recently started using suite2p. Its great, however we would love help on a few issues.
1. For some movies it does not find the cells (even in the not cells category). Is there a way to add one? Maybe add one to the not cells category that can then be moved to the cells category ?
2. Is it correct that suite2p will not accept dual channel movies? For the registration there is the option to register by channel 2. Do we interleave the movies and somehow upload both movies ?
Thanks !

**Comment by carsen-stringer** [comment]
yes, there is a manual labelling option in the GUI: https://suite2p.readthedocs.io/en/latest/gui.html#manual-adding-of-rois

and yes, suite2p expects these interleaved, unless you have Bruker ome.tiff single page tiffs: https://suite2p.readthedocs.io/en/latest/inputs.html#frame-ordering

**Comment by anubhuthi** [comment]
Thank you Carsen ! We did find additional documentation and figured it out.
Sorry I should have updated the forum.
