### ISSUE TITLE
cellpose error with two channel data

### ISSUE THREAD

**Issue by alemessurier** [MouseLand/suite2p#755]
Hi, I'm having the same issue described in issue #695 - when I run suite2p with two channels, the masks detected on the anatomical channel are detected but then thrown out (error message below). I don't get this issue with single channel data. I get this error from multiple installs on different computers, mac and windows. Was there a solution to the original issue that I'm missing? I updated scipy to 1.6.2, and pip installed cellpose in the environment. My current install is from the github version a week ago. Thanks!

<img width="651" alt="Screen Shot 2021-10-20 at 10 25 13 PM" src="https://user-images.githubusercontent.com/27868008/138200527-7d04b303-f3ab-49cf-b89b-c209fb1c3cfd.png">

**Comment by TheUwe** [comment]
Hi,
I have the same problem on Win10. I am looking at 2 channel data and need the anatomical channel for identifying the same cells across multiple days, even when they become inactive.
I tried creating a new environment, install the latest s2p version + pip installing cellpose. 
Did anybody find a solution, or knows if this worked in previous versions?
