### ISSUE TITLE
Running suite2p from Jupyter Notebook on a HPC

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#758]
_Hello!
I'd like to run suite2p from Jupyter Notebook on a HPC. I am looking at the code provided [here ](https://github.com/sarahapark/suite2p/blob/master/jupyter/run_pipeline_tiffs_or_batch.ipynb)and have some questions. The provided code starts like so:_

`import numpy as np`
`import sys`

# option to import from github folder
`sys.path.insert(0, 'C:/Users/carse/github/suite2p/')`
`from suite2p import run_s2p`

# set your options for running
`ops = run_s2p.default_ops()` # populates ops with the default options

_My Questions:_
_1) for `sys.path.insert(0, 'C:/Users/carse/github/suite2p/')`: Do I change the path to where suite2p is installed on the HPC?
2) for `ops = run_s2p.default_ops()`: If I want to change some options, how do I do that? i.e., I'd like to save the mat file and the registered tif file._

_Here's the next provided code:_

# provide an h5 path in 'h5py' or a tiff path in 'data_path'
# db overwrites any ops (allows for experiment specific settings)
```
db = {
      'h5py': [], # a single h5 file path
      'h5py_key': 'data',
      'look_one_level_down': False, # whether to look in ALL subfolders when searching for tiffs
      'data_path': ['C:/Users/carse/github/tiffs'], # a list of folders with tiffs 
                                             # (or folder of folders with tiffs if look_one_level_down is True, or subfolders is not empty)
                                            
      'subfolders': [], # choose subfolders of 'data_path' to look in (optional)
      'fast_disk': 'C:/BIN', # string which specifies where the binary file will be stored (should be an SSD)
    }
```

# run one experiment
`opsEnd=run_s2p.run_s2p(ops=ops,db=db)`

_My Question:_
_3) **`'data_path': ['C:/Users/carse/github/tiffs']`**: If I want to point to the path where the tiff files are located, is this the only line that needs to be changed?
4) What is h5py?_

_If I want to batch process, the provided code is this:_
# make a list of db's and loop over them
`db = []`
`db.append({'data_path': ['C:/Users/carse/github/tiffs']})`
`db.append({'data_path': ['C:/Users/carse/github/tiffs2']})`

for dbi in db:
    `opsEnd=run_s2p.run_s2p(ops=ops,db=dbi)`

_My Question:
5) Is there a max limit to the number of files that can be batch processed? The GUI limits batch processing to 9 files, I think._

_The last section of provided code is the save to section:_

## change the save directory from 'suite2p' to a chosen name
# note the fast_disk will always be in 'suite2p', just the save_path will change

`ops = run_s2p.default_ops()` # populates ops with the default options
`ops['sparse_mode'] = 1`
`ops['threshold_scaling'] = 3.0`
```
db = {
      'h5py': [], # a single h5 file path
      'h5py_key': 'data',
      'look_one_level_down': False, # whether to look in ALL subfolders when searching for tiffs
      'data_path': ['D:/DATA/GT1/singlechannel_half/'], # a list of folders with tiffs 
                # (or folder of folders with tiffs if look_one_level_down is True, or subfolders is not empty)
      'save_folder': 'suite2p_sparse_mode'
    }
```

# run one experiment
`opsEnd=run_s2p.run_s2p(ops=ops,db=db)`

_My Questions
6) If batch processing do I change the code to this?

`ops = run_s2p.default_ops()`
`ops['sparse_mode'] = 1`
`ops['threshold_scaling'] = 3.0`
`db = []`
`db.append({'data_path': ['D:/DATA/output']})`
`db.append({'data_path': ['D:/DATA/output2']})`
`opsEnd=run_s2p.run_s2p(ops=ops,db=db)_`

_Thank you!
Sarah_

**Comment by carsen-stringer** [comment]
there are no limits to batch processing in a notebook. you need to loop over the dbs, otherwise your final code looks good!
```
from suite2p import default_ops, run_s2p
ops = default_ops()
ops['sparse_mode'] = 1
ops['threshold_scaling'] = 3.0
db = []
db.append({'data_path': ['D:/DATA/output']})
db.append({'data_path': ['D:/DATA/output2']})
for dbi in db:
     opsEnd=run_s2p(ops=ops,db=dbi)
```

check out the latest jupyter notebook for the latest syntax and some info about processing in python: https://github.com/MouseLand/suite2p/blob/main/jupyter/run_suite2p_colab_2021.ipynb

**Comment by sarahapark** [comment]
Do I have to be in a specific directory in Jupyter Notebook to run suite2p?

**Comment by sarahapark** [comment]
Hi Carsen,
I'm trying to do a test run of suite2p on Jupyter Notebook using your data. I am following the code [here](https://github.com/MouseLand/suite2p/blob/main/jupyter/run_suite2p_colab_2021.ipynb) in the "Running suite2p on example data" section and got this error message.

![image](https://user-images.githubusercontent.com/51828933/140806236-27e41631-ed04-4670-84d4-19b5c8a74506.png)

How do I correct this?

**Comment by generalciao** [comment]
You need to "import os", as is shown further up in the notebook, so that python can find the os.path.isfile() method. Did you run the earlier cells in the notebook, including the cell with all the import statements? The code in each cell builds on the work done by previous cells.

**Comment by sarahapark** [comment]
I see. I did not run the cells above. Do I still need to `!pip install suite2p` if I have suite2p already installed? If I need to install suite2p through Jupyter Notebook, into which path is the 2nd suite2p being installed?

**Comment by generalciao** [comment]
You should not need to install suite2p again, I think you can skip that first part. But note, the Jupyter notebook you are using is intended for running/testing Suite2p on Google Colab remotely. There is another file in the same folder, "Run Suite2p.ipynb", for running it locally. You can compare the two files to see what's different between them - some differences will reflect the local/colab setup. I believe Carsen suggested you refer to the colab version, because it is most up-to-date (the local one has not been updated in >1 year).

**Comment by sarahapark** [comment]
I ran import os and got an error message. Should I `!pip install suite2p`? Will this mess up my local suite2p?
![image](https://user-images.githubusercontent.com/51828933/140810495-f563485a-984a-4bf4-8726-fcfb38f090ce.png)

To make sure I understood you correctly, running suite2p on Jupyter Notebook is running suite2p remotely on Google Colab. I can then compare the results from Jupyter Notebook on Google Colab to the results from my local suite2p GUI? Is the Google Colab suite2p expected to be different from the local suite2p GUI? In what ways are they different?

**Comment by generalciao** [comment]
Sarah, I may need to "tap out" here, as I myself have very little experience with Jupyter notebooks and I don't want to give you wrong information. You should be able to find lots of generic (non-suite2p) info and tutorials on using Jupyter notebooks with a quick search, though. Also, if you have installed Anaconda, it has a fair bit of Jupyter support.

> To make sure I understood you correctly, running suite2p on Jupyter Notebook is running suite2p remotely on Google Colab. I can then compare the results from Jupyter Notebook on Google Colab to the results from my local suite2p GUI? Is the Google Colab suite2p expected to be different from the local suite2p GUI? In what ways are they different?

But briefly: 
Not quite. Jupyter notebook lets you write and run python code interactively, with comments and results and plots included in-line in the document. It can be a convenient way to annotate/explain code and run an analysis step-by-step. You can install and use it locally, or you can use a remote installation in a web browser. Google Colab is one way to run Jupyter Notebooks remotely. Carsen has provided a specific notebook that works on Google Colab - for example so that a new user can try out suite2p in their browser (without the GUI), without installing it on their own computer. Carson also provided a different notebook, to run suite2p locally in Jupyter. Both files are on github. You might find it useful to compare those files, as a way to see what is different between them. But I believe only the colab version is fully up-to-date, so perhaps you should just focus on that one. I don't know whether you need to make any changes to it, if you are going to use it locally.

**Comment by sarahapark** [comment]
Thanks so much for your help and explanation so far! It makes sense to stick with the Google Colab code. Thanks!

**Comment by sarahapark** [comment]
Hi Carsen,
I am trying to run the Google Colab code on Jupyter Notebook and am running into error messages. First, after `!pip install suite2p`, I got the below error messages (in bold). Could you please help me with this? Thank you!


Collecting suite2p
  Using cached suite2p-0.10.3-py3-none-any.whl (638 kB)
Requirement already satisfied: paramiko in c:\anaconda3\lib\site-packages (from suite2p) (2.7.2)
Collecting rastermap>0.1.0
  Using cached rastermap-0.1.3-py3-none-any.whl (80 kB)
Collecting natsort
  Using cached natsort-8.0.0-py3-none-any.whl (37 kB)
Requirement already satisfied: importlib-metadata in c:\anaconda3\lib\site-packages (from suite2p) (3.10.0)
Requirement already satisfied: tifffile in c:\anaconda3\lib\site-packages (from suite2p) (2021.4.8)
Collecting torch>=1.7.1
  Using cached torch-1.10.0-cp38-cp38-win_amd64.whl (226.6 MB)
Requirement already satisfied: h5py in c:\anaconda3\lib\site-packages (from suite2p) (2.10.0)
Requirement already satisfied: matplotlib in c:\anaconda3\lib\site-packages (from suite2p) (3.3.4)
Requirement already satisfied: scikit-learn in c:\anaconda3\lib\site-packages (from suite2p) (0.24.1)
Requirement already satisfied: numba>=0.43.1 in c:\anaconda3\lib\site-packages (from suite2p) (0.53.1)
Collecting sbxreader
  Using cached sbxreader-0.2.0-py3-none-any.whl (19 kB)
Requirement already satisfied: numpy>=1.16 in c:\anaconda3\lib\site-packages (from suite2p) (1.20.1)
Collecting scanimage-tiff-reader>=1.4.1
  Using cached scanimage-tiff-reader-1.4.1.tar.gz (989 kB)
Requirement already satisfied: scipy>=1.4.0 in c:\anaconda3\lib\site-packages (from suite2p) (1.6.2)

  **ERROR: Command errored out with exit status 1:
   command: 'C:\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\parks6\\AppData\\Local\\Temp\\pip-install-0_cku4pj\\scanimage-tiff-reader_fe6e3c352aaf47a2ae95e8dde3794f77\\setup.py'"'"'; __file__='"'"'C:\\Users\\parks6\\AppData\\Local\\Temp\\pip-install-0_cku4pj\\scanimage-tiff-reader_fe6e3c352aaf47a2ae95e8dde3794f77\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\parks6\AppData\Local\Temp\pip-wheel-4az9g3ja'
       cwd: C:\Users\parks6\AppData\Local\Temp\pip-install-0_cku4pj\scanimage-tiff-reader_fe6e3c352aaf47a2ae95e8dde3794f77\
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\ScanImageTiffReader
  copying src\ScanImageTiffReader\__init__.py -> build\lib\ScanImageTiffReader
  running egg_info
  writing src\scanimage_tiff_reader.egg-info\PKG-INFO
  writing dependency_links to src\scanimage_tiff_reader.egg-info\dependency_links.txt
  writing requirements to src\scanimage_tiff_reader.egg-info\requires.txt
  writing top-level names to src\scanimage_tiff_reader.egg-info\top_level.txt
  reading manifest file 'src\scanimage_tiff_reader.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.h' found anywhere in distribution
  warning: no previously-included files matching '*.a' found anywhere in distribution
  warning: no previously-included files matching '*.lib' found anywhere in distribution
  warning: no previously-included files matching 'src\**\external\**\bin\*' found anywhere in distribution
  writing manifest file 'src\scanimage_tiff_reader.egg-info\SOURCES.txt'
  copying src\ScanImageTiffReader\__init__.pyc -> build\lib\ScanImageTiffReader
  creating build\lib\ScanImageTiffReader\__pycache__
  copying src\ScanImageTiffReader\__pycache__\__init__.cpython-36.pyc -> build\lib\ScanImageTiffReader\__pycache__
  copying src\ScanImageTiffReader\__pycache__\__init__.cpython-37.pyc -> build\lib\ScanImageTiffReader\__pycache__
  creating build\lib\ScanImageTiffReader\external
  copying src\ScanImageTiffReader\external\README.md -> build\lib\ScanImageTiffReader\external
  copying src\ScanImageTiffReader\external\__init__.py -> build\lib\ScanImageTiffReader\external
  copying src\ScanImageTiffReader\external\__init__.pyc -> build\lib\ScanImageTiffReader\external
  creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin
  creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
  copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
  creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux
  creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib
  copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib\libScanImageTiffReaderAPI.so -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib
  creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64
  creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib
  copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib\ScanImageTiffReaderAPI.dll -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib
  creating build\lib\ScanImageTiffReader\external\__pycache__
  copying src\ScanImageTiffReader\external\__pycache__\__init__.cpython-36.pyc -> build\lib\ScanImageTiffReader\external\__pycache__
  copying src\ScanImageTiffReader\external\__pycache__\__init__.cpython-37.pyc -> build\lib\ScanImageTiffReader\external\__pycache__
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data
  creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib
  creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader**

Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in c:\anaconda3\lib\site-packages (from numba>=0.43.1->suite2p) (0.36.0)
Requirement already satisfied: setuptools in c:\anaconda3\lib\site-packages (from numba>=0.43.1->suite2p) (52.0.0.post20210125)
Collecting pyqtgraph
  Using cached pyqtgraph-0.12.3-py3-none-any.whl (992 kB)
Requirement already satisfied: typing-extensions in c:\anaconda3\lib\site-packages (from torch>=1.7.1->suite2p) (3.7.4.3)
Requirement already satisfied: six in c:\anaconda3\lib\site-packages (from h5py->suite2p) (1.15.0)
Requirement already satisfied: zipp>=0.5 in c:\anaconda3\lib\site-packages (from importlib-metadata->suite2p) (3.4.1)
Requirement already satisfied: pillow>=6.2.0 in c:\anaconda3\lib\site-packages (from matplotlib->suite2p) (8.2.0)
Requirement already satisfied: cycler>=0.10 in c:\anaconda3\lib\site-packages (from matplotlib->suite2p) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\anaconda3\lib\site-packages (from matplotlib->suite2p) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\anaconda3\lib\site-packages (from matplotlib->suite2p) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\anaconda3\lib\site-packages (from matplotlib->suite2p) (1.3.1)
Requirement already satisfied: cryptography>=2.5 in c:\anaconda3\lib\site-packages (from paramiko->suite2p) (3.4.7)
Requirement already satisfied: bcrypt>=3.1.3 in c:\anaconda3\lib\site-packages (from paramiko->suite2p) (3.2.0)
Requirement already satisfied: pynacl>=1.0.1 in c:\anaconda3\lib\site-packages (from paramiko->suite2p) (1.4.0)
Requirement already satisfied: cffi>=1.1 in c:\anaconda3\lib\site-packages (from bcrypt>=3.1.3->paramiko->suite2p) (1.14.5)
Requirement already satisfied: pycparser in c:\anaconda3\lib\site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko->suite2p) (2.20)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda3\lib\site-packages (from scikit-learn->suite2p) (2.1.0)
Requirement already satisfied: joblib>=0.11 in c:\anaconda3\lib\site-packages (from scikit-learn->suite2p) (1.0.1)
Building wheels for collected packages: scanimage-tiff-reader
  Building wheel for scanimage-tiff-reader (setup.py): started
  Building wheel for scanimage-tiff-reader (setup.py): finished with status 'error'
  Running setup.py clean for scanimage-tiff-reader
Failed to build scanimage-tiff-reader
Installing collected packages: pyqtgraph, natsort, torch, scanimage-tiff-reader, sbxreader, rastermap, suite2p
    Running setup.py install for scanimage-tiff-reader: started
    Running setup.py install for scanimage-tiff-reader: finished with status 'done'
Successfully installed natsort-8.0.0 pyqtgraph-0.12.3 rastermap-0.1.3 sbxreader-0.2.0 scanimage-tiff-reader-1.4.1 suite2p-0.10.3 torch-1.10.0


  **creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external
  copying build\lib\ScanImageTiffReader\external\README.md -> build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external
  creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin
  creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
  copying build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so -> build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
  error: could not create 'build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so': No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for scanimage-tiff-reader
  DEPRECATION: scanimage-tiff-reader was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.**

**Comment by sarahapark** [comment]
Hi Carsen,
I was able to go through the entire Google Colab code despite the error messages that popped up after `!pip install suite2p`.
I will try running the code on one of my data sets next.

**Comment by sarahapark** [comment]
Good news!
I was able to run suite2p on Jupyter Notebook with the hidden parameters set to my old ops settings in suite2p v0.9.3. The Jupyter Notebook registration looks good and so do the ROIs. The ROIs from the Jupyter Notebook run are close to identical to results from an old suite2p GUI run on the same data set with the same hidden ops parameters.

Results from old suite2p GUI run:
![image](https://user-images.githubusercontent.com/51828933/140999363-d6006cf8-1b0a-4854-9d88-3bbe042a4514.png)
![image](https://user-images.githubusercontent.com/51828933/140999400-8c261c3b-f112-4ff7-95f9-c4c75f1aa30d.png)

Results from Jupyter Notebook run:
![image](https://user-images.githubusercontent.com/51828933/140999429-954235ce-581c-4665-9a7e-3e5dcaf0132a.png)
![image](https://user-images.githubusercontent.com/51828933/140999450-92abfd12-509b-4614-ad0a-081bfd398a44.png)

Next test: I will create an ops.npy file with Jupyter Notebook with the hidden parameters already setup so that I can use this ops.npy on the local suite2p GUI.

Question: If I want to batch process on Jupyter Notebook, how do I write the code to write to multiple "save_path0"s? (see below in bold)

```
ops = suite2p.default_ops()
ops = default_ops()
ops['sparse_mode'] = 1
ops['threshold_scaling'] = 3.0
```
**ops['save_path0'] = 'C:/Users/parks6/tif'** <-- How do I change this to write to multiple save_paths?
```
db = []
db.append({'data_path': ['D:/DATA/output']})
db.append({'data_path': ['D:/DATA/output2']})
for dbi in db:
     opsEnd=run_s2p(ops=ops,db=dbi)
```

**Comment by bgriffen** [comment]
I also get the same error as above running `pip install suite2p` on my M1 macbook. 

```
error: could not create 'build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so': No such file or directory
```
