### ISSUE TITLE
Negative peak artifact in Suite2P 

### ISSUE THREAD

**Issue by JaiSubKU** [MouseLand/suite2p#759]
Hello Drs. Stringer and Pachitariu, I am new to suite2p. Thanks for this great tool. I see negative peaks in Suite2p output for ROIs that don't show any negative fluorescence values when analyzed directly in ImageJ. Please see the attached picture. Can you please tell me why Suite2p is generating the negative peak artifact? Thank you - J
![negative-peaks](https://user-images.githubusercontent.com/76710561/138932736-3b53827f-ed51-45bb-b843-cdebfc05548b.png)
ai

**Comment by carsen-stringer** [comment]
thanks @generalciao for the advice! indeed this looks like an overflow issue, going to close for now, let us know if you need more help
