### ISSUE TITLE
27677 warnings when running tests

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/suite2p#761]
When running the tests, there were an enormous number of warnings!  This could possibly be hiding bugs.  It can make it hard for developers to know if they introduced any issues.

Ubuntu 20.04, python 3.8.10, installed via pip @ 9473e9a

```
pytest tests/
...
26 passed, 27677 warnings in 221.82s (0:03:41)
```

**Comment by carsen-stringer** [comment]
thanks for pointing this out! that's because I used `np.bool` instead of `'bool'` and numpy is deprecating that syntax. there's a deprecation warning remaining that is inside `scipy.io.loadmat` not suite2p, but that's it for deprecation warnings at least. I'm getting 6 warnings now.
