### ISSUE TITLE
ROI XY coordinate 

### ISSUE THREAD

**Issue by RisaIguchi** [MouseLand/suite2p#762]
Hi, I’m looking for XY coordinates for selected ROIs.

I tired to export ROI plot data on the cells image as CSV or HDF5a,
File > Export as image (svg) > Item to export ViewBox (cells) > CSV from plot data or HDF5 Export: plot (x, y)

But I got this message 
raise Exception("Must have a PlotItem selected for CSV export.")
Exception: Must have a PlotItem selected for CSV export.

I already have installed dependencies on list. Is there any other thing needed for the export?
https://github.com/MouseLand/suite2p

I also checked stat.npy on matlab, structure array but couldn't figure out which one refers to the coordinates. 
Can I get the information if I access to xcirc and ycirc?

I'm a quite beginner in coding and hoping for your help. 
Thank you!

**Comment by carsen-stringer** [comment]
hey @RisaIguchi it's stat['ypix'] and stat['xpix'], see the code here: https://suite2p.readthedocs.io/en/latest/outputs.html#stat-npy-fields

note that you need to use this allow_pickle=True flag in the loading: "stat = np.load('stat.npy', allow_pickle=True)", we need to fix that in the documentation

**Comment by RisaIguchi** [comment]
Thank you so much @carsen-stringer !! I will try the code.

**Comment by RisaIguchi** [comment]
Hi @carsen-stringer  Finally I could open stat.npy with spyder.  I appreciate your help!
![211115](https://user-images.githubusercontent.com/93522269/141732120-558891df-13f0-4393-8664-b784894eb95c.JPG)
