### ISSUE TITLE
What do these ops parameters do?

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#767]
Hi Carsen,
I saw these ops parameters listed while running suite2p (v. 0.10.3) in Jupyter Notebook. I don't see an explanation of these parameters on the [website](https://suite2p.readthedocs.io/en/latest/settings.html). Could you explain what these parameters are doing and the accepted inputs for each parameter?

_FORMAT: parameter (accepted inputs)[ops category, i.e., main settings, output settings, registration, etc] = what does it do?_
- bidi_corrected (true/false) [?] = ? 
- lam_percentile (?) [?] = ?
- norm_frames (true/false) [?] = ?
- force_refImag (true/false) [?] = ?
- cellprob_threshold (?) [?] = ?
- flow_threshold (?) [?] = ?
- force_sktiff (true/false) [?] = ?
- frames_include (?) [?] = ?
- subpixel (?) [?] = ?
- pad_fft (true/false) [?] = ?
- nbinned (?) [?] = ?
- chan2_thres (?) [?] = ?
- baseline (?) [?] = ?
- prctile_baseline (?) [?] = ?

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
please see info here: https://github.com/MouseLand/suite2p/blob/12dc119ac0c7c4355e9cd3e07bebc447755623e4/suite2p/run_s2p.py#L25

and also in the release notes there are slides on the new parameters added in v0.10.0: https://github.com/MouseLand/suite2p/releases
