### ISSUE TITLE
error: this is not a stat.npy file :( (needs stat[n]["ypix"]!)

### ISSUE THREAD

**Issue by ytsimon2004** [MouseLand/suite2p#768]
Hi, 
Recently I was trying to install the latest version suite2p on another pc, but encountered a problem, which has not happened before. I used *sbx* file for imaging acquisition, and 4 planes using ETL in total. (linux, python==3.8.12, suite2p==0.10.2)

Could you please help me interpret further the error message attached below? 

![image](https://user-images.githubusercontent.com/65637150/141021845-133e38f9-a590-4d61-8ae0-48485f7fa8f7.png)
![image](https://user-images.githubusercontent.com/65637150/141021357-8b3092ec-c78f-4111-8566-da64d759bf0d.png)
![image](https://user-images.githubusercontent.com/65637150/141017181-0de9d611-45c7-4dbb-b966-e3f33c7bab44.png)

**Comment by sarahapark** [comment]
Hi,
I also encountered this issue when I ran the GUI on a HPC VMware. Suite2p basically doesn't finish the analysis. I would find it helpful to know what is causing this error as well. Thank you!

**Comment by carsen-stringer** [comment]
I'm sorry we cannot support bugs or software issues with versions earlier than the latest version of suite2p (0.10.3) please upgrade and let us know if you're still having issues. going to close for now, can reopen if there are still problems

**Comment by ytsimon2004** [comment]
Hi Carsen, I have checked this issue further, perhaps it's due to memory error, then killed by the OS. 
I believe that it would be great that the information could be print in the GUI.

**Comment by carsen-stringer** [comment]
Oh I see! Try decreasing your ops['batch_size'], yes I agree I'm not sure
how to do this though
