### ISSUE TITLE
Setting up classifier and building the classifier using Jupyter Notebook

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#769]
Hi Carsen,
Is there an example python code for setting up the classifier and building the classifier using Jupyter Notebook?
In the ops parameter list, I see `use_builtin_classifier: False` and `classifier_path: 0`, but I don't know how to run suite2p so that I'm building the classifier as I would with the GUI.

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
you need to build the classifier in the GUI and then you can set the classifier_path in the ops file
