### ISSUE TITLE
Mean image in GUI not matching ROI detection channel when using ch 2

### ISSUE THREAD

**Issue by ransona** [MouseLand/suite2p#77]
Hi
I'm processing data using a GECI detected on channel 2 (red) so I ran the pipeline via the GUI with functional_chan = 2 and align_by_chan = 2.  When I open the processed data in the GUI to check ROIs I think it displays the mean img (or mean img enhanced) from ch 1 as far as I can tell.
This is the pipeline config:
![image](https://user-images.githubusercontent.com/7849066/45036038-5040d380-b053-11e8-929b-ec5aa92ec763.png)
Thanks for the great work
Adam

**Comment by carsen-stringer** [comment]
This should now be fixed, let me know if it still doesn't work. There were several bugs with functional_chan=2, so please rerun the whole pipeline.

**Comment by ransona** [comment]
Great thanks will try this now. I take it this update isn't in the pip package as version number didn't increment?

**Comment by ransona** [comment]
It now works when I run the pipeline with 'functional_chan' : 1 & 'align_by_chan' : 2 - i.e. can load the stat.npy files and use the new gui button to view both the mean of ch 1 and ch 2
But with: 'functional_chan' : 2 & 'align_by_chan' : 2 , I get this error in the gui when I try to load stat.npy
![image](https://user-images.githubusercontent.com/7849066/45214460-6dafb080-b292-11e8-9a0f-8f659f207861.png)

**Comment by carsen-stringer** [comment]
oops, pull the latest github version, it's fixed on here only for now. this is just a gui issue so you shouldn't have to rerun the pipeline

**Comment by carsen-stringer** [comment]
"it's fixed on here only for now" <-- by this I mean that I will make the fixed pypi release later today

**Comment by ransona** [comment]
Brilliant thanks - that has fixed it!
But seems to have generated another bug when you try to view all depths at once in gui (this was working before). Maybe related to assuming a 512x512 frame size (this data is 256x256)? Error message is:
![image](https://user-images.githubusercontent.com/7849066/45220185-3991bb00-b2a5-11e8-8709-3b3130a8806f.png)

**Comment by carsen-stringer** [comment]
Ah yes, forgot to stitch the second channel mean for combined view. Try it out now.

**Comment by carsen-stringer** [comment]
Also, the naming convention is as follows:
ops['functional_chan'] => meanImg, reg_file
2-ops['functional_chan'] => meanImg_chan2, reg_file_chan2

So chan2 doesn't mean second channel in your recording, it means the non-functional channel

**Comment by ransona** [comment]
Can you suggest the best way to run the pipeline if you have 2 functional channels, only one of which you want to use for registration, and want to avoid creating the bin files and running the registration twice? 
i.e. I want to:
1) Make binaries and register all data (both channels) using red channel
2) Detect/extract rois on green channel
3) Detect/extract rois on red channel

I've run it with A) 'functional_chan' : 2 / 'align_by_chan' : 2; followed by B) running with 'functional_chan' : 1 which reuses the binaries and registration from A. However B then overwrites the extracted rois from A, and also when you open the stat.npy file from B in the gui the mean image is still set to the functional channel from A.

So it seems I could copy the stat.npy etc data out after step A and just put up with the mean image not being correct given you can now show the non-functional image in the gui. Or run pipeline twice with different output directories and put up with the registration etc running twice. Or is there another way?

**Comment by ransona** [comment]
.. forgot to say that it is all seems to be working perfectly now with respect to the errors above!
Thanks
Adam

**Comment by carsen-stringer** [comment]
I've written a jupyter-notebook to automate this so you don't have to run registration twice: https://github.com/MouseLand/suite2p/blob/master/jupyter/multiple_functional_channels.ipynb

**Comment by ransona** [comment]
That's brilliant, thanks so much!

**Comment by ransona** [comment]
A few more bugs related to channel 2 I'm afraid!

When you run this jupyter-notebook with 'combined': True you get the below error when it is processing the 2nd channel:

ValueError                                Traceback (most recent call last)
<ipython-input-2-1684f12c0f17> in <module>()
     45 del ops0['save_path']
     46 ops0["diameter"] = 5
---> 47 opsEnd=run_s2p(ops=ops0,db=db)

C:\ProgramData\Anaconda3\lib\site-packages\suite2p-0.3.9-py3.6.egg\suite2p\run_s2p.py in run_s2p(ops, db)
    158     else:
    159         for k in range(len(ops1)):
--> 160             ops1[k] = utils.get_cells(ops1[k])
    161     ######### SPIKE DECONVOLUTION AND CLASSIFIER #########
    162     for ops in ops1:

C:\ProgramData\Anaconda3\lib\site-packages\suite2p-0.3.9-py3.6.egg\suite2p\utils.py in get_cells(ops)
    300     ops['diameter'] = np.array(ops['diameter']).astype('int32')
    301     print(ops['diameter'])
--> 302     ops, stat = celldetect2.sourcery(ops)
    303     print('time %4.4f. Found %d ROIs'%(toc(i0), len(stat)))
    304     # extract fluorescence and neuropil

C:\ProgramData\Anaconda3\lib\site-packages\suite2p-0.3.9-py3.6.egg\suite2p\celldetect2.py in sourcery(ops)
    550 def sourcery(ops):
    551     i0 = tic()
--> 552     U,sdmov, u      = getSVDdata(ops) # get SVD components
    553     S, StU , StS = getStU(ops, U)
    554     Lyc, Lxc,nsvd = U.shape

C:\ProgramData\Anaconda3\lib\site-packages\suite2p-0.3.9-py3.6.egg\suite2p\celldetect2.py in getSVDdata(ops)
     99 
    100 def getSVDdata(ops):
--> 101     mov = get_mov(ops)
    102     nbins, Lyc, Lxc = np.shape(mov)
    103 

C:\ProgramData\Anaconda3\lib\site-packages\suite2p-0.3.9-py3.6.egg\suite2p\celldetect2.py in get_mov(ops)
     85             inds = ix + np.arange(0,dbin.shape[0])
     86             # crop into valid area
---> 87             mov[inds,:,:] = dbin[:, ops['yrange'][0]:ops['yrange'][-1], ops['xrange'][0]:ops['xrange'][-1]]
     88             ix += dbin.shape[0]
     89     nimgbatch = min(mov.shape[0] , max(int(500/nt0), int(240./nt0 * ops['fs'])))

ValueError: shape mismatch: value array of shape (50,256,256) could not be broadcast to indexing result of shape (50,256,512)

**Comment by ransona** [comment]
Second I think here in the 3rd cell of multiple_functional_channels.ipynb the mimg should be put in ops['meanImg_chan2'] right?

mimg = ops['meanImg']
ops['meanImg'] = ops['meanImg_chan2']
ops['meanImg_chan2'] = ops['meanImg']  should be => ops['meanImg_chan2'] =mimg

**Comment by ransona** [comment]
Third, there's something funny going on when you run multiple_functional_channels.ipynb whereby the bin files that end up in the chan2 folders are different between depths but the rois detected and their traces are the same - see the image below from the new 'view registered binary' window (already very useful thanks!):
![image](https://user-images.githubusercontent.com/7849066/45381101-417e9180-b5fc-11e8-8d67-4bcb8b617ee2.png)

For an example see the tif files linked to below. They are from 2 depths with 2 channels and either have signal on green channel (example_green.tif) or red (example_red.tif) - they're the same data with the channels, just with the channels swapped.  If you run the red one with ch2 as the functional channel and registration channel and then open it in the gui you should hopefully be able to see what I mean - Depth 0 looks fine (rois match anatomically identifiable cells) but depth 1 has rois extracted from depth 0.

If you run the green one with ch1 as the functional channel and registration channel it works fine.

https://drive.google.com/file/d/1szKOLVbfrOqCif9tFd20BBhA3PZBr-z_/view?usp=sharing

**Comment by ransona** [comment]
Finally when you open data in gui from channel 2 the correlation map overlay is correct for depth 0 but all other depths seems to have the correlation maps from channel 1 - although doesn't seem to be detecting rois using this correlation map:
![image](https://user-images.githubusercontent.com/7849066/45382069-177a9e80-b5ff-11e8-9e36-b0393416bb4a.png)

**Comment by ransona** [comment]
Hope it's ok to put all of this here as I think it is all related to the work around in multiple_functional_channels.ipynb !

**Comment by carsen-stringer** [comment]
Does this work correctly if you don't use my script? I mean if you run both completely separately?

**Comment by ransona** [comment]
Yes it does, including correct correlation maps.

**Comment by carsen-stringer** [comment]
Instead of concatenating and trying to make a new ops1, try running suite2p in each pass of the loop (because it seems to have worked for the first one).

**Comment by ransona** [comment]
Deleting these options before running the pipeline the second time did the trick:
del ops0['ops_path']
del ops0['reg_file']
del ops0['reg_file_chan2']
