### ISSUE TITLE
suite2p on AMD processors

### ISSUE THREAD

**Issue by MariangelaP** [MouseLand/suite2p#770]
Hello, I'm about to purchase a new work station for running analysis of 2p data. I'd like to configure it with an AMD processor rather than an Intel one. I know that AMD processors have compatibility issue with Intel's MKL library, and I was wondering how much suite2p relies on MKL. Are you aware (or have performed) any benchmarks running suite2p between the two processor families? Also, can you think of any other reason why suite2p may have issues with AMD processors?

**Comment by carsen-stringer** [comment]
please see this issue: https://github.com/MouseLand/suite2p/issues/725, you can see if the contributor there has any suggestions but unfortunately recent Intel MKL libraries are not fast on AMD. I would recommend Intel for the time being unless you have another processing pipeline you wish to run on that computer that's faster with AMD
