### ISSUE TITLE
Re-extracting signals given existing ROIs and modified image data

### ISSUE THREAD

**Issue by chaplinta** [MouseLand/suite2p#772]
Hi,

I was wondering if there is any straightforward way to rerun the signal extraction (F, neuropil, deconv) with pre-existing ROIs and modified image data, using code not the GUI.

My particular use case is that I run Deepinterpolation on my processed and registered suite2p outputs, but then I want to calculate new denoised traces and compare them to the old ones.

Currently I have to rerun detection again on the denoised data, and end up with slightly different ROIs so I can't make direct comparisons. 

I can just try and take code from run_s2p and run_plane but since it seems there is bit going on there I was hoping there might be a proper way to do it.

Incidentally, in this scenario of reprocessing data from Deepinterpolation that is already registered by suite2p, it seems that if I turn off ops["do_registration"] it never creates a data.bin file (only a data_raw.bin file) which causes an error. To work around this I just re-register the already registered data, but it might be good if data.bin was created automatically when it's missing and ops["do_registration"] is False by just copying the data_raw.bin.

Cheers,
Tristan

**Comment by carsen-stringer** [comment]
we are happy to take a pull request which modifies the code and copies 'data_raw.bin' to 'data.bin' when ops['do_registration'] is False; alternatively do you need to run with ops['keep_movie_raw']=True? You would not have this problem if you set ops['keep_movie_raw']=False
