### ISSUE TITLE
Having trouble submitting Google colab/Jupyter Notebook suite2p job on HPC

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#773]
Hi,
I tried to submit the Google Colab/Jupyter Notebook [script](jupyter/run_suite2p_colab_2021.ipynb) using suite2p on an HPC and got an error message. I am getting the error message with `!pip install suite2p`. What could be going wrong with this? 

FYI. I successfully ran the code on my laptop’s local Jupyter Notebook.

![image](https://user-images.githubusercontent.com/51828933/141479009-79d4c993-8191-4fba-a9a2-00fd912c3321.png)
![image](https://user-images.githubusercontent.com/51828933/141479020-2467c0ef-818b-454c-8d9a-550ab865d987.png)

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
you could try install scanimage-tiff-reader separately, or please talk to your HPC

**Comment by sarahapark** [comment]
Here's what I'm getting after `pip install scanimage-tiff-reader`.
![image](https://user-images.githubusercontent.com/51828933/141501693-6e604529-325c-43d3-b09f-99352aa4c762.png)

Question: I installed a GUI version of suite2p on the HPC. The GUI version is not finishing the job (like so: #[768](https://github.com/MouseLand/suite2p/issues/768#issue-1049552208)), which is a different problem I need to address later. I'm wondering if the GUI version is messing up the `!pip install suite2p` command in the job submitted using Jupyter Notebook? 

What does `!pip install suite2p` do when sent as a command on Jupyter Notebook? Is the command temporarily installing and running suite2p for that specific job or is it a permanent installation of suite2p? If the latter is the case, can I omit the command in successive Jupyter Notebook jobs?

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
I think you should talk to your HPC coordinators if you have questions
about the python setup. It also looks like you are using python 3.9 instead
of python 3.8, which is what is specified in the environment.yml file in
suite2p, so you may not have activated your suite2p environment "conda
activate suite2p" before running the notebook.
