### ISSUE TITLE
Registration documentation is not aligned with default settings in the code.

### ISSUE THREAD

**Issue by danielsf** [MouseLand/suite2p#774]
This paragraph in the documentation
```
We first perform rigid registration (assuming that the whole image
shifts by some (dy,dx)), and then optionally after that we perform
non-rigid registration (assuming that subsegments of the image shift by
separate amounts). To turn on non-rigid registration, set
``ops['nonrigid']=True``. We will outline the parameters of each
registration step below.
```
seems to imply that nonrigid registration is turned off by default. Consulting the code

https://github.com/MouseLand/suite2p/blob/main/suite2p/run_s2p.py#L89-L93

that is not the case. Nonrigid registration is turned on by default. This caused some confusion for us over the last few months. Can you please update the documentation to reflect what the code does?

**Comment by chriski777** [comment]
Hey @danielsf, sorry about that! This has been addressed in #869 and should accurately reflect the default settings once it's merged!
