### ISSUE TITLE
"Remove last added" button on the ops parameter panel is disabled

### ISSUE THREAD

**Issue by sarahapark** [MouseLand/suite2p#775]
Hi,
The "remove last added" button on the ops parameter panel is inactive/disabled on my suite2p. Is there a way to activate the button on my GUI?

![image](https://user-images.githubusercontent.com/51828933/141821747-1c97e3f1-2c15-4381-ab98-7ac3251cb844.png)

Thank you!
Sarah

**Comment by carsen-stringer** [comment]
it is activated after you click save settings

**Comment by sarahapark** [comment]
Hi Carsen,
For some reason, it's not activated after I click save settings.

![image](https://user-images.githubusercontent.com/51828933/172701757-69d92b6b-4453-4b18-a73b-d4005676cd96.png)
