### ISSUE TITLE
Registration issue: grating-like noise

### ISSUE THREAD

**Issue by Makinolab** [MouseLand/suite2p#776]
For some reason I have not known yet, there is grating-like noise/interference from time to time when I was doing 2 photon imaging. Then using these raw data images I got a registration results as below.
![suite2pIsCell](https://user-images.githubusercontent.com/88810496/142343750-7b985dd1-7c4f-4001-9a67-98fe406248d3.png)
![suite2pNotCell](https://user-images.githubusercontent.com/88810496/142343742-ca60a105-8dcf-403c-b89b-99fd4784d124.png)

I think this is the output of suite2p and not the raw images, because this grating-like appearance is not present in our raw images. below image is simple average results of raw data by imageJ. We cannot see any grating on it. 
![SUM_GZ0024-L_2
11021_Tactile_lick_4s_delay_bothSides_perturbation_70Control_00001_00009_region8-1](https://user-images.githubusercontent.com/88810496/142344197-ff950e1b-7ded-4e22-9d7c-a9eca266d344.jpg)
Would appreciate any suggestions on how to reduce the occurrence of this grating-like appearance. And if there are any parameters/options of suite2p that we can adjust?

For reference. My suite2p options as bellow
![suit2pOpts](https://user-images.githubusercontent.com/88810496/142360557-9de8686e-c8ec-4ca3-b0cb-47a6af9a9f4e.png)

**Comment by SuilKim** [comment]
I see a similar grating. How did you solve it?
