### ISSUE TITLE
Error in Manual labelling following upgrade of Suite2p and Cellpose

### ISSUE THREAD

**Issue by dkushinsky** [MouseLand/suite2p#777]
Hi!
I recently upgraded my suite2p and cellpose versions (using pip) on my computer and am suddenly having issues with manual labelling (see error below)
Any suggestions about how to solve this? 
![image](https://user-images.githubusercontent.com/56402452/142457332-396129ee-aec0-480e-b8ba-03638b2c38f4.png)

Thanks!

**Comment by dkushinsky** [comment]
For anyone who is also facing this issue, I solved this by downgrading my numpy version to 1.18.0. Im not sure if the cellpose still works with this numpy version.

**Comment by carsen-stringer** [comment]
please provide more info if you're still having trouble, closing for now
