### ISSUE TITLE
"NameError: name 'scipy' is not defined" during output of Matlab data

### ISSUE THREAD

**Issue by ransona** [MouseLand/suite2p#78]
When I enable 'save_mat' I get the below error during the spike detection stage of pipeline. 'Fall.mat' is without a problem at earlier stages. Think it just needs an import scipy at the top of utils.py.
Thanks
Adam

NameError                                 Traceback (most recent call last)
<ipython-input-2-2b96c57b39ce> in <module>()
      5 
      6 for dbi in db:
----> 7     opsEnd=run_s2p(ops=ops,db=dbi)

C:\ProgramData\Anaconda3\lib\site-packages\suite2p-0.3.7-py3.6.egg\suite2p\run_s2p.py in run_s2p(ops, db)
    187     #### COMBINE PLANES or FIELDS OF VIEW ####
    188     if len(ops1)>1 and ops1[0]['combined']:
--> 189         utils.combined(ops1)
    190 
    191     for ops in ops1:

C:\ProgramData\Anaconda3\lib\site-packages\suite2p-0.3.7-py3.6.egg\suite2p\utils.py in combined(ops1)
    408     if ('save_mat' in ops) and ops['save_mat']:
    409         matpath = os.path.join(ops['save_path'],'Fall.mat')
--> 410         scipy.io.savemat(matpath, {'stat': stat,
    411                                    'ops': ops,
    412                                    'F': F,

NameError: name 'scipy' is not defined

**Comment by carsen-stringer** [comment]
should work now

**Comment by ransona** [comment]
Working now thanks.
