### ISSUE TITLE
Why does dynamic range affect cell detection?

### ISSUE THREAD

**Issue by danielsf** [MouseLand/suite2p#787]
I am a software engineer at the Allen Institute for Brain Science. We are working on building a cell detection pipeline that uses Suite2P to detect cells in 2-photon movies that have been denoised using the deepinterpolation tool developed by Jerome Lecoq

https://github.com/AllenInstitute/deepinterpolation

Something curious we have observed in the course of developing our pipeline is that the ROIs found by Suite2P's cell detection algorithm depend on the dynamic range of the pixels in the movie being segmented. Here is a figure demonstrating what I mean

![dynamic_range](https://user-images.githubusercontent.com/1682854/144515419-5d05d0ed-4b25-42d0-a2a2-8d36e13cf713.png)

Each panel in the above figure represents the unclassified ROIs found by Suite2P in a movie with the dynamic range specified in the panel's title (the first panel is just the maximum projection of the movie). **Note:** these movies were generated by taking a fiducial movie (the one with the dynamic range [0, 4899]) and multiplying it by a scaling factor. The dynamic range of pixel values is the only difference between these three movies.

Do you have a sense why the absolute dynamic range of the movie would matter when running Suite2P's cell detection algorithm? Is there a sweet spot in dynamic range that we should be aiming for when using Suite2P for cell detection?

Granted: the differences only appear to occur in low SNR regions of the field of view, and qualitative differences only appear when the dynamic range changes by an order of magnitude, but we are hoping that denoising will give us access to cells that appear in low SNR regions and the denoising scheme we are using gives us some degree of freedom to choose the dynamic range of the output. Is there a constraint we have in mind when setting this factor?

**Comment by carsen-stringer** [comment]
there is a threshold `ops['threshold_scaling']` that should make each of these scaled movies equivalent if altered. this threshold is on the variance explained of the ROI which is a squared metric, so the same threshold will result in different numbers of ROIs I think. but as you've noted you likely do not want to take some of these ROIs in the dim regions
