### ISSUE TITLE
"iplane" data is missing in stat.npy files with manually selected ROIs (but exist in stat_orig.npy)

### ISSUE THREAD

**Issue by ahsenko** [MouseLand/suite2p#789]
Hi, 
I need to select all ROIs manually because the expression is very sparse and my image is noisy.. After extracting ROIs, I want to drop one of the planes, but "iplane" data is missing in stat.npy files. When I try it on original data, it works. does anyone have a suggestion about how I could drop plane in processed stat files as well?
Thanks in advance!

**Comment by carsen-stringer** [comment]
this is fixed
