### ISSUE TITLE
Incorrect number of frames registered (tif and haus inputs)

### ISSUE THREAD

**Issue by aashishkhimasia** [MouseLand/suite2p#791]
Hi,

Thank you for developing this very useful software.

I have used suite2p previously to read tiffs with no problem, but am currently having issues with this. I have raw files which I have tried running using haussmeister, but following issues with this I am converting them to tiffs and running them in suite2p.

When I run the raw file with haus input, it reads it as having 500 frames, which is incorrect, but suite2p is interrupted by issues with haussmeister. 
When I input the tif converted from the raw file, it registers 1 frame and causes a ValueError due to the number of frames.

![image](https://user-images.githubusercontent.com/72612451/147834834-417f62ed-43e2-4798-8c71-5d431f63bf65.png)
![image](https://user-images.githubusercontent.com/72612451/147834796-5272b86e-9962-4ced-8810-079373b4d19f.png)

I have tried changing the tif format when converting from the raw file on ImageJ, however using a virtual stack or changing the image type is not successful. 

Could you please let me know if you know why this may be happening, or if you have any solution for this?

**Comment by carsen-stringer** [comment]
can you please open your tiff in python with `tifffile.imread`? it's hard to know what the shape is from imageJ. it needs to be n_time x y_pix x x_pix
