### ISSUE TITLE
anatomical not working

### ISSUE THREAD

**Issue by MariangelaP** [MouseLand/suite2p#794]
Hello,
I'm quite happy with the way suite2p works on some FOVs I have similar to the one in the picture below. However, it is still clearly missing some neurons, especially at the top of the FOV, and on the left side. They may be silent, but they should be detectable when using the anatomical features only. To implement this, I'm setting anatomical_only = 3, and diameter = 12. While running suite2p, I get the following message "tried anatomical but failed, install cellpose to use...". I imagine that suite2p switches to using the functional+anatomical features, then. Indeed, if I then rerun everything while setting anatomical_only = 0, and spatial_scale = 2, I get exactly the same number of cells.
Do you know why the anatomical mode is failing and how I may avoid this from happening? Can you suggest any other ways for detecting the missed cells?
many thanks!
ps: I'll leave below a screenshot of the ops

![59over70cells_camk2](https://user-images.githubusercontent.com/31733932/150380088-2ac21139-cd88-4a23-8459-a951c857e054.PNG)
![fov](https://user-images.githubusercontent.com/31733932/150383106-3280a3a2-6f35-4a76-93b2-9777cdcee1b3.PNG)

**Comment by MariangelaP** [comment]
Hi, 
thanks for your quick reply. I keep having issues unfortunately. Here's what's happening:
 I installed cellpose but suite2p crashes when trying to find masks (on the enhanced mean proj), seemingliy because the diameter I've set is wrong?? see the first picture attached. After this error, the process keeps running, it seems to be finding ROIs, but then crashes again, this time completely (see second picture attached). 
How can I fix this?
thank you again in advance

![1](https://user-images.githubusercontent.com/31733932/150674152-6dee7690-cd26-4b11-a6b0-d5b14b9638bc.PNG)
![2](https://user-images.githubusercontent.com/31733932/150674162-8f690d44-ecbf-40b0-9ae9-f1fb3f12582f.PNG)

**Comment by marysethomas** [comment]
I am not one of the developers, only another user. From what I can tell in those screenshots, those seem like status updates and not necessarily errors with cellpose (but I can't tell for sure). My only other suggestion is to make sure you are running the most recent developer's version of Suite2p.

**Comment by MariangelaP** [comment]
thanks a lot! yeah, I'm using the latest version indeed. I'll wait for updates from the developers. Thanks again

**Comment by RebeccaG342** [comment]
I am having this same problem. Did you find a solution?

**Comment by darikoneil** [comment]
@RebeccaG342 Preface: not one of the developers, but try installing the 0.6.5 version of cellpose specifically. There were some conflicting dependencies related to cell-pose recently. For reference, attached the packages in my env.
[environment.txt](https://github.com/MouseLand/suite2p/files/8247337/environment.txt)

**Comment by RebeccaG342** [comment]
@darikoneil Thank you! That worked.
