### ISSUE TITLE
Using Zarr for processing datasets in Suite2p

### ISSUE THREAD

**Issue by jmdelahanty** [MouseLand/suite2p#795]
Hello Suite2p team! I was wondering if there was a way to use Zarr for processing/visualizing datasets. I learned how to convert recordings off a Bruker scope from tiffs to zarrs using Dask and it was mindblowingly fast! It made a process that normally takes 25 minutes to do (convert tiffs to H5) and did it just over one minute! Suite2p is already pretty quick since it's using Numba for acceleration on CPU, but maybe it'd somehow go EVEN FASTER if we could write to files in parallel like zarr lets us do! As far as I'm aware, HDF5 doesn't allow for parallel writing to files. I'd imagine it could be pretty hard to add another whole file format to use, but since Zarr is using numpy arrays (I'm pretty sure) maybe it's not as hard as I think!

Is this something that would be interesting or helpful? Would it be something you think a novice Python programmer could help with?

**Comment by jmdelahanty** [comment]
Sidenote, it could also be cool to have a GPU option for zarrs, but I don't know if that's necessary or would even be useful since it's so fast using CPU already.

**Comment by carsen-stringer** [comment]
closing for now, I think it might make sense to go to NWB instead for easier sharing
