### ISSUE TITLE
Changing Parameters of already processed data

### ISSUE THREAD

**Issue by whaus123** [MouseLand/suite2p#796]
Hi. We have already processed data and run analysis on multiple mice using Suite2p. We set the neucoeff deconvolution value as 0.7, and we have recently discovered that 0.5 might be a better value to use. We are wondering if there is a way to change the neucoeff value to 0.5 on already processed data without having to rerun each cell and have to recount. 

Thanks!

**Comment by marysethomas** [comment]
Hi @whaus123,

I have changed parameters as you described using Spyder (or any other python editor). Here is an example where I change the allow_overlap parameter. If you find what neucoeff is called in the ops.npy file, you can change its value and save a new ops.npy file without having to re-extract ROIs

```
import numpy as np
np.load('ops.npy', allow_pickle=True)
ops.item()['allow_overlap'] = True
np.save('ops2.npy', ops, allow_pickle=True)
```

**Comment by whaus123** [comment]
Hi,

Thank you so much! What is an easy way to open up the ops.npy file and make the edits?

Thanks,
Will Hauser

**Comment by marysethomas** [comment]
The .npy file is a NumPy file type so it must be edited in python as far as I know.

**Comment by carsen-stringer** [comment]
thanks for the help @marysethomas !
