### ISSUE TITLE
Modifying `batch_size` parameter changes motion correction results when setting `smooth_sigma_time != 0`

### ISSUE THREAD

**Issue by morriscb** [MouseLand/suite2p#798]
Registration in Suite2p loads data in batches of frames to limit memory usage. However, when the parameter `smooth_sigma_time` is set, the edges between batches cause frames near the edge of the batch to be smoothed over fewer frames. This means that running the same settings with a different batch parameter will produce different motion corrections.

The code uses [gaussian_filter1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter1d.html) to do the smoothing which has a default cutoff of 4 standard deviations. This means that, for larger values of `smooth_sigma_time`, approximately 5-10% of the frames in a batch of default size 500 are affected by this issue. I ran a comparison of results between different batch sizes and found that the average image could change by a mean of 2% per pixel. Additionally, the motion shifts found were different between batch size settings.

The issue could be fixed by adding code to pad the size of the batch loaded by `ceil(smooth_sigma_time * 4.0)` at the beginning and end of the batch then removing these padded frames and their resulting shifts before writing to the output.

**Comment by carsen-stringer** [comment]
generally I would not recommend a super large `smooth_sigma_time`, you will be missing some movements of the sample. therefore I think this warrants a warning in the code / documentation rather than a fix
