### ISSUE TITLE
Types of Compression Supported in Suite2p

### ISSUE THREAD

**Issue by jmdelahanty** [MouseLand/suite2p#799]
Hello fellow peas in a two-photon imaging pod!

I was wondering about the kinds of compression that Suite2p supports when reading/writing images. I was looking through the documentation and didn't see specifics about the kinds of compression libraries it can read from. The reason I'm asking is because I've made a post on [this forum](https://forum.image.sc/t/converting-tiffs-to-h5-balloons-file-size-in-matlab/62532/9?u=jmdelahanty) and one of the people helping me said to make sure the compression method I use for converting the tiffs into H5 is supported by the software we're using. [Here's the repo](https://github.com/Tyelab/bruker_pipeline) I'm using to perform the conversion of raw Bruker datasets into tiffs and then into H5 files. It's adapting what the [Deisseroth Lab](https://github.com/deisseroth-lab/two-photon) has written for the lab I work in so credit goes to them.

I'm hoping I can keep things in zarr format as per this issue I submitted #795 since it's so crazy fast for other things, but until then keeping it in H5 is what we'll be doing.

Any advice?

**Comment by carsen-stringer** [comment]
Hey Jeremy, I've refactored suite2p so it's file format agnostic, this way you could have a file wrapper that allows indexing (like h5 or zarr) and still run the pipeline, see the code here: https://github.com/MouseLand/suite2p/tree/refactor. I'm not planning on switching suite2p's main file format because binary files (well anything but h5 really) are very fast, but it means that developers could write additional io classes that suite2p can read. I did this to make it easier to run suite2p with arrays or NWB style data.

**Comment by jmdelahanty** [comment]
Hello! Thank you for your response! That's really cool you can get it file format agnostic, I didn't think that kind of thing was possible!

So using this refactor branch we can just feed a folder of zarrs already to to suite2p and it knows how to read it?

**Comment by carsen-stringer** [comment]
it's not quite there, but the entry point is the `pipeline` function: https://github.com/MouseLand/suite2p/blob/fae2e56586e2cba3c89bd2a4dde4d352fe722995/suite2p/run_s2p.py#L24

you can set f_reg to be an array or an opened suite2p binary file or a zarr hopefully

**Comment by jmdelahanty** [comment]
I will try it and see what happens! I need to clone that branch in particular. Should I follow the developer installation docs to test it out?

**Comment by jmdelahanty** [comment]
It looks like this recording might just be a dataset that can't be easily salvaged. From what I've seen so far, it looks like `Suite2p` handles `lz4`, `gzip`, `blosc` compression just fine. So I'll close this now and if I make progress with zarrs I'll update that issue.
