### ISSUE TITLE
Dendritic ROI Segmentation

### ISSUE THREAD

**Issue by wisamreid** [MouseLand/suite2p#801]
I am interested in segmenting and separating somatic and dendritic ROIs. 
While I see some discussions here, I haven't been able to find much documentation on using suite2p for this.
Could someone give me a pointer to any resources on this? 
I haven't had much luck playing around with the ops file parameters/dendrite mode in the GUI?
Any help would be much appreciated.

**Comment by carsen-stringer** [comment]
are you using the latest version of suite2p? we've had success with dendrites if the recording is sufficiently long -- suite2p looks for ROIs that are correlated in time so there need to be a few transients to isolate a dendrite

**Comment by samaramiller** [comment]
Hi @carsen-stringer, how long is sufficiently long? Trying to detect axons with suite2p. Pretty good so far but wondering how if I can improve it in any way. Thanks!

**Comment by carsen-stringer** [comment]
depends on how many events you have, you could also try decreasing the binning during detection (set the "tau" smaller for example), or change the high-pass filtering in space up or down (ops["spatial_hp_detect"])
