### ISSUE TITLE
Number of frames in .tiff

### ISSUE THREAD

**Issue by jmwelland** [MouseLand/suite2p#803]
This is probably a rookie question, but I'm having an issue with analyzing a .tiff in suite2p. My .tiff consists of 120 images, but suite2p reads it as having 240 frames. I've tried converting it to different image types (8-bit grayscale, 8-bit color) with no luck. I'm using essentially the default suite2p settings. Any suggestions?

**Comment by tdincer** [comment]
@jmwelland Could there be an extra dimension in your frame counts that you are missing? A second depth, channel, or pointing would double the number of your frames to 240.

**Comment by carsen-stringer** [comment]
I agree with @tdincer can you try opening it in a jupyter notebook with `tifffile.imread` and see what dimensions it thinks the tiff is? closing issue for now please let us know if it's not fixed
