### ISSUE TITLE
run nwb conversion regardless of moved files

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#806]
here is output and error:

----------------
root <class 'pynwb.file.NWBFile'>
Fields:
  acquisition: { }
  analysis: { }
  devices: { }
  electrode_groups: { }
  epoch_tags: {}
  ic_electrodes: { }
  imaging_planes: { }
  lab_meta_data: { }
  modules: { }
  ogen_sites: { }
  stimulus: { }
  stimulus_template: { }
  time_intervals: { }

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\suite2p\gui\menus.py", line 54, in <lambda>
    lambda: save_nwb(get_suite2p_path(parent.basename))
  File "C:\ProgramData\Anaconda3\lib\site-packages\suite2p\io\nwb.py", line 291, in save_nwb
    manufacturer='The best microscope manufacturer'
  File "C:\ProgramData\Anaconda3\lib\site-packages\hdmf\utils.py", line 386, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: unrecognized argument: 'description', unrecognized argument: 'manufacturer'
------------

can you help?

thanks, evan

**Comment by vickerse1** [comment]
Is there a way to load an existing stat.npy and create an nwb file from the gui, or can the nwb file only be created when the data is initially processed with suite2p?

Thanks,
Evan

**Comment by vickerse1** [comment]
Hi,

I entered "pip install pynwb==1.4.0" in ipython (didnt seem to work in anaconda shell?). My previous version of pynwb was 1.0.2. When this was replaced with 1.4.0, the problem went away.

However, I had a new problem with the save directory, which appears to be suite2p looking for the path to the original analysis output directory, which no longer exists (I do runs on a GPU cluster and then post-hoc stuff on a local workstation):

----------
(suite2p) C:\Users\McCormick Lab\Documents\Python>python -m suite2p
Warning: cellpose did not import
No module named 'cellpose'
cannot use anatomical mode, but otherwise suite2p will run normally
D:/Mesoscope_Analysis_IV_May27_2021-/E267_A1V1M2/4022_210609_E267_3_1_1_2D_HAL/suite2p_out/suite2p/plane0/stat.npy
no channel 2 labels found (redcell.npy)
2.295999765396118
root pynwb.file.NWBFile at 0x2931073006616
Fields:
  file_create_date: [datetime.datetime(2022, 3, 7, 12, 18, 8, 501295, tzinfo=tzlocal())]
  identifier: /data/evicker2/suite2p_run
  session_description: suite2p_proc
  session_start_time: 2022-03-07 12:18:08.501295-08:00
  timestamps_reference_time: 2022-03-07 12:18:08.501295-08:00

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\suite2p\gui\menus.py", line 54, in <lambda>
    lambda: save_nwb(get_suite2p_path(parent.basename))
  File "C:\ProgramData\Anaconda3\lib\site-packages\suite2p\io\nwb.py", line 345, in save_nwb
    iscell = np.load(os.path.join(ops['save_path'], 'iscell.npy'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/evicker2/suite2p_out/suite2p/plane0\\iscell.npy'
-------------------

Is there an easy way to add an option for a user designated save directory / target directory, if those have changed?

Thanks,

Evan
________________________________

**Comment by kir0ul** [comment]
> However, I had a new problem with the save directory, which appears to be suite2p looking for the path to the original analysis output directory, which no longer exists (I do runs on a GPU cluster and then post-hoc stuff on a local workstation)

Maybe as a workaround, you could borrow some ideas from this [test fixture](https://github.com/MouseLand/suite2p/blob/main/tests/test_io.py#L48=), which seems to do something close to what you want, i.e.:
1. loading the `ops.npy` file,
2. updating the `save_path` with some other path,
3. saving the updated  `ops.npy` file.

**Comment by carsen-stringer** [comment]
I think this should be fixed now but let me know if not

**Comment by carsen-stringer** [comment]
(there were some changes in NWB formatting last year)
