### ISSUE TITLE
ERROR: ops.npy incorrect / missing ops['regPC'] and ops['regDX']

### ISSUE THREAD

**Issue by simbru** [MouseLand/suite2p#808]
Whether I try to do analyses by calling API in a custom script or through the GUI using the default ops, I get the following error in the console when checking registration metrics: 

`ERROR: ops.npy incorrect / missing ops['regPC'] and ops['regDX']
'regPC'`

The input files are .tiffs, typically 512x512 and around 500 frames long. 

Edit: During registration phase, I get the following warning 

``----------- REGISTRATION STEP 2
(making mean image (excluding bad frames)
registering 567 frames
NOTE: user reference frame given
C:\Users\skrem\miniconda3\envs\2panalysis\lib\site-packages\suite2p\registration\register.py:45: RuntimeWarning: invalid value encountered in true_divide
  dxy = dxy / dxy.mean()
added enhanced mean image``

**Comment by carsen-stringer** [comment]
the registration metrics only run if you have more than 1500 frames, you can run them manually by loading the ops in a jupyter-notebook and running
```
ops = registration.get_pc_metrics(ops)
```
