### ISSUE TITLE
Error while running anatomical mode in Suite2p v10.3

### ISSUE THREAD

**Issue by NidhiGujar** [MouseLand/suite2p#814]
Hello!
I have been trying to run Suite2p v10.3 with the anatomical mode on. However I end up getting the following error for every run- 

----------- ROI DETECTION
Binning movie in chunks of length 08
Binned movie [1488,170,220] in 4.52 sec.
Binned movie denoised (for cell detection only) in 17.75 sec.
CELLPOSE finding masks in max_proj / mean_img
**!NOTE! ops['diameter'] set to 5.00 for cell detection with cellpose
ERROR<<<
cellprob_threshold and dist_threshold are being deprecated in a future release, use mask_threshold instead**
100 masks detected, median diameter = 7.86
Detected 100 ROIs, 34.53 sec
----------- Total 57.49 sec.
----------- EXTRACTION
Masks created, 0.20 sec.
Extracted fluorescence from 100 ROIs in 12060 frames, 9.15 sec.
----------- Total 9.82 sec.
----------- CLASSIFICATION
['skew', 'compact', 'npix_norm']
----------- Total 0.08 sec.
----------- SPIKE DECONVOLUTION
----------- Total 0.13 sec.
Plane 0 processed in 68.06 sec (can open in GUI).
total = 68.27 sec.
TOTAL RUNTIME 68.27 sec
Interrupted by error (not finished)

Could you let me know what the issue might be and how could it be solved?

Thanks and Regards,
Nidhi

**Comment by gosipe** [comment]
I am also having the same issue. I tried installing a previous version of cellpose (0.6.5) but I was getting certificate errors. Any help on this is much appreciated!

Thanks,
-Gray

**Comment by christian-potter** [comment]
My lab has an identical bug on several computers (with suite2p v 10.3), and the issue persists when we upgraded those computers from cellpose v 1.0  to 2.0

**Comment by carsen-stringer** [comment]
consolidating issues: #794

**Comment by carsen-stringer** [comment]
this should be fixed now
