### ISSUE TITLE
Memory error with torch fft

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/suite2p#815]
I updated my s2p to the main github branch. When trying to process a stack, I ran into a memory error when using torch.ifft ( DefaultCPUAllocator: not enough memory: you tried to allocate 9437184000 bytes). When I reverted the ifft to the mkl_fft version (by uncommenting https://github.com/MouseLand/suite2p/blob/12dc119ac0c7c4355e9cd3e07bebc447755623e4/suite2p/registration/utils.py#L40-L43

and leaving everything else the same, it worked just fine. Not sure what is going on, but just posting this in case anyone else runs into this issue.

**Comment by frikyng** [comment]
Had the same issue and this fix worked for me. Thanks!

**Comment by jmdelahanty** [comment]
Out of curiosity are you running on an Intel or AMD processor?

**Comment by chriski777** [comment]
@alex-attinger and @frikyng, what OSes were y'all using? Also, do you by any chance remember what version of torch you had installed when you faced this error?

**Comment by alex-attinger** [comment]
It's on a Windows machine, with an Intel processor, running Windows 10 Enterprise, with this torch version: '1.11.0+cpu'

**Comment by frikyng** [comment]
Hi, being late to the party here - I also ran Win10 (professional) with an Intel processor. Unfortunately, I don't have access to that PC anymore so I can't check what version of torch I used back then.

**Comment by carsen-stringer** [comment]
are you still getting these issues with the latest torch versions? going to close for now but let me know if it's still a problem with the latest torch versions
