### ISSUE TITLE
Unable to view registered and raw binary files together in GUI

### ISSUE THREAD

**Issue by Nick3151** [MouseLand/suite2p#819]
Hi, I tried to run suite2p through a python script but could only visualize the registered binary video in the GUI. (I could not check the "view raw binary" checkbox in the GUI). I have also kept the same settings and ran suite2p on the same data with GUI and I was able to view the raw and registered data side-by-side. I have set "keep_movie_raw" to be True. I guess it might be due to the file structure or some ops settings that I was missing in my python script. 

The file structure I got by running python script looks like this:
- parent_dir
  - plane0
    - ops.npy
  - suite2p
    - plane0
      - data.bin
      - data_raw.bin

However the file structure I got by running in GUI looks like this:
- parent_dir
  - suite2p
    - plane0
      - data.bin
      - data_raw.bin
      - ops.npy
    - run.log
 
FYI, the link to my python script is [here](https://github.com/Nick3151/MotionMetrics/blob/ec510b77a06f3097e5bf8681a736ba4ac9772f8b/main.py).

Could you help me figure out where is going wrong?

Liang

**Comment by carsen-stringer** [comment]
please do not specify the path to fast disk as a subfolder: https://github.com/Nick3151/MotionMetrics/blob/ec510b77a06f3097e5bf8681a736ba4ac9772f8b/main.py#L29

suite2p will automatically write data.bin and data_raw.bin to the appropriate folder, if you specify fast_disk it assumes it's a different hard drive and creates the suite2p/plane0/... file structure

**Comment by Nick3151** [comment]
Thank you!

**Comment by oli1DA** [comment]
我

**Comment by oli1DA** [comment]
i have a same question that i could not check the "view raw binary" checkbox in the GUI, i don't understand.
