### ISSUE TITLE
Read data.bin file in MATLAB as Row X Col X num of images.

### ISSUE THREAD

**Issue by hemant22** [MouseLand/suite2p#822]
Hi,
Can somebody please help me with a code that reads data.bin file in Matlab as Row X Col X num of images.

Thank you.
Hemant

**Comment by alex-attinger** [comment]
Hi, I read in the .bin file into matlab the following way:

nR=mov_size(1);
nC = mov_size(2);
totalFrames = mov_size(3);
fi_mem = memmapfile(bin_path,'Format',{'int16',[nR nC totalFrames],'x'});

This generates a memory mapped file. You can access the movie like this:
fi_mem.Data.x

Hope this helps.

**Comment by hemant22** [comment]
> Hi, I read in the .bin file into matlab the following way:
> 
> nR=mov_size(1); nC = mov_size(2); totalFrames = mov_size(3); fi_mem = memmapfile(bin_path,'Format',{'int16',[nR nC totalFrames],'x'});
> 
> This generates a memory mapped file. You can access the movie like this: fi_mem.Data.x
> 
> Hope this helps.

**Comment by hemant22** [comment]
Thanks @alex-attinger. It works
