### ISSUE TITLE
Memory Error during ROI Detection

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/suite2p#834]
I am getting a memory error during ROI DETECTION, usually more towards the end, when there are >1000 detected ROIs. The error is usually thrown by 'getSVDproj' in line 54 of sourcery.py. Does anyone know what the best parameters are that I could change to reduce RAM requirements during ROI detection?

**Comment by jmdelahanty** [comment]
I think the way suite2p allocates RAM is dependent on how large of a batch size you do. So if you load a bunch of images from the binary they convert things to into memory, maybe the amount of RAM left over to put the results of that computation is insufficient and overwhelms the system? How much RAM does your computer have?

There's a parameter in the ops.npy and the GUI that lets you change the batch size value, so it could be worth it to try lowering that number. Although why it would get through registration and struggle at that step on not sure...

Also I'm pretty sure it will mean that your run will be slower.

One thing I've done in the past is literally just stare at what my computer is doing while a run happens. So on windows I'll watch the task manager's RAM monitor to see if I'm peaking that resource.

On Linux you can use 'htop' or 'free' to follow things. There's ways of piping free to an output file too if you want, something like this from your terminal:

'$ free -g -s 5 | output.txt'

That will poll the system every 5 seconds and give you memory statistics for how much RAM is being used up and write it into that output file.

I'm not sure how to do it on windows unfortunately...

**Comment by carsen-stringer** [comment]
you could reduce the number of SVDs used in sourcery by reducing the number of `ops['nbinned']` frames but that may not be the best solution. we could alternatively use an SVD algorithm that only gets so many components rather than the full SVD. is there a reason sparsedetect isn't working for you? sourcery is relatively deprecated

**Comment by alex-attinger** [comment]
Thank you for the feedback. I have gotten around it so far with decreasing ['nbinned'] when necessary, as you suggested. I was not aware that sparse_mode is now preferred. I saw that in the current version on github, ['sparse_mode'] defaults to True, however, in the documentation, that value is described as default False, so that is what I have been doing. I'll give sparse_mode a try.
