### ISSUE TITLE
Data Quality/Processing Questions for Motion Correction

### ISSUE THREAD

**Issue by jmdelahanty** [MouseLand/suite2p#838]
EDIT:

The way I subtracted the artifacts was definitely incorrect because it seems like every ~120 frames or so there's just frames missing, so I need to fix that for any of this to be more relevant...

Hello suite2p devs! I've been wondering about whether or not [subtracting artifacts from our 2p data](https://forum.image.sc/t/efficient-artifact-subtraction-of-electrical-and-resonant-scanning-artifacts-using-python-and-zarr-matlab/62939) would be helpful for things like motion correction. It looks like it didn't help as much as I thought it would unfortunately! At least on a dataset with a pretty good SNR. I still need to test things on a low SNR recording.

A couple people I talked with online told me that our data looks quite noisy (and it does!). I figured I would post a video here of what it looks like and see if anyone could point out ways we can improve our data collection/analysis.

On the left is where artifact subtraction as described [here](https://forum.image.sc/t/image-subtraction-in-python-behaves-differently-than-imagej/67942) has been done. On the right is where no artifact subtraction has been done.

First, here's what the max projections look like:

![image](https://user-images.githubusercontent.com/28411193/172507830-55cbb04a-d5b2-453b-a77c-a770ef80a5a3.png)

Next, what the correlation maps look like:

![image](https://user-images.githubusercontent.com/28411193/172508725-3d00fac1-d20d-4136-9571-3a930146d49d.png)

Now, what the mean enhanced image looks like:

![image](https://user-images.githubusercontent.com/28411193/172508805-9f28edb2-6f52-4b12-9bcc-8447547bc6dd.png)

Here's a side by side of the registered binary movie:

https://user-images.githubusercontent.com/28411193/172510195-2e4a6388-e68c-40ab-a8cb-149cfa4ac029.mp4

As you can see, there's a bit of motion still there in the video for both of them. It looks like artifact subtraction didn't do much.

Here's a side by side of the registered binary for the data without subtraction against the raw binary:

https://user-images.githubusercontent.com/28411193/172510833-e52affa0-79ad-479c-883f-009e7e083391.mp4

It looks like the motion registration didn't do that much in this case!

These were the parameters used for the run:

![image](https://user-images.githubusercontent.com/28411193/172511139-6f546c10-9484-49a6-b970-f64fac94098a.png)

The data that was given to Suite2p was acquired down a GRIN lens using resonant scanning with a framerate collected close to 30Hz in the mPFC of a headfixed (poorly apparently) mouse. You'll notice that the data looks pretty noisy.

There was no rolling average applied to the images before running Suite2p on them. Some people I've asked have told me that you definitely don't want to average your data before putting it through. Others have told me you definitely _do_ want to do that. Others still have told me that doing an average for finding ROIs/motion correction is good practice and then use those ROIs around the raw data. Another person suggested we slow down our framerate at acquisition time.

So what do my fellow peas in the 2-photon pod think? Any advice about how we can get better imaging from our brains?

**Comment by carsen-stringer** [comment]
I think I would recommend turning on the 1P registration options as they spatially high-pass filter the data for registration. you're also welcome to post this in the discussions, I will close the issue
