### ISSUE TITLE
Git hooks?

### ISSUE THREAD

**Issue by kir0ul** [MouseLand/suite2p#842]
Would you be interested in adding some code quality checks on this repo? One thing that could be nice to have are some Git hooks that run automatically at commit time. For example, running `git commit` [with `pre-commit`](https://pre-commit.com/) would look like this.

![image](https://user-images.githubusercontent.com/6053592/173172396-a5171423-6a7e-4615-9cc4-77b35d804daa.png)

Maybe one could add some fairly standard pipelines like [Black](https://black.readthedocs.io/en/stable/) for autoformatting and [Flake8](https://github.com/pycqa/flake8) to run some static analysis of the codebase?

Another benefit of using `pre-commit` is that you can easily run the exact same checks both locally and in Ci.

EDIT: I could make a PR if that's of interest :slightly_smiling_face:

**Comment by carsen-stringer** [comment]
thanks @kir0ul for the offer, we don't use black so I don't think we want to use this at this time
