### ISSUE TITLE
Qt issue on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by noamza** [MouseLand/suite2p#844]
Hi I am installing Suite2p on Linux Ubuntu 22.04 LTS.
I followed the steps in the installation doc https://suite2p.readthedocs.io/en/latest/installation.html
However trying to start suite2p I am getting the following:

`(suite2p) user01:~/Downloads/suite2p$ suite2p
Warning: cellpose did not import
No module named 'cellpose'
cannot use anatomical mode, but otherwise suite2p will run normally
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
`
Thanks for the help

**Comment by asjessie** [comment]
I encountered the same problem recently in the Linux CentOS system.

**Comment by jmdelahanty** [comment]
You can try out what helped our cluster admins on #797 get it working for us when we ran into those error messages.

**Comment by jmdelahanty** [comment]
Nice! I'll pass this along to our IT admin. I've seen the solution in that linked issue still not work for every machine in our cluster. It seems like this is probably a better answer.

**Comment by carsen-stringer** [comment]
thanks we will add this info to the install instructions
