### ISSUE TITLE
Cell detection only from channel 2 (red) and purely anatomical

### ISSUE THREAD

**Issue by generalciao** [MouseLand/suite2p#845]
My understanding is that with anatomical (cellpose) mode, only the time-averaged fluorescence is used for cell detection, i.e. activity does not play a role in finding cells. Is that accurate?

If yes, I'd like to know how to detect cells purely from the second (red) channel. My second channel represents red nuclear fluorescence and I would like to use this as means to automatically segment ROIs, avoiding bias by (green) activity. Can the pipeline do this currently? I'd still want to extract the activity traces from the green channel in later steps, but for the ROIs defined from the red channel.

Perhaps it would be ideal to use the red anatomical ROIs as seed points, and then fine-tune the ROI footprint taking into consideration the green (activity) channel, but for now I'd be happy to try it out with footprints derived solely from channel 2.

**Comment by carsen-stringer** [comment]
cells in the anatomical channel are detected with cellpose. then `F_chan2.npy` is the activity inside each of those ROIs across time in the functional channel. is that sufficient for your purposes?

**Comment by carolinerunyan** [comment]
@carsen-stringer To clarify your answer, 'anatomical only'/cellpose will use only fluorescence from the non-functional channel to define ROIs? 

We were also expecting that F_chan2 is the fluorescence from the non-functional channel - is this not the case?

**Comment by carsen-stringer** [comment]
sorry "anatomical_only" uses fluorescence from the functional channel to create ROIs. F_chan2 is the "activity" over time in the non-functional channel. so you could run suite2p with the functional_chan=2 (if that's the anatomical channel) and anatomical_only, then use the fluorescence from F_chan2 (now "chan2" is your actual functional channel)
