### ISSUE TITLE
omp_set_nested routine depricated

### ISSUE THREAD

**Issue by markuspleijzier** [MouseLand/suite2p#848]
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

**Comment by markuspleijzier** [comment]
Running on MacBook Pro, Mojave 10.14.6.

**Comment by markuspleijzier** [comment]
with intel chip (not M1)

**Comment by carsen-stringer** [comment]
please try this https://github.com/MouseLand/suite2p/issues/597

**Comment by carsen-stringer** [comment]
closing due to duplicate / inactivity please let me know if you need more help
