### ISSUE TITLE
GUI batch processing

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#85]
Would be nice / more convenient than running a script.

**Comment by marius10p** [comment]
There should be another button labelled "save & new ops", and "Run Suite2p" should dynamically change to "Batch runS2p" if more than one ops have been set up.

**Comment by carsen-stringer** [comment]
Batch processing has been added to the GUI. add data_path or h5 path and change settings and then click "save settings and add more (batch)" and then set up another recording and so on... You can also delete the last added recording from the queue.

**Comment by carsen-stringer** [comment]
Also, if you load an ops for each processing plane, non-visible settings (such as mesoscope processing settings) will also be saved for batch processing. In other words it should work the same as processing one at a time.
