### ISSUE TITLE
registration failed

### ISSUE THREAD

**Issue by ywtsay** [MouseLand/suite2p#853]
hi there,

I'm finished install with suite2p with conda, when running [Run Suite2p.ipynb] on jupyter notebook,

It gives the following message

<img width="1339" alt="截圖 2022-07-05 下午1 15 19" src="https://user-images.githubusercontent.com/24360030/177254335-3737dfa6-456e-46d8-a9a0-f0620ad791ad.png">

not sure which step I'm missing or doing wrong

thanks for your help

**Comment by tbabola** [comment]
We also just experienced this issue on a Mac. Correct me if I am wrong, Suite2p just boots you out after registration without doing anything?

On our end, it ended up being a torch crash on the fft during registration.

Torch 1.12 was the culprit. Solution was to pip uninstall torch, and reinstall v 1.11. Worked for us.

pip install torch==1.11.0

**Comment by ywtsay** [comment]
@tbabola thank you for your swift response

GUI version and Jupyter version both works after reinstalling torch 1.11.0

many thanks !

**Comment by chriski777** [comment]
Thanks for bringing our attention to this issue! Just wondering, @ywtsay and @tbabola, were you both using Mac machines with intel processors (non-M1) and what OSes did y'all have? We've seen this issue only on Mac machines so far and just wanted to make sure this is the case for y'all. We've currently pinned torch to be 1.11.0 in the setup.py for the upcoming release so I'll close this issue for now.

**Comment by ywtsay** [comment]
@chriski777 hi

I'm using macOs 12.4 with iMac 2019

**Comment by tbabola** [comment]
We were running latest OS 12.5 on M1 processor. Thanks for addressing!


On Thursday, July 21, 2022, Chris Ki ***@***.***> wrote:
> Thanks for bringing our attention to this issue! Just wondering, @ywtsay
and @tbabola, were you both using Mac machines with intel processors
(non-M1) and what OSes did y'all have? We've seen this issue only on Mac
machines so far and just wanted to make sure this is the case for y'all.
We've currently pinned torch to be 1.11.0 in the setup.py for the upcoming
release so I'll close this issue for now.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci6.googleusercontent.com/proxy/H0p9VOC4x-AKtD4TzlDm7U8dceJBmipYytoUdOx4t5s9_BVx2HLSMTpYJZUlMXZ6-JDgtr5W2oNNNjNWJp68Soj3OwvqbEywvLBg3aFeKhBBmOsJ_F8aFmMBGwZe3yzXPDmeolsjP31QGA99wOjjQKDztC5wOOKHx_EE8YlJCQjLGyeXNudV1ucnP8ljRuePqa53wLLFd3jByY-DQW474HDABS0wLDyzcAsD9hlEsw=s0-d-e1-ft#https://github.com/notifications/beacon/ABQQ7ZV4JWVXKNUQR35YO5TVVGZQ5A5CNFSM52U5GLU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOI4FTYGY.gif>Message
ID: ***@***.***>

-- 
Travis A. Babola
PhD, Johns Hopkins University
***@***.***
