### ISSUE TITLE
Can I use suite2p/Cellpose to detect calcium activity in Axons?

### ISSUE THREAD

**Issue by noamza** [MouseLand/suite2p#854]
Not sure if this is the right forum to ask this, but I didn't see another forum in the documentation to ask on. I have 2P video where my ROI's are axons. Is it possible to use suite2p/cellpose to identify ROI's that are axon shaped? I have not played around with suite2p extensively, so I am not sure if this is possible.
Thanks!

**Comment by carsen-stringer** [comment]
yes, we've used suite2p on axonal boutons with success, I'd recommend trying it out and seeing what happens. comment here if there are problems
