### ISSUE TITLE
crash when no ROI detected in a plane

### ISSUE THREAD

**Issue by yz22015** [MouseLand/suite2p#863]
Hi, I am running suite2p v0.11.0 on12-plane datasets, using `anatomical_only = 3` for ROI detection.
I noticed that the process crashes when no ROI is detected at a plane. e.g. 
![image](https://user-images.githubusercontent.com/32736815/183862052-61d9a359-2141-45ad-9722-d8caf8e16444.png)

Plane0-6 were processed successfully. But the process stopped at plane7.

The error messgae is:

![image](https://user-images.githubusercontent.com/32736815/183863669-a43c5342-fe48-4640-97d4-05251c59bba2.png)

Would it be possible to skip signal extraction etc for plane7 and continue to plane8-11?
Thanks!

**Comment by chriski777** [comment]
@yz22015, thanks for letting us know about this! This issue has been resolved in commit f0250161851de4167650051988031f921c796089. If you update suite2p to the latest version on the `main` branch of our repo, you should be good to go.
