### ISSUE TITLE
allow for autorescaling with non - int16 data types

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#87]
Right now, suite2p expects tiffs to have a maximum value 32767, and, when casting the tiffs into int16 format, will clip them if they're above this value. It is recommended to use 'int16' format. Rescaling will be added for non-int16 data types.

**Comment by dmnburrows** [comment]
Hi there - has this rescaling option been added yet? 

thanks!

**Comment by carsen-stringer** [comment]
I've updated this to check for "uint16" tiffs - it then rescales correctly (*on one dataset that's been tested) the frames to "int16" to write the binary. is this the format your tiffs are in?

**Comment by dmnburrows** [comment]
Great that is the format of my files - thanks

**Comment by carsen-stringer** [comment]
I'm going to close this, please reopen if there are more issues
