### ISSUE TITLE
Possibility to label ROIs in different groups

### ISSUE THREAD

**Issue by maristanye** [MouseLand/suite2p#875]
Dear suite2p people,

first of all thanks for the amazing software! It would be really cool if one could label ROIs e.g. select 10 ROIs and label them with layer5neurons and then another group and call them layer 2/3 neurons. In such a manner that later when working e.g. with the Fall.mat file one could separate the ROIs in groups for further analysis.

Cheers,
Eduardo

**Comment by carsen-stringer** [comment]
this will be possible when we allow red-channel labelling option in the gui, it's on the to-do list
