### ISSUE TITLE
registration_wrapper, nonrigid_offsets, ValueError (expected 3, got 0)

### ISSUE THREAD

**Issue by edwardnieh** [MouseLand/suite2p#885]
Hi all, I'm new to suite2p and new to Python, so apologies if I'm missing something simple. I'm setting `nonrigid' to False but it appears as if suite2p is attempting to perform nonrigid registration anyways. Thank you for your help!

ops settings:
ops = default_ops() #populate with default settings
ops['fs'] = 15
ops['nplanes'] = 2
ops['tau'] = 1.3 #this matters for the binning (in time)
ops['max_overlap'] = 0.5 #new parameter; was running at default, i.e. 0.75, previously
ops['nonrigid'] = False
ops['maxregshift'] = 0.1 #normal setting- changing to 0.05/0.03 only saved me 2-3 seconds
ops['subpixel'] = 10; #normal setting, didnt find an improvement from chanigng to 1/2
# ops['smooth_sigma'] = 1.15
ops['smooth_sigma'] = 2
ops['smooth_sigma_time'] = 2 #for noisy data
ops['sparse_mode'] = False
ops['diameter'] = 10    #dunno maybe why not
ops['do_registration'] = True
ops['roidetect']=True 
ops['save_mat'] = True

Error Message: 
...
Registered 53500/54000 in 543.27s
Registered 54000/54000 in 548.24s
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [1], line 86
     68 #tifflist
     69 
     70 
     71 # provide an h5 path in 'h5py' or a tiff path in 'data_path'
     72 # db overwrites any ops (allows for experiment specific settings)
     73 db = {
     74       'h5py': [], # a single h5 file path
     75       'h5py_key': 'data',
   (...)
     83     'save_path0': outpath,
     84 }
---> 86 opsEnd=run_s2p(ops=ops,db=db)

File ~\.conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:429, in run_s2p(ops, db, server)
    426                 op[key] = ops[key]
    428     print('>>>>>>>>>>>>>>>>>>>>> PLANE %d <<<<<<<<<<<<<<<<<<<<<<'%ipl)
--> 429     op = run_plane(op, ops_path=ops_path)
    430     print('Plane %d processed in %0.2f sec (can open in GUI).' % 
    431             (ipl, op['timing']['total_plane_runtime']))  
    432 run_time = time.time()-t0

File ~\.conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:292, in run_plane(ops, ops_path, stat)
    289         f_reg_chan2.close() 
    290         f_reg_chan2 = None
--> 292     ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
    294 if ops.get('move_bin') and ops['save_path'] != ops['fast_disk']:
    295     print('moving binary files to save_path')

File ~\.conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py:78, in pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat)
     75 refImg = ops['refImg'] if 'refImg' in ops and ops.get('force_refImg', False) else None
     77 align_by_chan2 = ops['functional_chan'] != ops['align_by_chan']
---> 78 registration_outputs = registration.register.registration_wrapper(f_reg, f_raw=f_raw, f_reg_chan2=f_reg_chan2, f_raw_chan2=f_raw_chan2, 
     79                                                                     refImg=refImg, align_by_chan2=align_by_chan2, ops=ops)
     81 ops = registration.register.save_registration_outputs_to_ops(registration_outputs, ops)
     82 # add enhanced mean image

File ~\.conda\envs\suite2p\lib\site-packages\suite2p\registration\register.py:615, in registration_wrapper(f_reg, f_raw, f_reg_chan2, f_raw_chan2, refImg, align_by_chan2, ops)
    613 refImg, rmin, rmax, mean_img, rigid_offsets, nonrigid_offsets, zest = outputs
    614 yoff, xoff, corrXY = rigid_offsets
--> 615 yoff1, xoff1, corrXY1 = nonrigid_offsets
    617 if nchannels > 1:
    618     mean_img_alt = shift_frames_and_write(f_alt_in, f_alt_out, yoff, xoff, yoff1, xoff1, ops)

ValueError: not enough values to unpack (expected 3, got 0)

**Comment by lschm** [comment]
Hi, 
I am seeing the same error. Likewise trying to register without the nonrigid registration. Likewise seems to report successful registration (Registered x/y in s) but then reports not enough values to unpack in line 615 in the registration wrapper. If I run nonrigid = true on the same data there is no error. 
Best wishes

**Comment by Klab-cmu** [comment]
We also have the same error, using just one channel, if 'nonrigid' is set to false.  If 'nonrigid' is set to true we do not get the error, and runs fine.

**Comment by chriski777** [comment]
Hi everyone, this issue has been fixed in the latest `main` branch of this repo. Could y'all try running this command to install the latest version of the main branch for suite2p?

```pip install git+https://github.com/MouseLand/suite2p.git@main```

This will be fixed once we make a new release for suite2p but as of now, this will be a quick fix. I'll close this for now but please feel free to re-open this if this issue persists!
