### ISSUE TITLE
TypeError: mode() got an unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by enot14134** [MouseLand/suite2p#886]
Hi,

I am a new suite2p user with very little python familiarity.
I am currently collecting a data set capturing live GCaMP6f activity in human brain organoids (imaged on a confocal microscope, not a 2-photon) and am very interested in assessing the suitability of the suite2p analysis pipeline for my data.

To start, I have attempted to run a provided example data set to get things up and running however I am coming across the below error message (also attached).

I would appreciate any suggested fixes.

Many thanks,

{'data_path': ["C:/Users/60288184/OneDrive - Children's Medical Research Institute/KR/SNAP25 Project/Calcium Imaging/Suite2Pfiles/Data_path"], 'subfolders': [], 'save_path0': "C:/Users/60288184/OneDrive - Children's Medical Research Institute/KR/SNAP25 Project/Calcium Imaging/Suite2Pfiles/Save_path", 'fast_disk': "C:/Users/60288184/OneDrive - Children's Medical Research Institute/KR/SNAP25 Project/Calcium Imaging/Suite2Pfiles/Fast_path", 'input_format': 'tif'}
tif
** Found 1 tifs - converting to binary **
2000 frames of binary, time 19.39 sec.
time 19.49 sec. Wrote 2000 frames per binary for 1 planes
 PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
NOTE: applying default C:\Users\60288184\.suite2p\classifiers\classifier_user.npy
----------- REGISTRATION
Reference frame, 42.34 sec.
Registered 500/2000 in 460.11s
Registered 1000/2000 in 1019.69s
Registered 1500/2000 in 1465.94s
Registered 2000/2000 in 1951.87s
----------- Total 2007.89 sec
Registration metrics, 356.56 sec.
----------- ROI DETECTION
Binning movie in chunks of length 10
Binned movie of size [200,656,776] created in 6.83 sec.
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
>>>ERROR<<<
    run_s2p(ops, db)
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 429, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 292, in run_plane
>>>ERROR<<<
    ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 129, in pipeline
    ops, stat = detection.detection_wrapper(f_reg,
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\detect.py", line 148, in detection_wrapper
    stat = select_rois(
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\detect.py", line 203, in select_rois
    new_ops, stat = sparsedetect.sparsery(
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\sparsedetect.py", line 307, in sparsery
    scale, estimate_mode = find_best_scale(I=I, spatial_scale=spatial_scale)
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\sparsedetect.py", line 266, in find_best_scale
    scale = estimate_spatial_scale(I=I)
  File "C:\Users\60288184\Anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\sparsedetect.py", line 256, in estimate_spatial_scale
    im, _ = mode(imap[ipk][isort[:50]], keepdims=True)
TypeError: mode() got an unexpected keyword argument 'keepdims'
Interrupted by error (not finished)

[220929_example data_error_downgradedpython to 3.8.txt](https://github.com/MouseLand/suite2p/files/9680604/220929_example.data_error_downgradedpython.to.3.8.txt)

**Comment by samilcase** [comment]
I'm new to suite2P as well and having this exact same issue...

**Comment by chriski777** [comment]
Hi @enot14134 and @samilcase, just wondering, what version of scipy do you have installed on your machines?

**Comment by chriski777** [comment]
Also, can you specify which version of suite2p you are using?

**Comment by samilcase** [comment]
Hi there. I was using the latest version of suite2p (V0.11.1).  I believe it was an error that occurred during the installation process.  I removed all versions and tried again and it seems to work perfectly now.  Thanks!

**Comment by cgaletzka** [comment]
Hi, could you please let me know how you installed the newest version (python version etc.)? I’m having the same problem and reinstalling suite2p does not solve the error for me…
________________________________

**Comment by chriski777** [comment]
Hi @cgaletzka, hope these steps help:

1. First, make sure you've activated the conda environment for suite2p: `conda activate suite2p`.
2. You can try uninstalling suite2p by running:` pip uninstall suite2p `. 
3. Run `pip install suite2p`.
4. You can then check what version you have by running `pip show suite2p`.

**Comment by cgaletzka** [comment]
Hi @chriski777 , I reinstalled suite2p with these instructions, but I keep getting the same error as before. suite2p version is 0.11.1 with python 3.8.12 and scipy 1.8.0

Here is a list of the packages and version in my conda environment:

[New Text Document.txt](https://github.com/MouseLand/suite2p/files/9808329/New.Text.Document.txt)

**Comment by JAMoreno-Larios** [comment]
I had the very same error as @enot14134  and others, I was using Scipy 1.8.0. I updated it to Scipy 1.9.2 and the problem was fixed.

**Comment by chriski777** [comment]
Hey @cgaletzka, sorry about that, it seems one of my steps had an error. As @JAMoreno-Larios mentioned, this has to do with the scipy version you have installed. suite2p requires the version of scipy to be >= 1.9.0. 

Can you try reinstalling suite2p with the following command `python -m pip install suite2p` instead of `pip install suite2p`? Make sure you activated the suite2p environment with `conda activate suite2p` and that you're in the suite2p directory (should contain setup.py) when calling `python -m pip install suite2p`. 

You can also fix this by just upgrading scipy to any version above 1.9.0. I'll keep this closed for now but feel free to re-open if this issue persists!
