### ISSUE TITLE
saving and viewing XY offsets

### ISSUE THREAD

**Issue by vrutten** [MouseLand/suite2p#89]
Hi,

Would it be possible to save or have the option to save the XY offsets which the registration section estimates? I usually find it useful to be able to briefly glance at the registration shifts as a sanity check and check for any large deviations or oscillations, especially when dealing with moving animals.

e.g.: so that we could see something like:
(x-axis: pixel, y-axis: frame)

![registration shifts](https://user-images.githubusercontent.com/15912669/45257217-81c9df80-b370-11e8-9e1a-bf5169ebe8cd.png)

**Comment by carsen-stringer** [comment]
These are saved in ops.npy as 'yoff' and 'xoff', but we could also plot them in the GUI

**Comment by ransona** [comment]
I second the request for any 'sanity checks' for registration. With registration with NoRMCorre we sometimes saw an issue where one sub-tile/block of the frame (a bit with not much signal) had two best registration fit positions that it was constantly jumping back and forth between. Is this something we need to keep an eye out for with suite2p? We only noticed this when playing back the registered video - so a convenient way to play the registered video would be a valuable sanity check. Any other metrics that could flag up potentially dodgy registration would also be helpful, like spotting tiles which are being shifted significantly differently from the rest of the frame or that seem to have 2 or more discrete best registration positions?

**Comment by ransona** [comment]
... and also flagging up presence of signatures of slow z-drift would be really help with QC - i.e. https://figshare.com/articles/Drift_correction_for_electrophysiology_and_two-photon_calcium_imaging/5946574 - or some metric of how consistent the appearance of the putative neuron within an ROI is.

**Comment by marius10p** [comment]
We are currently working on some metrics for this. We'll let you know when they are available.

**Comment by ransona** [comment]
Great thanks.

**Comment by carsen-stringer** [comment]
I've added the ability to view the registered binary file in the GUI (see the new registration menu at the top). You can load in a file then click "View registered binary" or you can load your ops.npy file in the "view registered binary" window.
![binary](https://user-images.githubusercontent.com/15067541/45370715-c6df5300-b5b6-11e8-889b-c173da260224.png)

**Comment by carsen-stringer** [comment]
Alternatively if you want the registered frames in tiff format, you can set `ops['reg_tif']=1`.
