### ISSUE TITLE
Cannot load tiffs processed via imageJ even when saved as OME-TIFFs

### ISSUE THREAD

**Issue by jaimemcc** [MouseLand/suite2p#891]
First of all, thanks for creating and maintaining suite2p. It's a wonderful utility!

This is related to #135 but I think a new error that has not been reported.

Briefly, I have large (~20GB) TIFFs created in Scan Image that work fine in suite2p but I want to preprocess them in ImageJ before analysing (finding max projection of the 3 Z planes).

If I save as regular TIFF in ImageJ the files do not load in suite2p as they are >4GB as reported in issue #135 .

But if I save as OME-TIFF I also get an error relating to an argument being passed to _imread_ when it's called from _tiff_to_binary_

> imread() got unexpected keyword arguments 'pages'

I've attached the output errors from both cases. Before I go digging into the source I thought it would be useful to find out if others had experienced this issue.
[errors after imagej processing.txt](https://github.com/MouseLand/suite2p/files/9826319/errors.after.imagej.processing.txt)

**Comment by jaimemcc** [comment]
Hi @JoannaKlos For now, I have used a workaround by adding some code in my imagej script that saves the video into smaller (<4GB) chunks. As long as they are all in the same directory, suite2p does a great job of registering them to the same reference frame and producing a single binary. My imagej script is here in case you want to use bits of it: https://github.com/jaimemcc/azure/blob/main/split_2p_tiff.ijm

**Comment by butterm** [comment]
I encounter the same problem when I try to run the example and my files (smaller than 4G).
I would appreciate a solution
Thank you

**Comment by chriski777** [comment]
Hi everyone, thanks for reporting this issue and sorry for the late response. This issue with the imread method call should be fixed in the latest release. Feel free to reopen this issue if the problem persists!
