### ISSUE TITLE
Updated scipy crash - TypeError: mode() got an unexpected keyword argument 'keepdims' Interrupted by error (not finished)

### ISSUE THREAD

**Issue by catubc** [MouseLand/suite2p#892]
In case anyone gets this error:

`  File "/home/cat/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/detection/sparsedetect.py", line 256, in estimate_spatial_scale
    im, _ = mode(imap[ipk][isort[:50]], keepdims=True)
TypeError: mode() got an unexpected keyword argument 'keepdims'
Interrupted by error (not finished)
`
Seems related to scipy version. Upgrading to latest (1.9.3 as of time of writing).

[can close issue]

**Comment by chriski777** [comment]
Thanks, @catubc! As mentioned in #886, the latest version of suite2p requires version 1.9.3. The newest release will make sure this constraint for scipy is met.
