### ISSUE TITLE
Workaround for Rosetta terminal creation on Apple Silicon Macs running macOS Ventura or later

### ISSUE THREAD

**Issue by ryan-gorzek** [MouseLand/suite2p#897]
Starting with macOS Ventura, you can no longer duplicate Terminal.app, so the Rosetta terminal creation method from the article linked in the suite2p installation instructions won't work exactly as described.

Fortunately, installing iTerm2 (https://iterm2.com/) is an easy workaround. If you're not already using iTerm, simply install it into /Applications, right-click iTerm.app, select "Get Info", and check "Open using Rosetta". If you're already using iTerm, duplicate it first (rename it something like iTermRosetta.app if you'd like), then follow the same steps. Using that Rosetta iTerm terminal, you can follow the rest of the suite2p installation instructions for Apple Silicon Macs.

**Comment by gorzek-ryan** [comment]
Also, after `python -m pip install suite2p` I got the exception "PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported." when calling `python -m suite2p` to open the GUI. `pip install pyqt5` resolves this and everything works nicely.

**Comment by faezehrabbani97** [comment]
I have the same issue:
"PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported."
and installing pyqt5 didn't help.

**Comment by ryan-gorzek** [comment]
@faezehrabbani97 can you post the exception you get after installing PyQt5?

**Comment by chriski777** [comment]
Thanks, @ryan-gorzek! I've added these instructions to our `refactor` branch which we'll merge to `main` soon. `python -m pip install suite2p` actually installs a minimal version of suite2p (without the GUI dependencies) so a command like `python -m pip install suite2p[all]` can install the GUI/NWB dependencies. 

@faezehrabbani97, if this issue is still persisting, feel free to open up an issue! I'll be closing this issue as the README.md has been updated.

**Comment by trose-neuro** [comment]
Just to confirm this: suite2p runs on apple silicon? Because I have massive trouble installing. Pulling 'imagecodecs' form conda forge solved some issues - but pyqt5 fails to install entirely (Preparing metadata (pyproject.toml) ... error)...

**Comment by chriski777** [comment]
Ah, it does run on the Mac computers with the M1 chip for sure but I'm not too sure about machines with the M2 chips. Just checking, you can't install pyqt5 even on a rosetta-opened iterm2 session?

**Comment by trose-neuro** [comment]
Actually: I can now. I did (of course) not follow the instructions properly (blanked on CONDA_SUBDIR=osx-64 in the environment creation).

**Comment by chriski777** [comment]
Ah, no worries! Glad to hear it works for you!!!
