### ISSUE TITLE
`sig_baseline` unit for spike deconvolution

### ISSUE THREAD

**Issue by tjjlemaire** [MouseLand/suite2p#902]
Hi,

I've been playing around with the `dcnv.preprocess` function from the `suite2p.extraction` module to extract/remove a baseline from fluorescence signals. Looking at the source code, I am a bit confused by the unit of the `sig_baseline` parameter. The docstring refers to it as "width of Gaussian filter in seconds", but this parameter does not seem to be multiplied by the sampling rate before being fed into the `gaussian_filter` function. Could you please clarify this? Thank you!

**Comment by carsen-stringer** [comment]
sorry that is incorrect in the source code, I've fixed it
