### ISSUE TITLE
TypeError when running suite2p on sample data

### ISSUE THREAD

**Issue by jacobaclay** [MouseLand/suite2p#903]
Good afternoon, 

When I try to run suite2p on the sample data set provided, I get the following error: 

![image](https://user-images.githubusercontent.com/78123210/204593452-d0ee6793-cddc-4550-9e2a-7b955ed1dc18.png)

Could you please let me know what might be causing it? Please note that I am unable to view the full error message, as the window is not scaled to the screen (see my first question). 

Thanks for your time, 
Jacob

**Comment by chriski777** [comment]
Hi Jacob, this issue seems to be related to #831 and #900. Can you try using the latest version of suite2p by following the section titled "Installing the latest github version of the code" on the README.md?

**Comment by chriski777** [comment]
Hi @jacobaclay, this should be fixed in the latest release v0.12.0. I'll close this issue for now but feel free to reopen it if updating to the latest version doesn't fix this.
