### ISSUE TITLE
Potentially duplicate/missing backgrounds in NWB file

### ISSUE THREAD

**Issue by tuanpham96** [MouseLand/suite2p#905]
In these lines when converting to NWB file, if I understand the code correctly, this is only saving the last plane instead of all planes when reading/writing `Backgrounds_{}` image data. 

https://github.com/MouseLand/suite2p/blob/d7915fa191a3c9cdcdf140a4194acab2011dbe5c/suite2p/io/nwb.py#L516-L523

Should this changed to

```python
 # (meanImg, Vcorr and max_proj are REQUIRED) 
 # nplanes = ops["nplanes"]  # removed
 # for iplane in range(nplanes): # removed
 for iplane, ops in enumerate(ops1): # added
```

 Thanks!

**Comment by chriski777** [comment]
Hi, @tuanpham96, you're absolutely right! Thanks for reporting this issue. This has been fixed and the code will be pushed soon.
