### ISSUE TITLE
NWB RoiResponseSeries outputs are transposed

### ISSUE THREAD

**Issue by rly** [MouseLand/suite2p#909]
The NWB output for suite2p includes 3 Fluorescence objects which each contain an RoiResponseSeries: "Deconvolved", "Fluorescence", and "Neuropil". These objects have "data" datasets that are num_rois x num_time. However, they should be num_time x num_rois. 

When appending to these files with the latest version of PyNWB, a warning is raised because of the mismatched dimensions.

fyi @bendichter

**Comment by chriski777** [comment]
Hi @rly, what version of suite2p are you using? I ran the following block of code on the latest version on the master branch `0.11.2.dev47+gd7915fa` and the shapes for those datasets match num_time x num_rois. 
```
ops = suite2p.default_ops()
db = {
    'data_path': ['/Users/chriski/Desktop/suite2p_data/test_inputs'],
    'save_path0': '/Users/chriski/Desktop/suite2p_data/test_inputs',
    'tiff_list': ['input_1500.tif'],
}
ops['save_NWB']=1
output_ops = suite2p.run_s2p(ops=ops, db=db)

io =  NWBHDF5IO("/Users/chriski/Desktop/suite2p_data/test_inputs/suite2p/ophys.nwb", mode="a")
read_file = io.read()

read_file.processing['ophys']['Deconvolved'].roi_response_series['plane0'].data.shape
read_file.processing['ophys']['Fluorescence'].roi_response_series['plane0'].data.shape
read_file.processing['ophys']['Neuropil'].roi_response_series['plane0'].data.shape
```

We made a couple of changes to the `save_nwb` function in suite2p since v0.11.1 so this might not be a problem in the most updated version. Did you still find this issue on the latest version on the master branch?

**Comment by chriski777** [comment]
Hi @rly, just wanted to check in again and see if this was still an issue with the latest release of suite2p?

**Comment by chriski777** [comment]
I still can't reproduce this issue on my end so I'll close this due to inactivity but please feel free to reopen if the issue still persists!

**Comment by rly** [comment]
Hi @chriski777 , sorry about the late response! The bug report was based on older data that a collaborator was working with. I tried to reproduce it yesterday by running suite2p on my end and could not reproduce it either, so this issue is good to close. Perhaps my collaborator generated results using a much older version of suite2p before some fixes.

**Comment by chriski777** [comment]
No worries, @rly! I'm glad to hear that. Thanks for letting us know!
