### ISSUE TITLE
cannot load or save options in suite2p 0.12.0

### ISSUE THREAD

**Issue by ziyizhu1996** [MouseLand/suite2p#914]
### Describe the issue:

After opening suite2p GUI, if I want to save a set of parameters using 'save ops to file', after putting in a file name, an error occurs (as described in error message).

If I do 'save ops as default', suite2p GUI will crash (python will stop responding).

### Reproduce the code example:

```python
python -m suite2p
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\zzhu34\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 459, in save_ops
    self.save_text()
  File "C:\Users\zzhu34\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 484, in save_text
    self.ops[key] = self.editlist[k].get_text(self.intkeys, self.boolkeys)
TypeError: get_text() missing 1 required positional argument: 'stringkeys'
```

### Version information:

suite2p 0.12.0

**Comment by chriski777** [comment]
Hi @ziyizhu1996, thanks for letting us know about this issue! It's been fixed in the latest version of the `refactor` branch. Could you try pulling those changes and trying it now? I'll close this issue for now but feel free to reopen it if you are still having problems!
