### ISSUE TITLE
DOC: Outdated ops.npy documentation

### ISSUE THREAD

**Issue by nspiller** [MouseLand/suite2p#916]
### Issue with current documentation:

The settings that appear in the suite2p GUI are not explained in the [documentation](https://suite2p.readthedocs.io/en/latest/settings.html). 

Settings in the GUI that are not mentioned in the documentation.
- **Main settings**: `multiplane_parallel`, `ignore_flyback`
- **Output settings**: `save_NWB`,  `delete_bin`, `move_bin`
- **Registration**: `th_badframes`
- **Functional detect**: `denoise`, `spatial_hp_detect`
- **Anat detect**: everything
- **Extraction/Neuropil**: `neuropil_extract`
- **Classify/Deconv**: `soma_crop`, `spikedetect`

`reg_tif`, `reg_tiff_chan2` are listed as **Registration** in the documentation.
`spatial_hp_reg` is called `spatial_hp` in the documentation.
**Functional detect** is called **ROI detection** in the documentation.
**Extraction/Neuropil** is called **Signal extraction** in the documentation.
**Classify/Deconv** is called **Spike deconvolution** in the documentation.

I am running `suite2p 0.12.0`. 

### Idea or request for content:

It would also be helpful to mention that False=0 and True=1.

**Comment by chriski777** [comment]
Hi @nspiller, thanks for reporting this. We've updated the docs to correctly show the missing settings.
