### ISSUE TITLE
suite2p fails with only rigid registration

### ISSUE THREAD

**Issue by rozmar** [MouseLand/suite2p#917]
This line expects a list with 3 elements, but if ops['nonrigid'] is set to False, it is an empty list.

https://github.com/MouseLand/suite2p/blob/d0a454dcd274ccc37d1fe8e55cb369ba382055b4/suite2p/registration/register.py#L615

**Comment by chriski777** [comment]
Hi @rozmar, this issue was fixed in the commit d53fe68951dd2f52babcac7727d3c25906b3501d. Could you update to the latest version 0.12.0 and see if this issue persists for you? I will close this for now but feel free to reopen the issue if you are still having problems.
