### ISSUE TITLE
How to deal with different cell sizes?

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#92]
I have data with a mixed cell size (3 to 16). If I set the cell size to 3, I find the small and medium sized cells very well, but miss the large ones.

What would you suggest to try out?

**Comment by marius10p** [comment]
First you should determine that the large cells have activity. Try running the pipeline with the largest cell size. It should be somewhat robust to this parameter, at least over a factor of 2, so if the large cells really do have activity, you could try setting the diameter in-between.

**Comment by Cumol** [comment]
Will try that and report back. Thank you for the quick responses!

**Comment by Cumol** [comment]
I went with a ROI size of 7 that works well in my case. Thanks for the suggestion!
