### ISSUE TITLE
FEATURE: registering structural z-stacks without averaging (frame order difference problem)

### ISSUE THREAD

**Issue by rozmar** [MouseLand/suite2p#920]
### Feature you'd like to see:

To get crisp structural average Z-stacks, it would be nice to create short movies of each plane, then register the frames each plane separately, average, then make a Z-stack. The problem is that if you create a Z-stack this way, the images are not in the same order as how suite2p expects, and due to the randomness of the reference image, the subsequent planes can be shifted in XY relative to each other.

I have a solution for single-channel Z-stacks, but cannot figure out the way for 2-channel ones..

### Attempted alternative approaches:

For a single channel, I just reorder the frames by iterating through them:
```
tiff_orig = tifffile.imread(scanimage_tiff_file_name)
imgperplane = tiff_orig.shape[1]
tiff_reordered = np.zeros([tiff_orig.shape[0]*tiff_orig.shape[1],tiff_orig.shape[2],tiff_orig.shape[3]],np.int16)
for slice_i, slicenow in enumerate(tiff_orig):
    for img_i, imgnow in enumerate(slicenow):
        tiff_reordered[img_i*nplanes+slice_i,:,:] = imgnow
tifffile.imsave(reordered_tiff_file_name,tiff_reordered)
```
Then run s2p registration on the big file. 
Then iterate through the planes, and then align each plane to the previous one, since they are quite similar:
```
maskMul, maskOffset = rigid.compute_masks(refImg=meanimages[-1],
                                          maskSlope=1)
cfRefImg = rigid.phasecorr_reference(refImg=meanimages[-1],
                                     smooth_sigma=1)
ymax, xmax, cmax = rigid.phasecorr(data=np.complex64(np.float32(np.asarray([ops['meanImg']]*2)) * maskMul + maskOffset),
                                   cfRefImg=cfRefImg,
                                   maxregshift=50,
                                   smooth_sigma_time=0)
regimage = rigid.shift_frame(frame=ops['meanImg'], dy=ymax[0], dx=xmax[0])
```

But for some reason, it doesn't work for me for 2 channel movies:
```
imgperplane = tiff_orig.shape[1]
tiff_reordered = np.zeros([tiff_orig.shape[0]*tiff_orig.shape[1]*tiff_orig.shape[2],tiff_orig.shape[3],tiff_orig.shape[4]],np.int16)
for slice_i, slicenow in enumerate(tiff_orig):
    for img_i, imgnow in enumerate(slicenow):
        for ch_i, ch_imgnow in enumerate(imgnow):
            tiff_reordered[img_i*nplanes*nchannels+slice_i*nchannels+ch_i,:,:] = ch_imgnow
```
What am I missing? Should it be frames X channels X dim1 X dim2 ?

**Comment by carsen-stringer** [comment]
yes it should be frames by channels by dim1 by dim2

most people take z-stacks in this way interleaved, if they have a piezo, so that's why we support tiffs in their current order
