### ISSUE TITLE
wobbly registration

### ISSUE THREAD

**Issue by sdaste** [MouseLand/suite2p#921]
Hi,
I'm having issues with Suite2P registration for particular data. You can find [here](https://drive.google.com/file/d/19xiiNrwLIfrEG4rjxmIQvy_8CA4bE-UN/view?usp=share_link) a snapshot of registered (left) versus unregistered (right) data from Suite2P GUI. The registrated data is overall worse and wobbly than the raw one, which nonetheless shows non-rigid movement.
Attached are the parameters have been using for it.

Do you have any suggestions on parameter changes I could make to improve it?

Thanks in advance for your help! Please let me know if you need further information.

Simon
<img width="1031" alt="Screenshot 2023-02-09 at 16 06 18" src="https://user-images.githubusercontent.com/58048615/217940426-0afbe7a8-6420-4c31-ac6f-3dc2f5d505d9.png">

**Comment by chriski777** [comment]
Hi @sdaste, thanks for reaching out about this. Could you try running with a smaller `block_size` and larger `spatial_taper`?  This "wobbliness" may be induced by the registration module including the black background during registration. By increasing the `spatial_taper`, it should hopefully remove the effects of pixels involved in the black background for registration.

**Comment by chriski777** [comment]
Hi @sdaste, have you tried the advice above?

**Comment by chriski777** [comment]
Hi @sdaste, I will close this issue due to inactivity. Please feel free to reopen the issue if it persists.
