### ISSUE TITLE
ROI classification into somas, dendrites and rest?

### ISSUE THREAD

**Issue by samupicard** [MouseLand/suite2p#932]
### Feature you'd like to see:

I have a pan-excitatory dataset with a mixture of somas, dendrites and neuropil fluorescence. I would ideally like to keep both somas and dendrites that have a clear footprint, but classify these two types of ROI into separate classes. Having only briefly looked into how suite2p does classification, I was wondering whether it would be possible to classify ROIs not as cells v not cells (2 classes) but as somas, dendrites or junk (3 classes). Ideally the current logistic regression would be replaced by a multi-class regression that would output the probability of each class, and then choose the one with the highest probability. Do you think this would be possible given the right training set?

### Attempted alternative approaches:

Given that binary classification seems to be the only option for now, the work-arounds I can think of right now would be:
1. to run two separate binary classifications, one using a classifier trained on somas vs. non-somas, and another using a classifier trained on dendrites vs. non-dendrites, and somehow combine their probabilities to assign the ROI to one class 
2. take the output of a general cell v. non-cell classifier and further subdivide this using a second classifier trained on a different set of features (maybe morphological?)

**Comment by carsen-stringer** [comment]
the first approach seems good. I would recommend trying the "aspect_ratio" and "compactness" stat fields? that may help you solve this. we will not be supporting this directly
