### ISSUE TITLE
BUG: jupyter/Run Suite2p.ipynb not working

### ISSUE THREAD

**Issue by nspiller** [MouseLand/suite2p#935]
### Describe the issue:

Hi,

I want to use the jupyter notebooks to better understand how suite2p is working under the hood. However, the notebook `Run Suite2p.ipynb` is not working out of the box.

Steps to reproduce:

- Clone repo
- Open and run `Run Suite2p.ipynb`
- Line 
`output_ops = suite2p.run_s2p(ops=ops, db=db)`
 throws the error : 
 `FileNotFoundError: [Errno 2] No such file or directory: '..\data\\test_data\\input_1500.tif'`
- If I use my own data, the line 
`im = suite2p.ROI.stats_dicts_to_3d_array(stats, Ly=output_ops['Ly'], Lx=output_ops['Lx'], label_id=True)`
 fails with 
 `TypeError: __init__() missing 2 required positional arguments: 'med' and 'do_crop'`

The first error arises, because the `data` folder was removed in some past release. Is there some test data in the repo somewhere?

I guess that the second error arises due to some changes in the ROI class so that the `from_stat_dict` method is not working anymore.

Cheers

### Reproduce the code example:

```python
import suite2p
from tempfile import TemporaryDirectory
import numpy as np

ops = suite2p.default_ops()
db = {
    'data_path': ['../data/test_data'],
    'save_path0': TemporaryDirectory().name,
    'tiff_list': ['input_1500.tif'],
output_ops = suite2p.run_s2p(ops=ops, db=db)
}

stats_file = Path(output_op['save_path']).joinpath('stat.npy')
iscell = np.load(Path(output_op['save_path']).joinpath('iscell.npy'), allow_pickle=True)[:, 0].astype(bool)
stats = np.load(stats_file, allow_pickle=True)

im = suite2p.ROI.stats_dicts_to_3d_array(stats, Ly=output_op['Ly'], Lx=output_op['Lx'], label_id=True)
```

### Version information:

0.12

**Comment by chriski777** [comment]
Hi @nspiller, thanks for letting us know about this! The jupyter notebook should be fixed along with the `from_stat_dict` bug you mentioned. You can pull these changes from the main branch. I'll close this issue now but please let me know if you have any additional issues!
