### ISSUE TITLE
DOC: how does suite2p determine the order in which to concatenate tiff files

### ISSUE THREAD

**Issue by KangByungwoo** [MouseLand/suite2p#936]
### Issue with current documentation:

Hi,

So far, I've either saved the entire recording session to a single tiff file or multiple files with a limit of 500 frames per file (all using Scanimage version 2022) in a single folder, and suite2p has given me reasonable results, so I believe it has concatenated the files in the correct order. But, now that I am concatenating tiff files across days to track the same neurons across days, I am curious how suite2p determines the order in which to concatenate tiff files (apparently I couldn't find this info on the documentation). I am currently doing it by adding tiff directories to data_path in the order of earlier to later recording days (each tiff directory can contain either a single tiff file containing all frames from a recording session or multiple tiff files each containing at most a specified number of frames as specified in Scanimage). Is this the right way to do it?

**Comment by chriski777** [comment]
Hi @KangByungwoo, that is correct. You can refer to [this link](https://github.com/MouseLand/suite2p/blob/399e38ef2b7b7900334cd606636f51b60d284e75/suite2p/io/tiff.py#L97) if you'd like more information on how the files would be read in. I will close this issue for now but feel free to reopen if you have any other questions!
