### ISSUE TITLE
BUG: Footprint takes integer values suite2p v0.12.0

### ISSUE THREAD

**Issue by jacobaclay** [MouseLand/suite2p#937]
### Describe the issue:

While running suite2p on data from the V1 of a SOM-Cre mouse with indicator GC6f, we encountered integer values for the footprint, which surprised us. What might be the explanation for this phenomenon? 

![image](https://user-images.githubusercontent.com/78123210/229255165-c954b616-8a00-4cc4-9d67-c01f94f16ae4.png)

(NOTE: This isn't a bug per se, but that was the most appropriate label out of the ones available). 

### Reproduce the code example:

```python
This is not applicable--see above explanation.
```

### Version information:

suite2p v0.12.0

### Context for the issue:

We have hundreds of TIFFs of this form, and we need to make sure that we can correctly interpret the results of suite2p before preprocessing them.

**Comment by chriski777** [comment]
Hi @jacobaclay, can you clarify what you mean by the footprint?

**Comment by jacobaclay** [comment]
Hi @chriski777,

Thanks for your reply. From suite2p's documentation: 

footprint: spatial extent of an ROI’s functional signal, including pixels not assigned to the ROI; a threshold of 1/5 of the max is used as a threshold, and the average distance of these pixels from the center is defined as the footprint

All the best,
Jacob

**Comment by carsen-stringer** [comment]
I wouldn't use this metric, it has a new definition in the latest algorithm version that makes it an integer based on its approximate scale
