### ISSUE TITLE
ROIs don't seem to match mean image

### ISSUE THREAD

**Issue by jacobaclay** [MouseLand/suite2p#938]
While running suite2p on TIFFs from mouse V1, we encountered ROIs that didn't seem to match the mean image on multiple occasions, even after adjusting the probability threshold. Here are two examples:

SOM-Cre mouse, GC6f:
![image](https://user-images.githubusercontent.com/78123210/229256677-83cfcbe2-d82d-4c88-a81d-469ade9b6eae.png)
![image](https://user-images.githubusercontent.com/78123210/229256684-b1bad1ee-c591-4cdf-91f7-61ded59e9aba.png)

Scnn1a-Cre mouse, CG6f:
![image](https://user-images.githubusercontent.com/78123210/229256708-66e0d75e-5052-499a-9b13-4ade51de5ebc.png)
![image](https://user-images.githubusercontent.com/78123210/229256712-c1aa58bf-73f8-458b-859a-a8866009f931.png)

If you could help us explain these, we would greatly appreciate it. The preprocessing of thousands of TIFFs from this dataset is on hold until the issue is resolved.

**Comment by carsen-stringer** [comment]
It seems like there is poor expression and activity in these cells, I would recommend using the cellpose segmentation with the `anatomical_only` option
