### ISSUE TITLE
(Over/under)-correlated traces

### ISSUE THREAD

**Issue by jacobaclay** [MouseLand/suite2p#939]
We're trying to interpret traces that seem unusually correlated (first image) and unusually correlated (second image). Do you have any explanations for this phenomenon? We'd be happy to share the TIFFs if that would be helpful. Thanks in advance! 

SOM-Cre mouse, GC6f:
![image](https://user-images.githubusercontent.com/78123210/229256936-297ffe25-8fe1-47da-9755-244caa95abcf.png)

Scnn1a-Cre mouse, CG6f:
![image](https://user-images.githubusercontent.com/78123210/229256944-1fc257ee-7f88-4f23-b1a8-c8cad8c0690b.png)

**Comment by carsen-stringer** [comment]
I'm sorry I don't see anything suspicious here?
