### ISSUE TITLE
Strange mean image

### ISSUE THREAD

**Issue by jacobaclay** [MouseLand/suite2p#940]
We found a strange mean image characterized by horizontal bars and square ROIs (see below). Could you please let us know what might be causing the issue? It might be a problem with the data itself, but in that case, we'd like to know whether it's feasible to run the pipeline on such data. Thanks!

![image](https://user-images.githubusercontent.com/78123210/229257167-ae0bc3be-b682-4084-8a94-1c4fe990c50b.png)

**Comment by chriski777** [comment]
Hi @jacobaclay, what do individual frames of the dataset look like? Do they have these square ROIs too? How does the recording look when you play it?

**Comment by jacobaclay** [comment]
Hi Chris, 

Thanks for prioritizing this. Individual frames of the TIFF look like this: 

![image](https://user-images.githubusercontent.com/78123210/231513632-aee496e6-5fb5-4df6-9a52-60703fb0e4b7.png)

Scrolling through the TIFF reveals that the dark diagonally oriented bars move slowly across the screen as the recording plays, from top right to bottom left. 

All the best, 
Jacob

**Comment by carsen-stringer** [comment]
I'm sorry Jacob it seems like there's something wrong with your microscope, we cannot remove this sort of thing inside suite2p.

You may want to do manual segmentation but I'm not sure if the registration worked - you'll need to watch the binary.

I would recommend talking to an optical engineer from the company who makes your scope or some other imaging expert.
