### ISSUE TITLE
DOC: temporal high pass filter is applied to binned movie

### ISSUE THREAD

**Issue by nspiller** [MouseLand/suite2p#943]
### Describe the issue:

I am going through the `sparsery` function [here](https://github.com/MouseLand/suite2p/blob/main/suite2p/detection/sparsedetect.py). In line 278, the `temporal_high_pass_filter` from [here](https://github.com/MouseLand/suite2p/blob/main/suite2p/detection/utils.py) is applied. 

In my case, `high_pass = 100` and my 2000 frames got binned into 95 chunks of length 21 (`mov.shape = (95, 512, 512)`).
Therefore, the `hp_rolling_mean_filter` is selected and a `width = 100` is passed to it. In the function `hp_rolling_mean_filter`, the step length of the `range` is equal to the `width`. 
```
for i in range(0, mov.shape[0], width):
    mov[i:i + width, :, :] -= mov[i:i + width, :, :].mean(axis=0)
```

Am I reading this wrong? To me, it appears that the `high_pass` option in the [ROI detection](') specifies the number of frames, but the `hp_rolling_mean_filter` acts in bins.

As a side note, the [documentation](https://suite2p.readthedocs.io/en/latest/settings.html#roi-detection-settings) explains the `high_pass` as _running mean subtraction across time with window of size ‘high_pass’_. However, the `hp_rolling_mean_filter` docstring states that a _non-overlapping rolling mean kernel_ is used, which is obvious from the code snippet above. In my opinion, this is not really a [running mean](https://en.wikipedia.org/wiki/Moving_average). 

Furthermore, if `high_pass < 10`, the function `temporal_high_pass_filter` selects `hp_gaussian_filter`, which is not a temporal filter, right? It is applied to the x-component of the movie:
```
for j in range(mov.shape[1]):
    mov[:, j, :] -= gaussian_filter(mov[:, j, :], [width, 0])
```

### Reproduce the code example:

```python
import numpy as np
import suite2p
from tempfile import TemporaryDirectory

ops = np.load('./test_recording/suite2p.npy', allow_pickle=True).item()
db = {
    'data_path': ['./test_recording'],
    'save_path0': TemporaryDirectory().name,
    'tiff_list': ['data.tif'],
}

output_ops = suite2p.run_s2p(ops=ops, db=db)
```

### Version information:

0.12.1

**Comment by carsen-stringer** [comment]
we will fix the documentation to state that this is in bins not in samples

we're sorry that is not a non-overlapping rolling mean, that is a standard rolling mean.

regarding the "bug", that is incorrect, that second code snippet the gaussian filter still applied to the first dimension, we just wrote it in a strange way.
