### ISSUE TITLE
FEATURE: adding leading zeros to the reg_tif file list

### ISSUE THREAD

**Issue by zahramansoor** [MouseLand/suite2p#944]
### Feature you'd like to see:

Hello,

I've been using the registered images from the generated `reg_tif` folder from suite2p motion correction to run separate analysis. Since these are typically split every 500 frames in the default ops parameters, it generates a list of tifs named `file000_chan0.tif`, `file500_chan0.tif`, `file1000_chan0.tif`, etc. However, if you have over 1000 frames the length of the file names is off by 1 for the first 2 files because the first 2 tifs (000 and 500) do not have leading zeros. This creates a problem when you want to generate 1 concatenated tif out of the individual registered tifs because file sorting in both MATLAB and Python will place `file500_chan0.tif` after `file4500_chan0.tif` for example and not after `file000_chan0.tif`. I would suggest adding up to 5 leading zeros in the filenames in `reg_tif` (e.g. `file00000_chan0.tif`, `file00500_chan0.tif`) will fix this problem for anyone trying to do separate downstream analysis.

### Attempted alternative approaches:

Currently I am just renaming the `reg_tif` files in my pipeline before doing any further analysis but it would be great if suite2p has this feature built in.

**Comment by tdincer** [comment]
@zahramansoor 
Here is a simple solution without changing any file names.

```python
# Create some file names based on Suite2p's default behavior
reg_files = [f"file{x*500}_chan0.tif" for x in range(5)]

# Mess with the order of file_names.
reg_files = reg_files[::-1]

# Sort them.
import re
reg_files.sort(key=lambda f: int(re.sub('\D', '', f)))
```

**Comment by chriski777** [comment]
Sorry for the long wait @zahramansoor! This change has been added to the `dev` branch if you'd like to use it now. It should be merged into the main branch soon.
