### ISSUE TITLE
ROI not detected on Fish 

### ISSUE THREAD

**Issue by bdshaw37** [MouseLand/suite2p#945]
Hi,
The main issue I am running into so far is ROI detection. I have attached several screenshots below of the post-processing from different recordings. What I am observing is the processed data is detecting a lot of ROI's outside of the fish, while not detecting many inside.

I have been trying to tweak the setting and see if any improvement can be made. Mainly "threshold_scaling" and "max_iterations". I have also attached the most recent setting I have been processing with.
<img width="595" alt="Screen Shot 2023-04-13 at 6 17 30 PM" src="https://user-images.githubusercontent.com/99566582/231913060-ceafdcaa-4d8f-484c-a9a8-bf4be3eae4a4.png">
<img width="1083" alt="Screen Shot 2023-04-13 at 6 10 16 PM" src="https://user-images.githubusercontent.com/99566582/231913065-2e6fbb5f-9ae0-4d37-86ef-2b14b0f0cd9c.png">
<img width="1064" alt="Screen Shot 2023-04-13 at 6 10 50 PM" src="https://user-images.githubusercontent.com/99566582/231913069-d78939b0-4595-40f5-aa4f-6814f711ec7c.png">
<img width="1127" alt="Screen Shot 2023-04-13 at 6 08 40 PM" src="https://user-images.githubusercontent.com/99566582/231913071-fa19cee4-96c5-412d-914a-c5c8347f2656.png">
<img width="1008" alt="Screen Shot 2023-04-13 at 6 09 53 PM" src="https://user-images.githubusercontent.com/99566582/231913072-39a88c3a-26fb-4dbb-903d-6def2fcd0abf.png">

**Comment by carsen-stringer** [comment]
If you do not have a lot of time frames, then activity detection won't work. You can try to decrease spatial_hp_detect or to use cellpose with anatomical_only
