### ISSUE TITLE
ScanImage TiffReader not able to read the sample data

### ISSUE THREAD

**Issue by marytunun** [MouseLand/suite2p#946]
### Describe the issue:

1) I successfully installed all the requirements except scanimage-tiff-reader(described later).
2) Was able to open the suite2p GUI and setup the configuration
3) But after i press 'Run' i see this error in the GUI of the suite2p is as follows: 

{'data_path': ['C:/Users/Maria/Documents/suite2p/tiffs'], 'subfolders': [], 'save_path0': 'C:/Users/Maria/Documents/suite2p/save_path', 'fast_disk': 'C:/Users/Maria/Documents/suite2p/fast_disk', 'input_format': 'tif'}
tif
** Found 5 tifs - converting to binary **
2000 frames of binary, time 18.01 sec.
4000 frames of binary, time 31.26 sec.
6000 frames of binary, time 42.81 sec.
>>>ERROR<<<
Traceback (most recent call last):
>>>ERROR<<<
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\runpy.py", line 197, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 411, in run_s2p
>>>ERROR<<<
    ops0 = io.tiff_to_binary(ops.copy())
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 135, in tiff_to_binary
    tif, Ltif = open_tiff(file, use_sktiff)
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 82, in open_tiff
    tif = ScanImageTiffReader(file)
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\ScanImageTiffReader\__init__.py", line 173, in __init__
>>>ERROR<<<
    self.open(filename)
  File "C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\ScanImageTiffReader\__init__.py", line 222, in open
>>>ERROR<<<
    raise Exception(self.__ctx.log.decode("utf-8","strict"))
>>>ERROR<<<
Exception: No strip offsets found.  This reader only reads Tiffs with strip data

-----------**********---------------**************-------------------------***********----------------------------------
I suspect that the issue somehow relates to the **error that Scanimage-tiff-reader encounters during installation**. The package is not able to build a wheel and is installed by the legacy method using setup.py, here is the error:

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'ScanImageTiffReader.external' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'ScanImageTiffReader.external' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'ScanImageTiffReader.external' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'ScanImageTiffReader.external.__pycache__' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'ScanImageTiffReader.external.__pycache__' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'ScanImageTiffReader.external.__pycache__' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'ScanImageTiffReader.external.__pycache__' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      copying src\ScanImageTiffReader\__init__.pyc -> build\lib\ScanImageTiffReader
      creating build\lib\ScanImageTiffReader\__pycache__
      copying src\ScanImageTiffReader\__pycache__\__init__.cpython-36.pyc -> build\lib\ScanImageTiffReader\__pycache__
      copying src\ScanImageTiffReader\__pycache__\__init__.cpython-37.pyc -> build\lib\ScanImageTiffReader\__pycache__
      creating build\lib\ScanImageTiffReader\external
      copying src\ScanImageTiffReader\external\README.md -> build\lib\ScanImageTiffReader\external
      copying src\ScanImageTiffReader\external\__init__.py -> build\lib\ScanImageTiffReader\external
      copying src\ScanImageTiffReader\external\__init__.pyc -> build\lib\ScanImageTiffReader\external
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
      copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib
      copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib\libScanImageTiffReaderAPI.so -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib
      copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib\ScanImageTiffReaderAPI.dll -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib
      creating build\lib\ScanImageTiffReader\external\__pycache__
      copying src\ScanImageTiffReader\external\__pycache__\__init__.cpython-36.pyc -> build\lib\ScanImageTiffReader\external\__pycache__
      copying src\ScanImageTiffReader\external\__pycache__\__init__.cpython-37.pyc -> build\lib\ScanImageTiffReader\external\__pycache__
      C:\Users\Maria\anaconda3\envs\suite2p\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external
      copying build\lib\ScanImageTiffReader\external\README.md -> build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
      copying build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so -> build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
      error: could not create 'build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scanimage-tiff-reader
  Running setup.py clean for scanimage-tiff-reader
Failed to build scanimage-tiff-reader
Installing collected packages: scanimage-tiff-reader
  Running setup.py install for scanimage-tiff-reader ... done
  DEPRECATION: scanimage-tiff-reader was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 23.1 will enforce this behaviour change. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368

### Provide environment info:

 active environment : suite2p
    active env location : C:\Users\Maria\anaconda3\envs\suite2p
            shell level : 2
       user config file : C:\Users\Maria\.condarc
 populated config files : C:\Users\Maria\.condarc
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\Maria\anaconda3  (writable)
      conda av data dir : C:\Users\Maria\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Maria\anaconda3\pkgs
                          C:\Users\Maria\.conda\pkgs
                          C:\Users\Maria\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Maria\anaconda3\envs
                          C:\Users\Maria\.conda\envs
                          C:\Users\Maria\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

-------------------------**********************-------------------------------*****************************---------------
To solve the wheel building issue of the imagescan-tiff-reader, i also have installed (following this thread https://stackoverflow.com/questions/71470989/python-setup-py-bdist-wheel-did-not-run-successfully):
**nes-py
Cmake**

**Comment by carsen-stringer** [comment]
Sorry this library needs to update, we've removed this dependency for now, please `pip install git+https://GitHub.com/mouseland/suite2p.git`
