### ISSUE TITLE
DOC: Specifying bad frames (for photostim artifacts) when concatenating multiday recordings

### ISSUE THREAD

**Issue by KangByungwoo** [MouseLand/suite2p#949]
### Issue with current documentation:

Hi,

I am wondering how to specify the bad frames (for photostim artifacts) when concatenating multiday recordings. Should I use frame indices of the concatenated tiff file for this? And also just to be sure, frame indices use the convention such that they start from 0? So for example, if I have bad frames at 20th, 40th, 60th frame on both days of recordings of 40000 frames, then bad_frames.npy should have [19, 39, 59, 40019, 40039, 40059]?

**Comment by chriski777** [comment]
Yep, that is right. You should use the frame indices (starting from 0) corresponding to the concatenated file.
