### ISSUE TITLE
optimising roi detection threshold

### ISSUE THREAD

**Issue by ransona** [MouseLand/suite2p#95]
Do you have any suggestions on how to set the roi detection threshold for data from very sparsely labelled tissue, or tissue where the sparseness is unpredictable? As I understand it the roi detection threshold calculation assumes that there are always rois to detect (i.e. thres  = ops['threshold_scaling'] * np.median(peaks[peaks>1e-4]))? This gives a lot of false positives when there is for example just a single axon in the FOV (see image below).
![image](https://user-images.githubusercontent.com/7849066/45508767-97367380-b78d-11e8-832c-f6f2120dd7f8.png)

**Comment by marius10p** [comment]
You should try a much larger diameter.
