### ISSUE TITLE
installation error about scanimage-tiff-reader

### ISSUE THREAD

**Issue by HuijeongJeong** [MouseLand/suite2p#950]
### Describe the issue:

I keep getting an error during installation like below. Any ideas? 

`Building wheels for collected packages: scanimage-tiff-reader
  Building wheel for scanimage-tiff-reader (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [198 lines of output]
      D:\anaconda3\envs\suite2p\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\ScanImageTiffReader
      copying src\ScanImageTiffReader\__init__.py -> build\lib\ScanImageTiffReader
      running egg_info
      writing src\scanimage_tiff_reader.egg-info\PKG-INFO
      writing dependency_links to src\scanimage_tiff_reader.egg-info\dependency_links.txt
      writing requirements to src\scanimage_tiff_reader.egg-info\requires.txt
      writing top-level names to src\scanimage_tiff_reader.egg-info\top_level.txt
      reading manifest file 'src\scanimage_tiff_reader.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.h' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching 'src\**\external\**\bin\*' found anywhere in distribution
      adding license file 'LICENSE'
      writing manifest file 'src\scanimage_tiff_reader.egg-info\SOURCES.txt'
      D:\anaconda3\envs\suite2p\lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'ScanImageTiffReader.__pycache__' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'ScanImageTiffReader.__pycache__' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'ScanImageTiffReader.__pycache__' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'ScanImageTiffReader.__pycache__' to be distributed and are
              already explicitly excluding 'ScanImageTiffReader.__pycache__' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\anaconda3\envs\suite2p\lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'ScanImageTiffReader.external' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'ScanImageTiffReader.external' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'ScanImageTiffReader.external' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'ScanImageTiffReader.external' to be distributed and are
              already explicitly excluding 'ScanImageTiffReader.external' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      D:\anaconda3\envs\suite2p\lib\site-packages\setuptools\command\build_py.py:201: _Warning: Package 'ScanImageTiffReader.external.__pycache__' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'ScanImageTiffReader.external.__pycache__' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'ScanImageTiffReader.external.__pycache__' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'ScanImageTiffReader.external.__pycache__' to be distributed and are
              already explicitly excluding 'ScanImageTiffReader.external.__pycache__' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying src\ScanImageTiffReader\__init__.pyc -> build\lib\ScanImageTiffReader
      creating build\lib\ScanImageTiffReader\__pycache__
      copying src\ScanImageTiffReader\__pycache__\__init__.cpython-36.pyc -> build\lib\ScanImageTiffReader\__pycache__
      copying src\ScanImageTiffReader\__pycache__\__init__.cpython-37.pyc -> build\lib\ScanImageTiffReader\__pycache__
      creating build\lib\ScanImageTiffReader\external
      copying src\ScanImageTiffReader\external\README.md -> build\lib\ScanImageTiffReader\external
      copying src\ScanImageTiffReader\external\__init__.py -> build\lib\ScanImageTiffReader\external
      copying src\ScanImageTiffReader\external\__init__.pyc -> build\lib\ScanImageTiffReader\external
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
      copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib\libScanImageTiffReaderAPI.so -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib
      copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib\libScanImageTiffReaderAPI.so -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Linux\lib
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64
      creating build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib
      copying src\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib\ScanImageTiffReaderAPI.dll -> build\lib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-win64\lib
      creating build\lib\ScanImageTiffReader\external\__pycache__
      copying src\ScanImageTiffReader\external\__pycache__\__init__.cpython-36.pyc -> build\lib\ScanImageTiffReader\external\__pycache__
      copying src\ScanImageTiffReader\external\__pycache__\__init__.cpython-37.pyc -> build\lib\ScanImageTiffReader\external\__pycache__
      D:\anaconda3\envs\suite2p\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer, pypa/build or
              other standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external
      copying build\lib\ScanImageTiffReader\external\README.md -> build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external
      creating build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin
      error: could not create 'build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin': The filename or extension is too long
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scanimage-tiff-reader
  Running setup.py clean for scanimage-tiff-reader
Failed to build scanimage-tiff-reader
ERROR: Could not build wheels for scanimage-tiff-reader, which is required to install pyproject.toml-based projects`

### Provide environment info:

     active environment : suite2p
    active env location : D:\anaconda3\envs\suite2p
            shell level : 4
       user config file : C:\Users\Huijeong Jeong\.condarc
 populated config files : C:\Users\Huijeong Jeong\.condarc
          conda version : 22.9.0
    conda-build version : 3.23.1
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : D:\anaconda3  (writable)
      conda av data dir : D:\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\anaconda3\pkgs
                          C:\Users\Huijeong Jeong\.conda\pkgs
                          C:\Users\Huijeong Jeong\AppData\Local\conda\conda\pkgs
       envs directories : D:\anaconda3\envs
                          C:\Users\Huijeong Jeong\.conda\envs
                          C:\Users\Huijeong Jeong\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False

**Comment by chriski777** [comment]
Hi @HuijeongJeong, this seems to be an issue that the developers of the scanimage-tiff-reader can better solve. Could you post an issue [there](https://gitlab.com/vidriotech/scanimagetiffreader-python/-/issues) and see what they say?

**Comment by carsen-stringer** [comment]
you could also try python=3.8, it seems that pypi just recently deprecated the legacy way that scanimagetiffreader is installed

**Comment by jnnfr-ding** [comment]
Hi Carsen and Chris, 

I have tried python = 3.8 as well as tried 'pip install git+https://GitHub.com/mouseland/suite2p.git' and neither seem to work, unfortunately. 

After trying pip install git+https://GitHub.com/mouseland/suite2p.git, I tried to open suite2p but was unable to open the GUI. I got this error below: 

  File "C:\Users\scanimage\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\__init__.py", line 5, in <module>
    from .tiff import mesoscan_to_binary, ome_to_binary, tiff_to_binary, generate_tiff_filename, save_tiff
  File "C:\Users\scanimage\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 82, in <module>
    sktiff: bool) -> Tuple[Union[TiffFile, ScanImageTiffReader], int]:
NameError: name 'ScanImageTiffReader' is not defined

_______________________________________________________________________________
When trying the regular installation method with python = 3.8, I received the error below: 

 python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [135 lines of output]
.
.
.
C:\Users\hl\anaconda3\envs\suite2p\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'ScanImageTiffReader.__pycache__' as data is deprecated, please list it in `packages`.
          !!
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'ScanImageTiffReader.__pycache__' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'ScanImageTiffReader.__pycache__' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'ScanImageTiffReader.__pycache__' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
.
.
.
error: could not create 'build\bdist.win-amd64\wheel\scanimage_tiff_reader-1.4.1.data\purelib\ScanImageTiffReader\external\ScanImageTiffReader-1.4.1-Darwin\lib': The filename or extension is too long
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scanimage-tiff-reader
  Running setup.py clean for scanimage-tiff-reader
Failed to build scanimage-tiff-reader

**Comment by carsen-stringer** [comment]
oops I forgot to fix that import on line 82 of tiff.py, please try again with the latest version of the code

**Comment by jnnfr-ding** [comment]
Hi Carsen, 

Thanks for your help! Now I can open suite2p (after downloading a couple of additional modules). However, It looks like it is still a bit buggy. 

I downloaded suite2p a year ago, and it works well on my local desktop. I downloaded suite2p just a day ago on a new computer with your help. Running suite2p on both my local desktop and the new computer yields vastly different results. Using the same parameters (roidetect = 1, anatomical_only = 3), I detect around 1000 ROIs for a test tiff file on my local desktop and only 10 ROIs on the new computer. For some reason, the newly downloaded suite2p is completely missing all the cells. 

Is there any way to maybe download an older version of suite2p? Or might there be another solution? 

Thanks again!

Sincerely, 

Jen

**Comment by carsen-stringer** [comment]
my hunch would be that you didn't set the diameter parameter to the average cell size - Cellpose (anatomical algorithm) is very sensitive to that. I would check all the ops are the same in the previous run and the current run. I tried anatomical_only=3 with the latest version and had no issues. You can also turn off the flow_threshold (set it to 0; `ops["flow_threshold"]=0`)

**Comment by jnnfr-ding** [comment]
Thank you so much, Carsen! I changed the diameter to a reasonable number, and it was able to detect a lot of ROIs. Whoohoo!
