### ISSUE TITLE
FEATURE: Add .nd2 input format in the GUI

### ISSUE THREAD

**Issue by BptGrm** [MouseLand/suite2p#951]
### Feature you'd like to see:

I understand that .nd2 compatibility was added fairly recently, and it seems like it hasn't been added to the list of accepted formats in the GUI.

### Attempted alternative approaches:

I believe it would just require adding `'nd2'` to the list found [here](https://github.com/MouseLand/suite2p/blob/f8d2c28a9846ddeb6aa7e82b2b28de9d2620f50a/suite2p/gui/rungui.py#L236) : 
```
[self.inputformat.addItem(f) for f in ['tif','bruker','sbx', 'h5','mesoscan','haus']]
```

**Comment by chriski777** [comment]
Thanks, @BptGrm! This has been added to the gui and should be in the newest release. If you'd like access to the version with this compatibility, feel free to pull from the `refactor` branch.
