### ISSUE TITLE
BUG: sparse detection not available via GUI

### ISSUE THREAD

**Issue by nspiller** [MouseLand/suite2p#954]
### Describe the issue:

The [Documentation](https://suite2p.readthedocs.io/en/latest/settings.html#roi-detection-settings) mentions the `sparse_mode` detection, but this feature is not available in the GUI.

I noticed that in the[ `create_buttons`](https://github.com/MouseLand/suite2p/blob/f8d2c28a9846ddeb6aa7e82b2b28de9d2620f50a/suite2p/gui/rungui.py#L84) function, `'sparse_mode'` appears in the `self.boolkeys`attribute, but not in the `cellkeys` list.

### Reproduce the code example:

```python
conda activate suite2p
suite2p
# Ctrl + R
```

### Version information:

0.12.1

**Comment by chriski777** [comment]
Thanks, @nspiller, this has been fixed in #958 and will be merged soon into the main branch. Feel free to pull the latest changes from the `refactor` branch if this is urgent.
