### ISSUE TITLE
FEATURE: Allow loading MESc files with image data

### ISSUE THREAD

**Issue by zoltanhock** [MouseLand/suite2p#955]
### Feature you'd like to see:

It would be nice to see "femtonics" option at run suite2p Input format combobox

### Attempted alternative approaches:

We have hdf5 based file format so our customers can use h5 option but they need to rename the filetype from .mesc to .h5 and modify h5 key from "data" to "/MSession_0/MUnit_0/Channel_0" for example.

### Additional Context

Let me know if you need more information. Alternatively, a user-defined type could be also cool.

**Comment by carsen-stringer** [comment]
I'm adding "*.mesc" to the list of files searched when using the h5 option. users can specify the folder with `ops["h5py"] = ["folder_with_mesc"]` and they can specify the key with `ops["h5py_key"]="/MSession_0..."`
