### ISSUE TITLE
DOC: Is Rastermap and PC sorted activity display in GUI colormapped to data normalized across ROIs, or within ROIs?

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#956]
### Issue with current documentation:

If one loads data in the GUI, selects all cells, and then sorts by either Rastermap or PC, is the heatmap LUT mapped to zscored activity after normalization across all cells, or within each cell? In other words, does the same shade of bright yellow (or black, or whatever) in each row correspond to the same absolute activity level across rows, or to the same relative level within each row?

Thanks,

Evan

**Comment by carsen-stringer** [comment]
each row is z-scored separately, but each row can be sums of different groups of neurons depending on the sorting. does that answer your question?

**Comment by vickerse1** [comment]
Yes thanks

-evan

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
