### ISSUE TITLE
Installation error: Failed to build scanimage-tiff-reader

### ISSUE THREAD

**Issue by Elsword016** [MouseLand/suite2p#957]
### Describe the issue:

I am trying to install suite2p with conda and pip and getting error:
Could not build wheels for scanimage-tiff-reader, which is required to install pyproject.toml-based projects

### Provide environment info:

active environment : suite2p
    active env location : C:\Users\saha\miniconda3\envs\suite2p
            shell level : 2
       user config file : C:\Users\saha\.condarc
 populated config files : C:\Users\saha\.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : C:\Users\saha\miniconda3  (writable)
      conda av data dir : C:\Users\saha\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\saha\miniconda3\pkgs
                          C:\Users\saha\.conda\pkgs
                          C:\Users\saha\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\saha\miniconda3\envs
                          C:\Users\saha\.conda\envs
                          C:\Users\saha\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.9.16 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False

**Comment by chriski777** [comment]
As mentioned in #950, could you try using python=3.8? If that doesn't work, you can also try posting an issue with the tiff-reader developers. I'll close this issue for now but feel free to re-open if you have additional questions.
