### ISSUE TITLE
BUG: Cannot load processed data into GUI after running suite2p

### ISSUE THREAD

**Issue by Acnowlogia** [MouseLand/suite2p#959]
### Describe the issue:

After running suite2p, the data should be loaded into GUI as mentioned in the dialog
![image](https://github.com/MouseLand/suite2p/assets/54861409/b980677c-a8b5-4529-ac5a-550f3c664de9)

But the GUI did not shows any data
![image](https://github.com/MouseLand/suite2p/assets/54861409/813599ed-18b0-4b36-911c-89b0bad8ff5d)

In prompt, it said no channel 2 labels found. 
![image](https://github.com/MouseLand/suite2p/assets/54861409/ece245b5-880c-456f-aab9-52e3b11aeebb)

My data have only one channel, and run suite2p for 1 plane and 1 channel. How can I load the result successfully?

### Reproduce the code example:

```python
python -m suite2p
% Used GUI after opened suite2p
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\Purdu\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\rungui.py", line 439, in finished
    io.load_proc(self.parent)
  File "C:\Users\Purdu\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\io.py", line 307, in load_proc
    load_to_GUI(parent, basename, output)
  File "C:\Users\Purdu\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\io.py", line 332, in load_to_GUI
    make_masks_and_enable_buttons(parent)
  File "C:\Users\Purdu\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\io.py", line 49, in make_masks_and_enable_buttons
    yext, xext = utils.boundary(ypix, xpix)
  File "C:\Users\Purdu\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\utils.py", line 10, in boundary
    msk = np.zeros((np.ptp(ypix)+6, np.ptp(xpix)+6), np.bool)
  File "C:\Users\Purdu\anaconda3\envs\suite2p\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### Version information:

suite2p v0.12.1

### Context for the issue:

I cannot run the full pipeline of suite2p with this issue.

**Comment by ambtetl** [comment]
I found this since I had the same problem. I am not sure if this is the optimal answer but I ran the following lines to remove numpy and downgraded. 

 python -m pip uninstall numpy
python -m pip install numpy==1.23.1

**Comment by Acnowlogia** [comment]
> I found this since I had the same problem. I am not sure if this is the optimal answer but I ran the following lines to remove numpy and downgraded.
> 
> python -m pip uninstall numpy python -m pip install numpy==1.23.1

Thanks! This also works for me.
