### ISSUE TITLE
DOC: For non-neuronal cells, should the deconvolved output be disregarded?

### ISSUE THREAD

**Issue by RandallJEllis** [MouseLand/suite2p#963]
### Issue with current documentation:

My group is imaging GCaMP6f in cultured cancer cells. We have used Suite2p to analyze the data, but we are wondering, since they are not neurons, if we should use the deconvolved output (`spks.npy`), or the cell fluorescence (`F.npy`). Any clarification on this would be greatly appreciated.

**Comment by carsen-stringer** [comment]
maybe not? the calcium events in neurons are caused by spikes and that's what we try to extract with deconvolution since the gcamp decay timescale is much longer than those events, but I don't know what happens in cancer cells. cool to hear it's working in that cell type though!

**Comment by RandallJEllis** [comment]
Thank you @carsen-stringer! I'm trying to figure out which parameters would be worth changing to adapt the pipeline to cancer cells. I'm thinking `win_baseline` and `sig_baseline` because the activity is much slower than action potentials, but if any other parameters come to mind, that would be very helpful.

**Comment by RandallJEllis** [comment]
Trying to simplify this question: Is there anything about the [oasis_trace](https://github.com/MouseLand/suite2p/blob/main/suite2p/extraction/dcnv.py#L12) function that is neuron-specific and disqualifies it from being used in other cell types? 

1. I see that Reference 26 in the Suite2p [paper](https://www.biorxiv.org/content/10.1101/061507v2.full.pdf) is to a [paper](https://onlinelibrary.wiley.com/doi/10.1002/jbio.201100133#:~:text=Laser%20scanning%20microscopy%20%28LSM%29%20is%20a%20common%20technique,quantum%20efficiency%20of%20the%20imaging%20system%20is%20increased.) that uses non-negative deconvolution in xenopus laevis embryos, so I'm guessing `oasis_trace` is cell-type agnostic, unless there are specific details about the exponential kernel that make it neuron-specific? 
2. In the review paper about deconvolution, there is this quote: 

> An incorrect interpretation of deconvolved spike trains is that they represent the “firing rates” or “probabilities” of neural spiking; this is not true. Instead, they represent a time-localized and noisy estimate of the [calcium influx](https://www.sciencedirect.com/topics/neuroscience/calcium-transport) into the cell. The calcium influx events may vary in size from spike to spike ([Figure 4](https://www.sciencedirect.com/science/article/pii/S0959438818300977#fig0020)e and f). Therefore, a deconvolution algorithm which estimates event amplitudes cannot perfectly reconstruct a spike train even when the exact spike times are known from simultaneous [electrophysiology](https://www.sciencedirect.com/topics/neuroscience/electrophysiology) [[47](https://www.sciencedirect.com/science/article/pii/S0959438818300977#bib0235)] ([Figure 4](https://www.sciencedirect.com/science/article/pii/S0959438818300977#fig0020)d and g). This variability in spike-evoked amplitudes in turn places an upper bound on blind spike detection accuracy. **The upper bound is saturated when performance is evaluated in bins of 320 ms or larger ([Figure 4](https://www.sciencedirect.com/science/article/pii/S0959438818300977#fig0020)g). In smaller bins, the deconvolution does not saturate the upper performance bound ([Figure 4](https://www.sciencedirect.com/science/article/pii/S0959438818300977#fig0020)g), which appears to be due to variability in the timing of the deconvolved spike times on the order of ≈100 ms ([Figure 4](https://www.sciencedirect.com/science/article/pii/S0959438818300977#fig0020)h).** 

I don't see the 100ms-320ms window hard-coded anywhere in the Suite2p codebase, so I'm guessing this assumption wasn't used?

Any clarification on this is tremendously appreciated.
