### ISSUE TITLE
merging ROIs based on correlation and spatial constraints

### ISSUE THREAD

**Issue by irinamarguerita** [MouseLand/suite2p#964]
Hi, 

I am doing 2p imaging of axonal boutons. Suite2p (the GUI) does a great job for me in identifying the ROIs, however I am struggling with the merging afterwards to make 1 merge out of 1 axon. Ideally, I would like to merge the ROIs/boutons based on their correlation coefficient and their spatial constraints. The axons I am imaging are generally appearing horizontal/diagonal in my field of view. (fyi, in my case, it is possible that two axons on opposite sides of the FOV light up at the same time and are highly correlated, but I would like to treat them as separate axons/groups initially). 

So far, I have been using the MATLAB version, but I recently started experimenting with the python version. When I select one ROI and look at the correlation of this ROI with other ROIs in python, it often does a great job at identifying the ROIs that I think belong to one axon (they can be of slightly different correlation coefficients however). I could click on these ROIs one by one in order to merge them, however in one session I generally have around 500-1000 boutons, so it takes quite long. I could also use your autosuggested merges, but for me, it does not always catch the whole axon, and generally just suggests the 3-5 closest boutons. I have also tried to take the top 20-50 ROIs every time that are correlated to one ROI, but since my axons can be of various lengths its not always ideal, and it is also quite time consuming.

I was wondering if there is any chance (or if someone is working on) to implement a more automated approach to selecting one ROI based on its correlation coefficient. What would work well (I think) would be a selection approach similar to the top n based on the correlation coefficient, but instead with a correlation coefficient threshold. So, I would be able to select one ROI, and from there set a correlation threshold (and preferably also a spatial threshold along one axis), which would select all ROIs that correlate more than the threshold with the selected ROI. From there I could merge the selected ROIs and select a new starting ROI.

**Comment by carsen-stringer** [comment]
Have you tried the automated merging function in the GUI? It's in the Merge menu. I think this is exactly what you're looking for. Let us know if not
