### ISSUE TITLE
FEATURE: Return X Y matrix of ROI mask to visualize morphology across days

### ISSUE THREAD

**Issue by neurovanlin** [MouseLand/suite2p#970]
### Feature you'd like to see:

Return X Y matrix of ROI mask to visualize morphology across days

### Attempted alternative approaches:

I am attempting to compare the ROI masks of my cells from different days in order to assess their qualitative similarity over time. Although I can reconstruct an alternative ROI using the center and radius information from the Fall.mat file, it does not assist me in achieving the desired comparison. Is there a method to obtain an XY matrix consisting of zeros and ones?

**Comment by carsen-stringer** [comment]
please check out the stat.npy documentation and use the code here to retrieve ypix and xpix: https://suite2p.readthedocs.io/en/latest/outputs.html#stat-npy-fields

**Comment by carsen-stringer** [comment]
Please use python, if that doesn't work we'll reopen the issue
