### ISSUE TITLE
Upgrade fails due to `Cannot uninstall 'llvmlite'` error

### ISSUE THREAD

**Issue by zelunw** [MouseLand/suite2p#971]
### Describe the issue:

In the `(suite2p)` environment, running `pip install --upgrade suite2p` terminates with the error message 

> ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

What do?

### Provide environment info:

     active environment : suite2p
    active env location : C:\Users\zelun.wang\Anaconda3\envs\suite2p
            shell level : 2
       user config file : C:\Users\zelun.wang\.condarc
 populated config files : C:\Users\zelun.wang\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\zelun.wang\Anaconda3  (writable)
      conda av data dir : C:\Users\zelun.wang\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\zelun.wang\Anaconda3\pkgs
                          C:\Users\zelun.wang\.conda\pkgs
                          C:\Users\zelun.wang\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\zelun.wang\Anaconda3\envs
                          C:\Users\zelun.wang\.conda\envs
                          C:\Users\zelun.wang\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.7 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False

**Comment by carsen-stringer** [comment]
please make a new clean environment as per the install instructions and try again I would guess that upgrading torch is having issues, let us know if not and we can reopen
