### ISSUE TITLE
non-rigid registration

### ISSUE THREAD

**Issue by ransona** [MouseLand/suite2p#98]
I see that there's non-rigid registration code and a 'nonrigid' option in the default ops - is is possible to use this already?
Thanks
Adam

**Comment by marius10p** [comment]
We are still testing it, but very soon. Looks very good, even better than the Matlab version in fact. It approximately doubles the run time of registration though.

**Comment by ransona** [comment]
brilliant, looking forward to giving it a try.

**Comment by marius10p** [comment]
We pushed a version where you can enable non-rigid, so give it a try.  

The only remaining issue I have with it is that if some parts of your image are quite dim, the XY estimate for that block could be noisy. To address this, we compute an SNR for every single patch of every image, and smooth over blocks if that snr is low. That is the parameter ops['snr_threshold'], set to 1.0 by default, which doesn't do anything. If registration fails in dark portions of the image, try 1.25 or 1.5 and let us know if it helps.

**Comment by ransona** [comment]
brilliant, will give it a go today.

**Comment by ransona** [comment]
If you have nonrigid on does the reference image get produced with nonrigid too?

**Comment by ransona** [comment]
Also, am I right in my reading of the subsample_frames function that the n frames for making the reference are selected from the start of the frame sequence - i.e. not sub-sampled from throughout (as in the Matlab version if I remember rightly)?

**Comment by marius10p** [comment]
No, they are sampled [uniformly](https://github.com/MouseLand/suite2p/blob/e345f566ee8f408bbc696dcb75a071db394e76b2/suite2p/register2.py#L332).
Reference image is not produced with nonrigid. Let us know if you have issues with that, but it should usually be possible to find half of the frames well aligned to each other, which is what the initializer is looking for.

**Comment by marius10p** [comment]
Actually, I am wrong, the initializer also uses non-rigid.

**Comment by carsen-stringer** [comment]
the initializer does NOT use non-rigid, let us know if there are issues with your reference image
