### ISSUE TITLE
h5py and paramiko packages not installed with 'python -m pip install suite2p[gui]'

### ISSUE THREAD

**Issue by Atika-Syeda** [MouseLand/suite2p#987]
### Describe the issue:

Followed installation instructions for GUI version on a linux machine but the commands `suite2p --version` and `python -m suite2p` resulted in following errors:
`ModuleNotFoundError: No module named 'h5py'`
and
`ModuleNotFoundError: No module named 'paramiko'`
Errors were resolved after installing the packages in the conda env.

### Provide environment info:

     active environment : suite2p
    active env location : /home/stringlab/anaconda3/envs/suite2p
            shell level : 1
       user config file : /home/stringlab/.condarc
 populated config files : /home/stringlab/.condarc
          conda version : 4.11.0
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/stringlab/anaconda3  (writable)
      conda av data dir : /home/stringlab/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/stringlab/anaconda3/pkgs
                          /home/stringlab/.conda/pkgs
       envs directories : /home/stringlab/anaconda3/envs
                          /home/stringlab/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Linux/5.15.0-75-generic ubuntu/20.04.6 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by carsen-stringer** [comment]
thanks this is now fixed with more documentation
