### ISSUE TITLE
y-axis for stim trace on the right side

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#99]
Would it be possible to add a second y-axis on the right for the loaded stim trace in the GUI?

I guess in many cases it is 0/1 but in my case it is for example temperature.

Small QOL enhancement

**Comment by marius10p** [comment]
Sorry, they are z-scored in order to be shown on the same plot. This feature is only there for convenience of visualizing traces and not for any kind of serious measurements. If you want to add it, you are encouraged to make a pull request.
