### ISSUE TITLE
Python deconvolution implementation seems very different from OASIS and old Matlab implementation

### ISSUE THREAD

**Issue by RandallJEllis** [MouseLand/suite2p#996]
Sorry if I'm missing something obvious, but the deconvolution [implementation](https://github.com/MouseLand/suite2p/blob/main/suite2p/extraction/dcnv.py) appears to be quite different from the original OASIS [implementation](https://github.com/j-friedrich/OASIS/blob/master/oasis/functions.py#L110) and the original C/MATLAB [version](https://github.com/cortex-lab/Suite2P/blob/master/SpikeDetection/deconvL0.c) of Suite2p. As far as I can tell, the Suite2p [preprint](https://www.biorxiv.org/content/10.1101/061507v2.full.pdf) and JNeuro [paper](https://www.jneurosci.org/content/jneuro/38/37/7976.full.pdf) are written about the MATLAB implementation, but I'm wondering if the newer, seemingly more minimalistic Python implementation is written about anywhere, specifically how it differs from the original OASIS method (aside [from](https://suite2p.readthedocs.io/en/latest/FAQ.html) not inferring spike trains or imposing L1 penalties)? 

Is the deconvolved output supposed to show:
1. Underlying calcium activity after removing the influence of the sensor and frame rate?
2. Underlying calcium transient amplitudes
3. Underlying action potential amplitudes
4. Something else?

Any clarification is greatly appreciated.

**Comment by Hananel-Hazan** [comment]
piling on @RandallJEllis question I open discussion post #1001

**Comment by carsen-stringer** [comment]
We re-implemented OASIS (this function here: https://github.com/j-friedrich/OASIS/blob/6dae97381b295f764530d952a3b2bf5033a009b1/oasis/oasis_methods.pyx#L25) in numba without L0 and L1 penalties. The OASIS paper discusses the interpretations of spike deconvolved traces, and we discuss this in our review paper, it is correlated to the firing rate of the neuron: https://www.sciencedirect.com/science/article/pii/S0959438818300977
