### ISSUE TITLE
Error with rastermap.mapping

### ISSUE THREAD

**Issue by harshidapancholi** [MouseLand/suite2p#999]
### Describe the issue:

Hello there, I'm installing suite2p and running into the following error:
![suite2p_error](https://github.com/MouseLand/suite2p/assets/53277874/f9ffa3ff-1f9a-46cd-ad77-2b41a1ac5502)

I've tried pip install rastermap, but that doesn't seem to have solved it. Any help would be appreciated, thanks!

### Provide environment info:

active environment : suite2p
    active env location : C:\Users\brentoncooper\Anaconda3\envs\suite2p
            shell level : 2
       user config file : C:\Users\brentoncooper\.condarc
 populated config files : C:\Users\brentoncooper\.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\brentoncooper\Anaconda3  (writable)
      conda av data dir : C:\Users\brentoncooper\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\brentoncooper\Anaconda3\pkgs
                          C:\Users\brentoncooper\.conda\pkgs
                          C:\Users\brentoncooper\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\brentoncooper\Anaconda3\envs
                          C:\Users\brentoncooper\.conda\envs
                          C:\Users\brentoncooper\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

**Comment by splendourcw** [comment]
I am having the same issue. Could anyone help?

**Comment by Rukh-mani** [comment]
Hello ! I am having the same issue! Help would be appreciated! Thanks :)

**Comment by dykim224** [comment]
Hello, I am having the same issue ;)

**Comment by carsen-stringer** [comment]
please "pip install rastermap==0.1.3", the rastermap algorithm has been updated, and the suite2p package will be updated accordingly soon too

**Comment by harshidapancholi** [comment]
thank you, that solved the issue!
